### ISSUE TITLE
Cannot make any requests from null

### ISSUE THREAD

**Issue by DBotThePony** [CapsAdmin/pac3#10]
Hi.

Garry's Mod using Chrome engine to download file. So. When Downloading OGG in console displayed [PAC] XMLHttpRequest cannot load http://my IP/patch.ogg. Cannot make any requests from null.
Another, he say ERROR 101 (Switching Protocols, http://en.wikipedia.org/wiki/List_of_HTTP_status_codes#1xx_Informational )
Garry's Mod DO request

my IP Requested GET /sounds/steam/sentry_upgrading_steam1.ogg
my IP Sent 1460 bytes
my IP Fully downloaded - 18.77 K @ 712 KB/s - /sounds/steam/sentry_upgrading_steam1.ogg
BUT
[PAC3] OGG error: stream[0x62b4a928][15][http://my IP/patch.ogg] reason: download failed

You can Fix it?
P.S. Models and textures from my ip is loading normally.
P.S.S. From sites OGG also not working

**Comment by hobnob11** [comment]
In case anyone finds this with google, and they are trying to use NginX with PAC, you need this: https://enable-cors.org/server_nginx.html

**Comment by SladeXanthas** [comment]
location ~* \.(ogg|obj|mid)$ {
        expires epoch;
        add_header Access-Control-Allow-Origin *;
    }

**Comment by CapsAdmin** [comment]
Also, sound2 does not have this restriction.
