### ISSUE TITLE
Broken pac3 since computer change

### ISSUE THREAD

**Issue by zriku1** [CapsAdmin/pac3#100]
The following pac has been broken ever since my computer died.
Rather than having messed up scaling or improper placement, it simply will not load.
http://pastebin.com/v1hT6YiP
I have tried rounding all numbers, removing GlobalID from each part, and pasting the code into another pac. 
![4000_screenshots_2013-10-13_00002](https://cloud.githubusercontent.com/assets/10055403/5275197/7e88f680-7a44-11e4-9d91-c30df46eefc9.jpg)

**Comment by CapsAdmin** [comment]
this is sadly due to gmod updates changing how scaling is done. there's a legacy scale option in tools that may help you
