### ISSUE TITLE
Activity names in .zips get replaced with other, already used activities.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1000]
That causes some animations to get randomized.
For example, `ACT_HL2MP_ZOMBIE_SLUMP_ALT_RISE_FAST` is replaced with `ACT_HL2MP_GESTURE_RANGE_ATTACK_MELEE`, but that activity is already used by the `range_melee` sequence. That means the `zombie_slump_rise_02_fast` sequence is sometimes going to play instead of `range_melee`.
Left part is created by PAC, right is the original file. 
![image](https://user-images.githubusercontent.com/12747052/107762713-ba362a80-6d2d-11eb-9592-80926790746d.png)
![image](https://user-images.githubusercontent.com/12747052/107763437-eb632a80-6d2e-11eb-9383-646dbca12b8d.png)

Can be seen on this model when trying to attack with the crowbar
https://dl.dropboxusercontent.com/s/3qoeuan58a750wi/pac%20test3.zip

**Comment by thegrb93** [comment]
I noticed that as well and wasn't sure if it was correct. I think it was an attempt to get models with unknown activities compatible with gmod? https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/shared/util.lua#L418 Basically if the ACT enum found in the model isn't known to gmod, then it replaces it with whatever it can find that's less length it seems.

**Comment by thegrb93** [comment]
They're listed here, https://wiki.facepunch.com/gmod/Enums/ACT

Apparently there's a bug linked to it as well. https://github.com/Facepunch/garrysmod-issues/issues/3075

**Comment by thegrb93** [comment]
We can workaround the gmod bug by adding the missing enum values manually.

**Comment by Yagira** [comment]
Keep in mind custom activities also get replaced, some models use those for custom taunts/gestures/whatever.

> Basically if the ACT enum found in the model isn't known to gmod, then it replaces it with whatever it can find that's less length it seems.

The question is, do they have to be replaced in the first place? GMod doesn't really care, if the activity is unknown it simply won't play. I think that out of the two options its better for the 'bad' activities to never play than have them mess up other activities.

**Comment by thegrb93** [comment]
@Yagira does commenting https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/shared/util.lua#L415-L427 fix the issue?

**Comment by Yagira** [comment]
Yes, it works fine.
