### ISSUE TITLE
[Dev] Gesture custom animations resetting when reaching end of last frame

### ISSUE THREAD

**Issue by AeoMayo** [CapsAdmin/pac3#1002]
(Sorry for the huge influx of issues; I was asked by Caps to do this for easier tracking!)

A couple custom animations I have, like one that's meant to raise a shield and keeps the arm in position until an event hides it, reset when they get to the end of the animation. Video showcasing that here:
https://cdn.discordapp.com/attachments/463236715453218817/808877852241821736/2021-02-09_20-51-24.mp4
Note that I only ever use "gesture" animation type.

**Comment by Yagira** [comment]
I don't think that is a bug. Gestures only play once, what you're looking for is a `stance`.

**Comment by AeoMayo** [comment]
> 
> 
> I don't think that is a bug. Gestures only play once, what you're looking for is a `stance`.

Haha, the big problem is I think stance didn't exist when I made 99% of my PACs. I've been working on a severely outdated version upkept by my friends and I for about three years, and on this custom version, gesture animation types hold the last frame indefinitely until the part is hidden. Note that we have never touched any part of the code related to this.
Upon changing it to "stance" however, the animation now loops undesirably.

**Comment by Yagira** [comment]
Well, I guess PAC just changed a bit.
> Upon changing it to "stance" however, the animation now loops undesirably. 

Right click the last keyframe and click `set restart pos` or something similar.

**Comment by AeoMayo** [comment]
There's only one keyframe. Setting restart pos didn't keep it from looping. I duplicated the only keyframe to ensure there was more than one and tried setting it there, and that didn't prevent it from looping either. I tried every option and none of them stop it from looping.

**Comment by Yagira** [comment]
Save the animation after doing that and reload, it doesn't update properly.

**Comment by AeoMayo** [comment]
Ah, that worked. Thank you.

Still somewhat irritating that the behavior changed though, I've got a _lot_ of animations to fix with this version, phew...

**Comment by AeoMayo** [comment]
Closing issue, a solution for me being whiny and picky was made with a small script by Caps that automatically converts any animation parts under this criteria into a "stance" type with the keyframe duplicated and "set restart" attribute applied.

If anyone else may need this, though I doubt it lmao:
`for _, part in pairs(pac.GetLocalParts()) do
    if part.ClassName == "custom_animation" then        
        local data = util.JSONToTable(part:GetData())
        
        if data then

            if #data.FrameData > 1 then 
                print("skipping", part, "because it contains ",#data.FrameData," frames")
                continue 
            end

            print("setting restart frame to last for", part)
            data.Type = "stance"

            table.insert(data.FrameData, table.Copy(data.FrameData[#data.FrameData]))

            data.RestartFrame = #data.FrameData
            
            print("\t", part, "'s restart frame is now ", data.RestartFrame)

            part:SetData(util.TableToJSON(data))
        else
            print("\t", part, "does not contain any data, its url is: ", part:GetURL())
        end
    end
end`
