### ISSUE TITLE
[Dev] Pressing left/right arrow keys with editor open causes inexplicable lag with complicated outfits

### ISSUE THREAD

**Issue by AeoMayo** [CapsAdmin/pac3#1005]
(Sorry for the huge influx of issues; I was asked by Caps to do this for easier tracking!)

For some inexplicable reason, pressing the left and right arrow keys in the editor causes a freeze for a good second or two when large PACs are loaded. I'm not sure why, or what this is supposed to do.

**Comment by Techbot121** [comment]
left/right arrow keys were supposed to expand/collapse the current selected node. It wasn't working before, but I just fixed it, maybe it also fixes this issue but I'm not sure.
