### ISSUE TITLE
[Dev] Loading PAC with different animation set causes "wrong bones" until worn

### ISSUE THREAD

**Issue by AeoMayo** [CapsAdmin/pac3#1006]
(Sorry for the huge influx of issues; I was asked by Caps to do this for easier tracking!)

It seems if you load a PAC that changes your playermodel to one that uses a different animation set (e.g. Mossman to Barney), bones are a bit wonky until worn. This used to be fixed by just disabling and re-enabling PAC to re-render myself, but no longer is.

By wonky I mean that bone parts are on the wrong side, e.g. left hand bone part affects right hand bone, and anything attached to them are also on the wrong side in the same manner.

**Comment by Techbot121** [comment]
I just tried it out again today and while it's still wonky `pac_enable 0;pac_enable 1` in the console seems "re-render" like you described.
