### ISSUE TITLE
[Dev] Holdtype part occasionally fails to override original holdtype animations

### ISSUE THREAD

**Issue by AeoMayo** [CapsAdmin/pac3#1007]
(Sorry for the huge influx of issues; I was asked by Caps to do this for easier tracking!)

Holdtype part does not always successfully override the holdtype's original attack animation as seen here:
https://cdn.discordapp.com/attachments/463236715453218817/808879796259782656/2021-02-09_20-59-00.mp4

**Comment by Techbot121** [comment]
I can't see the video, but it doesn't seem to happen anymore.
