### ISSUE TITLE
[Dev] [Suggestion] Transluscent enabled by default on trail parts

### ISSUE THREAD

**Issue by AeoMayo** [CapsAdmin/pac3#1010]
(Sorry for the huge influx of issues; I was asked by Caps to do this for easier tracking!)

Translucent should be default enabled on trail parts much like they are on sprites. On old versions of PAC, they didn't have to have this enabled to not render behind things. I guess something changed?

Either translucent should be default, or perhaps the thing that now makes trails draw behind things if it's not enabled when it was not always this way should be addressed.

**Comment by Techbot121** [comment]
looks like caps already did this and didn't close this issue.
