### ISSUE TITLE
Converting pac3 visclips to E2 holo

### ISSUE THREAD

**Issue by cobaltST** [CapsAdmin/pac3#1013]
When converting visclipped models in pac3 to E2 holos, the visclips are drawn further back than what they were in the pac3 editor, resulting in some big gaps.

![ff1](https://user-images.githubusercontent.com/22684529/109188381-2cc5f200-7793-11eb-90d0-fedb3e86f6b4.png)
![ff2](https://user-images.githubusercontent.com/22684529/109188398-30f20f80-7793-11eb-898e-f26e28ae0940.png)

**Comment by CapsAdmin** [comment]
There was an old bug with clips that offsetted the plane by 1 source unit. 

This was fixed by introducing a new clip part that doesn't have this bug to keep backwards compatibility.

I'm guessing the bug is related to this.

**Comment by cobaltST** [comment]
Where do I find this new clip part? I tried with both modifiers->clip and
model->clip

**Comment by CapsAdmin** [comment]
I'm saying the problem might be with the new clip part. The old one is in legacy. Does that one work?

And what tool is this so I can test?

**Comment by cobaltST** [comment]
Sorry I'm not sure what you mean exactly. Should I switch to a different
branch and try or...?

**Comment by CapsAdmin** [comment]
Sorry I'm not being clear here. I'm just explaining why this might be happening.

Can you tell me what addon you're using in the screenshot? With this I can probably figure it out and fix the problem in pac, or the addon if necessary.

**Comment by cobaltST** [comment]
It's just 2 SProps models in PAC3 clipped and converted into E2 holos. It
happens on any model though.

**Comment by CapsAdmin** [comment]
It should be fixed now in develop.
