### ISSUE TITLE
Animation parts act as if owner_cycle is enabled

### ISSUE THREAD

**Issue by diemarthaha** [CapsAdmin/pac3#1019]
I was planning on refurbishing one of my pacs till i noticed a very big change with how the animation part worked, instead of acting normally it acts as if owner_cycle is enabled, as the title suggested. I hadn't used pac3 properly in a few days but when i was deciding to just get back into it i only just noticed it.

I don't know what causes this, so maybe any of you guys have an idea of what the problem is. All i know is that it might've been an attempt at fixing the desync issue, which hasn't been an issue for me in a while, but you never know.

**Comment by CapsAdmin** [comment]
can you send me an example outfit and explain how it's supposed to look?

**Comment by diemarthaha** [comment]
> can you send me an example outfit and explain how it's supposed to look?

https://www.dropbox.com/s/yahckmv93u71uj5/stormbirdexample.txt?dl=0
Here's one of my pacs lowered down to only the walking system, if its normal it should look like every animation is trying to go forward, but if it isn't it should be de-synced and look like its trying to move backwards.

**Comment by CapsAdmin** [comment]
but the animation rate is set to -0.77, setting it to 0.77 seems to look like the intended result.

Is there something I'm not understanding here?

**Comment by diemarthaha** [comment]
> but the animation rate is set to -0.77, setting it to 0.77 seems to look like the intended result.
> 
> Is there something I'm not understanding here?

It's meant to be set to -0.77 and have invert animation on. But invert animation doesn't work, nor does any of the other options.

**Comment by CapsAdmin** [comment]
I understand. 

I've fixed your case in develop, could you try that branch?

**Comment by diemarthaha** [comment]
Alright.

**Comment by diemarthaha** [comment]
Alright, it seems to be fixed now. Thank you very much! It also fixed the de-sync issue i guess. I suppose i'll close the issue here.
