### ISSUE TITLE
event wheel bug

### ISSUE THREAD

**Issue by CapsAdmin** [CapsAdmin/pac3#1020]
"the new event wheel that was added recently, it works well but i've noticed you can't right click to cancel triggering an event like it says, it closes the menu but letting go of the event wheel key still causes the last highlighted event to trigger"

**Comment by thegrb93** [comment]
This selected = nil needs to be outside of the if block, that should fix it.
https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/parts/event.lua#L2028

**Comment by CapsAdmin** [comment]
dev is merged to master and workshop now
