### ISSUE TITLE
Weapon part hides and doesn't show up after switching weapons.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1028]
1. Take out the pistol
2. Add the weapon part and set the class to `weapon_pistol`
3. Add a model or tweak some settings
4. Switch to a different weapon then back to pistol

https://user-images.githubusercontent.com/12747052/113753899-f1620000-970e-11eb-8a56-02c72e6f9ce9.mp4

**Comment by CapsAdmin** [comment]
fixed
