### ISSUE TITLE
Root Owner on events and proxies is broken.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1030]
Reposting from Discord so it doesn't get lost.

> root owner is kinda broken, it shows as enabled when its disabled, show the entity name instead of true/false, when you actually set it to true it changed to a text field and you cant disable it anymore, happens on events and proxies

https://user-images.githubusercontent.com/12747052/113755007-1c008880-9710-11eb-88be-0047eee2318a.mp4

**Comment by CapsAdmin** [comment]
fixed
