### ISSUE TITLE
Time argument on events displays an incorrect value.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1033]
Lets take the Command event for example.
When time isn't set to anything it displays `0` in the editor but the actual value is `0.1`, if you click it by accident (causing it to update) or set it back to `0` after messing with it the event wont work anymore which might confuse some people.

**Comment by CapsAdmin** [comment]
I agree. I think I'll change the event code to allow default variables and behave a bit more like how parts are setup.

**Comment by Techbot121** [comment]
I think this has been fixed
