### ISSUE TITLE
Materials that use $phong without $basetexture are fully black.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1038]
This worked fine before the merge.

![image](https://user-images.githubusercontent.com/12747052/113858154-b2ca5500-97a3-11eb-9693-a7c93d3bd9a5.png)

**Comment by Yagira** [comment]
Seems related to lights.

https://user-images.githubusercontent.com/12747052/113859767-94655900-97a5-11eb-9dad-69379e60f753.mp4

**Comment by CapsAdmin** [comment]
defaulting basetexture to white material
