### ISSUE TITLE
Weapon - Disabling 'override position' breaks lighting on the weapon.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1049]
Kinda acts as if it was stuck where it was disabled.

https://user-images.githubusercontent.com/12747052/114187859-c2cf6980-9948-11eb-9cc0-8e88b71def57.mp4

**Comment by Yagira** [comment]
Seems like the position doesn't update anymore?

https://user-images.githubusercontent.com/12747052/114189532-9583bb00-994a-11eb-8ea1-a781fa15aae7.mp4

**Comment by CapsAdmin** [comment]
close if you think it's fixed

**Comment by Yagira** [comment]
seems fine
