### ISSUE TITLE
Problem murder

### ISSUE THREAD

**Issue by Bammer013** [CapsAdmin/pac3#1052]
Hi, since I installed pac3 I have this problem with the murder gamemode

[Murder] gamemodes/murder/gamemode/cl_ragdoll.lua:23: attempt to call method 'GetRagdollOwnerOld' (a nil value)
  1. GetRagdollOwner - gamemodes/murder/gamemode/cl_ragdoll.lua:23
   2. fn - addons/nx_pac3/lua/pac3/core/client/parts/bone.lua:302
    3. unknown - addons/ulib/lua/ulib/shared/hook.lua:109 (x31)

**Comment by Bammer013** [comment]
Same

**Comment by CapsAdmin** [comment]
try to get MechanicalMind to look at this pull request in order for it to be fixed

https://github.com/MechanicalMind/murder/pull/78
