### ISSUE TITLE
Parts continuously trigger when unhidden by a proxy.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1058]
Outfit: [unhide_proxy.txt](https://github.com/CapsAdmin/pac3/files/6343684/unhide_proxy.txt)

https://user-images.githubusercontent.com/12747052/115399867-ea47f100-a1e8-11eb-8c02-4daf6a1228b5.mp4

**Comment by CapsAdmin** [comment]
asdawdawsd
