### ISSUE TITLE
ForceObjUrl became false when wearing (legaсy convertation).

### ISSUE THREAD

**Issue by owltaver** [CapsAdmin/pac3#1066]
After convert legacy to new obj part, obj loads normaly, but not when you wear it. For some reason ForceObj became false when wearing and obj(s) start loading like mdl(s) causing console mdl dl error spam.
Outfit used for testing: https://pastebin.com/r5qiV0gv (convert via tools>wear)

**Comment by Techbot121** [comment]
seems to work now
