### ISSUE TITLE
 PAC3 unable to properly update playermodel world position to clients

### ISSUE THREAD

**Issue by EmpyTM** [CapsAdmin/pac3#1068]
I've been having this issue for some time now, and was wondering if this has been looked at before. I find this only occurs when another player's PAC uses a ZIP file for model uploading. Most of the time a player's position does wonky stuff and does not update on my end.

**Comment by Yagira** [comment]
I think this was fixed in #1112

**Comment by thegrb93** [comment]
Sounds likely. Feel free to respond if not
