### ISSUE TITLE
use :GetBoneMatrix() instead of :GetBonePosition() (was: Hats and Masks Weird Behaviour)

### ISSUE THREAD

**Issue by RoliMG** [CapsAdmin/pac3#107]
Hello guys

we have the following problem on our server:
Accessories (hats, masks) are jumping back and forth very rapidly if a player moves. When the player stands still and only looks around they are at their desired place.
Is this a configuartion problem or a known bug from pac3?
Thank you for your help.

**Comment by LUModder** [comment]
It's not a file thing, it's coded into the game. You can't change it.

**Comment by Ameno-Sagiri** [comment]
What's the server tickrate? 11,22,33,66?

We have ours set to 22 with 40 players and a ton of shit going on and usually clients hardly ever experience that issue.

When you're on the server and you see it happening, type net_graph 4, where is the number by "sv:" at? Does it look like the number is dropping into single digits and turning yellow a lot? If it is, the server is having a hard time coping with everything going on in the server.

 Is the lerp: 100.0 ms shaking around hardcore and blinking yellow?
 If that's happening, your connection to the server is lagging quit a lot.

**Comment by CapsAdmin** [comment]
This seems to be a bug with the :GetBonePosition() function. I've been advised to use :GetBoneMatrix() but this may break some outfits.

**Comment by BAPEsta** [comment]
So at this point there is literally nothing we can do? If so, can someone please show me a possible fix for this issue I really need this to be handle ASAP.

**Comment by BAPEsta** [comment]
Can you send me a fixed version of pac using :GetBoneMatrix() instead so I can get mine's to work?

**Comment by BAPEsta** [comment]
Can someone please explain to me what is going on here?, I am still confused and don't know what to do to fix this. HELP!
