### ISSUE TITLE
Console error on x64 dedicated server

### ISSUE THREAD

**Issue by StrawWagen** [CapsAdmin/pac3#1073]
addons/pac3/lua/pac3/core/shared/entity_mutator.lua:143: player is invalid
stack traceback:
	addons/pac3/lua/pac3/core/shared/entity_mutator.lua:70: in function <addons/pac3/lua/pac3/core/shared/entity_mutator.lua:69>
	[C]: in function 'assert'
	addons/pac3/lua/pac3/core/shared/entity_mutator.lua:143: in function 'RestoreMutations'
	addons/pac3/lua/pac3/core/shared/entity_mutator.lua:362: in function <addons/pac3/lua/pac3/core/shared/entity_mutator.lua:360>
	[C]: in function 'xpcall'
	addons/pac3/lua/pac3/core/shared/entity_mutator.lua:360: in function 'func'
	lua/includes/extensions/net.lua:32: in function <lua/includes/extensions/net.lua:17>
addons/pac3/lua/pac3/core/shared/entity_mutator.lua:143: player is invalid

**Comment by thegrb93** [comment]
This was fixed recently
