### ISSUE TITLE
PAC problem "IMPORTANT!"

### ISSUE THREAD

**Issue by Smalleyboi2000** [CapsAdmin/pac3#108]
So when I put on my PAC other people around me can see it but I can't and I can't see other peoples PAC's neither

**Comment by Ameno-Sagiri** [comment]
Sounds like you don't have PAC enabled clientside. If you disable PAC clientside, other people will still be able to see your own if you're wearing one. It just turns them off for only you. Check the options/utilities menu and make sure PAC is enabled in the checkbox.

Or, type pac_enable 1 in the console

**Comment by CapsAdmin** [comment]
reopen if this is still an issue
