### ISSUE TITLE
Events/ Script Errors

### ISSUE THREAD

**Issue by JunkoEnoshima2** [CapsAdmin/pac3#1082]
When I'm on my server with the most up to date pac3, Some events like "Owner Alive" Doesn't work when it's suppose to. and When I die or respawn, It just flickers. and also the amount of script errors I get for web audio for tabbing out and tabbing back in?
![image](https://user-images.githubusercontent.com/78762383/126050428-a5df55e6-707b-4fef-a862-a5556994001d.png)
I really want this fixed.. and Fix your web audio.. when I raise the volume, they distort very badly instead of getting louder. and do please make it so when you're trying to load an MLD, it doesn't show: "this player wants to use *model*." It gives people a free model to use on their own and that ruins pac3 for some people.

Thanks, Regards ☠Junko Enoshima❤

**Comment by thegrb93** [comment]
I think it's fixed on develop now with https://github.com/CapsAdmin/pac3/commit/ec2c769eb2d46a569733aaafadd3c3ba01f97746
