### ISSUE TITLE
Http:// appearing as https:\ in console renders the audio to be broken

### ISSUE THREAD

**Issue by Dragotiger** [CapsAdmin/pac3#1084]
This happens when using dropbox links, which turns it as https:\ in an unknown reason with legacy sound, in effects. 
![image](https://user-images.githubusercontent.com/79160983/127839380-8a129ed5-9abb-4552-a6e0-cd7731413193.png)
![Screenshot 2021-08-02 192917](https://user-images.githubusercontent.com/79160983/127839437-3e2625d3-1c84-4945-94f2-d35fc94a6b44.png)

**Comment by DBotThePony** [comment]
User error, `legacy sound` is for playing sounds from disk.
