### ISSUE TITLE
Camera + Playersize + bulletproof

### ISSUE THREAD

**Issue by mrvecz** [CapsAdmin/pac3#109]
When i set player size to 1.5, in first person the camera is at same height, again and again, why the camera height doesnt scale too ?

And that also lead to one question
hitboxes seems to be scaled, unlike camera, but its possible to make player model bullet proof on some places ?

**Comment by LUModder** [comment]
Might have to wear for the camera to adjust itself.

And the last one, if you have small enough size, no one can hit you.

**Comment by mrvecz** [comment]
How can camera adjucts it self ? please explain

I tryied to put camera highter, but accuracy, is something i lost then, i cannot hit combine soldier standing in front of me
But anyway thanks for your time

**Comment by LUModder** [comment]
I thought you meany the main camera, not the camera part, the camera part WILL be off from your crosshair thus meaning you have to have a small transparent hitpos model to aim.

**Comment by mrvecz** [comment]
No i mean the main camera, just camera height in first person doesnt match the player real height, if its fix-able ? how ?

**Comment by LUModder** [comment]
It won't change if you're messing with the Z axis of the player.

**Comment by mrvecz** [comment]
I will ask other way, how to make player bigger in first person ?

**Comment by LUModder** [comment]
As I mention before camera part and hitpos model.

**Comment by mrvecz** [comment]
hitpos model ? (what is that ? where can i find it ? what it will do :?
Iam sorry but iam still new to PAC3, and i thank you for your lost time with me but this is only problém i got with editor now

And it is possible to make player bullet proof ? but not entirely ? only chest for example ?

**Comment by LUModder** [comment]
Hitpost model is just a model at about 0.25 size, alpha at 0.5 and on the hitpos bone.

Bulletproofing isn't really possible without stuff like Lua to be used.

**Comment by mrvecz** [comment]
I still didnt gotten my answer

how to addjust height of first person camera

**Comment by mrvecz** [comment]
Set viewmodel (camera)
Wear it
Nothing happens

**Comment by LUModder** [comment]
Either
1. You're putting camera part in a viewmodel group, don't do that.
2. You're PAC is only in one group and you hit the 64kb limit.

**Comment by mrvecz** [comment]
What limit, one group ? those are new words for me

**Comment by LUModder** [comment]
If you have a bunch of stuff in just the my outfit group, it may be over 64 kb and not wear, try making some new groups outside my outfit and splitting it up.

**Comment by mrvecz** [comment]
Can you make step by step tutorial about it ?
I didnt still manage to do it ?!

**Comment by LUModder** [comment]
I give up, if you can't understand how to simply add a camera part and position it how you need, you shouldn't be doing PAC then.

**Comment by CapsAdmin** [comment]
reopen if this is still an issue

**Comment by thegrb93** [comment]
Addon conflict probably
