### ISSUE TITLE
Halo on model showing up weirdly dependent on location in the map

### ISSUE THREAD

**Issue by HallowedFlux** [CapsAdmin/pac3#1093]
I wanted to make a bubble around my character while flying, using a model sphere with a halo on it, the problem now is that dependent on where i am in the map, there seems to be a border where the halo stops showing up.

![image](https://user-images.githubusercontent.com/29779604/134816988-18bb6c9c-ad61-4f14-8927-1dbe3875b7e7.png)

**Comment by Yagira** [comment]
I'm 51% sure that this is fixed in the dev version.

**Comment by thegrb93** [comment]
Feel free to respond if its still not fixed
