### ISSUE TITLE
pac_restart causes entity desync

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1098]
If you use `pac_restart` while SOMEONE ELSE is using the entity part they will get stuck in place or start lagging/teleporting/whatever on your end. This is not a new problem, it's been a thing for a while. It persists until you restart/rejoin the server. 

Video: https://drive.google.com/file/d/1k2OaKZE5T8OLoc3hHWKyBJW9bUPylgER/view?usp=sharing

If you use `pac_restart` while YOU are using the entity part you will end up in that weird state with broken animations or something. Also persists until restart (?).

Video: https://drive.google.com/file/d/1LzYuXeZ3EyRMkdGJhMZKSMkAeWK1X_sI/view?usp=sharing

As a bonus this breaks the model_name event even since apparently `:GetModel()` returns the wrong model (???) after a restart.

Model used: https://wiki.pac3.info/_media/tutorial/mdl/animegirl.zip

**Comment by thegrb93** [comment]
Could you try a commit from June? If that fixes the issue, then try late July/early August. Should only take 3 or 4 attempts to find the culprit if you're bisecting the version timespans.

**Comment by Yagira** [comment]
> If you use `pac_restart` while SOMEONE ELSE is using the entity part they will get stuck in place or start lagging/teleporting/whatever on your end. This is not a new problem, it's been a thing for a while. It persists until you restart/rejoin the server.

So, I've tried a bunch of different versions, I went back to 2018 where the custom models didn't even load properly and this was already broken at that point. Either it never actually worked or a gmod update broke it? 

> If you use `pac_restart` while YOU are using the entity part you will end up in that weird state with broken animations or something. Also persists until restart (?).

This started happening in f804040fc74d85e666c3218add12fa32d1dbe216, here to be specific https://github.com/CapsAdmin/pac3/blob/f804040fc74d85e666c3218add12fa32d1dbe216/lua/pac3/core/client/parts/model.lua#L541 also causes #1089

**Comment by Yagira** [comment]
Well, I might have found the cause of the first problem. 
https://github.com/CapsAdmin/pac3/blob/93992dca76f9cdc5f6be536a57fcd796a71adc32/lua/pac3/core/shared/util.lua#L171
`PAC_MDL_SALT` is used when generating ids for mdl files, and it goes up with every restart. So if I understand correctly, when two players try to download the same link while one of them used `pac_restart`, they are gonna end up with two different mdl files. 

I assume it was originally added to redownload the model on restarts but that just doesn't work in multiplayer and isn't exactly needed either. A new link can be forced by adding `?` to it.

Anyway, it seems to work fine without it.

**Comment by DBotThePony** [comment]
https://github.com/CapsAdmin/pac3/commit/f804040fc74d85e666c3218add12fa32d1dbe216 Fixes an issue where bones under custom models are not properly initialized, resulting in pacs staying broken until you hide/show affected parts, and i can only see it being an issue if `PART:RefreshModel` is called while model part is no longer valid

**Comment by Yagira** [comment]
Oh yeah, this was fixed, forgot to close it.

**Comment by thegrb93** [comment]
Reverted closing PR so reopening.
