### ISSUE TITLE
Discord OBJs don't work

### ISSUE THREAD

**Issue by umustbeloggedintododat** [CapsAdmin/pac3#1099]
Hello, I uploaded my obj and texture files to discord, but they won't load and say "download aborted" and the console says "invaild model". What gives? I provided a direct download link, so why doesn't it work? The textures load fine, but the model doesn't.
Example OBJ file: https://cdn.discordapp.com/attachments/754045717261320253/897560496272720033/body5.obj
![image](https://user-images.githubusercontent.com/54049600/137015882-a0003e3f-0332-43b8-8f12-a5b0d43c4597.png)
![image](https://user-images.githubusercontent.com/54049600/137015896-03d93323-8c75-4e92-8393-3593a8ec6ee6.png)

**Comment by thegrb93** [comment]
I think discord started rejecting steam http requests

**Comment by umustbeloggedintododat** [comment]
NVM, the objs were cached and turned out the icloud objs didn't work. I just settled for Google Drive instead.
