### ISSUE TITLE
Problems with the entity part

### ISSUE THREAD

**Issue by AlexanderB2109** [CapsAdmin/pac3#1101]
When I try to set my entity model to something else, it works but my character begins to slow down and kinda rubberbands a bit. GMod itself doesn't slow down, though. Also, when I fire a weapon, i go back to my normal playermodel for a split second before returning to the PAC model, and the animation doesn't play.

**Comment by Yagira** [comment]
Make sure that model changes are enabled, `pac_modifier_model 1`
Also try disabling other addons that force playermodels such as the Enhanced PlayerModel Selector

**Comment by AlexanderB2109** [comment]
Alright. I DID have Enhanced Playermodel Selector, but uninstalled it due to compatibility errors. I just turned the command on and it works! Thanks!
