### ISSUE TITLE
Up-down view fails after using PAC3

### ISSUE THREAD

**Issue by Mremenar** [CapsAdmin/pac3#1105]
I would like to start by saying "thank you" for PAC3--I think it is awesome and I am truly grateful to finally have a way to customize characters in GMOD.
The problem I am facing is that after using PAC3, I lose the ability to look up or down.  My view can only move from side to side.
This is regardless of whether I use PAC3 on myself/my player character OR if I gussy up an NPC in any way.  Ironically I don't even have to make changes to the character/NPC, just opening PAC3 causes the in game problems.
This appeared to happen after installing TF2 to the list of games imported into GMOD, but I am not 100% sure that that is the cause.
Any help would be greatly appreciated.

**Comment by thegrb93** [comment]
Mounting tf2 shouldn't cause any issue. Are you seeing any lua error appear in your console? I haven't seen this happen before so it seems like a mod issue/conflict of some kind.

**Comment by Mremenar** [comment]
Thank you for the quick response!  I do not have any errors showing up in the problems/lua errors tabs.  I did make a recording to be able to show you:

https://user-images.githubusercontent.com/48491179/140232443-8ab11ed3-c9f2-45ee-af5f-64dd4438b5bc.mp4

I'm using the version from the workshop.

A secondary question, please:  How do I keep my changes and modify NPCs?  I seem to not have the ability to keep my costume changes when I switch to modify an NPC's appearance with PAC3.  I must be doing something wrong; I just can't quite figure out my error.

**Comment by thegrb93** [comment]
Definitely have never seen that before so I think you have a conflicting addon. Not sure what the answer to your question is. The pac3 discord may have users willing to help though.

**Comment by Mremenar** [comment]
I've posted a couple of variations of this help request to the Steam discussion/help board:

     "In PAC3, after modifying your character, how do you change to editing NPCs without losing the changes just made to your own player character?

      ( I have tried changing the possession of the costume at the bottom left corner of the screen--this moves my character changes to the NPC.  I have tried changing the outfit thru loading at the top, this just loads the NPC's costume changes to me.  )

      It would be nice to have a custom character and custom NPCs on the same screen at the same time.

      Any help would be greatly appreciated!"

So far no response.  I could include another video for you if that would help clarify?  I had hoped as the creator of the software/addon you would be able to help direct me with what is probably a user error on my part.

**Comment by Mremenar** [comment]
Yesterday, the up-down problem disappeared.  Today, it reappeared in full force.

**Comment by thegrb93** [comment]
> Yesterday, the up-down problem disappeared. Today, it reappeared in full force.

I wonder if its a program installed on your computer causing the issue then.

**Comment by thegrb93** [comment]
It doesn't happen with anyone else that I know of.

**Comment by Mremenar** [comment]
Doing some Google searching, I found someone else who had the problem asking for this same help on Steam, and stumbled upon someone else who isolated the add on “Glue Library” as the add on conflicting with PAC3.
I have taken Glue off my machine, so far no repeat of the problem.  I’ll stress test this theory over the next couple of days and let you know if this is the permanent solution.
M

“Fall seven times; stand up eight.”
—Japanese proverb

**Comment by thegrb93** [comment]
Good to know. Thanks for adding the soluton.

**Comment by Mremenar** [comment]
PAC3 is an awesome add-on, happy to help.

“Fall seven times; stand up eight.”
—Japanese proverb
