### ISSUE TITLE
c_arms support for MDL zips

### ISSUE THREAD

**Issue by sr229** [CapsAdmin/pac3#1107]
It will be nice if MDL ZIPs also can override c_arms provided the folder for the model exist with the valid files. This opens customization for those who want to stay in first person.

**Comment by Yagira** [comment]
The arms are just a model so you can make a separate zip with just the arms then load and bonemerge it in `viewmodel`
[arms_custom3.txt](https://github.com/CapsAdmin/pac3/files/7628542/arms_custom3.txt)
