### ISSUE TITLE
Strange replacement issue - Beer cans for hats

### ISSUE THREAD

**Issue by Mremenar** [CapsAdmin/pac3#1109]
Love this addon, great work!
I recently developed a problem where the hats are being replaced in game with beer cans, despite showing up in the tree as hats.  For some reason the game is replacing what should be with a default model (beer can)--how can I fix this?
Many thanks,
JMAS
![beer cans for hats](https://user-images.githubusercontent.com/48491179/144107795-273cc2c1-675c-4a84-9213-de6302185f7d.png)

**Comment by thegrb93** [comment]
A can is a missing model. Maybe you need to mount tf2

**Comment by Mremenar** [comment]
Wow.  Both Steam and GMod recognize that TF2 “was” installed.
TF2 was 22 GB and now it’s gone.  I have no idea how that happened.
Thank you for the help!


“Fall seven times; stand up eight.”
—Japanese proverb
