### ISSUE TITLE
How edit multiple entities

### ISSUE THREAD

**Issue by Mremenar** [CapsAdmin/pac3#1110]
My apologies if this is the wrong place for this; I have been unable to find answers elsewhere.
How does one change their appearance in PAC3, and change the appearance of one or more NPCs in the same session?  I keep modifying the NPCs only to end up wearing their modified costume, or vice versa?

The end result is that at the same time, in the same gaming session, I would like to have my player character costume be custom and have 2 - 3 NPCs also be customized.

**Comment by thegrb93** [comment]
You can customize one, then duplicate the group and apply it to the others. I don't think you can have multiple entities per group.

**Comment by Mremenar** [comment]
Let’s say I’m not playing on a server.  Instead I’m recording/filming.

Imagine that I modified myself to look like Luke Skywalker, and modified NPC Father Gregori to look like Chewbacca, and some random NPC girl to look like Princess Leia.  

How can I get everyone to be modified and on the screen at the same time?

“Fall seven times; stand up eight.”
—Japanese proverb
