### ISSUE TITLE
Edit self and NPCs?

### ISSUE THREAD

**Issue by Mremenar** [CapsAdmin/pac3#1111]
Sorry I wasn't clear enough in my first attempt to articulate my question better for you to understand my issue:

Let’s say I’m not playing on a server.  Instead I’m recording/filming.

Imagine that I modified myself to look like Luke Skywalker, and modified NPC Father Gregori to look like Chewbacca, and some random NPC girl to look like Princess Leia.  You can imagine anyone from any fictional that you want (Luke, Chewie, Leia; or Kirk, Spock, Uhura; or Joey, Chandler, Phobe, whatever).

How does one change their appearance in PAC3, AND change the appearance of one or more NPCs in the same session? I keep modifying the NPCs only to end up wearing their modified costume, or vice versa?

How can I get everyone to be modified and on the screen at the same time?

The end result is that at the same time I would like to have my player character costume be customized and have 2 - 3 NPCs also be customized, in the same gaming session.

**Comment by thegrb93** [comment]
Use the group part and assign each group to each npc. Then the parts in a group will apply to whatever entity the group is assigned with.

**Comment by Mremenar** [comment]
Awesome.  What's the group part?
![group part is what](https://user-images.githubusercontent.com/48491179/144160820-dc6bf332-fc14-45e2-8bac-b06e34fe051a.png)

**Comment by Mremenar** [comment]
For example, here are the characters that I have so far:
![example1](https://user-images.githubusercontent.com/48491179/144162112-31338d5a-31e0-44b0-9b90-d275b66c7a6f.png)

How do I load any of the characters into the scene with the existing one currently loaded in PAC3?

**Comment by Yagira** [comment]
If you right click the editor (the white space) and load an outfit from there it's gonna add it to your current outfit instead of replacing it. That way you can load multiple things at once.

**Comment by Mremenar** [comment]
Bless you, Yagira!  This did lead to answering my question.
