### ISSUE TITLE
Pac to Holo export doesn't export nested holos.

### ISSUE THREAD

**Issue by freedom7341** [CapsAdmin/pac3#1118]
If I have a pac, like the one attached, and I export it through Pac to Holo, it doesn't create holos for any of the nested models, such as the numbers. 
E2 holo output:
[wgauges_needles_clock.txt](https://github.com/CapsAdmin/pac3/files/7654827/wgauges_needles_clock.txt)
PAC:
[wgauges_needles_clock.txt](https://github.com/CapsAdmin/pac3/files/7654828/wgauges_needles_clock.txt)

If you load the holo and the pac, you can see the pac has numbers but the holo does not.

**Comment by thegrb93** [comment]
Yeah and it doesn't seem to be working at all on develop branch

**Comment by thegrb93** [comment]
Nevermind, I just did it wrong. You have to select the group first.

**Comment by thegrb93** [comment]
This was probably intended. It would probably easy to step through the model parts' children and include them too but it'll need to be added.

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/editor/client/tools.lua#L674-L678

**Comment by thegrb93** [comment]
Should be fixed in develop
