### ISSUE TITLE
Playermodel issue

### ISSUE THREAD

**Issue by PartyAtGibbons** [CapsAdmin/pac3#112]
So, whenever I choose a playermodel in singleplayer, that same playermodel shows up in multiplayer, Even though I'm using a different skin in the pointshop. Any way to fix this?

**Comment by LUModder** [comment]
Clear PAC and it'll reset the playermodel, or just set your playermodel with entity part that way some PACs may not have problems afterwards.

**Comment by CapsAdmin** [comment]
reopen if this is still an issue
