### ISSUE TITLE
Pac editor f*cking up view

### ISSUE THREAD

**Issue by LegitSpy** [CapsAdmin/pac3#1120]
Basically when I enter the pac editor and add a model anywhere I lose the ability to look up and down and my character loses his animations. This happens on both github and workshop ver

**Comment by Yagira** [comment]
It's 99% an addon conflict

**Comment by thegrb93** [comment]
Probably same shit as this https://github.com/CapsAdmin/pac3/issues/1105

**Comment by thegrb93** [comment]
The said it was “Glue Library” causing it

**Comment by LegitSpy** [comment]
> The said it was “Glue Library” causing it

alr thanks mate, solved it
