### ISSUE TITLE
Closing off the animation editor for superadmins only

### ISSUE THREAD

**Issue by dence47** [CapsAdmin/pac3#113]
Hi, I am new to PAC. I read the documentation to add the hook to disallow the Pac Editor from being opened but would would the hook be to disallow the Animation Editor from being opened for anyone besides superadmins?

Thanks a lot and sorry if this was the wrong section.

**Comment by LUModder** [comment]
Already asked Suchipi about it, he said pretty much there's not a default hook, but look in anim editor code. Last time I looked, couldn't find anything for preventing it from open.

**Comment by blt950** [comment]
+1

Should be easy to add a hook the developers could use to disable it, just like the PAC editor it self.

**Comment by LUModder** [comment]
Just look through the code and restrict it yourself, heck, I'll do it right now.

**Comment by LUModder** [comment]
[Line 742](https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/editor/client/animeditor.lua#L742) already has an if statement for it commented out, just uncomment it.

**Comment by blt950** [comment]
I use the workshop addon. So I can't uncomment it.
Or well, I can.. But it would be easier if its fixed in Workshop addon as well.

**Comment by LUModder** [comment]
Copy the one file and it should overwrite.

**Comment by Ameno-Sagiri** [comment]
blt950, the Workshop one doesn't need to be "fixed", why would they automatically disable it? Many servers have open PAC/animation editor. What about all those people?

Get GMAD, extract PAC3, OR simply download the github PAC3 which is what I use on my server, and then you have free reign over it.

**Comment by blt950** [comment]
I never said that it should be default/auto disabled. I said that the hook that gives the possibility to disable it with Lua hook.Add should been uncommented in the workshop version.

No problem for me to copy the one file and override it, already done that.

**Comment by CapsAdmin** [comment]
I'll make it so if you're not allowed to go into the normal editor you're not allowed to go in the animation editor.

**Comment by blt950** [comment]
That sounds like a good solution
