### ISSUE TITLE
Animation rate is inconsistent

### ISSUE THREAD

**Issue by Jacbo1** [CapsAdmin/pac3#1133]
The rate of animations sometimes is correct and sometimes is too fast but the issue is very inconsistent and I can't find a way to reliably reproduce it. It just happens when it feels like it. I'm not sure but it also seems to sometimes change speed as it plays. I know about the bug where they play slowly when in first person but this is happening in third person and they are sped up instead of slowed down.

**Comment by thegrb93** [comment]
It may be because FrameTime isn't being used to advance the animation. Is it an issue both before and after https://github.com/CapsAdmin/pac3/pull/1117

**Comment by Jacbo1** [comment]
I don't think it was inconsistent before #1117 but it was also a seemingly random number

**Comment by thegrb93** [comment]
I think caps fixed it in https://github.com/CapsAdmin/pac3/commit/dfcc5db12d07b9a0a28bedb02d7336f34602742c
and
https://github.com/CapsAdmin/pac3/commit/843b1162d02576c709963d499bd9f783bc3ee995

The animation logic was getting ran multiple times per frame it seems. Let me know if it should be reopened or not.
