### ISSUE TITLE
Face Poser Only Works Partially

### ISSUE THREAD

**Issue by M1G-N008** [CapsAdmin/pac3#1149]
I've been using PAC3 for quite some time now but recently I've noticed that the Face Posing only works on some parts of the face, including all the individual parts listed. This issue never happened to me in the past, so I assume it's new. Also, I've tried using the flex tool instead and that doesn't work either. I don't think it's the playermodel I'm using, because I've used this playermodel before and it worked fine then.

**Comment by thegrb93** [comment]
Might be your model quality setting. Make sure its set to high
