### ISSUE TITLE
PAC Bodygroups are bugged

### ISSUE THREAD

**Issue by Weapon317** [CapsAdmin/pac3#115]
Most of the time when selecting a bodygroup from a model only two or one bodygroup works. The others don't toggle. And even when selecting a bodygroup in PAC and when you do 'wear outfit' afterwards, other people don't see the said bodygroup and what it changed. But you do yourself when you look at your own model as if its clientside only?

I hope this can be fixed.

**Comment by LUModder** [comment]
We know about this, we can't really fix it but we can find workarounds for certain things to act as bodygroups.

**Comment by Weapon317** [comment]
I'd really like to know whenever PAC gets updated with this workaround, this has been an issue quite awhile now.

**Comment by LUModder** [comment]
Apparently, you don't understand what a workaround is. It's something that can or can't be updated to the addon, but usually it's not updated. Contact me on Steam if you want so I can help you with workarounds for certain bodygroups.

**Comment by Weapon317** [comment]
Added you 2 or 3 times now and you denied the request, I can't leave a comment either on your profile.

**Comment by LUModder** [comment]
I don't know if that was you this morning with the obscene name and the profile that was private 2 minutes after I checked it.

**Comment by Weapon317** [comment]
Well if you could add me http://steamcommunity.com/id/lex317/ that'd be great!
