### ISSUE TITLE
PAC3 fails to request outfits periodically

### ISSUE THREAD

**Issue by Pumpkin101** [CapsAdmin/pac3#1154]
Was told to post this in the GitHub so it didn't get lost in the discord.

To explain. Two servers I'm apart of are having the same issues with this error popping up, which causes pac3 to fail when requesting other peoples pacs. I'm not sure if it's a pac3 thing or if maybe there's an incompatibility with some code that's causing the issues _(both servers use similar branches of Nutscript)_.

_**lua/pac3/libraries/string_stream.lua:656: StringStream:readType: Couldn't read type nil
stack traceback:
    [C]: in function 'error'
    lua/pac3/libraries/string_stream.lua:656: in function 'readType'
    lua/pac3/libraries/string_stream.lua:595: in function 'readTable'
    lua/pac3/editor/client/wear.lua:352: in function <lua/pac3/editor/client/wear.lua:350>
    [C]: in function 'xpcall'
    lua/autorun/netstream.lua:66: in function 'Remove'
    lua/autorun/netstream.lua:18: in function 'Request'
    lua/autorun/netstream.lua:29: in function <lua/autorun/netstream.lua:29>**_

All I know is this gets spammed in console _(only for some people)_, then will fix itself randomly after multiple relogs or just after a period of time. Also, from observations, it's a clientside problem that seems to be caused by something serverside. Because one person will have this issue, while the rest are fine, but all players are plagued by it at some point. Doesn't happen in single player from what we've seen.

Another error just popped up today as well, which is slightly different.

_**addons/pac3-master/lua/pac3/core/shared/entity_mutator.lua:143: player is invalid
stack traceback:
    addons/pac3-master/lua/pac3/core/shared/entity_mutator.lua:70: in function <addons/pac3-master/lua/pac3/core/shared/entity_mutator.lua:69>
    [C]: in function 'assert'
    addons/pac3-master/lua/pac3/core/shared/entity_mutator.lua:143: in function 'RestoreMutations'
    addons/pac3-master/lua/pac3/core/shared/entity_mutator.lua:362: in function <addons/pac3-master/lua/pac3/core/shared/entity_mutator.lua:360>
    [C]: in function 'xpcall'
    addons/pac3-master/lua/pac3/core/shared/entity_mutator.lua:360: in function 'func'
    lua/includes/extensions/net.lua:33: in function <lua/includes/extensions/net.lua:18>
addons/pac3-master/lua/pac3/core/shared/entity_mutator.lua:143: player is invalid**_

**Comment by thegrb93** [comment]
You need to update to develop branch of pac3 I think

**Comment by Pumpkin101** [comment]
Alright, I'll try that. Is it alright if you keep this open for now, so we can test it for a few days and see if it still has the error pop up?

**Comment by thegrb93** [comment]
Ya

**Comment by Pumpkin101** [comment]
Alright, thus far the requesting outfits has worked - okay. Is the best way to put it.

I've noticed. There's been issues where PACs aren't loading at all at times or parts of them are just completely invisible, haven't gotten any errors that seem to relate to that. But this one did recently pop up in our console, not sure by what either seeing as only two of us are currently on and aren't wearing PACs.

_**[pac3-develop] lua/pac3/core/client/parts/bodygroup.lua:9: attempt to call field 'StartStorableVars' (a nil value)
    1. unknown - lua/pac3/core/client/parts/bodygroup.lua:9
        2. include - [C]:-1
            3. LoadParts - addons/pac3-develop/lua/pac3/core/client/parts.lua:137
                4. unknown - addons/pac3-develop/lua/pac3/core/client/init.lua:57
                    5. include - [C]:-1
                        6. unknown - addons/pac3-develop/lua/autorun/pac_core_init.lua:29**_
