### ISSUE TITLE
New Update broke pre-existing PAC's

### ISSUE THREAD

**Issue by ThroatyChunk** [CapsAdmin/pac3#1160]
Title says all, I launched gmod, and my PAC's were all horribly misconfigured. It seems to only be broken when attached to something with bones but it still breaks a lot.

**Comment by CapsAdmin** [comment]
are you using the workshop version? does it still happen?

**Comment by thegrb93** [comment]
Please more info. My pac has bones and works still

**Comment by thegrb93** [comment]
@ThroatyChunk an example outfit would be a good help

**Comment by WolfKann** [comment]
#1163  I think I found the issue, I addressed it at the bottom of my post and after some testing it seemed to be the case for me.

**Comment by thegrb93** [comment]
Yeah that issue has more info so we'll track it there
