### ISSUE TITLE
Problem with Hide proxies interacting with children Events.

### ISSUE THREAD

**Issue by superkevin642** [CapsAdmin/pac3#1162]
The issue I have is regarding the interaction with hide proxies and events. Such as when I create a hide proxy then put an event as it's child, and then add a web sound underneath all that. What happens when I activate the proxy is that it bypasses the event and plays the sound regardless.

[example.txt](https://github.com/CapsAdmin/pac3/files/8106374/example.txt)

**Comment by CapsAdmin** [comment]
Can you try latest develop now? I'm not sure if this fix is correct but locally this outfit works.
[hideproxytest.txt](https://github.com/CapsAdmin/pac3/files/8112590/hideproxytest.txt)

**Comment by superkevin642** [comment]
There is another issue, whenever I have a jiggle with a model parented to a hide proxy. The model doesn't show. This also happens if I put a model underneath another model.

[proxytest.txt](https://github.com/CapsAdmin/pac3/files/8113368/proxytest.txt)

**Comment by CapsAdmin** [comment]
I've fixed that case now too in develop.

**Comment by superkevin642** [comment]
I have found another case, which is the same issue at the start of the thread. But instead of a using timerx event, I used a proxy with an expression that mimics a timerx event. It leads to the same issue.



[hideproxycommand.txt](https://github.com/CapsAdmin/pac3/files/8121891/hideproxycommand.txt)

**Comment by CapsAdmin** [comment]
Fixed last case in develop.

Thank you for these tests, they are very helpful!

**Comment by superkevin642** [comment]
Couldn't find any other bugs relating to proxies.
