### ISSUE TITLE
"Groups" need fixed/are bugged with childed entities

### ISSUE THREAD

**Issue by WolfKann** [CapsAdmin/pac3#1163]
Groups do not grab from the child entity, which breaks all old Pac3's

Example using Legacy Bodygroups

Model Bodygroups:
![image](https://user-images.githubusercontent.com/17802255/155015188-bc43b60b-9622-4734-bc73-f83bc714699f.png)

Actual Bodygroup selects Entity
![image](https://user-images.githubusercontent.com/17802255/155015225-e1587ee2-8304-4f41-9dab-0c1025acc3e1.png)

**Comment by WolfKann** [comment]
This comes from a bonemerge overlay I was doing with certain items appearing if I had a certain weapon out using bodygroups, I cannot do this with Pac anymore due to this bug?? (I hope it's a bug.)

**Comment by WolfKann** [comment]
Infact this breaks *anything* in a group under a model, it forces it all to use the base entity's options instead of the model, which is the intended feature

**Comment by WolfKann** [comment]
Another Example is with bones:

![image](https://user-images.githubusercontent.com/17802255/155015777-aa29a410-d2a9-4640-974a-9d0bae4ad51c.png)

For this case I want my head to shrink when a bind is done to put on a helmet, but if it's in a group it affects the entity.

![image](https://user-images.githubusercontent.com/17802255/155015811-c77fdd07-5759-4d65-8d15-842d74b97980.png)

These effects only want to work now if the item is directly under, but that means I have to spent more events to get something to work. which makes the pac even heavier on resources.

**Comment by thegrb93** [comment]
So the stuff you're putting in groups are basically not working because they are operating on the group itself instead of what the group is in I think?

**Comment by thegrb93** [comment]
Something in here might be broken https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/base_part.lua#L169-L182

**Comment by CapsAdmin** [comment]
There was a bug with events causing this that I fixed yesterday at least. Are you sure it's not fixed now?

Apart from that I can see that toggling the legacy bodygroup with an event is not working properly.

This setup works for me apart from bodygroup not hiding properly
![image](https://user-images.githubusercontent.com/204157/155033966-80b9d440-ef94-44fe-a090-1a916473e58e.png)

**Comment by WolfKann** [comment]
I'll take a look now and see

**Comment by WolfKann** [comment]
No, it's still broken. in the same way, it still just grabs from the parent groups 

![image](https://user-images.githubusercontent.com/17802255/155145822-fb89d372-7043-448f-9e73-68d26e65e189.png)

This should say Chestplate, not armor or health or anything becasue that's on the entity.

I'm not sure what's wrong with it. as for the bodygroups just not working maybe we can add an option to select *what* they effect? like the bodygroup name/ parent index, that way we can have one bind affect multiple parts or multiple models without needing multiple events?




Bones do not work however either, and they still only affect the parent entity. which is why my head and helmet still shrink. I dunno if I didn't get the update or if something broke but it's just not working at all.



also the sliding playermodel occurs if someone loads an OLD Pac with an old entity with stuff bone-merged to it

**Comment by WolfKann** [comment]
The sliding is the result of bones that are named after something that doesn't exist in an event (i.e a helmet bind to mess with a bone merged model only affecting the base entity.

because it thinks these bones exist on the entity, it auto-defaults to rotating and fucking with your root bone to not cause errors. this is mostly notable if you have bones fucking with special playermodels on your pac, then change your base model to not have those bones, your model will rotate. this bug came entirely because of groups breaking.

**Comment by CapsAdmin** [comment]
Given this example
![image](https://user-images.githubusercontent.com/204157/155180467-8c59e098-ad86-43c5-80c5-8c7e410325e1.png)
Do we expect (from old behavior) that the animation part is supposed to be applied on the female model and not my kleiner player model?

**Comment by CapsAdmin** [comment]
I've made some fixes regarding this now in develop and on workshop.

**Comment by CapsAdmin** [comment]
I did another fix in develop with events having ticked root owner messing up all child parts, I believe this could be the setup in the screenshots you posted and it might be why bodygroups is targetting the wrong model.

**Comment by WolfKann** [comment]
> Given this example ![image](https://user-images.githubusercontent.com/204157/155180591-03eddf40-d403-4393-ae5b-718afade7676.png) Do we expect (from old behavior) that the animation part is supposed to be applied on the female model and not my kleiner player model?

Yes that's what you'd expect.

**Comment by WolfKann** [comment]
I'm checking Singleplayer right now and seeing if it's fixed

**Comment by WolfKann** [comment]
![image](https://user-images.githubusercontent.com/17802255/155373532-6990f291-55a1-43c3-b1c1-088010dd917b.png)


Looks to be all correct now

**Comment by WolfKann** [comment]
> ![image](https://user-images.githubusercontent.com/17802255/155373532-6990f291-55a1-43c3-b1c1-088010dd917b.png)
> 
> Looks to be all correct now

This also fixed the issues with entity sliding, so my theory either was correct or you also just fixed that at the same time lol
