### ISSUE TITLE
Add the Ability for Events to Detect GetNWInt()/GetNWBool()/GetNWString() options 

### ISSUE THREAD

**Issue by WolfKann** [CapsAdmin/pac3#1164]
Since PAC3 handles both server-side and clientside based commands, and we also have the ability to create pac commands with binds, I was surprised we don't have the option for net-var bools, or atleast I can't find any.

It'd be interesting if I could do

let's say in theory

an Event with the "NetInt" option, that lets me insert the string in the "find" catagory, so that when it detects it to be false (or true) when inversed, it activates.

a good example being as followed, I currently can only make an event that detects if I'm holding a cloaking weapon in my hands or that I have in my inventory to activate a hide event

![image](https://user-images.githubusercontent.com/17802255/155375600-5924ae6c-7297-40d4-b152-d1ad81ac562a.png)

however, this weapon allows you to equip other weapons/guns while it's active. by default if I'm holding this specific gun, it works fine, It'll de-render or allow me to do special effects for my pac3, like so.

![image](https://user-images.githubusercontent.com/17802255/155375654-7b1af4ec-b5ad-4d65-9baa-9fcd6cdb8f18.png)

however when it is active there is no current way to detect the NetBool/NetInt/NetFloat/Etc

![image](https://user-images.githubusercontent.com/17802255/155375990-48bd6a12-3e4f-4e35-accc-c3d0f833bb94.png)

and it ends up doing this, revealing the outfit and not allowing for any special effects.

I think if possible this feature would make it easier to make Pac3's dynamic to special items or surroundings, a good example being I have a Jump-Kit addon that allows you to run on walls using a NetBool for third person animations, if I could grab this netbool I could add extra effects via Pac3 too.

**Comment by CapsAdmin** [comment]
I like this idea. I can use `ply:GetNWVarTable()` to populate available properties and while i'm at it `ply:GetSaveTable()` with https://wiki.facepunch.com/gmod/Entity:GetInternalVariable

**Comment by WolfKann** [comment]
Yeah!

**Comment by WolfKann** [comment]
The question comes how easily would this be, and would we make it as it's own thing under "event" or make a new type of pac3 option called "NetVar"?

**Comment by WolfKann** [comment]
> I like this idea. I can use `ply:GetNWVarTable()` to populate available properties and while i'm at it `ply:GetSaveTable()` with https://wiki.facepunch.com/gmod/Entity:GetInternalVariable

Have you ever looked into this further? I might attempt it myself here soon but I don't wanna waste my time if you've already figured it out haha
