### ISSUE TITLE
player is invalid

### ISSUE THREAD

**Issue by Zulbem** [CapsAdmin/pac3#1169]
`addons/pac3/lua/pac3/core/shared/entity_mutator.lua:143: player is invalid
stack traceback:
    addons/pac3/lua/pac3/core/shared/entity_mutator.lua:70: in function <addons/pac3/lua/pac3/core/shared/entity_mutator.lua:69>
    [C]: in function 'assert'
    addons/pac3/lua/pac3/core/shared/entity_mutator.lua:143: in function 'RestoreMutations'
    addons/pac3/lua/pac3/core/shared/entity_mutator.lua:362: in function <addons/pac3/lua/pac3/core/shared/entity_mutator.lua:360>
    [C]: in function 'xpcall'
    addons/pac3/lua/pac3/core/shared/entity_mutator.lua:360: in function 'func'
    lua/includes/extensions/net.lua:33: in function <lua/includes/extensions/net.lua:18>
addons/pac3/lua/pac3/core/shared/entity_mutator.lua:143: player is invalid`

**Comment by thegrb93** [comment]
Pretty sure this was fixed a long time ago
