### ISSUE TITLE
Models with child bone part lagging behind

### ISSUE THREAD

**Issue by FarukGamer** [CapsAdmin/pac3#1170]
I was told by a friend that the current PAC3 version on the workshop has a problem with models that have bone parts as a child.
As described by him, it lags behind him when he moves, this problem does not occur when converting to the new pac.

i was provided with a test outfit to reproduce, use Kleiner as Playermodel.
[scarf_testing.txt](https://github.com/CapsAdmin/pac3/files/8209136/scarf_testing.txt)

**Comment by thegrb93** [comment]
Its one of these issues. I don't think updating pac caused it.

https://github.com/CapsAdmin/pac3/issues/894
https://github.com/CapsAdmin/pac3/issues/944

**Comment by thegrb93** [comment]
Possibly caused by https://github.com/CapsAdmin/pac3/commit/c4f7ded2844a2b6e3092c0aeda3e25822da06fbc @CapsAdmin

**Comment by thegrb93** [comment]
Never-mind, that only triggers when their model changes

**Comment by thegrb93** [comment]
I'm guessing some kind of ordering issue? Model is drawn before bone applied?

**Comment by FarukGamer** [comment]
I am not sure, haven't tried it myself to be honest.

**Comment by thegrb93** [comment]
Yeah, bone.lua is at fault. Reverting it seems to fix the issue. Just need to find which revision broke it.

**Comment by thegrb93** [comment]
git bisect to the rescue. I found the cause is https://github.com/CapsAdmin/pac3/commit/8f5716506db221da45f84fea0372ac814bbe8c24

**Comment by thegrb93** [comment]
Specifically this continue https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/part_pool.lua#L823

**Comment by CapsAdmin** [comment]
I wonder if the fix is then to make sure that update_legacy_bones is done in the same drawing context as the above.

**Comment by thegrb93** [comment]
Yeah it seems it was relying on the isDraw3DSkybox step. I imagine this affected maps where there was no 3D skybox even without the change.

**Comment by CapsAdmin** [comment]
I think I've fixed this in develop. It seems to be something with mixing legacy bones with the new model part.

**Comment by thegrb93** [comment]
Looks fixed, yeah.

**Comment by FarukGamer** [comment]
Can confirm it is fixed, thanks for your time and effort you put in Pac.
