### ISSUE TITLE
Visual 3 axis part movement not appearing/working on old outfits

### ISSUE THREAD

**Issue by Tox00** [CapsAdmin/pac3#1172]
as the title says, all my old outfits and dupes with outfits I cannot edit the position of parts using the visual axis movement, I can still move them using the coordinates in the part info, and cannot move new parts on the old groups either, however it all works fine with new groups and parts. I am not sure if "convert legacy parts to new parts" is supposed to fix this, as I have tried just clicking it and it has not done anything. Not sure if I could be missing steps if so, or if its not working.

**Comment by thegrb93** [comment]
I can look into what's causing it tonight

**Comment by Tox00** [comment]
alright, awesome. let me know if you need any examples or anything

**Comment by thegrb93** [comment]
You're talking about the red+green+blue axis that appears on a part and you can drag it right? Is there a lua error or anything? My outfits work fine with it.

**Comment by Tox00** [comment]
> You're talking about the red+green+blue axis that appears on a part and you can drag it right? Is there a lua error or anything? My outfits work fine with it.

Yes, that one. I don't recall a lua error popping up but I will look again in a minute.

**Comment by Tox00** [comment]
Alright, it seems it works fine on old outfits loaded normally, however a dupe with an outfit attached does not.
The only thing it printed in console was this:
[PAC3] unique id collision between part[model2][error][87] and part[model2][fueltank xx][85]

**Comment by thegrb93** [comment]
Ok, I'll try it out tomorrow

**Comment by CapsAdmin** [comment]
That warning is pretty bad. Is the outfit 5+ years old? 

Can we have access to the original outfit somehow?

**Comment by Tox00** [comment]
The dupe is only maybe a month old or so, it has many groups attached to different props as I was using PAC3 to detail a build I have, and if you want I can send the dupe, I should have checked to see if I had it saved as an outfit though to see if that would still work.

**Comment by CapsAdmin** [comment]
Alright, if you can send the dupe somehow that's even better.

**Comment by Tox00** [comment]
I'll boot up the game real quick and remove a thing or two off it and I will send it, be warned it uses DakTank so it may not fully dupe in correctly without it.

**Comment by Tox00** [comment]
Heres the dupe: https://mega.nz/file/CEpGBKAb#29pCmPwR1lU5CbnTWcqw8cAYO5oOWY7iAv8kQVP4QL8

**Comment by thegrb93** [comment]
It seems to be happening because the group they are in has 'Hide' checked. When I uncheck it, the axis things appear. I can't really tell whats going on other than that because there's still error models despite having installed DakTank.

**Comment by thegrb93** [comment]
I'm assuming the problem is models used to have the axis appear while hidden, but now they don't

**Comment by thegrb93** [comment]
That behavior has existed for a year though so I think it's normal.

**Comment by Tox00** [comment]
Sorry for the long delay, but that was the problem. I thought it wasn't hidden since the parts still appeared, that is another issue on its own, but that is the end of this issue. Thanks so much for all the help on this!
