### ISSUE TITLE
Workshop Addon is banned and will not work

### ISSUE THREAD

**Issue by FilmYTP** [CapsAdmin/pac3#1175]
Workshop Addon is banned so I cant use PAC at all

**Comment by FilmYTP** [comment]
![20220314164735_1](https://user-images.githubusercontent.com/101600448/158259071-f5d5f9ab-402c-4f52-914e-0ea5173c9cf9.jpg)

**Comment by AlucardN0SF3RATU** [comment]
I'm also having this issue I can't see any reason why Pac3 would be banned

**Comment by WolfKann** [comment]
It was mass reported once and they think it's because a bot just constantly keeps removing it now
