### ISSUE TITLE
Clips in a text get a completely different origin from the entity instead of the text's position.

### ISSUE THREAD

**Issue by pingu7867** [CapsAdmin/pac3#1176]
Basically I think that when PAC tries to get the right way to position the clip, the text part gets skipped, even though text is one of the parts with a proper orientation to be treated as an object (and therefore the clip should be on the text). So the clip goes straight for some kind of fallback position or a bone on the entity. To sum up, clip cuts fine, but not at the right position, the pac issue is that the text part stopped providing the position to the clip.

In the example we have texts and clips, on both a player and a prop (must be reassigned to the right prop because props get different entity numbers...), and both have clips defaulting back to the head, creating disagreeable results.

[text_clip.txt](https://github.com/CapsAdmin/pac3/files/8258886/text_clip.txt)
![image](https://user-images.githubusercontent.com/3782245/158519190-03eae741-19b7-488f-a0a5-7af18d62e488.png)

**Comment by thegrb93** [comment]
I'll take a look

**Comment by thegrb93** [comment]
Probably same issue as https://github.com/CapsAdmin/pac3/issues/1178 . This code being the cause https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/base_movable.lua#L55-L66 . Will look closer though

**Comment by thegrb93** [comment]
Looks like the problem is the clip is getting parented to the model instead of the text

**Comment by thegrb93** [comment]
Looks like the problem is this GetBonePosition here https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/parts/clip.lua#L43

Also the angle and translation addition is here completely wrong.

**Comment by thegrb93** [comment]
The GetBonePosition is returning the prop's position instead of the text's

**Comment by thegrb93** [comment]
An is_boney check as mentioned in https://github.com/CapsAdmin/pac3/issues/1178 would fix it. The check could be added inside the GetBonePosition function

**Comment by thegrb93** [comment]
See if the latest develop version fixes it. If not, then I probably need to revise that angle math.

**Comment by pingu7867** [comment]
Updated. Now works as intended. Grand.
![image](https://user-images.githubusercontent.com/3782245/158868835-fb45122d-8c41-4536-8f39-d8ad749ea698.png)
