### ISSUE TITLE
Parts attached to the entity part follow its origin instead of the selected bone.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#1178]
Adding a part to the entity will attach it to the origin of the entity part rather than the selected bone. This happens on every part except the bone part, which got fixed some time ago, @CapsAdmin probably remembers what it was.

Image: https://i.imgur.com/3GUwqFS.jpg
Outfit: [ent+mod.txt](https://github.com/CapsAdmin/pac3/files/8254100/ent%2Bmod.txt)

**Comment by thegrb93** [comment]
It's because of this code. https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/base_movable.lua#L55-L66

Thoughts on a fix, @CapsAdmin ? I'm guessing you just need to add a check for `is_entity_part` but I think there should really be an is_boney property or something.

**Comment by thegrb93** [comment]
Should be fixed by 02d0342f
