### ISSUE TITLE
PAC3 Randomly stops 'working'

### ISSUE THREAD

**Issue by Geo2204** [CapsAdmin/pac3#118]
So I run a server using Clockwork, alongside the PAC3 editor for some nice ways for players to be able to make their characters unique. I've been using it on Clockwork servers since the beginning of GM13, and it's always worked near flawlessly. However we're now getting these issues for the first time.

Essentially, after the server has been up for anywhere ranging from minutes to hours, or sometimes never at all, the player loses the ability to 'wear' their PAC, it doesn't run the command properly or something, even if you use 'pac_wear_parts' in console.

I can tell it's not working, because from third person I do not see the 'flickering' that occurs when loading hitting 'wear' on a PAC, alongside the fact that no one else can see them. However if someone had something loaded prior to this happening, their PAC would still be visible to everyone else.

I was wondering if there's perhaps a way of rebooting PAC server side without restarting the server, or a way to avoid this bug. 'pac_restart' and other commands do not work to fix this issue.

**Comment by LUModder** [comment]
Just change the map to the same map if you don't wanna hard restart the server.

**Comment by CapsAdmin** [comment]
no replies in over a month, feel free to reopen
