### ISSUE TITLE
Using_Physgun event does not work

### ISSUE THREAD

**Issue by DannyDan4** [CapsAdmin/pac3#1187]
The using_physgun pac event is not triggering properly in find simple mode. This was on a ULX-based server, so I'm unsure if this is related to the issue. However, if there's something I'm missing, please let me know, so I can get this PAC working.

**Comment by thegrb93** [comment]
Do you have more than one event? It looks like the way they did this event, multiple instances of it will have issues.

**Comment by DannyDan4** [comment]
That is correct; so having multiple would break _every_ instance of it, or just all but the first in the list?

**Comment by thegrb93** [comment]
All but the last I think

**Comment by thegrb93** [comment]
Should be fixed in develop now
