### ISSUE TITLE
Webaudio will not play anything

### ISSUE THREAD

**Issue by THEKILLER2134** [CapsAdmin/pac3#1188]
I have been battling with webaudio for around 2 days now. from using direct download links to reinstalling pac and a whole lot of other things. It did work around 5 days earlier and now nope nothing like it is not even there. I have been trying to get it all to work and have reached the end of my rope. I have used dropbox and made dl=1 and the dropboxusercontent stuff but nothing seems to work and it just remains silent. I have seen that the server i play on has a limit on it and won't allow it to work but seeing as i am a manager i just changed the value and it still does not work.  Any ideas as to how this can be solved and i have moved back and forward between github and workshop pac like 3 times.

**Comment by thegrb93** [comment]
noblock flag no longer works on dropbox which might have something to do with it.

**Comment by thegrb93** [comment]
Try another file host and see if that resolves the issue.

**Comment by THEKILLER2134** [comment]
tried google drive and before this post github and nothing seems to work. like it downloads and all but it does not seem to play like I am getting nothing in console that would indicate an error at all.

**Comment by thegrb93** [comment]
Could you give an example outfit file?

**Comment by thegrb93** [comment]
I can't imagine this being a problem everyone experiences otherwise we'd be getting a flood of reports about this.

**Comment by THEKILLER2134** [comment]
okay so i have tried a few new things and it still does not work I can confirm though that it is not the link to the file as I had a friend use it yesterday and it worked fine. I am getting 2 errors in console though (3d noplay noblock) - BASS_ERROR_TIMEOUT and (3d noplay noblock) - BASS_ERROR_FILEOPEN.

**Comment by thegrb93** [comment]
Try a different file format or a different file. Bass doesn't like the one you're trying to play for some reason.

**Comment by THEKILLER2134** [comment]
okay so wav does work. so i guess everything of mine is going from mp3 to wav now. anyway thanks for the help!

**Comment by thegrb93** [comment]
mp3 should work. Maybe try making them mono channel if they are stereo.

**Comment by thegrb93** [comment]
Anyway, it does seem to be a problem with your files rather than pac.
