### ISSUE TITLE
Pac3 removed from workshop

### ISSUE THREAD

**Issue by ilker2445** [CapsAdmin/pac3#1192]
Pac3 is removed from workshop AGAIN!

**Comment by h3ll0-w00rld** [comment]
There are temporary re-uploads from what I saw.

**Comment by Yagira** [comment]
just use the github one bruh

**Comment by ilker2445** [comment]
The addon is back on Workshop.

**Comment by SpiffyJUNIOR** [comment]
got removed again :\

**Comment by bjoern90** [comment]
> got removed again :\

okay and?

**Comment by Margen67** [comment]
#1240
