### ISSUE TITLE
Gmod crashes when loading a map with PAC3 

### ISSUE THREAD

**Issue by anonymoususer05** [CapsAdmin/pac3#121]
when i start an map on Gmod with the workshop version of PAC3, the game crashes.

**Comment by LUModder** [comment]
Back up your autoload if you don't have a second copy of that PAC and delete the autoload file.

**Comment by anonymoususer05** [comment]
where i can find this file?

**Comment by LUModder** [comment]
data/pac3

**Comment by anonymoususer05** [comment]
Okay, i guy said that i have to do this, i checked the data folder on the steamapps/common/garrysmod/garrysmod and no pac 3 folder is created, is it this the correct folder or no?

**Comment by LUModder** [comment]
https://dl.dropboxusercontent.com/u/67402346/ShareX/2015/03/2015-03-10_13-58-09.png

Should be here

**Comment by anonymoususer05** [comment]
Ok, i searched this folder for 2 days and didn´t fonud it, there´s no pac3 folder created there. What should i do? It´s a bug from my pc (OS: Windows 7 64 bits) or its othere problem?

**Comment by LUModder** [comment]
Try not loading into singleplayer for PAC, honestly, there's no reason to be in singleplayer with PAC as stuff breaks like entity scale.

**Comment by CapsAdmin** [comment]
no replies in over a month, feel free to reopen
