### ISSUE TITLE
Flexes no longer can use values other then 1 or 0

### ISSUE THREAD

**Issue by WolfKann** [CapsAdmin/pac3#1213]
You use to be able to use 0.1, 0.5, 0.7 etc, whatever and it would only apply the flex that much, the recent update now has it so using flexes at any value past 0 instantly turns it to 1 and does not let you use the value partially

**Comment by CapsAdmin** [comment]
Which update are you referring to? The garry's mod june 2022 update?

**Comment by thegrb93** [comment]
I don't see any code that would cause rounding

**Comment by Yagira** [comment]
I feel like this was fixed already, use the latest version https://github.com/CapsAdmin/pac3/archive/develop.zip

**Comment by WolfKann** [comment]
correction, I redid the pac and it works now, It might have a consistancy problem however or something because sometimes it works with old pacs and othertimes it doesnt.

it seems like with the recent pac3 update our best bet is just to remake everything, but legacy stuff is having it's own issues
