### ISSUE TITLE
When uploading a custom .mdl from an addon it says unsuccessful.

### ISSUE THREAD

**Issue by Huxley2** [CapsAdmin/pac3#1218]
Hi! Im currently trying to upload a custom model from a workshop addon onto my pac for a server I play on. Im using GMAD Extractor and creating a new zip file with the model and materials, then uploading to dropbox. I then use the "Experimental" tab and click model, changing my dropbox link from a dl=0 to a dl=1. After 2 seconds of loading it then changes to a red text that says unsuccessful.

If anyone can help me that would be highly appreciated, Ill provide more information if needed.

**Comment by thegrb93** [comment]
I think you just pack the files in an uncompressed zip archive. Not a gma.

**Comment by Techbot121** [comment]
`unsuccessful` is usually displayed if something went wrong with the download.
If it happens again make sure to check the console, which might give you more info as to why it failed.
