### ISSUE TITLE
Animation editor is Broken

### ISSUE THREAD

**Issue by DrAquafresh** [CapsAdmin/pac3#122]
With the coming of yet another god-awful update by Garry, the animation editor is now broken. When you attempt to create a new animation, or try to modify an existing one, you immediately get script errors and it becomes rendered useless. Any help or advice to fix this would be appreciated, thanks.

**Comment by DrAquafresh** [comment]
Also, here's what I got in the console

[PAC3] lua/vgui/dform.lua:132: bad argument #1 to 'RunConsoleCommand' (string expected, got nil)
  1. RunConsoleCommand - [C]:-1
   2. OnSelect - lua/vgui/dform.lua:132
    3. ChooseOption - lua/vgui/dcombobox.lua:95
     4. AddChoice - lua/vgui/dcombobox.lua:154
      5. DoClick - lua/pac3/editor/client/animeditor.lua:285
       6. unknown - lua/vgui/dlabel.lua:204

**Comment by LUModder** [comment]
Just ignore this mention. Just making sure I get the memo out.
@suchipi
