### ISSUE TITLE
'SetFlexWeight' (number expected, got nil)

### ISSUE THREAD

**Issue by Kofro** [CapsAdmin/pac3#1221]
[pac3] addons/pac3/lua/pac3/core/client/bones.lua:409: bad argument #1 to 'SetFlexWeight' (number expected, got nil)
  1. SetFlexWeight - [C]:-1
   2. ResetBones - addons/pac3/lua/pac3/core/client/bones.lua:409
    3. HideEntityParts - addons/pac3/lua/pac3/core/client/part_pool.lua:166
     4. RenderOverride - addons/pac3/lua/pac3/core/client/part_pool.lua:149
      5. fn - addons/pac3/lua/pac3/core/client/part_pool.lua:802
       6. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

addons/pac3/lua/pac3/core/client/bones.lua:409: bad argument #1 to 'SetFlexWeight' (number expected, got nil)
stack traceback:
	addons/pac3/lua/pac3/core/client/part_pool.lua:121: in function <addons/pac3/lua/pac3/core/client/part_pool.lua:120>
	[C]: in function 'SetFlexWeight'
	addons/pac3/lua/pac3/core/client/bones.lua:409: in function 'ResetBones'
	addons/pac3/lua/pac3/core/client/part_pool.lua:70: in function <addons/pac3/lua/pac3/core/client/part_pool.lua:61>
	[C]: in function 'xpcall'
	addons/pac3/lua/pac3/core/client/part_pool.lua:135: in function 'RenderOverride'
	addons/pac3/lua/pac3/core/client/part_pool.lua:802: in function 'fn'
	addons/ulib/lua/ulib/shared/hook.lua:109: in function <addons/ulib/lua/ulib/shared/hook.lua:92>[PAC3] failed to render Player [86][Cringer]:

**Comment by Yagira** [comment]
It's already fixed on the develop branch, you can install it from https://github.com/CapsAdmin/pac3/archive/develop.zip
If you want to stick to the workshop then you'll have to wait for an update

**Comment by ColorfulDancer** [comment]
If the issue still affects, try to use CHROMIUM beta of Garry's Mod, it with the github version of PAC3 helped me with fixing the issue
