### ISSUE TITLE
Cannot look up or down once t-pose is enabled

### ISSUE THREAD

**Issue by jammingisbadass** [CapsAdmin/pac3#1223]
Prevents me from looking up or down once the T-Pose option in the right-click dropdown menu has been enabled. Only way to fix is to close the map.

This only started occurring when I got my new computer recently, which leads me to believe its some kind of hardware/software issue, but I still have no idea what could be causing it.

Video showcasing the issue:

https://user-images.githubusercontent.com/112972265/188701330-57a6ef2e-3174-4f5f-8e7b-f52e06fe63ee.mp4

**Comment by Techbot121** [comment]
Hi, I tried doing the exact same on the workshop and develop version and I cannot reproduce it.
I'm going to assume this might be an addon conflict somehow.

**Comment by jammingisbadass** [comment]
thank you for the reply!

I figured out it was an addon conflict after joining a friend's game, and ill be sure to look out for whichever addon is causing it.

**Comment by jammingisbadass** [comment]
I've found the addon causing the issue, and it appears to be a reuploaded version if View Extension
I'll link it here just in case. But nevertheless, thank you for your help!

_the addon in question:_ https://steamcommunity.com/sharedfiles/filedetails/?id=2816113584&searchtext=view+extension
