### ISSUE TITLE
I can't see other peoples PACs. They just flicker on for half a second and don't stay up.

### ISSUE THREAD

**Issue by LuciferXerxes** [CapsAdmin/pac3#123]
This started last night, I think, but I didn't notice it till today. Basically I can only see people's selected model. If they have a PAC model in use, I can't see it. It's there, because it will flicker on for a moment, but it isnt staying. No one else on the server is having this problem, so it may be something on my end. But if someone knows what's happening, please help me.

**Comment by LUModder** [comment]
Low draw distance?

**Comment by CapsAdmin** [comment]
closing due to no feedback within a month, reopen if you still have this issue
