### ISSUE TITLE
websound doesn't work with local sounds after wear outfit

### ISSUE THREAD

**Issue by PrincessMargarita** [CapsAdmin/pac3#1233]
this problem appeared a long time ago, it concerns both single-player and multiplayer. the local sound after these actions stops working even without wear, until I write to the pac_restart console

https://youtu.be/9hI_OHD4Ilw

**Comment by Yagira** [comment]
Download the latest version from https://github.com/CapsAdmin/pac3/archive/refs/heads/develop.zip and test it on singleplayer. Should be fixed.

**Comment by PrincessMargarita** [comment]
> Download the latest version from https://github.com/CapsAdmin/pac3/archive/refs/heads/develop.zip and test it on singleplayer. Should be fixed.

Thank you for pointing out this version. There is no such problem here, but a new one has appeared here. Web sounds from a link, for example from dropbox, they have a bad repeat here. there is no such problem in the workshop version

https://youtu.be/aq7KLgSqdtI

**Comment by Yagira** [comment]
Re-download and try again. The link is the same.

**Comment by PrincessMargarita** [comment]
> Re-download and try again. The link is the same.

the problem is solved. thank you
