### ISSUE TITLE
Legacy entity breaks materials on any bonemerged models

### ISSUE THREAD

**Issue by PrincessMargarita** [CapsAdmin/pac3#1234]
Another long-standing problem that I want to report. I think that everything will be clearly visible on the video. This applies to the materials to which the path was specified, as well as to the presence of the entity. Bonemerge and translucent makes the error more noticeable. The more such models exist, where the path of the material is indicated to them and bonemerged, it makes lower fps

https://youtu.be/-vnW5SPRFAg

**Comment by thegrb93** [comment]
Can you not use legacy entity then? I don't think we're fixing legacy part issues anymore.

**Comment by PrincessMargarita** [comment]
> Can you not use legacy entity then? I don't think we're fixing legacy part issues anymore.

I may not use it. There is a server on which they do not plan to use the new pac 3 (current). But if fixing legacy parts was not part of the plans, then I have no questions. Your answer is the main thing I wanted to know. Thank you
