### ISSUE TITLE
bone follow part crashes on wear with TF2 rigs

### ISSUE THREAD

**Issue by pingu7867** [CapsAdmin/pac3#1235]
(possibly other non-valvebiped rigs too)

[bone_crash.txt](https://github.com/CapsAdmin/pac3/files/9628362/bone_crash.txt)

**Comment by pingu7867** [comment]
For other information, if the follow part is outside of the player entity, no crash occurs.

I do have stack traces.


Executable: D:\games\SteamLibrary\steamapps\common\GarrysMod\bin\win64\gmod.exe

-Lua Stack Traces-
==================
  Client
    0. SetupBones - [C]:-1
      1. GetModelBones - addons/pac3-develop/lua/pac3/core/client/bones.lua:125
        2. GetBonePosAng - addons/pac3-develop/lua/pac3/core/client/bones.lua:303
          3. GetBoneMatrix - addons/pac3-develop/lua/pac3/core/client/base_movable.lua:84
            4. BuildWorldMatrix - addons/pac3-develop/lua/pac3/core/client/base_movable.lua:116
              5. GetWorldMatrix - addons/pac3-develop/lua/pac3/core/client/base_movable.lua:136
                6. GetWorldPosition - addons/pac3-develop/lua/pac3/core/client/base_movable.lua:147
                  7. BuildBonePositions2 - addons/pac3-develop/lua/pac3/core/client/parts/bone.lua:198
                    8. (null) - addons/pac3-develop/lua/pac3/core/client/parts/bone.lua:82
                      9. SetupBones - [C]:-1
                        10. GetModelBones - addons/pac3-develop/lua/pac3/core/client/bones.lua:125
                          11. GetBonePosAng - addons/pac3-develop/lua/pac3/core/client/bones.lua:303
                            12. GetBoneMatrix - addons/pac3-develop/lua/pac3/core/client/base_movable.lua:84
                              13. BuildWorldMatrix - addons/pac3-develop/lua/pac3/core/client/base_movable.lua:116
                                14. GetWorldMatrix - addons/pac3-develop/lua/pac3/core/client/base_movable.lua:136
                                  15. GetWorldPosition - addons/pac3-develop/lua/pac3/core/client/base_movable.lua:147
                                    16. BuildBonePositions2 - addons/pac3-develop/lua/pac3/core/client/parts/bone.lua:198

  Server
    *Not in Lua call OR Lua has panicked*

  MenuSystem
    *Not in Lua call OR Lua has panicked*

**Comment by thegrb93** [comment]
SetupBones and BuildBonePositions infinite loop due to FollowPart https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/parts/bone.lua#L198

I imagine this can be also triggered by making bone parts' FollowPart aim at each other.
Maybe GetModelBones shouldn't call SetupBones? @CapsAdmin

**Comment by thegrb93** [comment]
A simple fix would be to check whether SetupBones has been called already.

**Comment by thegrb93** [comment]
@pingu7867 mind checking if the fix works?

**Comment by pingu7867** [comment]
works. not sure if side effects might exist. I'll post another issue if I find one.
