### ISSUE TITLE
Legacy bones not functioning properly (indirectly influences jigglebones, alt bones not applying)

### ISSUE THREAD

**Issue by aoesza** [CapsAdmin/pac3#1238]
Technically 2 issues in 1

alt bones will not apply properly in models
https://cdn.discordapp.com/attachments/807633166118027315/1026610645862457354/testrender111.mp4
bone being moved is a control bone, alt bones are in the model, alt bones will not follow control bone, all types of bones in that PAC are legacy

legacy bones make jiggle bones 'stiffer' for some reason, used to be an issue with mixing legacy+normal bones in a model, now is caused by just legacy
https://cdn.discordapp.com/attachments/807633166118027315/1026618948785016933/testrenderaaaa52.mp4
https://cdn.discordapp.com/attachments/807633166118027315/1026621083291492392/jiggle_example.mp4

ik you guys don't want to touch legacy stuff but you can't do alt bones without legacy and they are very useful for fixing rigging errors on models

**Comment by thegrb93** [comment]
P sure this change broke it. https://github.com/CapsAdmin/pac3/commit/bf760c15fb15e52e5a55f817837c9226424ba2b3#diff-45d23872c8892b732b2936d63f38478dcd596daef4996b4b31fe6879437036e5L447

**Comment by thegrb93** [comment]
Should hopefully be fixed. Let me know if not

**Comment by aoesza** [comment]
bones appear to be applying properly but legacy bones still stiffen/interfere with jiggle bones compiled in the model for some reason

**Comment by thegrb93** [comment]
Ok, should be fixed for real now
