### ISSUE TITLE
pac3 default ball model not showing up

### ISSUE THREAD

**Issue by bananaduckgithub** [CapsAdmin/pac3#1239]
as i enter a multiplayer or singleplayer server, the default ball model for the pac3 editor does not show up, any other models do but the default one doesn't, if possible is there any fix?

**Comment by Techbot121** [comment]
are you using the workshop addon?

**Comment by sumpjumper** [comment]
as of this moment i cant acsess the workshop item of PAC3, and have tryed the git version still sporting broken default sphere
(most of my pacs are made of thease spheres sadly)

**Comment by thegrb93** [comment]
You'll have to install the mod locally by extracting the github zip into your addons folder. Steam is working on getting the workshop issue resolved.

**Comment by Margen67** [comment]
> You'll have to install the mod locally by extracting the github zip into your addons folder. Steam is working on getting the workshop issue resolved.

#1240
