### ISSUE TITLE
For some reason some of the sentences are white in the pac3 editor

### ISSUE THREAD

**Issue by Cyberthekid** [CapsAdmin/pac3#124]
![2015-03-16_00002](https://cloud.githubusercontent.com/assets/11510205/6679228/084bbb6c-cc13-11e4-9996-ac91c31bc0e3.jpg)
 notice that some stuff is clear in the pac3 editor so that screws me up, please help

**Comment by LUModder** [comment]
Change font

**Comment by Cyberthekid** [comment]
Wat?

**Comment by Cyberthekid** [comment]
How do I do that?

**Comment by Cyberthekid** [comment]
It won't work

**Comment by LUModder** [comment]
Right click outside editor > PAC font

**Comment by Cyberthekid** [comment]
K also it's happening to other people 2

**Comment by thegrb93** [comment]
I don't see the problem. What are you talking about?

**Comment by Cyberthekid** [comment]
K
