### ISSUE TITLE
Toggling PAC on and off based on player status?

### ISSUE THREAD

**Issue by brandonsturgeon** [CapsAdmin/pac3#125]
Sorry the name is a bit vague, and this may not actually be an issue, more of a "how do I?"

I'm running a Build/Kill server right now where players are able to turn on and off PvP mode. I need it so when they enable PvP, it disables their PAC (To prevent cheating with hitbox manipulation, model size, etc) and then when they go back to Build mode, re-enables the PREVIOUS PAC.

Currently I have it so when they enable PvP, it runs the `pac_clear_parts` command and then watches the `PrePACConfigApply` hook and returns false if they're in PvP mode. This works but I feel like it's a bit dirty, because that hook is called for every PART that is applied, which means if you wanted to say "You can't use PAC while in PvP mode", it'd print as many times as there are Parts to apply. 
**This is actually a problem though, if you `return false` inside of that hook, it will still print a "[PAC3]" string to chat for every part there is to apply**

It's mostly the second part I'm having trouble with. I can't seem to find any good way to save their current PAC and then using that saved data to re-apply their PAC when they go back into build mode. The `PrePACConfigApply` returns an outfit_data, but it doesn't seem like this is something I can save and then use later.
There's also the command `pac_wear_parts NAME` where Name is the name of the PAC outfit. This could be super helpful if I was able to save the outfit name when they went into PvP mode, and then use that when they go back into build mode.

Anyone have any ideas? Really hoping it's something much easier than I'm thinking.

Great stuff here guys, seriously do appreciate it. Have a great day!

**Comment by CapsAdmin** [comment]
there are some functions that you could try on the client

for _, ply in pairs(player.GetAll()) do pac.IgnoreEntity(ply) end 
during pvp and
for _, ply in pairs(player.GetAll()) do pac.UnIgnoreEntity(ply) end
to allow again

this is pretty much like disabling pac

**Comment by brandonsturgeon** [comment]
Not able to give it a try now, but I know that when you turn off PAC clientside, the modelsize of other players who use PAC stays the same. For example, if they change their model to 0.5*regular size, turning off PAC locally wouldn't make their modelsize change back to normal.

Would pac.IgnoreEntity(ply) have the same effect, or would it leave their modelsize as-is?

**Comment by CapsAdmin** [comment]
The model size of players might be set on the server (pac_modified_model 0 to turn it off)

If I recall correctly there is no way to do it with a pac function on the server at the moment. What you can do in the meantime is to call ply:SetModelScale(1) on everyone during pvp.

**Comment by CapsAdmin** [comment]
no replies in over a month, feel free to reopen

**Comment by brandonsturgeon** [comment]
The way I have PAC disabled during PVP just returns false every time they try to apply a single part, which works for the most part, but I think you can still change player scale and stuff. Would I need to have some sort of timer that runs a function on everyone in PvP mode? The function would reset their model scale, model color/alpha/material. Or do you think there's a better/more efficient way to do that?

(Hope this comment doesn't re-open the issue)
