### ISSUE TITLE
OBJ Problems

### ISSUE THREAD

**Issue by Ameno-Sagiri** [CapsAdmin/pac3#126]
Since the New Garry's Mod update, I seem to be having problems with certain custom models on some of my PACS. These are models that worked prior to the update, and now they just refuse to work and spit out a console error.

When the model is queued and begins to load up, it gets to either 98% or 99% in Processing Faces, and then it stops and gives me a console error:

Error in hook Think: addons/pac3-master/lua/pac3/core/client/libraries/urlobj.lua:250: addons/pac3-master/lua/pac3/core/client/libraries/urlobj.lua:159: attempt to index a nil value
stack traceback:
	[C]: in function 'error'
	addons/pac3-master/lua/pac3/core/client/libraries/urlobj.lua:250: in function 'fn'
	addons/ulib/lua/ulib/shared/hook.lua:179: in function <addons/ulib/lua/ulib/shared/hook.lua:162>
	[C]: in function '‭‬‌⁬﻿‎⁯⁮⁭'

[ERROR] 
  1. unknown - [C]:-1

I tested it on that Meta Construct version and this version and they both seem to give the same result. 

I hear traces are broken in this Garry's Mod update?

**Comment by LUModder** [comment]
Where is/are said OBJ's hosted?
