### ISSUE TITLE
PAC3 MDLs are cached but cache is never used at all

### ISSUE THREAD

**Issue by sr229** [CapsAdmin/pac3#1260]
In cases when the remote is unreliable, caching usually works to not pressure the remote since you would look for the cache first before attempting to pull for origin, which works for the OBJs, but for some reason, MDL ZIPs feels like they are never cached and always has to pull from remote despite being cached on the same manner as OBJs.

**Comment by Yagira** [comment]
Yeah it seems like the cache files can't be found in some cases but I'm not sure if that's the problem you're having.

Let me know if 39c35868d87cfa1de7891974e7098b900369146f fixes it for you.

**Comment by sr229** [comment]
Verified https://github.com/CapsAdmin/pac3/commit/39c35868d87cfa1de7891974e7098b900369146f works. Leaving it open since I think this should be merged to the master branch.

**Comment by thegrb93** [comment]
@CapsAdmin can we delete master branch. It's unnecessary extra work. Same to workshop branch.

**Comment by CapsAdmin** [comment]
@thegrb93 I've been wanting to delete the workshop branch and replace it with master, but develop is useful to have in cases like this for testing.

Branch divergence is the issue here really.
