### ISSUE TITLE
Things invisible in the PAC Editor

### ISSUE THREAD

**Issue by Ameno-Sagiri** [CapsAdmin/pac3#127]
Since the new Garry's Mod update, there seems to be a problem with the Derma of the PAC Editor. 

Certain values in the menus and lists are invisible until you double click on them to highlight them. 

Examples are Size, Color, Position, etc. I also noticed the T-Pose button under the Player tab is invisible.

**Comment by CapsAdmin** [comment]
fixed i think

**Comment by Ameno-Sagiri** [comment]
We'll check it out tomorrow...
