### ISSUE TITLE
PAC3 overwrites other addons :ManipulateBoneAngles()

### ISSUE THREAD

**Issue by Kotyarishka** [CapsAdmin/pac3#1270]
Hi! So I am addon developer that provides some aminations for players. I'm using :ManipulateBoneAngles() for this. It's seem that PAC3 overwrites this behavior in some way. I coudn't find a way around this. Is there anything I can do about it on my side?

**Comment by thegrb93** [comment]
You want to put your manipulations in this hook @Kotyarishka 

https://github.com/thegrb93/StarfallEx/blob/3fe27da6649d00358c0df89d2a0cfc2fa45f49c3/lua/starfall/libs_sh/entities.lua#L17-L33

**Comment by Kotyarishka** [comment]
I assume I can use [this method](https://github.com/thegrb93/StarfallEx/blob/3fe27da6649d00358c0df89d2a0cfc2fa45f49c3/lua/starfall/libs_sh/entities.lua#L144-L154) to do this?


Can't see a way to modify [`manips` table](https://github.com/thegrb93/StarfallEx/blob/3fe27da6649d00358c0df89d2a0cfc2fa45f49c3/lua/starfall/libs_sh/entities.lua#L144-L154) in other way.

**Comment by Kotyarishka** [comment]
Oh, my bad. Didn't see that it was a completely different repository. Thank you!
