### ISSUE TITLE
Suggestion: A variable, similar to feedback() in proxies, which can take the previous state of a variable

### ISSUE THREAD

**Issue by DannyDan4** [CapsAdmin/pac3#1279]
I'd like to see a variable added to proxies, which would work similarly to feedback(), but instead of taking that specific proxy's previous output as its input, it'd take the previous state of that variable as the input for the proxy. The primary use I'm thinking of for this would be to allow an object to spin at different rates depending on certain events, say firing a gun, but without having to reset the rotation of the object.

**Comment by Yagira** [comment]
Try the `property()` proxy. You can use it to get the current value of any property on the parent/target part and pass it to another.
Example: [property_proxy.txt](https://github.com/CapsAdmin/pac3/files/10563517/property_proxy.txt)

**Comment by DannyDan4** [comment]
oh! Could you do a review of the https://wiki.pac3.info/part/proxy part of the PAC3 wiki, and get that added to the list, along with any others that may be missing?

**Comment by DannyDan4** [comment]
There's not really anywhere fully in-depth & up-to-date documentation-wise, in either proxies or events, so I'd really appreciate you reviewing that! I'll test out the property() value later tonight, and see what it's like, and if it's what I was thinking of, and close this issue if that's the case. Thanks for the help!

**Comment by DannyDan4** [comment]
Looks like this is exactly what I wanted! Thanks for the help!
