### ISSUE TITLE
Can't see numbers for properties. PLZ FIX

### ISSUE THREAD

**Issue by cyborgebolt** [CapsAdmin/pac3#128]
I am trying to use the pac3 and decided to make a new pac, but the numbers are white. i noticed some of the other words are white because when i was looking through all the toggle settings they were white on white background. I really need this fixed in order to edit my stuff. I tried going through the different toggles and nothing is helping

**Comment by LUModder** [comment]
Update broke it, hopefully it'll be fixed soon.

**Comment by CapsAdmin** [comment]
I thought I fixed this.

**Comment by CapsAdmin** [comment]
reopen if not fixed
