### ISSUE TITLE
fire_bullets event isn't responding when firing a melee weapon

### ISSUE THREAD

**Issue by g3n3r1c-u53rn4m3** [CapsAdmin/pac3#1285]
https://user-images.githubusercontent.com/112830178/236640587-6b50e728-001e-4f4d-9358-b55327950cf4.mp4

I tried to make a metrocop in the PAC3 system, and so far it'd been working out, but now i can't have a light show up when i fire my melee weapon. I've tested it on sandbox, on other weapons, it seems to just not respond when firing a melee weapon.

**Comment by pingu7867** [comment]
that's because fire_bullets is not there to detect just any and all attacks, but specifically from weapons that use bullets...

the event to use for general attacks is animation_event, with "attack primary"

this is not a bug.

**Comment by g3n3r1c-u53rn4m3** [comment]
ah. i see. thanks
