### ISSUE TITLE
+pac_events not working

### ISSUE THREAD

**Issue by Spectator-v1** [CapsAdmin/pac3#1289]
when i bind a button to +pac_events it does not work, saying "Unknown command: +pac_events +" and i cant use the event wheel
![gmod_w8ZT4SgnFz](https://github.com/CapsAdmin/pac3/assets/91749205/d29fb888-5cb5-43a9-9c45-e19a5237c156)

**Comment by pingu7867** [comment]
sounds like an old or unofficial pac version on a server or a weird reupload you got from who knows where.

**Comment by Spectator-v1** [comment]
> sounds like an old or unofficial pac version on a server or a weird reupload you got from who knows where.

i got it from the steam workshop

**Comment by Spectator-v1** [comment]
so, how do i fix this?

**Comment by pingu7867** [comment]
I guess it is strange. The event wheel is in the workshop version... I don't know what could be removing the command. It is in theory possible that an addon is removing this command. I don't know what would or why it would.

Potential fixes I'm thinking of:
1-Disable all your addons except pac3
2-Verify your game files on Steam
3-Delete your garrysmod/garrysmod/lua folder and repeat step 2 to reacquire the right lua files for gmod to run
4-See if there's any folder-looking addons in your addons folder and delete/move them out, then restart gmod

**Comment by Spectator-v1** [comment]
alright, it seems to have worked with 3, thanks
