### ISSUE TITLE
attack primary@@ in animation event only works when jumping

### ISSUE THREAD

**Issue by ZzZMarkJonesZzZ** [CapsAdmin/pac3#129]
If I have an animation event set up with the find set to "attack primary@@" it will only play the sound I have the event linked to when I jump.

For example, I fire my pistol and it won't play the sound I set. When I jump and fire the pistol, it will play the sound I set.

Fix?

**Comment by LUModder** [comment]
Invert it

**Comment by ZzZMarkJonesZzZ** [comment]
I did, I'm not a noob. If I didn't invert it, it would be playing constantly and would stop when I jump. My problem is is that it plays ONLY when I jump AND shoot. I don't think you can read.

**Comment by LUModder** [comment]
So you decide to judge me based on me just skim reading the issue. Wow.

This is how I have mine set up
![](http://i.imgur.com/v1MBmPh.png)
And the sound event setup
![](http://i.imgur.com/Kg4jNVq.png)

**Comment by ZzZMarkJonesZzZ** [comment]
When I use your setup it doesn't work at all.

**Comment by Ameno-Sagiri** [comment]
Works for me. What exactly are you attacking with. Specifically, which addon/swep/weapon in particular. Maybe the SWEP doesn't trigger attack primary, I've come across a couple like that.

**Comment by ZzZMarkJonesZzZ** [comment]
I've tried Crowbar and Pistol

**Comment by CapsAdmin** [comment]
reopen if this is still an issue
