### ISSUE TITLE
Suggestion: Mesh Cloth part?

### ISSUE THREAD

**Issue by Ameno-Sagiri** [CapsAdmin/pac3#132]
Not sure if this can be done, because (forgive me I'm wrong here) of meshcloth in its current form using serverside physicst I recently came across a very old addon that was fixed up called MeshCloth. It lets you use it on any prop to give it realistic physics as if it's cloth. For instance, you could turn a phx plate into a waving movable cape. 
http://steamcommunity.com/sharedfiles/filedetails/?id=420325009

Upon seeing this, I was wondering if it would be possible to implement this as a PAC, even though PAC is clientside. I was thinking of ways it could be done, and maybe you would need to set up anchor points and possibly have it collide with your own player model. Anchor points being, you attach one corner to your right thigh, and the left corner to your left thigh, or you set them to follow other models on your PAC much like how you have to set Point A and Point B on ropes. 

Maybe it would be too intensive? Maybe you can't use this guys code? Maybe he WOULD let you adapt his code? Maybe it wouldn't work if it's entirely clientside? I'm not sure.

Just an idea to try out, let me know if it's impossible and why it wouldn't be possible if so.

**Comment by CapsAdmin** [comment]
It's possible to add but it may be a little slow. I'll maybe add it in the future.
