### ISSUE TITLE
Pac3 Screen shake with Custom URL models on Entity model

### ISSUE THREAD

**Issue by survivaler049** [CapsAdmin/pac3#1320]
there is a bug with custom url models when I wear my pac3 with any custom model and start walking, running or jumping the screen goes nuts and it is like when I have low fps then the custom model disappear and I see my Gmod PM
when I wear it again the custom model appears back but when I start to walk, run or jump it disappear again it Only does it with Entity Model
![Screenshot 2023-11-13 154855](https://github.com/CapsAdmin/pac3/assets/63236848/c6e2e60e-9673-4034-a1f1-2a4d99a4791b)

I tried to change pac3 addon to new version but it didn't fix it and other players are telling me that some events (custom commands are active even when on my end they are disabled and it happens with songs with web sound they can hear it but I can't) are happening even when I don't see anything on my screen and when I try to activate them the whole pac3 shows an error full of codes and my game crashes from the server

I can't play on any servers with my pac3
this doesn't happen on single player only the model low fps thing and those pac3 doesn't show any error in single player only my screen shakes as it would be on low fps and my model disappear

this wont happen with simple Model
only with Entity model that replaces the whole entity with model and animations.

**Comment by thegrb93** [comment]
Could you try attaching the outfit file here so we can try it?

**Comment by survivaler049** [comment]
[priest.txt](https://github.com/CapsAdmin/pac3/files/13342220/priest.txt)
here is only the outfit
(I'm using github version of pac3 and I don't have any addons that would effect pac3)
I have only simple third person mod and ulx mods

the bug happens with All my pac3 that replaces the entity model with url one
I can't send a video since it is limited to 10 mb

**Comment by survivaler049** [comment]
I don't have any addons that would force me to wear just regular PM
![Screenshot 2023-11-14 113004](https://github.com/CapsAdmin/pac3/assets/63236848/fb0116a8-cb9b-4c9f-b82f-f4af8fb35233)
that's that I have on my addons
the workshop one has only 2 maps that are big city and another big map.

**Comment by survivaler049** [comment]
I even verify my folder be integrity to fix some problems and nothing helps

**Comment by thegrb93** [comment]
Try without all that ulx, ulib, and slib stuff. Not sure what llm is either, but it shouldn't take too long to try without addons to see if that's the cause.

**Comment by survivaler049** [comment]
it is still not working after I tried to disable all my addons everything that I mad there on list it is still doing it that means it is something to do with pac3

I could send you my pac_develop if you find anything weird in lua or in game settings just let me know

here is the pac3 file (I'm using one drive for that)
https://1drv.ms/u/s!AiG-Fj_A1b-NjQPp4aZAh7DBxvfb?e=vU6Za0

**Comment by survivaler049** [comment]
if it is possible how can I restart every Pac3 settings (the Gmod console)
it may fix the issue if you don't having this issue

I tried new pac3 version or my old and the bug still remains in the game

**Comment by survivaler049** [comment]
I'm gonna try completely remove all Gmod files and do an hard reset on Gmod
if it fixes the problem I'll let you know

**Comment by survivaler049** [comment]
yea now it is fixed

but I don't guarantee that this bug was only my problem I think maybe others can have this issue too
thanks for the help

**Comment by thegrb93** [comment]
So it was possibly a setting? Maybe your current player model was something pac didn't like? Hard to know.
