### ISSUE TITLE
Material parts gone from editor after Gmod update (19th Dec 2023)

### ISSUE THREAD

**Issue by Generic-Name-Here** [CapsAdmin/pac3#1327]
Howdy,
Seemingly today's Gmod update has broken material parts as they no longer appear in the editor, aside from legacy materials which seems to work fine.

(edit)
Loading a Pac which used material parts causes the parts to change into a blank part and the models that were using these parts will no longer have any materials and will just use error textures.
![ec18cb1ac1efb8839676a7ed9b03ec4b](https://github.com/CapsAdmin/pac3/assets/20357923/da2af021-8b28-493d-8da3-fd454830661b)

The same issue occurs with both master and develop branches of Pac.
I have tested on the default and x86-64/64bit branches of Gmod as well as a fresh install of both.
I have tested with all addons disabled.
(Please let me know if you need anymore information and I'll try to provide as best I can.)

I get the following error in console.
```
Clientside Lua startup!
loading all parts

[ERROR] CreateConVar: Invalid ConVar name! (pac_enable_material_eye refract)
  1. RegisterPart - lua/pac3/core/client/parts.lua:89
   2. Register - lua/pac3/core/client/class.lua:204
    3. unknown - lua/pac3/core/client/parts/material.lua:598
     4. include - [C]:-1
      5. LoadParts - lua/pac3/core/client/parts.lua:137
       6. unknown - lua/pac3/core/client/init.lua:59
        7. include - [C]:-1
         8. unknown - lua/autorun/pac_core_init.lua:29


[ERROR] lua/pac3/core/client/parts.lua:102: attempt to index local 'cvar' (a nil value)
  1. RegisterPart - lua/pac3/core/client/parts.lua:102
   2. Register - lua/pac3/core/client/class.lua:204
    3. unknown - lua/pac3/core/client/parts/material.lua:598
     4. include - [C]:-1
      5. LoadParts - lua/pac3/core/client/parts.lua:137
       6. unknown - lua/pac3/core/client/init.lua:59
        7. include - [C]:-1
         8. unknown - lua/autorun/pac_core_init.lua:29
```
![8944633ff8bc9ad2fb49403b54c24503](https://github.com/CapsAdmin/pac3/assets/20357923/065ed8b8-ceb6-4449-9a13-bf4d884fc892)

**Comment by wrefgtzweve** [comment]
Should be fixed with https://github.com/CapsAdmin/pac3/commit/a8c1adc8f0c5f3533fd303c464faaa64c24a478f
See if the develop branch works for you

**Comment by Generic-Name-Here** [comment]
Normal materials shows up and works just fine as well as unlitgeneric and refract, however eyerefract is still bugged as it now shows up in the menu however when adding the part to a pac it will turn into a blank part.

**Comment by wrefgtzweve** [comment]
Pushed another update that might fix it

**Comment by Generic-Name-Here** [comment]
That seems to have done the trick, tested all the material types and they work perfectly fine now!
