### ISSUE TITLE
PAC3 files deleted anyway how i can restore it?

### ISSUE THREAD

**Issue by karlo346** [CapsAdmin/pac3#133]
Hey so recently my computer has to update and then suddenly my pac files got deleted even the backups.Any way i can restore the files?Please help.

ASAP

                                                                                                                                      -Requiem
=(server) =Intertech 
=Operator

**Comment by LUModder** [comment]
Restore from backups, that is, if you ever made any restore points. Otherwise, you're screwed.

**Comment by karlo346** [comment]
Oh flex?
from meta struct i suppose
well i didnt set up any backup in my comp so particularly im screwed

**Comment by karlo346** [comment]
but is there a program that can restore files?

**Comment by LUModder** [comment]
There is, but to truly get the files fully back is impossible because data can get overwritten, you can try to recover the data if you would like, but it might not be 100% perfect.

**Comment by Ameno-Sagiri** [comment]
Should have backed up your PAC3 folder in Data in Garry's Mod.

**Comment by Python1320** [comment]
Some technical solutions include
 - storing outfits on server for restoring and possibly other uses
 - binary module for backup that can't be removed by GMod otherwise
 - link dropbox to your pac data folder (you can restore deleted files)

**Comment by karlo346** [comment]
thanks for the help guys
