### ISSUE TITLE
After the last commit in the develop branch, at the stage of connecting to the server, a Lua error occurs.

### ISSUE THREAD

**Issue by ghost** [CapsAdmin/pac3#1336]
Actually, subject.
After this commit:
https://github.com/CapsAdmin/pac3/commit/1088e45e7c07cd1203a22dd788faca3db840a79b
At the stage of connecting to the server, a Lua error occurs:
```
[pac3] addons/pac3/lua/pac3/extra/shared/net_combat.lua:128: table index is nil
  1. unknown - addons/pac3/lua/pac3/extra/shared/net_combat.lua:128
   2. include - [C]:-1
    3. unknown - addons/pac3/lua/pac3/extra/shared/init.lua:5
     4. include - [C]:-1
      5. unknown - addons/pac3/lua/pac3/extra/client/init.lua:3
       6. include - [C]:-1
        7. unknown - addons/pac3/lua/autorun/pac_extra_init.lua:32
```

**Comment by pingu7867** [comment]
I don't understand it. There's nothing fancy or particularly risky going on at that line, it's just declaring some table entries with the Disposition enums, which should exist... But apparently they don't, at that point in time???

So I'll just patch it with the numbers these enums (global variables) lead to.
