### ISSUE TITLE
is_client doesn't do anything?

### ISSUE THREAD

**Issue by WolfKann** [CapsAdmin/pac3#1349]
I've attempted to use is_client numerous times to create client-side only events or hidden features in pac that I want for myself but not other players (Such as flashlights or other UI's) however the problem is, is_client doesn't do anything. It still lets other players view everything I make, and if I invert it, nobody can see anything I make, not even myself. I'm not sure if it's a bug with code or otherwise but  if someone could figure this out I'd appreciate it.

my pov (not inverted)
![image](https://github.com/CapsAdmin/pac3/assets/17802255/1ca3f56f-f4f5-4ee9-84e9-9f7c3c7de17c)
![image](https://github.com/CapsAdmin/pac3/assets/17802255/d16983d9-f11d-492f-b1ad-e9be1821f244)
friend pov (not inverted)
![image](https://github.com/CapsAdmin/pac3/assets/17802255/776964bb-1d5a-461c-b79a-984077dc11d6)

my pov (inverted)
![image](https://github.com/CapsAdmin/pac3/assets/17802255/82df3233-9160-4f11-af42-4c35c27c4ac1)
![image](https://github.com/CapsAdmin/pac3/assets/17802255/9139d1b3-13d5-4901-966a-d8a2f4215161)
friend pov (inverted)
![image](https://github.com/CapsAdmin/pac3/assets/17802255/3369adc7-ce15-48b9-a431-e03f23b9017d)

I've tried changing the operators, and root owner, and even moving the parts around and wearing the Pac to force a re-initialize of the parts but it still does not work.

**Comment by thegrb93** [comment]
That one is true if the part is attached to yourself. You want the 'viewed_by_owner' one.

**Comment by WolfKann** [comment]
viewed_by_owner? I don't see that one

**Comment by WolfKann** [comment]
Infact there's no event in either master or develop called "viewed_by_owner"

**Comment by thegrb93** [comment]
That's odd, I had it open in vscode earlier where I found that. I'll look again

**Comment by pingu7867** [comment]
> Infact there's no event in either master or develop called "viewed_by_owner"

Where are you looking? At the wrong repository, that's for sure.
It's right there at line 750.
https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/parts/event.lua



> That's odd, I had it open in vscode earlier where I found that. I'll look again

Don't be fooled into questioning yourself. You have enough historical memory to remember correctly. I personally added this. It's there.

**Comment by WolfKann** [comment]
> > Infact there's no event in either master or develop called "viewed_by_owner"
> 
> Where are you looking? At the wrong repository, that's for sure. It's right there at line 750. https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/parts/event.lua
> 
> > That's odd, I had it open in vscode earlier where I found that. I'll look again
> 
> Don't be fooled into questioning yourself. You have enough historical memory to remember correctly. I personally added this. It's there.

When I had checked both develop and master by searching for it, it did not appear. so unless something was reloaded, or when I swapped repositories it was gone.

it also wasn't in my server's version, which was a *recent* copy of develop. so. something doesn't add up.

**Comment by thegrb93** [comment]
It's not showing up in github search for some reason. I guess the develop branch isn't indexed.

**Comment by WolfKann** [comment]
That explains it
