### ISSUE TITLE
Error with Physics

### ISSUE THREAD

**Issue by rapidradiance** [CapsAdmin/pac3#1353]
i keep getting an error when unhiding an object with a physics inside it, the object used to work fine with no error but after i updated pac it started

**This is the error on develop**

[DLib] lua/dlib/extensions/extensions.lua:70: Tried to use a NULL physics object!
  1. __eq - [C]:-1
   2. EnableCollisions - lua/dlib/extensions/extensions.lua:70
    3. unknown - addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:77
     4. Enable - addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:286
      5. unknown - addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:252

Timer Failed! [Simple][@addons/pac3-develop/lua/pac3/core/client/parts/physics.lua (line 252)]

[DLib] lua/dlib/extensions/extensions.lua:70: Tried to use a NULL physics object!
  1. __eq - [C]:-1
   2. EnableCollisions - lua/dlib/extensions/extensions.lua:70
    3. unknown - addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:77
     4. Enable - addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:286
      5. unknown - addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:252

Timer Failed! [Simple][@addons/pac3-develop/lua/pac3/core/client/parts/physics.lua (line 252)]
lua/dlib/extensions/extensions.lua:70: Tried to use a NULL physics object!
stack traceback:
	addons/pac3-develop/lua/pac3/core/client/part_pool.lua:124: in function <addons/pac3-develop/lua/pac3/core/client/part_pool.lua:123>
	[C]: in function '__eq'
	lua/dlib/extensions/extensions.lua:70: in function 'EnableCollisions'
	addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:77: in function <addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:73>
	addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:286: in function 'Enable'
	addons/pac3-develop/lua/pac3/core/client/parts/physics.lua:187: in function 'OnThink'
	addons/pac3-develop/lua/pac3/core/client/base_part.lua:1216: in function <addons/pac3-develop/lua/pac3/core/client/base_part.lua:1193>
	addons/pac3-develop/lua/pac3/core/client/base_part.lua:472: in function 'CallRecursive'
	addons/pac3-develop/lua/pac3/core/client/part_pool.lua:88: in function <addons/pac3-develop/lua/pac3/core/client/part_pool.lua:64>
	[C]: in function 'xpcall'
	addons/pac3-develop/lua/pac3/core/client/part_pool.lua:138: in function 'RenderOverride'
	addons/pac3-develop/lua/pac3/core/client/part_pool.lua:846: in function <addons/pac3-develop/lua/pac3/core/client/part_pool.lua:748>
	lua/dlib/modules/hook.lua:904: in function <lua/dlib/modules/hook.lua:900>[PAC3] failed to render Player [1][Rapid Radiance]:
your pac3 outfit failed to render!

hiding your outfit to prevent further errors

**Here's the same error on master**

[DLib] lua/dlib/extensions/extensions.lua:70: Tried to use a NULL physics object!
  1. __eq - [C]:-1
   2. EnableCollisions - lua/dlib/extensions/extensions.lua:70
    3. unknown - addons/pac3-master/lua/pac3/core/client/parts/physics.lua:46
     4. Enable - addons/pac3-master/lua/pac3/core/client/parts/physics.lua:188
      5. unknown - addons/pac3-master/lua/pac3/core/client/parts/physics.lua:167

Timer Failed! [Simple][@addons/pac3-master/lua/pac3/core/client/parts/physics.lua (line 167)]
lua/dlib/extensions/extensions.lua:70: Tried to use a NULL physics object!
stack traceback:
	addons/pac3-master/lua/pac3/core/client/part_pool.lua:123: in function <addons/pac3-master/lua/pac3/core/client/part_pool.lua:122>
	[C]: in function '__eq'
	lua/dlib/extensions/extensions.lua:70: in function 'EnableCollisions'
	addons/pac3-master/lua/pac3/core/client/parts/physics.lua:46: in function <addons/pac3-master/lua/pac3/core/client/parts/physics.lua:42>
	addons/pac3-master/lua/pac3/core/client/parts/physics.lua:188: in function 'Enable'
	addons/pac3-master/lua/pac3/core/client/parts/physics.lua:110: in function 'OnThink'
	addons/pac3-master/lua/pac3/core/client/base_part.lua:1145: in function <addons/pac3-master/lua/pac3/core/client/base_part.lua:1122>
	addons/pac3-master/lua/pac3/core/client/base_part.lua:469: in function 'CallRecursive'
	addons/pac3-master/lua/pac3/core/client/part_pool.lua:87: in function <addons/pac3-master/lua/pac3/core/client/part_pool.lua:63>
	[C]: in function 'xpcall'
	addons/pac3-master/lua/pac3/core/client/part_pool.lua:137: in function 'RenderOverride'
	addons/pac3-master/lua/pac3/core/client/part_pool.lua:782: in function <addons/pac3-master/lua/pac3/core/client/part_pool.lua:684>
	lua/dlib/modules/hook.lua:904: in function <lua/dlib/modules/hook.lua:900>[PAC3] failed to render Player [1][Rapid Radiance]:
your pac3 outfit failed to render!

hiding your outfit to prevent further errors

**Comment by pingu7867** [comment]
I beg to differ which branch suffers from the issue. Clearly DLib is doing something, and it overrides a base function of gmod, which is a big no-no in general.

They say in a comment in the code it's to "shut up dumb addons" but who knows whether their code is actually properly implemented.

We use gmod's base functions unaltered and it works fine that way. If another addon comes in and changes them, whose fault is it if stuff breaks?

**Comment by rapidradiance** [comment]
oops i forgot to disable dlib sorry
dlib was the problem

**Comment by DBotThePony** [comment]
> We use gmod's base functions unaltered and it works fine that way. 

DLib appears in callback because it errors on `thisPhysics == worldPhysics` metamethod call, because `thisPhysics` is invalid. Error is caused by phys object being invalid in first place, and not something else.
