### ISSUE TITLE
Add support for TLS v1.3

### ISSUE THREAD

**Issue by EyBmr** [CapsAdmin/pac3#1387]
I am running my own webserver with HTTPS encryption.

PAC3 does not work with TLS v1.3. It shows "SSL Error" when trying to fetch from the webserver.

Downgrading my webserver from TLS v1.3 to TLS v1.2 makes PAC3 work and fetch the files from the server without issues.

Since TLS v1.2 is about to be deprecated, I highly suggest adding TLS v1.3 support in PAC3.

**Comment by pingu7867** [comment]
Don't quote me on that, but I don't think we've "added support" to anything of that to begin with. Aside from some of the decoding we do after receiving the raw data from downloads, we're just using gmod's included networking functions at the end of the day. It's not within our purview or my powers to do so. Take this up to gmod's devs.

And all in all, among the pac devs I'm definitely not a networking nerd. I'm definitely expecting others' opinion on that. But your premise that this protocol version is "about to" get deprecated seems wrong? Most of my searches say there's no official date for it.

**Comment by EyBmr** [comment]
Ok
