### ISSUE TITLE
.OGG plays only on clienside

### ISSUE THREAD

**Issue by The-Serious-Soul98** [CapsAdmin/pac3#150]
I've been trying to make an .ogg play through PAC3 and it has worked using the dropbox method until it got to others players being unable to hear the music. 

https://dl.dropboxusercontent.com/u/49157087/Spanish%20Flea%20by%20Herb%20Alpert.ogg

Above is the piece of music I've used and only appears on clientside for some reason. Other players have told me they are unable to hear it.

Any advice to assist would be much appreciated.

**Comment by LUModder** [comment]
Might of not of downloaded for them or they have ogg's disabled.

**Comment by CapsAdmin** [comment]
reopen if this is still an issue
