### ISSUE TITLE
Suggestion:Texturescroll for materials

### ISSUE THREAD

**Issue by karlo346** [CapsAdmin/pac3#151]
Hi,well ive been making pacs for over a year now and i came a cross a pac that i want to make that has textures that is impossible to make with the options in pac 3 by now @@
the pac im making:    https://www.google.ae/search?newwindow=1&rlz=1C1RNKA_enAE635AE635&es_sm=122&biw=1600&bih=799&tbm=isch&sa=1&q=shadow+fiend+arcana+gif&oq=shadow+fiend+arcana+gif&gs_l=img.3..0.12443.13176.0.13600.4.4.0.0.0.0.244.652.0j1j2.3.0.msedr...0...1c.1.64.img..1.3.650.EHp7dUP7OoM#imgrc=fGqInvVBMacxEM%253A%3BVGhtgStstsKlRM%3Bhttp%253A%252F%252Fimg0.joyreactor.cc%252Fpics%252Fpost%252FDota-%2525D1%252584%2525D1%25258D%2525D0%2525BD%2525D0%2525B4%2525D0%2525BE%2525D0%2525BC%2525D1%25258B-Shadow-Fiend-Dota-Gif-1545886.gif%3Bhttp%253A%252F%252Fdota.joyreactor.cc%252Fpost%252F1563757%3B408%3B466

**Comment by CapsAdmin** [comment]
It might be possible to add in the future. In the meantime you could build the torso out of 5 spheres and rotate them instead.

**Comment by Kamshak** [comment]
I'm not very experienced with PAC part editing but if it's of any help here is a way to create scrolling textures easily:
```lua
	self.NormalTexture = Material( itemClass.material )
	self.ScrollingTexture = CreateMaterial( "PS2_MatScrollingTrailIcn" .. itemClass.material, "UnlitGeneric", {
		["$basetexture"] = Material( itemClass.material ):GetTexture( "$basetexture" ):GetName( ),
		["$translucent"] = 1,
		Proxies = {
			TextureScroll = {
				textureScrollVar = "$basetexturetransform",
				textureScrollRate = "0.8",
				textureScrollAngle = "90",
			}
		}
	} 
```

**Comment by CapsAdmin** [comment]
I remember trying that and it didn't work. I'll see if I can integrate this in the material part.

If possible I wont add TextureScrollAngle and such but instead I'll make it so you can scroll the texture with a proxy part instead.

**Comment by CapsAdmin** [comment]
you can add the proxy part to the material part to scroll the texture

**Comment by karlo346** [comment]
Thanks for the help :D
:+1:  :dancer:

**Comment by karlo346** [comment]
Thanks
