### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by FrOsTy12** [CapsAdmin/pac3#153]
You cant hear your own sounds that you add, only if you're in third person or using camera. Also sometimes people doesn't even hear sounds I'm using, well probably they don't got that sound that I'm using... also forgot to add sound can be heared in PAC

**Comment by LUModder** [comment]
Well, yeah, your PAC doesn't render in first person, except for anything attached to viewmodels.

**Comment by FrOsTy12** [comment]
So I need to add something like model near my char and then output sound to it?

**Comment by CapsAdmin** [comment]
You can try the camera part or add sounds to your viewmodel.
