### ISSUE TITLE
Hide on weapon_class event not always working

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#154]
Some weapons, for some reason, will not hide when I use the hide function on the event part.

Won't hide:
![](http://i.imgur.com/HPJd2Tz.png)

Will hide:
![](http://i.imgur.com/WUogI9Z.png)

Only happens on my server

**Comment by LUModder** [comment]
Closing as resolved. Affect Children Only doesn't play nice.

**Comment by CapsAdmin** [comment]
then what was the bit about it only happening on your server?

**Comment by LUModder** [comment]
I thought it was only happening on my server but it happened everywhere.
