### ISSUE TITLE
Hl2rp problem

### ISSUE THREAD

**Issue by FrOsTy12** [CapsAdmin/pac3#161]
Okay so problem is, when you wear what ever or just press Wear/Clear it sets you to model that you have set on the single player, oh and I don't get it, why I can hear my own sound I add like npc/combine_soldier/vo/prison_soldier_bunker3.wav, some people hear it and some not, what I'm doing wrong? Because when I add sound I make event for it to be on voice chat.

**Comment by LUModder** [comment]
Entity part.

**Comment by FrOsTy12** [comment]
Yeah I've done that, but before updates model stood just fine, what about sounds, why else doesnt hear it but only I do on 3rd person?

**Comment by LUModder** [comment]
PACs for yourself don't render in firstperson, either use a camera part or be in thirdperson.

**Comment by FrOsTy12** [comment]
But last thing, how to make so people could hear sound that I use with event, I usually use root owner, play on footstep, and event with Voice Chat. But when I'm in third person only I hear the sound, people near me, doesn't.

**Comment by LUModder** [comment]
People can still here it just because you can't see your PAC. Also, root owner is useless and no one uses it.
