### ISSUE TITLE
Rendered bone origin is of parent bone

### ISSUE THREAD

**Issue by suchipi** [CapsAdmin/pac3#164]
When a bone part is selected in the editor, the 3D cursor is drawn at its parent bone's origin and angles instead of the bone the bone part is actually for. You can still rotate or offset the bone using this cursor, but it is unintuitive because the orientation is often different.

**Comment by suchipi** [comment]
Eg in this case, the left forearm is selected but the 3D cursor is drawn at the position of and with the angles of its parent bone, the left upperarm
![Example image](http://i.imgur.com/PsHZlJ5.png)

**Comment by CapsAdmin** [comment]
I think I did this for a reason but I forgot what that was now.
