### ISSUE TITLE
add lists for events (was: Slection list for animation events)

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#167]
Suggestion for a list as animation events get confusing when trying to use them with viewmodels. Also could be good to use for other animation events that exist but aren't used a lot.

**Comment by CapsAdmin** [comment]
I agree but the code that populates the properties needs to change in order to properly support it. There are other events that should have lists too.

**Comment by LUModder** [comment]
It shouldn't be hard to code if you just take the property list box from other things and implement it. The thing I really wanted to know is, where can you even get a list of animation events?
