### ISSUE TITLE
Respawning Bug

### ISSUE THREAD

**Issue by Dylanhism** [CapsAdmin/pac3#168]
Whenever I open PAC editor and close it, the next time I die, the camera will be in a roaming type view like I was in the PAC editor still. The only way to fix it is having to open it and close it every time I spawn.  It's just gets annoying after a while of dying.

**Comment by LUModder** [comment]
Sounds like conflicting addons. List of addons please?

**Comment by Dylanhism** [comment]
Here's a link to all my add-ons, http://steamcommunity.com/sharedfiles/filedetails/?id=451603958

Sorry for it being so long xD

**Comment by CapsAdmin** [comment]
reopen if this is still an issue

**Comment by Dylanhism** [comment]
Yes, this is still an issue I have to date.

**Comment by Dylanhism** [comment]
This is a video of the error if it helps explain my problem. https://youtu.be/AWsCWbQF53M

**Comment by Dylanhism** [comment]
Here is a video showing the error I'm talking about. I hope this adds more clarity as to what I'm talking about :).

**Comment by CapsAdmin** [comment]
It really does seem like an addon conflict. I can't guess exactly which addon it is but most likely the addon has something to do with thirdperson.
