### ISSUE TITLE
Bug/Issue with PAC please help

### ISSUE THREAD

**Issue by AlmightyTK** [CapsAdmin/pac3#171]
Guys I was on PAC and I decided to change screen resolution and now the browser square button on animations 
(Sequence name: the button) isn't there ... It disappeared and I tried changing resolution and restarting gmod but no hope and Yes I'm in advance mode , it shoes for color for example but no for sequence name , please help me.

**Comment by AlmightyTK** [comment]
It Shows for The color*

**Comment by LUModder** [comment]
Fixed in recent update. Not pushed to workshop.

**Comment by CapsAdmin** [comment]
managed to publish thanks to vnc working well under a shitty 3g connection
