### ISSUE TITLE
Scroll bug

### ISSUE THREAD

**Issue by Black-Mage-8** [CapsAdmin/pac3#174]
Um so I went on Meta today and I was gonna try making a pac but when i went to resize the model my mouse kept going to the bottom left corner of my screen and even if i held it down and try pulling my mouse upwards it flickers to the bottom of the screen constantly. I tried it with other scrollable parts and it did the same. Idk wtf is going on but there better be a solution to this. I can't do anything wtf. PLEASE HELP! Like why is this happening? :(

**Comment by Black-Mage-8** [comment]
Oh I also tried the pac_restart command and that didn't work at all.....

**Comment by Black-Mage-8** [comment]
One final note: Everytime it does this scroll shit it makes whatever value (for example size) spin up rapidly and gaining in size and i can't double click or anything. It's fucking annoying...

**Comment by CapsAdmin** [comment]
First of all does it happen outside of metastruct?

There's a feature where if you drag numbers and reach the top of your screen the cursor should warp to the bottom of the screen. This to me sounds like the function ScrH() is returning the wrong value which may be caused by an addon.

**Comment by LUModder** [comment]
I've never had problems inside/outside of Meta with the mouse jumping, but it's been apperent forever that scroll wheel value changing makes it skyrocket.

**Comment by CapsAdmin** [comment]
i think i fixed the mouse wheel issue when i added the mouse jumping feature

**Comment by Black-Mage-8** [comment]
Well it isn't from any addons because I've had the same addons for ages and PAC worked fine with them. But for some reason it just started fucking up and I don't know why/how.

**Comment by CapsAdmin** [comment]
reopen if this is still an issue
