### ISSUE TITLE
[PAC3] Permission denied

### ISSUE THREAD

**Issue by Aeverey** [CapsAdmin/pac3#178]
Hello,

Whenever the map changes some people disconnect from my server and they will get this message:
![screenshot](https://cloud.githubusercontent.com/assets/12924231/8192494/ddb71b22-146e-11e5-8b79-6ae561846bd3.jpg)

This started happening when i installed the Pointshop2 addon, with this addon. But since it was an PAC3 error i thought i'd come here for help.
I tried googling the error but got 0 results. 

I've noticed this only happens to all the usergroups except the superadmin.

**Comment by LUModder** [comment]
It's probably trying to load their autoload file and it's printing to all for some reason.

**Comment by Aeverey** [comment]
Do you have any idea where i can find that piece of code and edit it?

**Comment by LUModder** [comment]
See this: https://github.com/CapsAdmin/pac3/wiki/PAC-in-gamemodes
