### ISSUE TITLE
Pac 3 Server issue

### ISSUE THREAD

**Issue by killincreepers1** [CapsAdmin/pac3#179]
Hello! I'm an admin on a server. We've recently have a problem occurring with PAC 3. Some things such as proxys do not work. When a player opens up PAC 3 they receive a decoding error with all their save files as seen here http://prntscr.com/7hsji4 
     We are running the workshop version. Any fixes are gladly accepted! :)

**Comment by LUModder** [comment]
Have you tried using the github version?

(also it's really hard to read with code tags around the text, just saying)

**Comment by killincreepers1** [comment]
We are giving it a shot,  thank you for an answer ^~^

**Comment by CapsAdmin** [comment]
the github version at the moment is identical to the workshop version

**Comment by killincreepers1** [comment]
I can say that the github version did not help, any known mods to conflict with it?

**Comment by CapsAdmin** [comment]
I don't know. I've never seen this error before so I don't know what to do.

**Comment by killincreepers1** [comment]
I do now understand that QAC can cause issues, wow PAC and QAC. Anyways anyway to work around without removeing QAC?

**Comment by thegrb93** [comment]
Fix QAC

**Comment by CapsAdmin** [comment]
Try reporting the issue to QAC. Since it's an anti cheat it most likely overrides functions which PAC3 uses but probably missed something in a function which causes pac3 to break.
