### ISSUE TITLE
unable to move camera in editor mode (possibly with some addons making a hidden overlay panel like playx)

### ISSUE THREAD

**Issue by heavycube4u** [CapsAdmin/pac3#180]
Hello, I am having an issue with PAC editor. I am unable to move the camera with holding down left click.  Is there a solution to this?

**Comment by LUModder** [comment]
Does your weapon also attack when you attempt to move the camera?

**Comment by heavycube4u** [comment]
No

**Comment by heavycube4u** [comment]
Left click does nothing at all except for menus

**Comment by LUModder** [comment]
Might be conflicting addons

**Comment by heavycube4u** [comment]
It's either gmod itself or SCars (which is creating many errors repeatedly)

**Comment by CapsAdmin** [comment]
is there a playx nearby?

**Comment by heavycube4u** [comment]
No

**Comment by CapsAdmin** [comment]
I don't know what to say. It sounds like there is a hidden panel that's in the way of pac. I think PlayX  can do this too.

**Comment by heavycube4u** [comment]
There is a script error in the way, is that an issue?

**Comment by BanraiChan** [comment]
I also have this problem, I've tried to run the workshop version without any other addons running alongside it, still can't move the camera.  WASD and Space works, but nothing else, I've also noticed I can't click the small Position arrows on models either.   The same goes for when I tried to run it by getting the latest PAC from github, everything to no avail. Oddly enough there are no errors or anything. It would be a huge help if camera panning would work again!

**Comment by JohnOakman** [comment]
I would like to re-open this thread, here is my server's collection and I'm having the same issue.
http://steamcommunity.com/sharedfiles/filedetails/?id=399347262
And here another of my server which has the same problem: http://steamcommunity.com/sharedfiles/filedetails/?id=542613606

Thanks for the answer.

**Comment by Datamats** [comment]
@JohnOakman It can actualy be any of the addons, you should try to remove all of them that has anything to do with the view. There are many badly written addons out there that dosnt know how to use CalcView.

I can only guess this is the problem

**Comment by JohnOakman** [comment]
Is there any way to see every addons which use that hook ? (I know it's possible but I don't know how)

**Comment by Datamats** [comment]
try to run `lua_run PrintTable(hook.GetTable()["CalcView"])`

**Comment by roboderpy** [comment]
No answers - closing.

Also, if addon creates a panel that has :Paint() and not :SetVisible(false) BUT :SetAllowMouseInput(true), this is addon issue, not an issue with PAC3.
