### ISSUE TITLE
Add "Use Team Color"

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#183]

**Comment by CapsAdmin** [comment]
more clutter but okay. maybe there needs to be a list of what colors to take from. player, team, weapon, trace hitpos, etc

**Comment by LUModder** [comment]
That'd be better to do

**Comment by CapsAdmin** [comment]
I think I'll add this as a proxy feature instead and mark player and weapon color property as deprecated.

So if you want to use team color you should just add proxy to model and set it up to use whatever you want.

**Comment by CapsAdmin** [comment]
I forgot the proxy part doesn't work very well with vectors..
