### ISSUE TITLE
Use for DarkRP

### ISSUE THREAD

**Issue by Gordlix** [CapsAdmin/pac3#184]
Hi, i just want to use PAC3 for my DarkRP, but i wan't to add the custom model only on the job. Can you help me ?

Cordially, 

Lucas.

**Comment by LUModder** [comment]
https://github.com/CapsAdmin/pac3/wiki/PAC-in-gamemodes

**Comment by CapsAdmin** [comment]
I don't really know how DarkRP works. You need to find someone who can code this for you.
