### ISSUE TITLE
TTT + Pointshop2 + Pac3 / cleanup issues with the model part

### ISSUE THREAD

**Issue by P4sca1** [CapsAdmin/pac3#186]
Hello, 
Whenever a new round starts and I'm in the PAC Editor to create a new accessory or whatever all the PAC3 Items are getting invisible

**Comment by Python1320** [comment]
New round means a "fullupdate", which basically clears *everything* and then resets to the server's state. PAC is not part of this system so its entities (the drawn models) get removed and do not reappear. Basically what PAC should do is re-request all outfits after fullupdate from the server, since that's how the engine works if you want for example demos to work. With PAC it would get horribly inefficient so right now you need to do it manually. 

Maybe we could make a demo-breaking outfit reapplying, which doesn't mind a fullupdates. There is something like that for fullupdates already, but only for players that are still in your PVS.

**Comment by P4sca1** [comment]
So did I get it correctly?: 
After a round the server is doing a fullupdate, which clears everything including PAC. It would be possible to rerequest all the outfits but it is not implemted yet?

**Comment by LUModder** [comment]
Why not just call the code which is in aowl's !fixpac command at the beginning of each round to each player?

**Comment by P4sca1** [comment]
Sorry I dont know aowl's !fixpack command. Could you provide a link or something? (Sorry I'm new to pack).

**Comment by LUModder** [comment]
It pretty much refreshes all PACs that you can see

**Comment by CapsAdmin** [comment]
aowl has nothing to do with pac and I think that command is just re-wearing your outfit.

Clearing the map used to blow all the outfits up but I swear I fixed this a long time ago. If a model is removed it should recreate those models.

**Comment by P4sca1** [comment]
I have the newest version from github and the models are not visible again after a new round.
What am I doing wrong?

**Comment by LUModder** [comment]
Call this at every round start
``
if not pace then return end
	
ply:SendLua([[if pac and pac.review_reloading then pac.review_reloading() end]])
	
ply.pac_requested_outfits = false
pace.RequestOutfits(ply)
``

**Comment by P4sca1** [comment]
Thanks! :+1: 
Just to make sure I did it right: 
http://prntscr.com/7jzjn5

**Comment by LUModder** [comment]
LocalPlayer() is not called serverside.

```
hook.Add("TTTPrepareRound","ReloadPACs",function(ply)
if not pace then return end

ply:SendLua([[if pac and pac.review_reloading then pac.review_reloading() end]])

ply.pac_requested_outfits = false
pace.RequestOutfits(ply)
end)
```

**Comment by P4sca1** [comment]
thanks!

**Comment by P4sca1** [comment]
Sorry for all the questions, but Google did not help me with this: 
Is there any way to write custom lua code assigned to the item created? 
(Great use for Pointshop2)

**Comment by CapsAdmin** [comment]
can you try this now without the code LUModder provided?

**Comment by P4sca1** [comment]
I will try without the code, yeah. 
I will take about 30 minutes.

**Comment by P4sca1** [comment]
Working now. Thanks for the commit!

**Comment by comedinha** [comment]
Not fixed.
![2015-06-23_00002](https://cloud.githubusercontent.com/assets/5075051/8314996/9f60abae-19c3-11e5-9224-286e22848764.jpg)

To stop i use on console
record fix
stop record
and pac3 reload...

**Comment by Kamshak** [comment]
Guys, this is not the place for Pointshop 2 support, please always use the ticketing system on coderhire first. If the issues are in fact PAC3 and not Pointshop 2 issues i will open an issue here and attempt to fix it with the help of the pac authors & contributors.
