### ISSUE TITLE
Custom lua code assigned to pac3 item

### ISSUE THREAD

**Issue by P4sca1** [CapsAdmin/pac3#187]
Is there any way to write custom lua code assigned to the item created trough the pac3 editor? 
(Great use for Pointshop2)

**Comment by LUModder** [comment]
Command part if it's just clientside lua. Needs to be minified though.

**Comment by P4sca1** [comment]
What is the script thing?

**Comment by CapsAdmin** [comment]
It's an unfinished (and dangerous) part that is disabled by default until I find a way to fix it.

This is something pointshop 2 should do I think.

**Comment by Kamshak** [comment]
Definitely with Caps on this, you can already do it (see the jump pack for
an example). Easier way to do this is planned
Am 22.06.2015 20:20 schrieb "Elias Hogstvedt" <notifications@github.com>:

**Comment by P4sca1** [comment]
@Kamshak Yeah the purpose of this was to make the jump pack editable ingame.
