### ISSUE TITLE
View Postision

### ISSUE THREAD

**Issue by halowhooves** [CapsAdmin/pac3#192]
Whenever you have View Follow on sometimes your camera flings way out of the map and its almost impossible to get back unless you reset view. Though you can just simply turn off the View Follow but somtimes i forget and the new starters don't even know this. Caps pls fix.

**Comment by X-Coder** [comment]
I have a similar issue with the cam too, sometimes when I open the pac3 editor, the cam is suddenly far away from the model, above or close to the map borders for some reason, so I need to go all the way back to my model using alt+e or using reset view. But "camera follow" if turned off for me. Just tested with "camera follow" on the homer model, but then the whole editor view got black, and I needed to hit reset view.

**Comment by LUModder** [comment]
Reset view, turn off camera follow :v

**Comment by X-Coder** [comment]
Thats called a workaround - and we already know.
