### ISSUE TITLE
CAn't get .ogg fils to play?

### ISSUE THREAD

**Issue by Leafleafleafleaf** [CapsAdmin/pac3#193]
https://dl.dropboxusercontent.com/s/cnv1mb8lwn9l28z/Metro_2033_OST_-_Guitar_Song_2.ogg

This is the link, which goes straight to the download, but it won't play in pac3, I am using the workshop version.

**Comment by LUModder** [comment]
Dropbox.com to dl.dropboxusercontent.com in URL

On Jul 10, 2015 7:51 AM, "Leafleafleafleaf" <notifications@github.com>
wrote:
>
>
https://www.dropbox.com/s/cnv1mb8lwn9l28z/Metro_2033_OST_-_Guitar_Song_2.ogg?dl=1
>
> This is the link, which goes straight to the download, but it won't play
in pac3, I am using the workshop version.

**Comment by Leafleafleafleaf** [comment]
Did that, didn't work.

**Comment by LUModder** [comment]
Show link you used

**Comment by Leafleafleafleaf** [comment]
https://dl.dropboxusercontent.com/s/cnv1mb8lwn9l28z/Metro_2033_OST_-_Guitar_Song_2.ogg

**Comment by LUModder** [comment]
Should work then

On Jul 10, 2015 6:21 PM, "Leafleafleafleaf" <notifications@github.com>
wrote:
>
>
https://dl.dropboxusercontent.com/s/cnv1mb8lwn9l28z/Metro_2033_OST_-_Guitar_Song_2.ogg
