### ISSUE TITLE
expermiental commit made homer translucent

### ISSUE THREAD

**Issue by X-Coder** [CapsAdmin/pac3#194]
Your commit "experimental fix for translucent issues with ragdolls" broke your homer model, its half translucent now. Maybe other models broke too because of this. 

Github and current workshop version is affected.

I reverted the commit 48e89f4e968f5b8041fb8c6135cd341e2e400469 in my local repository and the model works again.
Tested it on my dedicated server.

The homer model is from your dropbox:
https://www.dropbox.com/sh/bi3d24ozin47c2n/AADQkacZpzl9LNrsRGZdjqKIa/homer.txt?dl=0

**Comment by LUModder** [comment]
Can you not use public pacs and be creative for once?

On Jul 10, 2015 9:14 PM, "X-Coder" <notifications@github.com> wrote:
>
> Your commit "experimental fix for translucent issues with ragdolls" broke
your homer model, its half translucent now. Maybe other models broke too
because of this.
>
> Github and current workshop version is affected.
>
> I reverted the commit 48e89f4 in my local repository and the model works
again.
>
> The homer model is from your dropbox:
>
https://www.dropbox.com/sh/bi3d24ozin47c2n/AADQkacZpzl9LNrsRGZdjqKIa/homer.txt?dl=0

**Comment by X-Coder** [comment]
The reasons I use CapsAdmin's public PACs like this one are:
a) for learning purposes
b) for debugging PAC3 when bug like this happens on my server
c) for reporting bugs (in this case it helps CapsAdmin to identify the cause of the bug, because he already knows his own homer model)

In this case it helped my to verify its a bug in PAC3, and not within the stuff I did on my own model, or a conflict with another addon. So I could just reverted back to find out what commit caused it.

So I am thankful to CapsAdmin he made some of his public so I can better understand how PAC3 works, and it allows me to see if something brakes.



And by the way, I guess, if he didn't want, that others might use it for learing or whatever, he would'nt have made them public in first place, and linked them.

**Comment by CapsAdmin** [comment]
@LUModder can you stop leaving snarky comments? If you can't help then don't post.

I kinda forgot now but I think there was an update that did something to something which made me have to do that fix. I don't really have a good unit test so I just check several outfits or ask people who use pac3.

It might be that the homer outfit relied on a bug.

**Comment by X-Coder** [comment]
Thank you. Do you have any idea how I could make such a half translucent model visible again with your bugfix in place? -Just in case some asks me on my server or I stumble on this again.
