### ISSUE TITLE
PAC3 JiggleBoneProblem 

### ISSUE THREAD

**Issue by karlo346** [CapsAdmin/pac3#195]
So when I was making a tail for my PAC3 outfit i encountered a problem.Whenever I make a jigglebone You would probably recognize that it goes on a stair shaped,Right?But when it gets to long i cant see the right side of the pac3 header
what do i do?

**Comment by Python1320** [comment]
Please provide pictures

**Comment by CapsAdmin** [comment]
You have to resize the editor by pulling the right left corner of the editor.
