### ISSUE TITLE
Make PAC Items invisible for a short time

### ISSUE THREAD

**Issue by P4sca1** [CapsAdmin/pac3#196]
I want to make an item for my ttt server that makes you invisible. It's no problem, but Pac Items, equipped in my pointshop2 are still visible. 
How can I make them invisible?

**Comment by P4sca1** [comment]
Can I disable pac rendering for a specific person for a specific amount of time?

**Comment by Kamshak** [comment]
pac.HideEntityParts
pac.ShowEntityParts

**Comment by MultiMazilka** [comment]
pac.TogglePartDrawing(self.Owner, false)
pac.TogglePartDrawing(self.Owner, true)

Gratitude to Kamshak
