### ISSUE TITLE
Cannot Pan nor Zoom camera in Animation Editor.

### ISSUE THREAD

**Issue by stu-pidface** [CapsAdmin/pac3#199]
I've used the Animation Editor for about a month now without and hick-ups, when all of a sudden, I could no longer move my camera around, I can still edit values but it is difficult to see what I am doing, I have found a workaround by using the gmod camera tool, though this isn't the ideal way I make my animations.

**Comment by LUModder** [comment]
Animation Editor needs a lot of help to be honest. Layout is too cluttered, no free movement and that stupid zoom slider isn't ideal.
