### ISSUE TITLE
Pac 3 screen earthquake when size is below 1.0 

### ISSUE THREAD

**Issue by BaseballBibbins** [CapsAdmin/pac3#202]
I was making a custom player model and I changed the size from 1.0 to 0.7 and then I hit wear, thats when the screen starts to shake like im on the cap of a soda bottle. w.w please help

**Comment by LUModder** [comment]
See #201

**Comment by BaseballBibbins** [comment]
"LightningFlash commented 4 hours ago
i managed to fix it, just using size 1.0 now"--- was this the fix? he just changed the size back to default

**Comment by Hazbelll** [comment]
[This] (https://github.com/CapsAdmin/pac3/issues/201#issuecomment-125375149) was the fix, specifically [this] (https://github.com/CapsAdmin/pac3/issues/201#issuecomment-127458663).

**Comment by BaseballBibbins** [comment]
Solved thanks a bunch
