### ISSUE TITLE
Cannot exit PAC Editor

### ISSUE THREAD

**Issue by SpaaloneBBGS** [CapsAdmin/pac3#203]
It seems that whenever I attempt to exit the PAC editor (with or without doing anything to my playermodel), it doesn't work, and the following lua error shows up:

[ERROR] lua/pac3/editor/client/init.lua:214: attempt to call method 'sub' (a nil value)
  1. RestoreExternalHooks - lua/pac3/editor/client/init.lua:214
   2. CloseEditor - lua/pac3/editor/client/init.lua:145
    3. DoClick - lua/pac3/editor/client/menu_bar.lua:40
     4. OnMouseReleased - lua/vgui/dlabel.lua:218
      5. unknown - lua/vgui/dmenuoption.lua:116

Help with this issue would be appreciated.  ^_^

**Comment by xSwindle** [comment]
This happened for me too, it fixed itself when I installed the workshop version.
