### ISSUE TITLE
I have a issue with the effect option.

### ISSUE THREAD

**Issue by ChanceTheGamer** [CapsAdmin/pac3#204]
As i was playing i downloaded the Ghost Rider playermodel and decided
to add a effect and choose the fire effect as i clicked it i saw it but, It was 
on my feet i tried to move it but it wouldn't move. Then i disable follow
then it went to the area i wanted it go so can you please fix it to follow you.

**Comment by ChanceTheGamer** [comment]
I forgot to say go to effect then effect again choost effect again, then just pick any particale

**Comment by LUModder** [comment]
Not really a bug because of how effects are coded

**Comment by Ameno-Sagiri** [comment]
Make a model, create an Effect inside/under that model, then move the model to move the effect. Make the model have an alpha of 0 to make it go invisible.

Last time I tried, every effect needs a another model to be under, you can't put 2 effects under 1 model.
