### ISSUE TITLE
CTD with little explanation.

### ISSUE THREAD

**Issue by Marstruc** [CapsAdmin/pac3#205]
I'll admit, I'm a little pissed.This phrase has plagued me for almost a year. 

"Reading externally referenced elements is not supported!" 

With PAC3 installed, loading up any map, connecting to any server (regardless of if the server uses it), and I crash with that line being the last line printed in the console. 

I have done, quite literally, everything within my power to understand and even combat it. I have even reinstalled Windows 7, twice. It is NOT Garry's Mod. It is NOT my computer. It is down to PAC3 only. What the hell is wrong?

Here's a link to the cleanest .mdmp file I have, where all I have mounted is HL2 and the Episodes, and I attempt to load gm_flatgrass: https://www.mediafire.com/?vr9yfrgq2tiw5x9

**Comment by LUModder** [comment]
Are you sure its not a module or any other addon?

**Comment by Marstruc** [comment]
I am absolutely, positively sure. There is no way it can be anything BUT PAC3.

**Comment by LUModder** [comment]
Full system specs?

**Comment by Marstruc** [comment]
CPU: AMD A8-6600K
RAM: 8GB
GPU: AMD Radeon HD 7950 TwinFrozr III BE
OS: Windows 7 Ultimate 64-bit, updated to the cusp of Windows 10.
HDDs: 1 500GB 5400RPM Samsung, 1 1TB 7200RPM Seagate.

Anything else you need?

**Comment by LUModder** [comment]
How updated are drivers? If you can and they're out, update to 15.8 beta
drivers. I dunno if its a driver issue or what.

**Comment by Marstruc** [comment]
I'm on 15.7, and they aren't. So I'm at the most updated point possible.

**Comment by LUModder** [comment]
Dunno how well it would help to run the mdmp file through
http://dumps.metastruct.uk.to/ cause I can't figure out how to read what's
wrong. I'm at a lost of what else to do.

**Comment by Marstruc** [comment]
Crash reason:  EXCEPTION_ACCESS_VIOLATION_WRITE
Crash address: 0x0

I've made sure that my Garry's Mod folders aren't readonly...

**Comment by Marstruc** [comment]
Alrighty, then. So... The problem, is that PAC3 is trying to access something that it isn't allowed to. Something that, I apparently lost after the start of October last year?

**Comment by LUModder** [comment]
Make sure data and data/pac3 are NOT in read only.

**Comment by Marstruc** [comment]
It isn't. Trust me when I say that.

**Comment by LUModder** [comment]
Any modules installed at all? (they'll be in lua/bin)

**Comment by Marstruc** [comment]
There isn't even such a folder.

**Comment by Marstruc** [comment]
Well...?

**Comment by CapsAdmin** [comment]
I don't know how to help you. I can't read the dump file because I don't have the source code for gmod.
