### ISSUE TITLE
An issue involving player models, not sure if PAC issue or server issue.

### ISSUE THREAD

**Issue by ejdude123** [CapsAdmin/pac3#206]
My friend owns a gmod DarkRP server, and in the server, the default player model is the customizable pony player model, however, I often like to use PAC to change my model to a human, but recently, that has not been possible for me and others on the server, if anyone can give me any information on whether or not this is a problem on any other servers as well, it would be appreciated. Also, I can change models normally on singleplayer or on other servers using models that don't have human bones.

**Comment by LUModder** [comment]
Use entity parts and models/player models for compatable playermodels
