### ISSUE TITLE
Black Screen Issue

### ISSUE THREAD

**Issue by Free14nder** [CapsAdmin/pac3#215]
It was working fine as soon as I downloaded it, and then suddenly whenever i try to put anything on a model (Effect, Bone, Entity, Etc) the viewscreen goes black. I can still mess with the Editor window, and when I exit the menu the Black screen disappears, but whenever i select the Added sub-item it turns black again. I haven't messed with any of the settings and I don't know whats happening. http://i.imgur.com/nMVxU6k.png

**Comment by LUModder** [comment]
Turn off camera follow :v

**Comment by Free14nder** [comment]
Wow. Thanks ^^"

**Comment by CapsAdmin** [comment]
lol
