### ISSUE TITLE
Hoverballs models invisible with certain addons

### ISSUE THREAD

**Issue by dany777** [CapsAdmin/pac3#216]
I have a Kirby PAC that most of the models uses hoverball models, they are invisible, im asuming that with some addons, but rarely works when it feels like

**Comment by LUModder** [comment]
Screenshot?

**Comment by dany777** [comment]
Its gonna have to wait until i get my Gaming PC back, but as soon i get it, i will publish the screenshot

**Comment by dany777** [comment]
Here is the screenshot

![gm_mobenix_v3_final0002](https://cloud.githubusercontent.com/assets/4022009/10288005/9709ce34-6b96-11e5-9323-275890f65f53.png)

**Comment by LUModder** [comment]
1. Playermodel you're using isn't supported (as this PAC as far as I know, doesn't have a model set for it's entity part)
2. Switch ALL hoverball models to models/pac/default.mdl

**Comment by dany777** [comment]
But i was using male07

**Comment by LUModder** [comment]
Either try option 2 or redownload the PAC cause I think Kombat/BoNana updated it recently

**Comment by dany777** [comment]
I did the option 2, but it gets worse the looking + im using the workshop version of PAC3, not the one from Github
