### ISSUE TITLE
Cape Material

### ISSUE THREAD

**Issue by Imusingthisforonce** [CapsAdmin/pac3#222]
So I play on servers that have free PAC and I see people with more realistic capes, A.K.A Material set to them. The problem is that I don't like my cape looking as smooth as butter and want it to look more realistic, Now the problem is that when I got to modifier > Material or whatever then change the texture. It doesn't actually change, Please help.

**Comment by LUModder** [comment]
Screenshot of the problem?

**Comment by Imusingthisforonce** [comment]
No Problems, The material I set it to just doesn't show up.

**Comment by Ameno-Sagiri** [comment]
This is related to the issue I just opened today. Material parts have been giving me lots of problems. Sometimes they cause textures to go black, white, or random polygons get textured pure black, and sometimes they do nothing at all. This is while I'm using a 1024x1024 texture too

**Comment by LUModder** [comment]
Again, see previous reply on x1024 textures and I'll see if I can get UV
maps for the capes and such

**Comment by CapsAdmin** [comment]
see #188
