### ISSUE TITLE
Webaudio No Longer Working

### ISSUE THREAD

**Issue by Demondev90** [CapsAdmin/pac3#223]
I have about 30 webaudio events set up. I pull whatever ones I want out and put them into my pacs. Last night, the webaudio events stopped working. I thought it might be fixed the today, but it seems that hasn't happened. I know they are in right, because I have had a few in there that have worked for weeks, and the files have not changed source locations. I don't know why they aren't working anymore. 

I have tried re-inserting the link, copying the link from the site again and inserting it, separating a webaudio into a different pac, messing with the volume, restarting my computer, re-subscribing to pac, and even completely deleting pac and putting the txt back in. 

Thing is, nobody else can hear them either, but I can still hear theirs. The webaudio events have not changed at all in the saves, so they should, in theory, still work, yet they don't.

The files are being retrieved from copy.com, if that matters.

**Comment by LUModder** [comment]
I don't know much about Copy and how they have public stuff, but update might of broken it. I recommend Dropbox or private hosting if you can.

**Comment by Demondev90** [comment]
I heard copy.com worked fine with this, but I went ahead and got Dropbox. It didn't make a difference. I tried a few files, none of which played. And yes, before you ask, my account was verified and the files were fully uploaded.

**Comment by LUModder** [comment]
Did you did the "public folder' rename "hack" so www.dropbox.com is switched to dl.dropboxusercontent.com?

**Comment by Demondev90** [comment]
To get a public folder, it says would have to get dropbox pro. There's no way I'm going to spend money on something like that, so I guess dropbox is out of the question for me. I know copy.com WAS working just fine, and there didn't seem to be any changes, so I just feel like it's something I accidentally toggled in pac or something.

**Comment by LUModder** [comment]
I mentioned the public folder rename hack so you DON'T have to pay

**Comment by Demondev90** [comment]
Where/how would I be able to get this? I have growing doubt it will work, but I at least want to try.

**Comment by LUModder** [comment]
Take the share link and change www.dropbox to dl.dropboxusercontent

**Comment by Demondev90** [comment]
Well I did it like you said, and tried it in google chrome just to test it. Worked fine, so I tried pac. Still nothing. I'm pretty sure it's not because of the source, but because of my pac. I just have no idea why it started doing this.

**Comment by 00875** [comment]
Works for me.

**Comment by LUModder** [comment]
Are you using this by chance: https://facepunch.com/showthread.php?t=1486313

**Comment by Demondev90** [comment]
No, I am not using the Awesomium replacement. I never even knew about that.

**Comment by Demondev90** [comment]
So I don't know what it was, but I deleted all of my 15 or so pages of addons, and only kept pac3. That seemed to fix it. I guess there was an addon I got somewhere that wasn't working with it.
