### ISSUE TITLE
Dropbox links no longer work

### ISSUE THREAD

**Issue by Locutus857** [CapsAdmin/pac3#227]
Dropbox links for models, textures, etc. that worked perfectly in the past no longer work for me anymore.
I get errors like this - doesn't matter what server I'm on, or if it's singleplayer, I have the same problem.
[PAC] Url failed loading http://dl.dropboxusercontent.com/s/sf5sj773jj762wp/headset1.obj?dl=0 (unsuccessful)

Someone told me a recent update is responsible for this bug.

**Comment by LUModder** [comment]
Please stop making issues on this, we're attempting to get it fixed.

**Comment by Locutus857** [comment]
Sorry.

Glad to here it's being worked on.
