### ISSUE TITLE
Most Events No Longer Working for Multiplayer

### ISSUE THREAD

**Issue by Demondev90** [CapsAdmin/pac3#230]
As the title says, most of my events are no longer working, meaning **I can see them, but others on servers cannot**. It started just a couple hours ago, after I added an event for a custom animation. When I joined a server, not only was the new custom animation not working, but most of my other events, too. 

This is **not only events requiring links, but even ones that are completely made on pac 3**, like my fiery rage event that changes the material and adds a few particles. There are a **few still working**, though, such as my crouch-to-activate box.

I've been working with others to figure it out, but nobody can see most of the events, and nobody knows why it is doing this.

*I have tried re-wearing the pac, re-joining the server, restarting Gmod, deleting anything I added to pac today, and removing any other addons other than the few being used.*

(note: most of the events are say events)

**Comment by LUModder** [comment]
Try seperating your PAC into smaller subgroups so it'll wear technically "multiple outfits", as only one "outfit" group can only be 64kb big to send. To make a new "outfit" group, make a new group just outside of the other groups with no parent.

**Comment by Demondev90** [comment]
I tried splitting it into multiple separate groups, no parents, as well as changing to command instead of say. Still the same problem.

**Comment by Demondev90** [comment]
I deleted my addons again, and this time even deleted pac. I only downloaded the ones used on the server I went on, which was most of them, and suddenly others could see it again! I have **NO** idea why it did this, since I have almost all of the same addons that I did before, but I guess I can close this issue.
