### ISSUE TITLE
add "between operator" for events

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#232]
It adds another find field and compares with the event. Only good for numeric based events but it's a good idea.

ex:
event | health
operator | between
find | 75
find2 | 25

will result in the event triggering when health is between 25 and 75

**Comment by Beauty-Bomber** [comment]
hmm we could also have an equal or between event.

**Comment by LUModder** [comment]
Why? That's exactly what between does.

**Comment by Beauty-Bomber** [comment]
do i look like i know what a jpeg is i just want a picture of a god dang hot dog!!!!

**Comment by LUModder** [comment]
Shouldn't this be feature tag and not enhancement?
