### ISSUE TITLE
Bodygroups bug when used under Entity

### ISSUE THREAD

**Issue by Konng** [CapsAdmin/pac3#234]
When setting a playermodel in my entity and adding a bodygroup under it, only one bodygroup can be active at any time.. if you have two only one of them will draw. I managed to work around this by adding the playermodel i wanted as a model and bone merging but it would be good if you could look into this.
![2015-11-23_01-41-22](https://cloud.githubusercontent.com/assets/10534708/11328490/5722be30-9183-11e5-94cd-46abc4cfbe3f.png)

**Comment by LUModder** [comment]
known bug but no one has done anything about it
