### ISSUE TITLE
Decoding pac3//objcache/7f3b804a.txt failed

### ISSUE THREAD

**Issue by Tazmily** [CapsAdmin/pac3#235]
So I'm using PAC3 for changable clothing/equipabble items on my server. I can change the bodygroups and bonemerge the items just fine, but whenever I fire my weapon one or more of the bodygroups change to the default and my console gets filled with this.

Decoding pac3//objcache/181d589e.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/1e9bb449.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/7f3b804a.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/881726c9.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/9c7e19d4.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/181d589e.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/1e9bb449.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/7f3b804a.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/881726c9.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/9c7e19d4.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/181d589e.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/1e9bb449.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/7f3b804a.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/881726c9.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/9c7e19d4.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Requesting texture value from var "$basetexture" which is not a texture value (material: pp/copy)
Decoding pac3//objcache/181d589e.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/1e9bb449.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/7f3b804a.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/881726c9.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'
Decoding pac3//objcache/9c7e19d4.txt failed: luadata_decode:1: unexpected symbol near 'char(3)'

Any idea what's causing this?

**Comment by LUModder** [comment]
Older version of PAC that doesn't have objcache

**Comment by Tazmily** [comment]
I updated my PAC and deleted any old installs, and now I don't get that console error, but my bodygroups still default to normal when I attack. Is there anything that can be done about this?

**Comment by LUModder** [comment]
Known bug that no one has even attempted to fix. There was a fix last month that apparently was tested but then the bug came back up again.

**Comment by Tazmily** [comment]
That's sort of discouraging, but all right. In that case nothing that can be done in the short term?
