### ISSUE TITLE
Material Parts are completely broken

### ISSUE THREAD

**Issue by Ameno-Sagiri** [CapsAdmin/pac3#236]
Been making quite a bit of PACs recently and a problem I have found is material parts are completely broke. Sometimes when I put the bumpmap on a model, it causes a ton of random missing black polygons in the texture, not the model itself. Sometimes the bumpmap and shininess work fine, then other times I load into a server and the bumpmap causes the entire model to go pitch black or white and flicker so fast it could give someone a seizure.

Not seeing any script errors, all I know is material parts are being unreliable. The case that finally made me post this is I was making a Fallout 4 Mr. Handy PAC from the Mr. Handy model on workshop. The reflectivity was working fine on the main body shell yesterday, but I woke up today and it's white/black back and forth. Also, the arms keeps getting pitch black polygons whenever I put a bumpmap on them.

**Comment by LUModder** [comment]
Is the texture size bigger than 1024x1024, if so urltex will panic

**Comment by Ameno-Sagiri** [comment]
It's 1024x1024, CapsAdmin told me once that problem is caused by textures larger than that, so I've always made sure to half or fourth the size of larger textures.

The bumpmap and the normal texture are both 1024x1024.

**Comment by LUModder** [comment]
Even x1024 textures will break, that's why I rescale mine to x512

**Comment by Ameno-Sagiri** [comment]
I'll try 512x512

**Comment by Ameno-Sagiri** [comment]
512x512 mostly works for me, but other people keep telling me random polygons are flickering black. This is on a new PAC, and the object specifically is the Soul Calibur weapon (The glassy Ice refractive looking thing).

**Comment by LUModder** [comment]
The thing with the random black on the model AFAIK is based on GPU for some reason, because I've rarely had it happen and I have a newer GPU than a lot of people, but I'm unsure if that's really the problem.

**Comment by Ameno-Sagiri** [comment]
If it helps any, It's Nvidia, EVGA GTX 770 2GB SC, drivers up to date as of 1/14/2015.

But yeah, always seems to be lightwarps that cause it, which is disappointing because you can really make models look alive with it. All well.

**Comment by CapsAdmin** [comment]
see #188
