### ISSUE TITLE
PAC:System recomnendat-on

### ISSUE THREAD

**Issue by karlo346** [CapsAdmin/pac3#238]
So basically im making a Vel'Koz Battlecast which turned out good with the custom particles and etc...
but the hardest thing making that PAC is how time-consuming it is to set up the jiggles and how i should set up the speed and strain and etc... to 50 jiggles

soo i was wondering where u could select all "like u would do in ur windows folder like shift+right click"
be implemented on PAC so that i dont have to deal with 50 jiggles or material or particles very time consuming for example

i have 5 jiggles

i selected the 5 jiggles "by shift+right clicking"

and then i changed the speed
to 5 and all the 5 jiggles have 5 speed

is that possible for pac :+1:

**Comment by Python1320** [comment]
I don't think there is such a thing, BUT you can try doing that in a text editor for the property you want to change for your outfit. The outfit files are in garrysmod/data/pac3
