### ISSUE TITLE
Need assistance with a simple PAC I'm trying to make

### ISSUE THREAD

**Issue by ejdude123** [CapsAdmin/pac3#239]
So I am creating a PAC to make my player look like the Marine from the original Doom games, so I got all of the original sprites for the game and created it using the Southpark example PAC as a base to work off of, however, the Southpark PAC only has 4 view directions, while the Doomguy has 8, and I do not know who to make the sprites show in their respective corners correctly. 

![2015-12-24_00002](https://cloud.githubusercontent.com/assets/13792528/11997174/0dfc2b8e-aa32-11e5-91a7-bfabf046c794.jpg)
How it is supposed to look, from the front-right angle

![2015-12-24_00003](https://cloud.githubusercontent.com/assets/13792528/11997182/221bde84-aa32-11e5-863e-c419936d94b8.jpg)
But from the front-left angle, it still shows the same sprite, and I do not know how to make it disappear at this angle.

If anyone could give me any help with fixing this, it would be greatly appreciated.

**Comment by LUModder** [comment]
See south park example.

**Comment by ejdude123** [comment]
I did, I used the southpark example as a base, as I said above, I just need assistance adding more angles to the PAC
