### ISSUE TITLE
Crash on mapchange

### ISSUE THREAD

**Issue by 0xnonSENSE** [CapsAdmin/pac3#241]
No other addons except pac3 (workshop) mounted / subscribed to. No modules. Map gm_flatgrass.
Gmod 2015.12.16 (production branch, no dev)

**Steps to reproduce:**
* Start local multiplayer game.
* pac_enable 1 in console (or through spawn menu options)
* changelevel gm_flatgrass in console
* Crash

[Crash dump](http://dumps.metastruct.uk.to/dumper.py?dump=hl2_151216_crash_2015_12_25T0_34_32C0.mdmp&key=Wcpfht9ZC-eIF5S1OE_UeqgZkjO8nCy_dPRaUJwTZl-X-YvM5kbsYSeZPYjfvLz0OxqolHO9cR442-Z3EJTkpDLs5yFlrlrHVwe6_mcII5R_Rom2pdJCCdiiGEM0S0DcPMm3BAUVajcOFiLUitTeHFaAEDhpyVsqGmp3UgIxblw=)

**Comment by LUModder** [comment]
1. We dunno what other scripts you have in your lua folder
2. Local multiplayer, there's a major problem
3. Crash dump isn't really useful as we don't have any source code to reference
4. Dunno how complex your autoload PAC is, which usually, if this does happen, delete your autoload file and then resave it.

**Comment by 0xnonSENSE** [comment]
* Vanilla gmod. Clean install. No other scripts / addons / content besides pac3.
* Does not appear to happen on singleplayer or dedicated servers
* Not sure what you mean by autoload
The reason for local multiplayer (listen server) is development of gamemodes / addons. This didn't use to be a problem at all; only recently (this update?) does the crashing occur on map change.

**Comment by LUModder** [comment]
Honestly, if you're using a listen server for development, you should be developing. Most devs should know it's better to run a local dedicated but whatever.

Anyways, if you have an autoload pac, sometimes when it loads on a listen server it'll crash your client.
