### ISSUE TITLE
Submaterial and bone merge

### ISSUE THREAD

**Issue by SpitfireOrMichina** [CapsAdmin/pac3#244]
Submaterial doesn't work when ragdol or props is on bone merge :/

**Comment by Python1320** [comment]
Submaterial is not even official yet, it has problem of not staying applied on various update scenarios. I'll work on it when I have time.

**Comment by SpitfireOrMichina** [comment]
Ok thanks Python 
Yoru are the best 
Kiss
Lel
Meow
