### ISSUE TITLE
Export PAC3 to Lua code (like in SWEP Construction Kit)

### ISSUE THREAD

**Issue by LuaTenshi** [CapsAdmin/pac3#245]
This option will allow people to easily position models on their player and then export them as code allowing them to position things for their own mods much easier and faster.

**Comment by LUModder** [comment]
PAC positioning doesn't translate to SCK properly, I've tried

**Comment by LUModder** [comment]
Though I could try to make something that could work

**Comment by LuaTenshi** [comment]
Well I was using SCK as an example. Would just be nice to be able to make a
PAC to Lua translator because then people would be able to do so much more
with it. Like making armour for RP etc.

**Comment by LUModder** [comment]
Yeah, I was gonna do that instead with my own DrawViewModel and DrawWorldModel for weapons and Draw for entities

**Comment by LuaTenshi** [comment]
Hopefully you actually get it working. Would love to see a prototype.

**Comment by CapsAdmin** [comment]
Have you looked at the gamemode section on the wiki? It tells you what to copy paste and where. I guess that could be automated somehow though.

It does rely on pac3 existing though.

You can also duplicate outfits that are applied on props as well as spawning outfits on server (this is very limited but if you stick to normal props without resizing it should work)

**Comment by LUModder** [comment]
My system won't have to rely on PAC existing though. It'll just convert it into tables and be read like SCK but with less of a headache of implimenting.

**Comment by Kamshak** [comment]
i don't get it, that's what PAC does? A Pac outfit is just a table of some part information. You can use pac without pace and it works just fine. Do i get you wrong or would you just be rewriting PAC? Tools to load the outfits already exist in the gamemode integartion.

**Comment by LuaTenshi** [comment]
Well the idea is to export a PAC into a lua file so that one would not only
be able to modify it (add more functionality) but also use it as a separate
addon without having to have PAC installed.

So if for example let's say your making a point shop, you would be able to
position your hats to your models correctly and then export the code. Then
you wouldn't need to have PAC as a requirement when uploading to the
workshop.

P.S. I hope I'm making since because I'm writing this at 6 am.

**Comment by LUModder** [comment]
The thing is, certain parts won't have functionality or even exist without them being readded. Examples are effects, particles, proxies, beams, command, etc

**Comment by LuaTenshi** [comment]
Yeah that may be a bit of a drawback however you could easily add stuff like that back in while coding your addon. It would just be really awesome to have a tool for developers that would help with positioning things.

**Comment by CapsAdmin** [comment]
I designed pac3 do be like that. Pointshop is an example of pac3 being used as you described.

**Comment by Kamshak** [comment]
yep, without the editor pac does exactly what you described @LuaTenshi . If you want to make it easier to embed you could merge all pac core files into one, load it in a fenv to make pac local and avoid conflicts. You could then ship that single lua file with your addon/swep/whatever. 

Still think simply telling people to install pac is the better option, it's not that much effort and works pretty well (i've created a few "models" for entities using PAC that are actually lua entities). If you look at @CapsAdmin 's fishing mod there are even more examples.

**Comment by LUModder** [comment]
I'm working on a tool via the editor to do this if anyone was wondering.

**Comment by LUModder** [comment]
Expirimental test version: http://pastebin.com/USkiVN0a
