### ISSUE TITLE
Optimize added features

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#247]
Apperently after a lot of features were added to PAC over the last 2 years, PAC has gotten laggy and unoptimized. This with how complex people make their PACs, is bad for older hardware. I dunno how much stuff is actually laggy and I might just be talking non-sense and it's not gonna get fixed and all that but still.

**Comment by thegrb93** [comment]
This needs to be reverted, https://github.com/CapsAdmin/pac3/commit/f01e98486ba36a86223802bc499361f311c5fcc1

You shouldn't have to restore the color of the shader. Simply don't allow the use of LightMappedGeneric shaders.

**Comment by CapsAdmin** [comment]
@thegrb93 If there's a list of shaders that actually do something without causing errors or other harm I'd use that list as a whitelist.

**Comment by thegrb93** [comment]
I can test them if I can find a list of all shaders. Most shaders don't even render properly on pac objects.
