### ISSUE TITLE
Not really an issue but i'm not sure where to ask this. how to add bodygroups?

### ISSUE THREAD

**Issue by dueldragon** [CapsAdmin/pac3#248]
There are some models i want to use with bodygroups. But i'm not sure how, so far i found that i can see the categories that has the bodygroups in them, can't see what's in the categories though, meaning i cannot use it.

**Comment by LUModder** [comment]
Until we can figure out how to network them for csmodels, its impossible rn

**Comment by dueldragon** [comment]
Oh well. thanks anyway
