### ISSUE TITLE
add missing model event

### ISSUE THREAD

**Issue by NavyCo** [CapsAdmin/pac3#249]
Could you add to the events list a possibility for if a model is missing for a client, it'll do the following?

**Comment by LUModder** [comment]
I dunno if it's a Meta only thing or not, but the error model should turn into a can already.

**Comment by NavyCo** [comment]
I know this... But I mean like if errors occures, such as if a model is invalid then try this shit after this in the event if this event fails then [repeat if types].

**Comment by LUModder** [comment]
but why

On Tue, Jan 26, 2016 at 7:46 AM, Nicholas Phillips <notifications@github.com

**Comment by NavyCo** [comment]
Have you thought of the possibility? The endless ifs? Like seriously now... If one person is missing a important model set... Then it'll go and activate [insert if statement here] if that === false also... Then it can do else if or else.

**Comment by LUModder** [comment]
Yeah but IsError isn't global for models

On Tue, Jan 26, 2016 at 8:21 AM, Nicholas Phillips <notifications@github.com

**Comment by NavyCo** [comment]
Well damn it.
