### ISSUE TITLE
Workshop PAC needs Updating - Old Bug causing Client Crashes

### ISSUE THREAD

**Issue by Hazbelll** [CapsAdmin/pac3#252]
The Workshop version of PAC hasn't been updated since last year. A lot of commits have passed since then, fixing some outstanding bugs. One of the most obvious being this: https://github.com/CapsAdmin/pac3/commit/08f16f036e60cb4617bab4c88d0082e7fc36e5de

This fixes said Lua error that occurred now and again on clients. It seemed to be harmless (although annoying), but it's actually a potential game crasher, although very rare.

Shortly before a crash, the Lua error gets spammed indefinitely:
![Image of PAC Lua Errors](https://cdn.discordapp.com/attachments/121877082560004096/143364737038548992/unknown.png)

Before finally (after literally a few seconds):
![Image of PAC Lua Errors Outcome](https://cdn.discordapp.com/attachments/121877082560004096/143364865182924800/unknown.png)

Although I took these screenshots with the Workshop version of PAC, I don't actually use the Workshop version anymore due to how outdated it is compared with the GitHub repo, but many other servers out there do, so it might be worth updating it sometime.

The issue itself is fixed, just not present in the Workshop version.

**Comment by LUModder** [comment]
I'm surprised servers are still even using the workshop version honestly. Yeah it should be updated for the simple people who don't know what git/svn is, but also more server owners who know how to should be switching over anyways.

**Comment by CapsAdmin** [comment]
done

**Comment by Hazbelll** [comment]
Thanks.
