### ISSUE TITLE
entity part flipping players

### ISSUE THREAD

**Issue by DaWinfred** [CapsAdmin/pac3#254]
Whenever you go to add 'Entity'. You're a person doing a 2011 Fad

**Comment by LUModder** [comment]
not descriptive enough

**Comment by LUModder** [comment]
You're probably using ragdoll models and not player models so this issue is invalid, wontfix if that's the case

**Comment by LUModder** [comment]
So apparently it only affects workshop version AFAIK

![](https://i.imgur.com/1yAc8VP.png)

**Comment by DaWinfred** [comment]
This all happened after that update today I believe, a bunch'a people in this RP server here are having the same effects with theirs

**Comment by LUModder** [comment]
GMod update broke it apperently. Dunno if it has to do with the VMatrix values being switched or not

**Comment by LUModder** [comment]
So I cannot confirm that this is recreatable in github version for some reason. Entity parts work fine for me on my server

**Comment by DaWinfred** [comment]
It's also unable to work when I load up Sandbox, with also choosing a random Civilian Playermodel

**Comment by Vuthakral** [comment]
People need to look into this. I don't personally have this issue but a lot of my friends are having it and annoying the fuck out of me just because I can commit chatsounds (fml). Neither they nor my server use the workshop version, all use the git version and are having the issue as well.

**Comment by LUModder** [comment]
I'm still assuming the fixing and networking of VMatrices is the problem

**Comment by Beauty-Bomber** [comment]
getting this too all my pacs are basically broken now coz garry fucked up....

**Comment by LUModder** [comment]
First off, Garry doesn't work on GMod anymore. Second off, this is happening too differently to be a replicatable bug

**Comment by CapsAdmin** [comment]
this was fixed i think cause it's not happening here
