### ISSUE TITLE
luadata decode error

### ISSUE THREAD

**Issue by Temmie1337** [CapsAdmin/pac3#255]
luadata_decode:1: unexpected symbol near '<'

This error won't upload my stuff from pastebin to pac3.

How to fix this?

**Comment by LUModder** [comment]
It's reading it as HTML for some reason I'm assuming.

**Comment by Temmie1337** [comment]
But, how to fix this?

**Comment by LUModder** [comment]
I can't recreate it without seeing the file that's doing it.

**Comment by Temmie1337** [comment]
I'll try to find that file.

**Comment by Temmie1337** [comment]
3d noplay noblock - that's the file that creating everything from pastebin to error.

**Comment by LUModder** [comment]
That's not a file. I wanted the pastebin file to see if I could recreate it if you don't mind.

**Comment by Temmie1337** [comment]
http://pastebin.com/pTKumbnb

**Comment by LUModder** [comment]
```
[PAC3] Failed to load 	http://mp3skullvideos.com/music/temp/Lovegame_(wWw.iPagalWorld.Com).mp3	(3d noplay noblock)
[PAC] Animation failed to parse from https://copy.com/4Dny6esUjbKvsJxr?download=
[PAC] Animation failed to parse from https://copy.com/4Dny6esUjbKvsJxr?download=
[PAC] Animation failed to parse from https://copy.com/4Dny6esUjbKvsJxr?download=
[PAC] Animation failed to parse from https://copy.com/4Dny6esUjbKvsJxr?download=

```

MP3Skull doesn't allow streaming of files, so you're gonna have to reupload it and all of your Copy links are missing a download key.

**Comment by Temmie1337** [comment]
Well, i tried (most of) Pac3 pastes, but everything is - luadata_decode:1: unexpected symbol near '<' .

And in single player too.

**Comment by Temmie1337** [comment]
I asced my friend to put in hes PAC3 this - http://pastebin.com/pTKumbnb.

I'TS WORKED FOR HIM WITHOUT ANY ERRORS.

**Comment by LUModder** [comment]
Somehing's blocking pastebin outside of your browser then.

**Comment by Temmie1337** [comment]
Well, i downloaded three browsers.

Nothing worked, again...

**Comment by Temmie1337** [comment]
it's just wohn't work...

**Comment by Temmie1337** [comment]
Hey, maybe i need to enable this? - Widevine Content Decryption Module

**Comment by Temmie1337** [comment]
Please, help...

**Comment by Temmie1337** [comment]
But, what is blocking it?

**Comment by Temmie1337** [comment]
No one wanna help me...? Well, ok...

**Comment by SpiralP** [comment]
try using http://pastebin.com/raw/pTKumbnb

**Comment by SpiralP** [comment]
also, it might have been asking for a captcha and giving you an html version instead because you visited too many pastebin links too fast or something, try using another site to host your stuff

wait, why not just save the pastebin as txt then load it into the game :v

**Comment by Temmie1337** [comment]
I fixed this error. How? I connected to other wifi, it's working now.

**Comment by Temmie1337** [comment]
i don't know why, but my wifi is blocking some pastebins.

**Comment by CapsAdmin** [comment]
I've heard russia blocks some pastes based on keywords. Or maybe it's your router. There's some command call with the word "sexy" in there. Try replacing it with something else maybe.

Now that I've written sexy here idk if you'll be able to reach this issue again though lol

**Comment by LUModder** [comment]
I bet he can't even get into his email now either.

**Comment by Temmie1337** [comment]
Yeah, my router blocking it.

**Comment by Temmie1337** [comment]
And i can get to email.
