### ISSUE TITLE
Flex part don't work on changed entity model (HWM models for example)

### ISSUE THREAD

**Issue by zxz41** [CapsAdmin/pac3#258]
Whenever I try to change Flex after changing model (To models/player/hwm/engineer.mdl). It stops working and nothing happen.

![image](https://cloud.githubusercontent.com/assets/11709919/13036010/7ab03cc2-d35c-11e5-916a-5c6b6280885c.png)
Model on left. Player on right. (I messed around with all the flex parts but no change, yes I tried "wear")

**Comment by zxz41** [comment]
![image](https://cloud.githubusercontent.com/assets/11709919/13036024/dff0649a-d35c-11e5-8f1d-1872018035fa.png)
Another example. Right eye blinks but otherwise nothing else works.

**Comment by zxz41** [comment]
Update: Found something related to the issue. Changing the name (left_Smile) to it's ID (34) fixes it. It don't translate Flex name to ID correctly in some patch it seems.

**Comment by Cordon** [comment]
Yeah, found this out the hard way too. Just use ID's instead of the names.

**Comment by CapsAdmin** [comment]
it should be fixed now. reopen if not
