### ISSUE TITLE
pace.Restore/DisableExternalHooks doesn't handle entity/panel hooks correctly

### ISSUE THREAD

**Issue by UselessGhost** [CapsAdmin/pac3#264]
Line 203 and Line 215 of client.lua attempts to perform string manipulation (specifically string.sub) on hook identifiers. This creates an error in specific situations because hook identifiers can be either strings or any object that implements IsValid, most commonly entities and panels.

This can be easily resolved by first checking if the hook identifier is a string before calling string.sub.

**Comment by LUModder** [comment]
then make a pull request instead of telling us?

**Comment by UselessGhost** [comment]
Kind of a hassle given I'm doing this on behalf of someone else but alright.
https://github.com/CapsAdmin/pac3/pull/265

**Comment by Noiwex** [comment]
Flex you're bizarre awful creature, no wonder everyone makes you want to go suicide, as you say.

**Comment by LUModder** [comment]
@Noiwex how is that related to anything?

**Comment by Noiwex** [comment]
lol, you're very rude to others, why do you even post?

**Comment by Noiwex** [comment]
And then you go and just wipe up the traces, but it's still there: https://github.com/LUModder?tab=activity
Very mature.

**Comment by UselessGhost** [comment]
Actually I deleted the branch which deleted his comments.
