### ISSUE TITLE
Pac 3 cloud files 

### ISSUE THREAD

**Issue by zombieworld** [CapsAdmin/pac3#267]
If I throw out my old computer and put in a new one will my old Pac files download with Garry Mod into my new computer or will they be lost forever

**Comment by LUModder** [comment]
Then back them up to like dropbox or a flash drive then?

**Comment by zombieworld** [comment]
@LUModder And if I didn't back them up will they still appear on the new computer

**Comment by LUModder** [comment]
No. Data folder doesnt cloud upload. You have to copy it over yourself

**Comment by zombieworld** [comment]
Well then this problem solved all meh pac's are lost FUCK

**Comment by LUModder** [comment]
Don't worry, I lost w months worth due to autistic HeX's server
