### ISSUE TITLE
WebAudio Errors / oggs don't work

### ISSUE THREAD

**Issue by insanekid2** [CapsAdmin/pac3#27]
Having an issue with playing OGG sounds, I enabled the debug mode and proceeded to try to play a OGG sound. It printed a few errors like this:

[WebAudio] TypeError: Cannot call method 'play' of undefined[WebAudio] TypeError: Cannot call method 'play' of undefined[PAC3] Your part ogg has been applied.

Although others can hear the sounds, but I cannot.

**Comment by CapsAdmin** [comment]
Some people have reported to me that turning off audio effects in their soundcard solves this. Effects with names like "real surround" or "tru bass" etc
