### ISSUE TITLE
Attach PAC .text outfit to player?

### ISSUE THREAD

**Issue by willwhitehouse** [CapsAdmin/pac3#271]
In a custom gamemode how would I go about attaching PAC outfits to players, I tried setupent and attaching it using the given functions but that only allows me to add the outfit to 1 person, and gives me an error for a second person, also this way doesn't update for other players once removef

**Comment by willwhitehouse** [comment]
My error is
 [ERROR] addons/pac3/lua/pac3/core/client/integration_tools.lua:95: attempt to index local 'outfit' (a boolean value)
  1. AttachPACPart - addons/pac3/lua/pac3/core/client/integration_tools.lua:95
   2. func - gamemodes/testgm/gamemode/cl_init.lua:21
    3. unknown - lua/includes/extensions/net.lua:32
Reply With QuoteEdit / DeleteReplyEditTHIS BUG NEEDS FIXING, BUT I DONT KNOW WHAT CAUSES IT, SO SHUT UP AND STOP POSTING ABOUT IT. Thanks.  Show Events

**Comment by willwhitehouse** [comment]
Ignore the last couple sentences, I copied this directly from facepunch

**Comment by LUModder** [comment]
https://github.com/CapsAdmin/pac3/wiki/PAC-in-gamemodes#how-do-i-attach-parts-to-my-entity

**Comment by willwhitehouse** [comment]
Attach parts to my player, this is for scripted entity's or npcs
