### ISSUE TITLE
Crash with pointshop2?

### ISSUE THREAD

**Issue by roastt** [CapsAdmin/pac3#273]
I am on Linux, running a surf gamemode (Flows), have newest ULX and Ulib installed, pointshop2 and pac3. When I load pointshop every thing works fine, but when I go onto the hats tab it crashes me (https://gyazo.com/d851b4b0a935ef4d03d13582f86202b3), but for everyone else they can see it fine. But it might happen to more people, its only been tested by 5 people. 

On pointshop2 the only thing I did different to anyone, is I was the one who pressed the button (add pac3 default items). I have tried removing my local pac3 data, didn't work, I have tried using both workshop and github version, didn't work and there is no pac3 data on the server. Thanks for the help in advance!

**Comment by roastt** [comment]
I have pointshop mySQL.

**Comment by roastt** [comment]
`WARNIG: uncaught error

0	

0

[roast|32|STEAM_0:1:5261809] Lua Error:

 

[ERROR] 

 

 

[roast|32|STEAM_0:1:5261809] Lua Error:

 

[ERROR] error in error handling

  1. __index - [C]:-1

   2. build_bone_callback - addons/pac3/lua/pac3/core/client/parts/bone.lua:131

    3. unknown - addons/pac3/lua/pac3/core/client/parts/bone.lua:197`

**Comment by LUModder** [comment]
There's a problem with the outfit its trying to preview then.

**Comment by roastt** [comment]
Its fine for everyone else though, and its defualt pointshop gear. Any idea on what I should do?

**Comment by roastt** [comment]
It crashes a few more people now.

**Comment by roastt** [comment]
https://gyazo.com/2918efed645871a13b0a65b1396edd74 All models seem to load fine, but it still crashes.

**Comment by roastt** [comment]
When the models display all together it happens, when I disable display images, it doesn't crash me. And I can display them fine 1 by 1.
