### ISSUE TITLE
Effects

### ISSUE THREAD

**Issue by Pokerface31001** [CapsAdmin/pac3#275]
When i want to go and put an Effect down i cant move the Effect around, all i can move is the dot that is suppost to have the Effect in. Please help me as its annoying.

**Comment by LUModder** [comment]
Have you tried moving it from the editor's position boxes?

**Comment by Purple0** [comment]
This isn't an issue with the effect part itself, you just need to set Point A and Point B (etc) to where you want the effect to go, 

or you can attach the effect to a model and do it that way.

**Comment by Pokerface31001** [comment]
Ah thank you i have not yet been able to find out why its doing this until now.
