### ISSUE TITLE
Particle Emitters Leak - Invisible Map Entities/Players

### ISSUE THREAD

**Issue by Hazbelll** [CapsAdmin/pac3#277]
Upon joining a heavily populated Server (40 - 50 players):

```
[PAC3] Requesting outfits...
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
CUtlLinkedList overflow! (exhausted index range) (65535)
```

Map entities turn invisible due to this, and in worse cases (as has just happened to me now), players too. Have to reconnect and _hope_ the latter doesn't happen again (the former, you just have to live with).

Did a quick search for the issue. Apparently it was once a bug in Garry's Mod, but since been patched. Such issue now is down to how addons manage particle emitters themselves:
https://facepunch.com/showthread.php?t=1350845

**Comment by thegrb93** [comment]
It's definitely still and issue with garrysmod since smoke emitters can still cause this. https://github.com/Facepunch/garrysmod-issues/issues/1968 .

**Comment by Hazbelll** [comment]
Ah right, fair enough. I thought it might've been long fixed, since I couldn't find anything past 2014 regarding it. Thanks for that. It's very irritating to say the least.

**Comment by thegrb93** [comment]
I think that issue is caused by the gmod_emitter leaking particleeffects. If so then yeah, that needs to be fixed and pac needs to fix its leaks too.

**Comment by thegrb93** [comment]
Nevermind, smoke emitters use ParticleEffect, not ParticleEmitter

**Comment by CapsAdmin** [comment]
So all the players are using particle emitters? If that's the case I'm not sure what to do other than to force a limit on the amount of particle emitters.
