### ISSUE TITLE
Pac 3 3rd and 1st person

### ISSUE THREAD

**Issue by wontonanimalchin** [CapsAdmin/pac3#279]
So, theres probably a simple fix but im currently making a server where i wont some pac items to be visible to the player ie. Pets and guns but i want most other pac items to be invisible in 1st person ie.. masks, hats and clothes. So i pretty much want a player to be able to see thier own pet in 1st person but have the hats and other pac items to be invisible in 1st person so they dont inhibit the players view. Is there any way to do this?

**Comment by LUModder** [comment]
You can do viewmodel groups, but it won't render the whole PAC.

**Comment by wontonanimalchin** [comment]
I tried using the "viewmodel" as the owner name but it just make the model invisible

**Comment by wontonanimalchin** [comment]
If i have the draw distance at -1, is there a way to single out the certain items to have a different draw distance?
