### ISSUE TITLE
Camera doesn't move for anyone on my multiplayer server.

### ISSUE THREAD

**Issue by daxxom** [CapsAdmin/pac3#282]
Hi, I've run into an issue where after downloading a few addons from the workshop and installing them to my server, pac's camera isn't able to be moved or rotated by the clicking with the mouse. (It was working before these addons.) Single player works just fine though. I've deleted the addons i added to the server and don't have them installed myself. So i'm wondering what could be causing the camera to stop working like that? Anything would be appreciated as i've run into this issue quite a few times after running servers and having better knowledge of this would help me help other people with their similar issues.

Thanks.

**Comment by LUModder** [comment]
Try removing and readding addons until it doesn't work

**Comment by daxxom** [comment]
We'll I've deleted the three addons that it seemed to be connected to already, You're saying remove more addons until the problem goes away correct?

**Comment by LUModder** [comment]
Yep

**Comment by daxxom** [comment]
I've deleted everything except the bare essentials for running the gamemode. It's the camera is still unable to be moved by the mouse. Any next step?

**Comment by LUModder** [comment]
Anything in addons folder or anything that anyone placed in lua folder if
you have other people that can access?

**Comment by daxxom** [comment]
I'm not really sure what to look for out of the ordinary. There are a bunch more addons in the addons folder that i don't have syncd up to my workshop collection that's giving the server it's content. I can't name names as they're all just a bunch of numbers with .gma at the end of them, but the folder does have a higher amount of .gma's than my workshop collection so that's something to note.

**Comment by LUModder** [comment]
GMAs are workshop, mainly want folders if any

**Comment by daxxom** [comment]
No folders in addons, and these are the lua folders I have. I'm not sure whats normal: autorun, bin, derma, drive, entities, includes, matproxy, menu, post process, skins, vgui, and weapons.

**Comment by daxxom** [comment]
After reinstalling everything for my server, I checked as I got in if Pac had been fixed. It was when I first logged in. But after spending about an hour and forty-five minutes creating props and no clipping around I checked in on pac and the same issue randomly popped into fruition. I still can't move the camera and this time it seems to have either be caused by pac itself, or whatever I did why working on my server, Which was using no-collide, precision tools and advance duplicator. I'm not sure if they're related to the PAC error in any way but they are the only things I did on my end that could have cause this error. Knowing this now, is are is there anything you suggest I do?

**Comment by 00875** [comment]
Some script is creating panel that is not hovered but have enabled inputs.

**Comment by daxxom** [comment]
I'm a little confused, sorry, so you're saying something is creating an overlay or panel, and it has inputs enabled. But what do you mean by hovered?

**Comment by 00875** [comment]
It means that panel is focused. For example, HUD panel is not focused everytime, but scoreboard what you are opening is focused.

**Comment by daxxom** [comment]
I think I understand what you mean, like it's the panel is currently in use, as in it's the selected tab on your browser. But in this case it's not in use and still overriding my controls when I use pac. Although oddly enough I can still click on the menu in pac and edit values, but not the screen space where I view what i'm working on.

**Comment by 00875** [comment]
It just like sheets of paper. PAC editor sheet if lay over everything, but something is lay over the PAC camera move panel

**Comment by daxxom** [comment]
That's very helpful thank you! Unfortunately I'm not really familiar with what could be doing this. I assume the it's the schema's overlay. But I'm not really sure how to check for this. I'll ask around on the forums for the schema. Thank you.

**Comment by 00875** [comment]
You can try run lua on your client when PAC is on
Server needs sv_allowcslua 1

Open PAC3
Open client console
String to run into your client console:
``` lua_run_cl timer.Simple(1, function() print(vgui.GetHoveredPanel()) end) ```
After running this, close console (and game menu if it didn't closed) and hover mouse over empty of PAC3 editor space (just where you are trying to move camera using mouse), wait 1 second, then open console again. You should see something like
``` Panel: [name:GModBase][class:CGModBase][0,0,1440,900] ```

**Comment by daxxom** [comment]
Okay, I'll try that, where do I set sv_allowcslua 1 on a hosted virtual server? Would I do this in game or through rcon?

**Comment by 00875** [comment]
If you have RCon access, you should use rcon. If you have ULX installed, try ulx rcon sv_allowcslua 1

**Comment by daxxom** [comment]
I should be logged into rcon, it's not giving me any indicator that the commands you told me to use are working though. I think i'm just not entering the syntax for the rcon password command correctly.

**Comment by 00875** [comment]
ulx rcon sv_allowcslua 1 on your client console or sv_allowcslua 1 into server console
lua_run_cl timer.Simple(1, function() print(vgui.GetHoveredPanel()) end) into your **client** console

**Comment by daxxom** [comment]
This is the responce i'm getting in return from the server: 
`Can't change replicated ConVar sv_allowcslua from console of client, only server operator can change its value
`

**Comment by 00875** [comment]
You are running ```sv_allowcslua 1``` in your client console, you must run it in your server console

**Comment by daxxom** [comment]
Okay, I got this:
`Panel: [name:HTML][class:CAwsHTML][0,0,2000,1400]`

**Comment by 00875** [comment]
You got it. Something is creating HTML panel that is not visible but have enabled inputs

**Comment by daxxom** [comment]
Okay, cool. Although that is a little strange because my screen space 1200 by 600, so why would something create a panel that is almost double my height and width of my screen? Not saying it's not but that's a bit strange to try to get 100% width and height from the users screen to build your overlay on.

**Comment by LUModder** [comment]
I'd honestly be hunting down that addon instead of working around it.
