### ISSUE TITLE
Add smooth transition toggle checkbox for bone entities

### ISSUE THREAD

**Issue by Cordon** [CapsAdmin/pac3#286]
This may have been requested before, but it would be nice if we could have bones transition smoothly in and out instead of jumping right to the position and angles.
If this is already possible then sorry for the unnecessary thread clutter.

**Comment by CapsAdmin** [comment]
I tried adding this a while back but getting it to look right was difficult.

**Comment by Cordon** [comment]
Look right, as in making the limbs not pass through each other, or something else?
