### ISSUE TITLE
add pac code to someone who just joined the server

### ISSUE THREAD

**Issue by shortshows** [CapsAdmin/pac3#288]
how would i add a code i made with pac to when someone joins the server thwy would have the same pac as what i set or something like that help plz

**Comment by LUModder** [comment]
What is the point of this?

**Comment by shortshows** [comment]
so say if you use weapons on back players would have it so like you have a ak and it would show on your back for like rp

**Comment by LUModder** [comment]
Why use PAC for this?

**Comment by bizzclaw** [comment]
PAC is for personalizing your appearance, not really for integrating in to an RP gamemode. just make a ClientsideModel, parent it to the player, set it's render origin/angles to the bone you want to attach it too with any offsets you want and Draw it in PostPlayerDraw or something.

I can't really go in to detail, so I recommend posting a discussion on facepunch to get help with this. This isn't an issue with PAC, so it really doesn't belong here.

**Comment by LUModder** [comment]
Bizzclaw is pretty spot on with this. Honestly if you want to use PAC just to get the positioning and angles that would work.
