### ISSUE TITLE
mouse1 cannot cause pac_events or button event parts to trigger

### ISSUE THREAD

**Issue by Vuthakral** [CapsAdmin/pac3#294]
In events set to button press, mouse_left does not work, and no events bound to mouse1 will trigger either. This bug appeared for me a few months ago but I figured it was just me and moved on, only to ask a few others today and it turns out this is a problem for multiple, if not all, pac users.

**Comment by LUModder** [comment]
I've had the complete opposite where they would trigger everywhere

**Comment by Vuthakral** [comment]
Odd, I have little knowledge for how PAC works behind the scenes, and I'm really confused how there could be exact opposite reactions to the same or similar binds

**Comment by LUModder** [comment]
I haven't tried it recently so don't quote me on it working opposite
