### ISSUE TITLE
Help! I can't change my model!!

### ISSUE THREAD

**Issue by VPG001** [CapsAdmin/pac3#297]
I notice that people can change their model (under entities) only with certain ragdolls, but when I try to do that, nothing happens... Argh! I can't replace my model with anything! What am I doing wrong?

**Comment by LUModder** [comment]
Does the server have the model you want?

**Comment by Kaosheaven** [comment]
try rightclicking on the model and copying and pasting that into the box that says model

**Comment by VPG001** [comment]
I've tried doing that, but it keeps being pasted-in as "nil".

**Comment by VPG001** [comment]
This also appears when I copy'n paste:

[PAC3] lua/pac3/core/shared/modifiers/model.lua:12: bad argument #1 to 'IsValidModel' (string expected, got nil)
  1. IsValidModel - [C]:-1
   2. SetPlayerModel - lua/pac3/core/shared/modifiers/model.lua:12
    3. unknown - lua/pac3/core/shared/modifiers/model.lua:45
     4. unknown - lua/includes/modules/concommand.lua:54

**Comment by LUModder** [comment]
Addon is overwriting something. List of addons if possible?

**Comment by VPG001** [comment]
[Uploading better_water_effects_107901100.gma…]()
[Uploading bone_merger_104601200.gma…]()
[Uploading boshi_170280413.gma…]()
[Uploading carnotaurus_playermodel_+_npc_640544506.gma…]()
[Uploading cat_and_dog_swep_709764982.gma…]()
[Uploading cat_model_707187486.gma…]()
[Uploading cdi_hyrule_kingdom_room_151736305.gma…]()
[Uploading city_ruins_151539013.gma…]()
[Uploading cry_of_fear_lantern_132470017.gma…]()
[Uploading death_animations_701595427.gma…]()
[Uploading doors_499280258.gma…]()
[Uploading double_jump__284538302.gma…]()
[Uploading drink_sweps_316968975.gma…]()
[Uploading dromaeosaurus_playermodel_+_npc_634463893.gma…]()
[Uploading drop_weapon_on_death_153246356.gma…]()
[Uploading easy_bodygroup_tool_104604943.gma…]()
[Uploading easy_bonemerge_tool_170917418.gma…]()
[Uploading empty_hands_swep_245482078.gma…]()
[Uploading enhanced_playermodel_selector_504945881.gma…]()
[Uploading errols_n64_pack__180483863.gma…]()
[Uploading extended_properties_104607712.gma…]()
[Uploading fallout_new_vegas_radio_v3.0_-_updated_132829658.gma…]()
[Uploading fallout_snpcs_104558227.gma…]()
[Uploading food_and_household_items_108024198.gma…]()
[Uploading gesture_menu_&_commands_145939873.gma…]()
[Uploading gm_bigcity_105982362.gma…]()
[Uploading gm_bigisland_169600867.gma…]()
[Uploading gmod_13_css_sweps_with_c_models_187933083.gma…]()
[Uploading gmod_legs_3_112806637.gma…]()
[Uploading gmod_tower_player_model_pack_150404359.gma…]()
[Uploading gpixelart_706170725.gma…]()
[Uploading half_life_2_settings_111335690.gma…]()
[Uploading half-life_2_leak_props_complete_310835919.gma…]()
[Uploading hank_hill_(model_only)_699628486.gma…]()
[Uploading hb_player_controller_626999805.gma…]()
[Uploading high_dragon_playermodel_678248473.gma…]()
[Uploading hometown_1999_107455292.gma…]()
[Uploading horror_gamemode_273668401.gma…]()
[Uploading horror_story_124828021.gma…]()
[Uploading hs-14_nova_369546736.gma…]()
[Uploading hwm_face_poser_fix_227947662.gma…]()
[Uploading improved_resistance_npcs_678527208.gma…]()
[Uploading inpc_-_artifical_intelligence_module_632126111.gma…]()
[Uploading kirby_crystal_shards_model_pack_298307652.gma…]()
[Uploading l4d2_velociraptors_playermodels_w_viewmodel_hands_223970812.gma…]()
[Uploading ladder_stool_708225419.gma…]()
[Uploading ladder_tool_708225419.gma…]()
[Uploading life_mod_528581758.gma…]()
[Uploading life_mod_a_garrys_mod_visual_overhaul_528581758.gma…]()
[Uploading mario_party_playermodels_638202234.gma…]()
[Uploading melonize_110958085.gma…]()
[Uploading metropolice_glowing_eyes_154436194.gma…]()
[Uploading mewtwo_(ssb4)_player_model_459083973.gma…]()
[Uploading minecraft_swep_116592647.gma…]()
[Uploading minerva_metastasis_437327606.gma…]()
[Uploading model_manipulator_(fixed)_181322214.gma…]()
[Uploading model_manipulator_105920435.gma…]()
[Uploading more_materials__105841291.gma…]()
[Uploading neohls_horror_gamemode_537167868.gma…]()
[Uploading nombat_-_ambientcombat_music_270169947.gma…]()
[Uploading nombat_-_fallout_pack_270813928.gma…]()
[Uploading npc_scene_121182342.gma…]()
[Uploading npc_tools_104486597.gma…]()
[Uploading npc_weapons_-_true_firepower_unleashed_632126535.gma…]()
[Uploading npcgroups_136077464.gma…]()
[Uploading nsmbw_mega_pack_153145700.gma…]()
[Uploading original_dismemberment_mod_705020400.gma…]()
[Uploading pac3_104691717.gma…]()
[Uploading parakeets_pill_pack_106427033.gma…]()
[Uploading phoneme_tool_465506167.gma…]()
[Uploading pikachu_player_model_541000799.gma…]()
[Uploading playermodel_-_ssb4_-_yoshi_555148163.gma…]()
[Uploading prism_rifle_375176934.gma…]()
[Uploading rag_morph_104509899.gma…]()
[Uploading ragdoll_resizer_470366741.gma…]()
[Uploading ragdoll_roper_162196866.gma…]()
[Uploading resizer_116892991.gma…]()
[Uploading rp_amsterville_107471183.gma…]()
[Uploading rp_city8_canals_132911524.gma…]()
[Uploading rp_littletown_131302441.gma…]()
[Uploading s.t.a.l.k.e.r._materials_tool_gun_689001265.gma…]()
[Uploading shrink_ray_mod_167016569.gma…]()
[Uploading simple_thirdperson_-_sliders_&_fixes__207948202.gma…]()
[Uploading slappers_105225353.gma…]()
[Uploading smart_remover_tool_107382750.gma…]()
[Uploading smartsnap_104815552.gma…]()
[Uploading snivy_colorable_playermodel_134943703.gma…]()
[Uploading soft_lens-flare_142146606.gma…]()
[Uploading sonic_screwdriver_153825236.gma…]()
[Uploading spinosaurus_playermodel_609224166.gma…]()
[Uploading ssb4_-_yoshi_playermodel_and_npc_534045470.gma…]()
[Uploading ssb4u_yoshi_580132389.gma…]()
[Uploading standing_pose_tool_104576786.gma…]()
[Uploading super_mario_ragdolls_pack_105290081.gma…]()
[Uploading t._rex_playermodel_612053603.gma…]()
[Uploading the_dog_snpc_347416847.gma…]()
[Uploading the_sit_anywhere_script__108176967.gma…]()
[Uploading third_person_flashlight_250533116.gma…]()
[Uploading toothless_playermodel_696201828.gma…]()
[Uploading villager_(wild_worldbrawl)_playermodel_495694123.gma…]()
[Uploading vj_base_131759821.gma…]()
[Uploading weapon_drop_v2_116003885.gma…]()
[Uploading weight_stool_104480013.gma…]()
[Uploading wheatleys_parkour_410645074.gma…]()
[Uploading working_pip-boy_708695587.gma…]()
[Uploading yahtzee_player_model_105292871.gma…]()
[Uploading yoshi_ssbb_ragdoll_reupload_145264946.gma…]()
[Uploading zelda_aeralfos_playermodel_686293076.gma…]()
[Uploading zero_punctuation__player_model_105292871.gma…]()
[Uploading zs_last_mansion_v3_428782656.gma…]()

**Comment by VPG001** [comment]
oh and...
[addon.txt](https://github.com/CapsAdmin/pac3/files/352295/addon.txt)

**Comment by LUModder** [comment]
dont know why you made them all useless links

**Comment by VPG001** [comment]
I did? Sorry about that, I'll try and fix it.

**Comment by VPG001** [comment]
Ok, here's a list of some of the most SUSPECT add-ons that could be causing this problem:


1. Gmod 13 CS:S Sweps with C_models
http://steamcommunity.com/sharedfiles/filedetails/?id=187933083

2. Model Manipulator
http://steamcommunity.com/sharedfiles/filedetails/?id=105920435

3. Advanced Bone Tool
http://steamcommunity.com/sharedfiles/filedetails/?id=279079869

4. Gmod Legs 3
http://steamcommunity.com/sharedfiles/filedetails/?id=112806637

5. Rag Morph
http://steamcommunity.com/sharedfiles/filedetails/?id=104509899

6. NPC Tools
http://steamcommunity.com/sharedfiles/filedetails/?id=104486597

7. Extended Properties
http://steamcommunity.com/sharedfiles/filedetails/?id=104607712

8. Easy Bonemerge Tool
http://steamcommunity.com/sharedfiles/filedetails/?id=170917418

9. Life Mod
http://steamcommunity.com/sharedfiles/filedetails/?id=528581758

10. Smart Remover Tool
http://steamcommunity.com/sharedfiles/filedetails/?id=107382750

11. Resizer
http://steamcommunity.com/sharedfiles/filedetails/?id=116892991

12. Ragdoll Resizer
http://steamcommunity.com/sharedfiles/filedetails/?id=470366741

13. Easy Bodygroup Tool
http://steamcommunity.com/sharedfiles/filedetails/?id=104604943

14. Enhanced PlayerModel Selecto
http://steamcommunity.com/sharedfiles/filedetails/?id=504945881r

15. iNPC - Artificial Intelligence Module
http://steamcommunity.com/sharedfiles/filedetails/?id=632126111

16. Weight STool
http://steamcommunity.com/sharedfiles/filedetails/?id=104480013

17. More Materials!
http://steamcommunity.com/sharedfiles/filedetails/?id=105841291

18. SmartSnap
http://steamcommunity.com/sharedfiles/filedetails/?id=104815552

19. GPixelArt
http://steamcommunity.com/sharedfiles/filedetails/?id=706170725

20. Half-Life 2 Leak Props: Complete
http://steamcommunity.com/sharedfiles/filedetails/?id=310835919

21. Model Manipulator (Fixed
http://steamcommunity.com/sharedfiles/filedetails/?id=181322214)

22. VJ Base
http://steamcommunity.com/sharedfiles/filedetails/?id=131759821

23. Original Dismemberment Mod
http://steamcommunity.com/sharedfiles/filedetails/?id=705020400

24. HB Player Controller
http://steamcommunity.com/sharedfiles/filedetails/?id=626999805

25. NPC Scene
http://steamcommunity.com/sharedfiles/filedetails/?id=121182342

26. Improved Resistance NPCs
http://steamcommunity.com/sharedfiles/filedetails/?id=678527208

I listed all the most Questionable add-ons that I have... Hopefully this helps!!!

**Comment by LUModder** [comment]
Either Model Manipulator or Model Manipulator (Fixed) seem to be the victims

**Comment by VPG001** [comment]
Cool, I'll give them a try.

**Comment by VPG001** [comment]
Nope, still nothin.
