### ISSUE TITLE
Adding more than one body group change to a model through pax 3

### ISSUE THREAD

**Issue by Nightmare-Night** [CapsAdmin/pac3#298]
Hi, so I've been recently trying to add more than one body group to my pac 3 model by adding two body group things under my entity, but the last body group overwrites the first one. Any idea how to make it so both body groups are in effect when I load the pac 3 model?

**Comment by Nightmare-Night** [comment]
Also I meant pac in the title, made this issue form through my phone.

**Comment by LUModder** [comment]
Body groups were never working to begin with and doubt anyone will care to
fix them. Repeat issue of various issues. :v

**Comment by Nightmare-Night** [comment]
Well, alright, thanks for letting me know.
