### ISSUE TITLE
Weird Issue Regarding PAC Rendering

### ISSUE THREAD

**Issue by Kuqih** [CapsAdmin/pac3#300]
The video explains this better than I can.
https://www.youtube.com/watch?v=kIeooiZj1KE

I don't check GitHub often, if this is some how an error of mine please Tweet me @Kuqih.

**Comment by LUModder** [comment]
Looks more like the weapon rendering is causing it more than PAC itself being the cause

**Comment by CapsAdmin** [comment]
probably related to #107

**Comment by CapsAdmin** [comment]
video is gone so i don't know what this is anymore

**Comment by Kuqih** [comment]
I figured it out, UTime's aim at / show time was causing the issue.
