### ISSUE TITLE
[Request] : Core damage type for projectiles

### ISSUE THREAD

**Issue by Avernakis-Fox** [CapsAdmin/pac3#301]
I know this isn't a proper issue just something i'd like to be added to pac3 in general.

I know there's like a dissolve damage type but i'd love for the core damage type, as in it's like dissolve but the "victim" gets disintegrated instantly instead of that floating, black body thing that disappears after around 3 secs. It's an actual effect in hl2 i'm pretty sure of it and i've seen it used in i think a weapon mod once where people were instantly "purged" from existence with a little dissolve kind of particle in the shape of where they were once standing when hit.

It'd be great for numerous pacs, including things like tripods from wotw heh.

**Comment by AfaaGames** [comment]
Issues can be marked as Features.

**Comment by LUModder** [comment]
@AfaaGames Yeah but no one but Caps and Python have access to do so and they don't regularly monitor issues like I do and I doubt any of them would give me access to do so, Python maybe but Caps, not so much
