### ISSUE TITLE
Entity Glitch

### ISSUE THREAD

**Issue by fuckinkomkommer** [CapsAdmin/pac3#302]
Sometimes, when changing your own model via the entity part, it simply will not work.

EG, you can't change yourself from a regular citizen into a barrel using the entity

**Comment by LUModder** [comment]
Server must have the model.

**Comment by fuckinkomkommer** [comment]
it isn't working on singleplayer

**Comment by CapsAdmin** [comment]
If the gamemode is not sandbox you need to set the console variable pac_modifier_model to 1
