### ISSUE TITLE
Turn PAC txt file code into a lua file for an addon

### ISSUE THREAD

**Issue by AfaaGames** [CapsAdmin/pac3#303]
Is this possible?

I made viewmodels for hl2 weapons and I want to add it to my server without having people use PAC Editor and create stuff.

If I set it to admins only, but let them wear that outfit only, they're able to use console commands to wear whatever they want, OR they will automatically be wearing whatever outfit they wore last on another server.

**Comment by LUModder** [comment]
I had a WIP tool option for this but I have lost it and it wasn't a perfect translation. I have a somewhat perfect translation as far as scale, position and angles but it doesn't really support materials yet but [if you want to mess with it](https://github.com/LUModder/FWP/blob/master/lua/weapons/weapon_flex_base.lua#L56-L114) and if you need an [example, try this](https://github.com/LUModder/FWP/blob/master/lua/weapons/weapon_fwp_railgun.lua#L52-L112).

**Comment by AfaaGames** [comment]
It doesn't use materials at all, just messes with the coordinates/position of the viewmodel of weapons.
Or does that still take materials?

**Comment by LUModder** [comment]
That'll be fine for what you need then, just put "" for the material when using AddVM/WM

**Comment by AfaaGames** [comment]
What do I do with this file though? I'm a bit confused

**Comment by LUModder** [comment]
You don't use the file, you implement the highlighted areas of the files
into your weapon base and weapons respectively.

I know you wanted simplicity but nothing isn't going to be simple. To a
beginner all code looks complicated. To an experienced person, you don't
want to really touch PACs code.

Even though adding a tool is really simple, there's no way to perfectly
export something without copy pasting, but doing that still has risks of
not working.
