### ISSUE TITLE
How to turn .TXT's into PAC (I know this sounds stupid but please Just listen to it)

### ISSUE THREAD

**Issue by Devlonation** [CapsAdmin/pac3#304]
So, My friend sent me the .txt code so I put it into a Text Document, And put it into Pac 3 But it doesn't work, And I have no Idea what to do about it can someone help?

**Comment by Devlonation** [comment]
Here is the Command  [1] = {
["children"] = {
[1] = {
["children"] = {
},
["self"] = {
["Size"] = 0.6,
["ClassName"] = "entity",
["HideEntity"] = true,
["UniqueID"] = "2684995436",
},
},
},
["self"] = {
["EditorExpand"] = true,
["UniqueID"] = "1923864345",
["ClassName"] = "group",
["Name"] = "my outfit",
["Description"] = "add parts to me!",
},
},
[2] = {
["children"] = {
[1] = {
["children"] = {
},
["self"] = {
["UniqueID"] = "938572061",
["Scale"] = Vector(0.20000000298023, 0.30000001192093, 0.20000000298023),
["Material"] = "models/antlion/antlion_innards",
["Position"] = Vector(1.1240234375, 1.26806640625, 0.2322998046875),
["Angles"] = Angle(47.58695602417, -90.651931762695, -176.49433898926),
["Color"] = Vector(225, 255, 0),
["Bone"] = "left calf",
["Model"] = "models/hunter/blocks/cube025x2x025.mdl",
["ClassName"] = "model",
},
},
[2] = {
["children"] = {
},
["self"] = {
["Position"] = Vector(-0.9921875, -0.0406494140625, 0.000885009765625),
["ClassName"] = "model",
["UniqueID"] = "2268410445",
["Size"] = 1.225,
["Color"] = Vector(225, 255, 0),
["Material"] = "models/debug/debugwhite",
["Model"] = "models/pac/default.mdl",
["Scale"] = Vector(0.40000000596046, 1, 1),
},
},
[3] = {
["children"] = {
[1] = {
["children"] = {
},
["self"] = {
["UniqueID"] = "1245370685",
["ClassName"] = "clip",
},
},
},
["self"] = {
["Position"] = Vector(-6.5537109375, -0.1099853515625, -0.00189208984375),
["ClassName"] = "model",
["UniqueID"] = "1999018207",
["Size"] = 1.225,
["Color"] = Vector(255, 223, 127),
["EditorExpand"] = true,
["Model"] = "models/pac/default.mdl",
["Angles"] = Angle(-5.4868298320798e-005, 178.60447692871, -0.00035026064142585),
},
},
[4] = {
["children"] = {
[1] = {
["children"] = {
},
["self"] = {
["UniqueID"] = "3786057747",
["ClassName"] = "clip",
},

**Comment by LUModder** [comment]
Pastebin it ffs

**Comment by LUModder** [comment]
And it's not a command, it's a Lua table

**Comment by Devlonation** [comment]
Oh I see, So put it in a pasebin?

**Comment by Devlonation** [comment]
Thank you as well.

**Comment by Devlonation** [comment]
Doesn't work still.

**Comment by Devlonation** [comment]
The pastebin Url doesn't work, Either.

**Comment by Devlonation** [comment]
It doesn't show up in my Pac 3 folder

**Comment by LUModder** [comment]
The error will be in the console whenever it fails to decode or load

**Comment by Devlonation** [comment]
Okay.

**Comment by Devlonation** [comment]
URL fail: http://pastebin.com/raw.php?i=8XqUQpDv : luadata_decode:1: '}' expected near 'is'
That is what it says

**Comment by Devlonation** [comment]
I have loaded the code into a .txt folder, then put it in the Pac3 Folder.
It doesn't work, and the URL still fails... Hm.

**Comment by LUModder** [comment]
Pastebin link doesn't work cause it's private

**Comment by Devlonation** [comment]
Oh Okay.

**Comment by Devlonation** [comment]
It now says this after it is in public
Decoding pac3//test.txt failed: luadata_decode:83: '}' expected (to close '{' at line 76) near '<eof>'
URL fail: http://pastebin.com/raw.php?i=v7v0Vc6a : luadata_decode:83: '}' expected (to close '{' at line 76) near '<eof>'

**Comment by LUModder** [comment]
Missing a } somewhere, friend messed up sending the file.

**Comment by Devlonation** [comment]
Okay

**Comment by Devlonation** [comment]
Thank you.

**Comment by Devlonation** [comment]
I will say if a problem comes up
