### ISSUE TITLE
add a way for the player's yaw aim to not turn in a grid in the entity part

### ISSUE THREAD

**Issue by CapsAdmin** [CapsAdmin/pac3#308]
so it doesn't do the grid ish turn like here
https://youtu.be/HKGmAb5voBg?t=9

**Comment by Cordon** [comment]
Why does it even do this? I really found it jarring while I was making that PAC, thought it had something to do with IK, but it's probably not that.

**Comment by thegrb93** [comment]
It does this so the player turns their head before their body.
