### ISSUE TITLE
Possible conflict with FPP?

### ISSUE THREAD

**Issue by Bryantdl7** [CapsAdmin/pac3#309]
Please see https://github.com/FPtje/Falcos-Prop-protection/issues/190 for the full post. 

[ERROR] workshop/lua/fpp/client/ownability.lua:43: Tried to use a NULL entity!

__newindex - [C]:-1
entGetOwner - workshop/lua/fpp/client/ownability.lua:43
CPPIGetOwner - workshop/lua/fpp/sh_cppi.lua:36
[ERROR] workshop/lua/fpp/client/ownability.lua:43: Tried to use a NULL entity!

__newindex - [C]:-1
entGetOwner - workshop/lua/fpp/client/ownability.lua:43
CPPIGetOwner - workshop/lua/fpp/sh_cppi.lua:36
check_owner - workshop/lua/pac3/core/client/owner_name.lua:23
HandleOwnerName - workshop/lua/pac3/core/client/owner_name.lua:123
CheckOwner - workshop/lua/pac3/core/client/base_part.lua:239
unknown - workshop/lua/pac3/core/client/parts/group.lua:19

**Comment by LUModder** [comment]
See the non flamewar parts of #200

**Comment by thegrb93** [comment]
This is already fixed
