### ISSUE TITLE
PAC Text Chat Events Not Working

### ISSUE THREAD

**Issue by CrimsonConch** [CapsAdmin/pac3#311]
This problem has been going on for some time, at first I thought it was just the server, so I reset the server, still wouldn't work, so I reinstalled PAC, and it still doesn't work. Any tips? Console commands that I made need to input??

**Comment by LUModder** [comment]
What gamemode and/or chatbox if any are you using

**Comment by CrimsonConch** [comment]
DarkRP and the default source chat. I do, howerver, have some modifications to the chat box. (Chat tags and player disconnect / connect / finished loading notification)

**Comment by roboderpy** [comment]
Chat tags kills it all

**Comment by LUModder** [comment]
Mind sending over the chat tags just to see if that's the case?

**Comment by LUModder** [comment]
@DBot cannot confirm until I see code

**Comment by CrimsonConch** [comment]
http://steamcommunity.com/sharedfiles/filedetails/?id=541919294&searchtext=chat+tags

Heres the link to the chat tag addon we use

**Comment by roboderpy** [comment]
Chat tags uses OnPlayerChat clientside and returns true. PAC use OnPlayerChat too for chat events, but because tags is returning true, PAC hook isnt getting called

**Comment by LUModder** [comment]
Yeah I'd get rid of it and make your own properly

**Comment by CrimsonConch** [comment]
Ok, thanks for the help!
