### ISSUE TITLE
Idea: Add a Polygonless "model"

### ISSUE THREAD

**Issue by DeadlyTiger** [CapsAdmin/pac3#312]
Add a Polygonless model, but one that still has a skeleton, that can be used for the "entity" Modifier. Reason for this, is for the Ragdolisation of the PAC outfit, but upon death, The model assigned to use, will appear, and can often leave an ugly result. and enabling the "hide ragdoll upon death" also hides the entire skeleton, and makes the death view bug out (once you die, the camera falls through the ground.
It also stop all the objects assigned to the different bones, from following the skeleton, As the skeleton is not there, due to it being hidden

So, quick resume of it, i suggest adding a model, with no polygons (or the minimum possible that still has the skeleton. 

Also, i have tried Changing the Alpha, and the texture, but they're reset upon death

**Comment by DeadlyTiger** [comment]
Also, sorry about the Closing the issue to start with, Accidentally hit enter and opened the Topic, before i had made the desc. First time user here, so i semi panicked

**Comment by thegrb93** [comment]
I don't think its a good solution for fixing death animation. Also obj doesn't support skeletons.

**Comment by DeadlyTiger** [comment]
I was more thinking of something within the PAC.3 Selection of models, like it has the Female Model, and the male model, and the capes. i am well aware about the OBJ's not being able to support bones, i'm already using Custom obj's atm for my current outfit. 
also, it's not as much Death animation, as much as it's Ragdolisation, as it's not an animation that's playing, but rather the physics

**Comment by thegrb93** [comment]
Oh I see what you mean. An actual biped model with no mesh. Death ragdoll color/texture being reset was fixed recently, so I think you can use this fix. https://github.com/Metastruct/pac3/commit/07fb2e86bd634e677fbf9e26ba4a061426d7749d

**Comment by DeadlyTiger** [comment]
oh, ok. Though i am not capable of understanding what the heckerino the post you refered to is, due to my Newbness with PAC 3, i've only used the Interface shown within G-mod, and not actually ventured beyond that (except for custom obj's, textures and such) so i'm not sure what to make of that code

**Comment by thegrb93** [comment]
Just download metastruct's pac code and use it until this repository pulls that fix.
