### ISSUE TITLE
PAC3 Won't work in single player.

### ISSUE THREAD

**Issue by ShrikeTheGod** [CapsAdmin/pac3#313]
Umm? Downloaded a long time ago, made a shit ton of wide bodies and mud trucks but now i cant even get into PAC3?

**Comment by roboderpy** [comment]
Always start listen multiplayer LAN server with two slots instead of singleplayer. Singleplayer is quite broken,

**Comment by ShrikeTheGod** [comment]
It does, download the pac zip that's in the desc of the add on of the workshop
