### ISSUE TITLE
Idea: Support For gm_bass

### ISSUE THREAD

**Issue by tokelpl** [CapsAdmin/pac3#314]
Give Support for gm_bass plugin like a proxy for visualisations

**Comment by thegrb93** [comment]
bass is for sound though?

**Comment by Kaosheaven** [comment]
Pac3 has sound parts

**Comment by Kaosheaven** [comment]
But that obv doesn't apply

**Comment by tokelpl** [comment]
I mean that we can create a visualisers with proxies or something

**Comment by LUModder** [comment]
Honestly not possible unless you want high net usage trying to network millions of parts to be synced with sound.
