### ISSUE TITLE
Entity Model problem

### ISSUE THREAD

**Issue by Wafflekek** [CapsAdmin/pac3#315]
I made a TF2 Sniper PAC and its been working fine but when i went into a single player server, Instead of the sniper model, it was a breen model (Which is what i had selected in the player model menu) Is it a problem with addons or is pac messing up?

**Comment by LUModder** [comment]
TF2 not mounted on that server then. Duplicate issue.

**Comment by Wafflekek** [comment]
When i joined a server that had TF2 mounted on it, My player model kept switching between a tf2 sniper (with holdtypes) and a t-pose breen model

**Comment by LUModder** [comment]
Then you have too many entity parts, you only need one and the scout
example uses more in a bad way. Rather replace gravgun and physgun than
move it.
