### ISSUE TITLE
I can't hear the music

### ISSUE THREAD

**Issue by gianlucarsm** [CapsAdmin/pac3#316]
in console appears this message: "[PAC3] Failed to load     https://dl.dropboxusercontent.com/s/yrv96t6hvrpqq94/F-777_-_Airborne_Robots_%28GEOMETRY_DASH_MELTDOWN%29.mp3    (3d noplay noblock)
"

**Comment by LUModder** [comment]
!()[http://i2.kym-cdn.com/entries/icons/facebook/000/018/489/nick-young-confused-face-300x256_nqlyaa.jpg]

**Comment by gianlucarsm** [comment]
lol, sorry im italian

**Comment by LUModder** [comment]
Nothing we can do about it, PAC owners fault

**Comment by gianlucarsm** [comment]
but my friend hear the music

**Comment by LUModder** [comment]
ITS NOT AN ISSUE WITH THE ADDON FFS

**Comment by gianlucarsm** [comment]
music of downloaded pac works...

**Comment by LUModder** [comment]
Then its that one specific PAC then

**Comment by gianlucarsm** [comment]
OMG, it works!

**Comment by LUModder** [comment]
Thanks for wasting my time.

**Comment by gianlucarsm** [comment]
thank you and sorry

**Comment by thegrb93** [comment]
Only people who see the outfit will be able to hear the sounds.
