### ISSUE TITLE
ULR and Paste issue

### ISSUE THREAD

**Issue by kidder666** [CapsAdmin/pac3#318]
Im trying to add a sound effect to my url, but it just keeps saying nil for some reason, then I clicked the url tab and pasted it, but it STILL dosent work, can someone help me? This is also an issue with the normal sound one as well.

**Comment by LUModder** [comment]
Related to #297

How are you pasting? Are you doing right click > paste or Ctrl+V

**Comment by kidder666** [comment]
right click.

**Comment by kidder666** [comment]
That works. Thanks.
