### ISSUE TITLE
PAC Problem Switching Old Copy.com links to Dropbox Links

### ISSUE THREAD

**Issue by Ameno-Sagiri** [CapsAdmin/pac3#319]
-Please read the entire post, I detail a couple different problems I'm experiencing with this. It's not just a single problem.-
I've made a ton of PACs, all of them hosting everything on Copy.com, which was like dropbox but offered more free space with no bandwidth limits. Copy shut down back in May and I transferred everything over to a Dropbox pro account and I have slowly been fixing any PAC I feel like using when I want to use it.

I've run into a serious problem though involving PAC refusing to cooperate and many PAC related script errors.

I load up a PAC full of Copy links (Models and textures, sometimes sounds). Whenever I load one up, it completely breaks web downloading on that PAC. I cannot simply replace a copy link with a Dropbox link or else it spits out this error and nullifies the field where model was:

```
[ERROR] addons/pac3-master/lua/pac3/core/client/util.lua:274: attempt to index local 'ent' (a nil value)
  1. CreateEntity - addons/pac3-master/lua/pac3/core/client/util.lua:274
   2. Initialize - addons/pac3-master/lua/pac3/core/client/parts/model.lua:118
    3. func - addons/pac3-master/lua/pac3/core/client/parts/model.lua:494
     4. unknown - addons/pac3-master/lua/pac3/editor/client/parts.lua:127
      5. Call - addons/pac3-master/lua/pac3/editor/client/init.lua:242
       6. OnValueChanged - addons/pac3-master/lua/pac3/editor/client/panels/properties.lua:403
        7. OnEnter - addons/pac3-master/lua/pac3/editor/client/panels/properties.lua:692
         8. unknown - lua/vgui/dtextentry.lua:77
```

If I add another model to the PAC altogether on its own, and put in Dropbox links, it still refuses. It seems that as long as there is any model present in my PACs using a Copy link, it refuses to let Dropbox work. I cannot clone a part using a Copy link, I cannot erase the model field and try it again. I've tested a lot of things such as re-wearing after removing a copy link, and re-saving as well, only to discover that the txt file is actually NOT SAVING my changes. It seems PAC is just unable to replace the Copy links even if I remove the links and re-save the PAC as a different name, or same name.

I managed to fix it once by manually editing out every instance of a copy link with Notepad++, but I've come across another PAC that just won't let this work. I'm curious to know what's going on here and if there is any way to fix this. This should just be a simple link replace procedure but it's turning out to be a huge headache. It's especially bad for the current one because it's using a ton of material parts with many different textures, and trying to figure out which textures go in which spots is a problem.

**Comment by LUModder** [comment]
Honestly people should drop Dropbox and Copy and just make a GitHub repo
and use raw links from GitHub.

**Comment by Ameno-Sagiri** [comment]
I never looked into it. I was trying to find something else but didn't realize Github could do that. Is there a syncing program so I can keep my folder structure I use for Dropbox? Also wondering if there's a size limit. My PAC folder of models and textures/sounds is about 2GB.

**Comment by LUModder** [comment]
There's a file size limit but I doubt there's a global limit that low.
There are many git clients, I personally would look into using git before
you go down that road but the client I use usually is either command line
or GitKraken if you want a GUI.

**Comment by Ameno-Sagiri** [comment]
Just an update on the actual issue incase anyone else has this problem. I deleted every instance of a copy link in Notepad++, then I had to load up the fixed up PAC, and then I had to replace every model field with a random letter to turn it into an ERROR model, then it allowed me to replace the error with a dropbox link.
