### ISSUE TITLE
Add option to use the rope part as a path for sprites

### ISSUE THREAD

**Issue by Immortalyes** [CapsAdmin/pac3#321]
Inspired by the wowozela, it would be neat to draw sprites on a specified path (made with the rope part). Maybe this can be its own part or option within rope, with frequency for how many sprites per path, sprite scale etc. as attributes, however the sprites are just like sprites in the sprite part, and not a texture.

**Comment by LUModder** [comment]
Would be also great to make paths for ropes in general.
