### ISSUE TITLE
Conflicts of multiple entity parts

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#322]
If there are inequal values on certain properties, one takes priority over the other or they "fight" for priority.
**ex:** part one has model and size set, other has weapon checked without size and model set, model gets unset and size rapidly changes back and forth.

Weapon property doesn't seem to br noticed by other entity parts. Multiple entity parts fight for priority.

There has been workarounds but for weapons like physgun, skin 2 of w_physics.mdl can also fight for texture color priority if someone else has their physgun out. (engine/sandbox issue?)

**Comment by LUModder** [comment]
#315 seems to be the only reported issue on this

**Comment by CapsAdmin** [comment]
So what do you expect to happen? That the last part shown should be prioritized?
