### ISSUE TITLE
PAC3 Websound and .OGG not working only for me

### ISSUE THREAD

**Issue by TheThreeQuestionMarks** [CapsAdmin/pac3#323]
I need some help with this. Two days ago, I was playing, and my pac WebAudio and .OGG stopped working, I hear other peoples, but me and others don't hear mine. All my original pacs, that I worked on forever REQUIRE webaudio or .ogg, And I need help as soon as possible. I did everything, pac_restart, Exiting the game, Restarted the computer, redownloading the mod, even waiting two days. And nothing on the internet helps me. I really can have some help here. Respond ASAP please.

**Comment by LUModder** [comment]
Any errors in the console?

**Comment by TheThreeQuestionMarks** [comment]
No.

**Comment by LUModder** [comment]
For clarification I'm looking for either
- [PAC3] Unable to play <url> (error)
- Invalid sample rate (#####)

**Comment by TheThreeQuestionMarks** [comment]
Let me see.

**Comment by TheThreeQuestionMarks** [comment]
Oh man, I didn't even notice.

**Comment by TheThreeQuestionMarks** [comment]
There is like this stuff
"[PAC3] Failed to load 	https://dl.dropboxusercontent.com/s/vb1siivb3izbtih/Pac-Man%20Remix.mp3	(3d noplay noblock)"

**Comment by TheThreeQuestionMarks** [comment]
What do I do to fix this?

**Comment by TheThreeQuestionMarks** [comment]
Hello?
Can you continute helping me?

**Comment by TheThreeQuestionMarks** [comment]
*Continue

**Comment by TheThreeQuestionMarks** [comment]
Adn this is for the .oggs
"[PAC3] OGG error: stream[0x90910010][188][https://dl.dropboxusercontent.com/s/oklpb7d69tazfmx/Wave6.wav] reason: decoding failed"

**Comment by LUModder** [comment]
sorry github didnt send me emails again

Your dropbox link gave me a 429, aka too much trafic.

Pretty much you're fucked for 24-48 hours


I best recommend making a github repo for content and use raw urls.

**Comment by thegrb93** [comment]
Sounds only play if you can see your outfit.

**Comment by LUModder** [comment]
@thegrb93 thats not the issue, test the link and you should get 429.

**Comment by TheThreeQuestionMarks** [comment]
Fuck. 48 hours? I already waited two days.

**Comment by TheThreeQuestionMarks** [comment]
THis started three days ago.

**Comment by TheThreeQuestionMarks** [comment]
Also, thanks for the help.

**Comment by TheThreeQuestionMarks** [comment]
You said 24-48 hours.
**_I've waited three days._**
# Why is it doing this?

**Comment by TheThreeQuestionMarks** [comment]
Hello?

**Comment by thegrb93** [comment]
Oh, the title made it sound like he was the only one who couldn't hear the sounds.

You're dropbox is messed up or something.

**Comment by TheThreeQuestionMarks** [comment]
Yeah, I figured that out wiht the otehr person.
The sounds work fine in the dropbox itself, somethings screwed up.

**Comment by TheThreeQuestionMarks** [comment]
Can I get a response for my latest question?

**Comment by TheThreeQuestionMarks** [comment]
You said 24-48 hours.
I've waited three days.

Why is it doing this?

**Comment by thegrb93** [comment]
He probably underestimated it. Use your brain.

**Comment by LUModder** [comment]
Dropbox doesn't want mass file hosting done on their servers.

I have made a guide for using github for content [here](https://github.com/CapsAdmin/pac3/wiki/Hosting-Custom-Content-on-GitHub)

**Comment by TheThreeQuestionMarks** [comment]
LUModder, Where do I go to for "upload files"?

**Comment by LUModder** [comment]
Should be on the right next to download, find files and new file

**Comment by TheThreeQuestionMarks** [comment]
I can't find that.

**Comment by TheThreeQuestionMarks** [comment]
# **_Where do I find this?_**

**Comment by TheThreeQuestionMarks** [comment]
I need help now
.

**Comment by TheThreeQuestionMarks** [comment]
![question_mark](https://cloud.githubusercontent.com/assets/22382589/18770436/bcfaf108-8103-11e6-95b2-7bd47c2818f3.PNG)

**Comment by TheThreeQuestionMarks** [comment]
This is my screen
Where is it?!

**Comment by TheThreeQuestionMarks** [comment]
Okay, I deleted some dropbox files, will it be fixed?

**Comment by Ameno-Sagiri** [comment]
No it won't be fixed just by deleting files. If you have a free Dropbox account, you likely have a very low traffic limit on it. Too many people tried to load stuff off your Dropbox, and it placed a lock on your account or that specific file on your account. 2 days was just a generalization, it could likely be longer than that.
