### ISSUE TITLE
Making PAC3 admin only?

### ISSUE THREAD

**Issue by jkarateking** [CapsAdmin/pac3#324]
PAC3 doesnt come under tool restrictions so I dont know how to make it admin only. How would I do this?

**Comment by LUModder** [comment]
[This should help you](https://github.com/CapsAdmin/pac3/wiki/PAC-in-gamemodes)

**Comment by CrimsonConch** [comment]
How would we edit this to make it so that it works for admins, vip usergroups and vip mod and trialmod?

**Comment by LUModder** [comment]
local ranks = {
"trialmod",
"vip",
"vipmod",
}

for k,v in pairs(ranks) do
if pl:GetUserGroup() == v or pl:IsAdmin() then
return true
else
return "Insufficient rank to use PAC"
end
end

**Comment by CapsAdmin** [comment]
could you add that code to the wiki?

**Comment by LUModder** [comment]
Added
