### ISSUE TITLE
Can't load outfit - table too large; bad values

### ISSUE THREAD

**Issue by Roshag** [CapsAdmin/pac3#326]
Made a "small" collection of three guns, can't load because of too much parts (may be). Opened the outfit file and saw terrible angles and positions like "["Angles"] = Angle(-90, 3.5764918720815e-005, 5.31786895408e-007)". Previous file size - 207 kb, after some cleaning - 199 kb. Why so large numbers? 4-5 signs after comma should be enough

**Comment by LUModder** [comment]
Net message can only send 64kb of data at once. Split things into separate outfit groups

**Comment by LUModder** [comment]
Also you can ctrl click values in the editor and it'll round them.

**Comment by Roshag** [comment]
Okay, thank you

**Comment by thegrb93** [comment]
Just so you know though, rounding the numbers won't lower the net message size.

**Comment by CapsAdmin** [comment]
@thegrb93 

Before sending I actually tostring the numbers and then tonumber them back again because I found that net.WriteTable rounds the numbers too much.

It should be easy to replace the method which sends and receives outfits with something that can be of arbitrary length. I tried to do this before but the library I was using was not working properly. Maybe there's something working now.

**Comment by thegrb93** [comment]
tonumber of the string should yield the same thing as net.ReadDouble. That's really weird, I'll have to test that.

**Comment by thegrb93** [comment]
I ran this code in starfall, and got 0,0,0,0
```
--@name 
--@author 
--@shared 

if CLIENT then
    if player()~=owner() then return end
    local S = {"1", "2.5", "1.2345", "1.5287394872324234267676782343465565498743434"}
    for i=1, #S do
        net.start("A")
        net.writeString(S[i])
        net.send()
        
        net.start("B")
        net.writeDouble(tonumber(S[i]))
        net.send()
    end
else
    local A, B
    hook.add("net","",function(n)
        if n=="A" then
            A = tonumber(net.readString())
        elseif n=="B" then
            B = net.readDouble()
        end
        if A and B then
            print(A-B)
            A = nil
            B = nil
        end
    end)
end
```
