### ISSUE TITLE
Glitches. Glitches everywhere.

### ISSUE THREAD

**Issue by Thekingofanimation** [CapsAdmin/pac3#329]
So the one. ONE glitch im talking about is the entity glitch. So everytime i add two entities for making 2 weapons not draw to show one model, one of them messes up when they are in a different group. please fix this problem i've been getting very, very frusturated with this problem so please, please fix this.

**Comment by LUModder** [comment]
Duplicate of #315 and #322

**Comment by Thekingofanimation** [comment]
How can I fix this problem because I always have this problem with entity's.

**Comment by LUModder** [comment]
Not use more than one entity part.
