### ISSUE TITLE
Random timer in event broken

### ISSUE THREAD

**Issue by Immortalyes** [CapsAdmin/pac3#331]
lua/pac3/core/client/parts/event.lua:80: attempt to compare number with boolean
hiding your outfit to prevent further errors

http://i.imgur.com/tR1PBpk.png

**Comment by LUModder** [comment]
Code looks good, dunno why it's doing it.

**Comment by LUModder** [comment]
Issue seems to be in `find simple` operator.

**Comment by SylveonBottle** [comment]
https://i.imgur.com/kjMc4cc.png
https://i.imgur.com/XHE2oWY.png

**Comment by roboderpy** [comment]
old as dinosaurs PAC3 version on screenshots
