### ISSUE TITLE
Pac clipping annoyance

### ISSUE THREAD

**Issue by OneEaredNeko** [CapsAdmin/pac3#334]
At the moment "pos + normal" is adding an annoying offset to clips 

```
local pos, ang = LocalToWorld(self.Position, self:CalcAngles(self.Angles), self:GetBonePosition())
local normal = ang:Forward()

render_PushCustomClipPlane(normal, normal:Dot(pos + normal))
```

the annoying offset can be fixed with

`render_PushCustomClipPlane(normal, normal:Dot(pos + (normal*0.0001)))`

**Comment by LUModder** [comment]
why not pull request it?

**Comment by CapsAdmin** [comment]
this is unfortunate but i think it's too late to change now
