### ISSUE TITLE
Request: Animation Part Randomization

### ISSUE THREAD

**Issue by zxz41** [CapsAdmin/pac3#336]
Just like how you can do
`http://example.com/pac3/sound/1.ogg;http://example.com/sound/pac3/2.ogg`

And it'll choose a random sound each time. It would be nice to be able to do
`http://example.com/pac3/animation/1.txt;http://example.com/animation/pac3/2.txt`

**Comment by LUModder** [comment]
Should be in the base part code but some things probably wouldn't benefit
