### ISSUE TITLE
Pac3 won't load anything from url

### ISSUE THREAD

**Issue by snesboxyoshi** [CapsAdmin/pac3#337]
the title says it pretty much all. i've tried loading stuff like models, .obj files and text files but nothing will load. can anyone help me? i'll leave a video as reference and the .txt file too that i used for reference.

https://www.youtube.com/watch?v=91fIh0Drqj4
http://puu.sh/kbBY7/380acf7754.txt

**Comment by snesboxyoshi** [comment]
(also sorry for my horrible english.)

**Comment by LUModder** [comment]
Can't help without errors from console.
