### ISSUE TITLE
Change PAC icon

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#338]
It'd be better to have simplistic cube than ugly pink thing, no offence

**Comment by homonovus** [comment]
ur dum lol

**Comment by zxz41** [comment]
I have to agree the pink image looks like something mashed together in paint under 5 minutes :v

Would be better with something like "The cube" remade with the [Silk style](http://www.famfamfam.com/lab/icons/silk/) in mind. ![](http://www.famfamfam.com/lab/icons/silk/icons/user.png)![](http://www.famfamfam.com/lab/icons/silk/icons/folder_magnify.png)

**Comment by LUModder** [comment]
Either way, silk style or the vector cube, anything is better than that abomination

**Comment by Kaosheaven** [comment]
I agree that the pink abomination does need changing to what idk but please
