### ISSUE TITLE
Tilted Player and Revive Option

### ISSUE THREAD

**Issue by Mrsexyness** [CapsAdmin/pac3#349]
This happens everyone once in awhile, a player will be tilted back and say revive o nthem, yet they can buy weapons and walk around normally.

Image is below:
http://images.akamai.steamusercontent.com/ugc/105104444281605007/07FCDF7E8D69B1B411E82280DCE48764478BDEF4/

**Comment by LUModder** [comment]
Seems more like conflicting or the gamemode's fault.

**Comment by Mrsexyness** [comment]
Im sorry delete this, I had two Github tabs open and posted it in the wrong one. ment to post it in the gamemodes Guthub.
