### ISSUE TITLE
Player entities can no longer have alpha, material or visibility set after game update.

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#350]
After the December 19th update of Gmod, player entities can no longer have their material, alpha or visibility set at all.
These were in the changelog:
"Added ITexture.__tostring"
"IMaterial.__tostring now acts more similarly to other __tostring metamethods in the game"

**Comment by LUModder** [comment]
Can replicate, no errors given at all.

**Comment by LUModder** [comment]
Yet if you exit out of the editor, it applies.

**Comment by nerdkoopa** [comment]
Hold on, I gotta check that too.

**Comment by nerdkoopa** [comment]
Nope, doesn't work in singleplayer. Player entity still fully visible.

**Comment by LUModder** [comment]
Like I said, color only

**Comment by nerdkoopa** [comment]
Ok, just noticed that. Fixing the description

**Comment by AwkwardFerret** [comment]
Damn, I hope PAC3 gets an update quick...

**Comment by LUModder** [comment]
Considering I can't find any reasonable traces to this, who knows what did it.

**Comment by Reginald-Halifrax** [comment]
Same here, closest i can get to getting it to work is using ULX Cloak since it doesn't affect Pac models
Hope this can get figured out for the some of us that use Bone merge for our models

**Comment by CapsAdmin** [comment]
seems like it's an issue with .RenderOverride not doing anything on players

**Comment by Reginald-Halifrax** [comment]
Any possible work arounds?

**Comment by LUModder** [comment]
There are workarounds but they're just generally bad things to use

**Comment by LUModder** [comment]
One workaround I tried still had alpha and invert broken, but also did weird things to positioning if you messed with it.

![](https://owo.whats-th.is/0e3a41.png)

**Comment by PhoNoTheSky** [comment]
please fix this

**Comment by CapsAdmin** [comment]
I committed a workaround and there's an official fix coming to gmod soon.

**Comment by AwkwardFerret** [comment]
Fix kinda worked, but now making an entity will hide your weapon, and I can't make it visible. Plus, bonemerged models become invisible...

Maybe it's just my game, but I have disabled all my addons...
