### ISSUE TITLE
PAC3 update fixed hide entity issue, but created new ones

### ISSUE THREAD

**Issue by AwkwardFerret** [CapsAdmin/pac3#352]
Hide entity works (thank god), but it has created some new issues with entities. Created an entity will render my weapons invisible. Bone merged models also are invisible.

Hopefully this issue exists only for me, but I really don't know...

**Comment by AwkwardFerret** [comment]
Joined 2 different servers, the problem persists.

**Comment by AwkwardFerret** [comment]
CLOSING THE POST, restarting gmod solved everything!

**Comment by Reginald-Halifrax** [comment]
I always found it was rule of thumb to restart gmod after addon updates due to how unstable gmod  even is

**Comment by CapsAdmin** [comment]
I think gmod fixed the issue so I should remove my old fix as it might cause outfits to draw twice.

**Comment by Reginald-Halifrax** [comment]
I have seen no such issue yet
