### ISSUE TITLE
Beam Problems.

### ISSUE THREAD

**Issue by ThunderNutss** [CapsAdmin/pac3#364]
So i've been trying to recreate https://www.youtube.com/watch?v=AgLAx5to48w like I've done quite a few times before. However, when I try to use the beams they absolutely will not go to the other model. It will only go back to the bone for some reason. I have been able to recreate this look many times before but for some reason it's no longer working. Wat do.

http://images.akamai.steamusercontent.com/ugc/96100468923707296/0C56EDA8ADDCDF9A444C297ABB09EAA06ADA46BD/

(For Reference.)

**Comment by CapsAdmin** [comment]
this works fine here
