### ISSUE TITLE
Problem with Pacoutfit

### ISSUE THREAD

**Issue by WMODEL** [CapsAdmin/pac3#369]
I've noticed that Players are not able to have more than 1 pacoutfit applied.

Could someone help me out with this issue? Is the problem caused by my pacoutfit lua?

ITEM.name = "Iron Class 1st Class"
ITEM.desc = ""
ITEM.model = "models/ironcross.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.outfitCategory = "medal1"
ITEM.pacData = {
    [1] = {
        ["children"] = {
            [1] = {
                ["children"] = {
                },
                ["self"] = {
                    ["Angles"] = Angle(0.051, -28.203, -90.7),
                    ["Position"] = Vector(1.374, 5.519, 0.03),
                    ["UniqueID"] = "4249811628",
                    ["Size"] = 1,
                    ["Bone"] = "spine 4",
                    ["Model"] = "models/ironcross.mdl",
                    ["ClassName"] = "model",
                },
            },
        },
        ["self"] = {
            ["ClassName"] = "group",
            ["UniqueID"] = "907159817",
            ["EditorExpand"] = true,
        },
    },
}
ITEM.newSkin = 1

ITEM.name = "Iron Class 2nd Class"
ITEM.desc = ""
ITEM.model = "models/ironcross.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.outfitCategory = "medal2"
ITEM.pacData = {
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["Angles"] = Angle(2.6, -19.375, -68.959),
					["Position"] = Vector(4.532, 6.907, 4.279),
					["UniqueID"] = "4249811628",
					["Size"] = 1,
					["Bone"] = "spine 2",
					["Model"] = "models/ironcross.mdl",
					["ClassName"] = "model",
				},
			},
		},
		["self"] = {
			["ClassName"] = "group",
			["UniqueID"] = "907159817",
			["EditorExpand"] = true,
		},
	},
}
ITEM.newSkin = 1

**Comment by Datamats** [comment]
This is a NutScript issue and is unrelated to the PAC core afaik

**Comment by WMODEL** [comment]
Sorry. But I'm not sure where I am supposed to post this elsewhere. Could you help me out?

**Comment by Datamats** [comment]
https://nutscript.rocks/
https://github.com/Chessnut/NutScript/issues

Using google should not be that hard.

**Comment by FarukGamer** [comment]
This is caused by identical class names, look at the code and you see 2 times this.

["ClassName"]="group"

Groups are like folders on you computer that contains the main objects, give them a unique name and it's should work. But make sure that you don't change other ClassNames accidentally.

**Comment by WMODEL** [comment]
Thank you so much for answering! Btw. Could you explain me what ITEM.newSkin does?

**Comment by WMODEL** [comment]
I tried
["ClassName"]="group1"
["UniqueID"]="907159817"

and 
["ClassName"]="group2"
["UniqueID"]="907159817".

They won't even appear now and I get this in console

tried to create unknown function: 0x46fafb70 "group1"!
pac3 tried to create unknown part group1
tried to create unknown function: 0x46fafb70 "group1"!
pac3 tried to create unknown part group1

**Comment by FarukGamer** [comment]
Wait wait, I made a mistake 😕
Please redo the changes and change only the UniqieID

**Comment by WMODEL** [comment]
It worked! Thank you so much! Btw, I have one more issue. When equipping multiple pacoutfits, unequipping one pacoutift also unequippes other pacoutfits.

ITEM.name = "Bayonet"
ITEM.desc = ""
ITEM.model = "models/weapons/syndod/w_k98bayonet.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.outfitCategory = "medal5"
ITEM.pacData = {
	[1] = {
		["children"] = {
			[1] = {
				["children"] = {
				},
				["self"] = {
					["Angles"] = Angle(79.884, 101.621, 4.57),
					["Position"] = Vector(-0.137, 5.953, -6.66),
					["UniqueID"] = "4249811628",
					["Size"] = 0.75,
					["Bone"] = "spine 1",
					["Model"] = "models/weapons/syndod/w_k98bayonet.mdl",
					["ClassName"] = "model",
				},
			},
		},
		["self"] = {
			["ClassName"] = "group",
			["UniqueID"] = "907159817",
			["EditorExpand"] = true,
		},
	},
}
ITEM.newSkin = 1

This is example of my pacoutfit lua. Is there someway to prevent this from happening?

**Comment by FarukGamer** [comment]
The same issue like before, change the uniqueID.

**Comment by WMODEL** [comment]
Replacing this UniqueID didn't help.  
["ClassName"] = "group",
["UniqueID"] = "907159817",
["EditorExpand"] = true,

I'll try replacing this UniqueID
["Position"] = Vector(-0.137, 5.953, -6.66),
["UniqueID"] = "4249811628",
["Size"] = 0.75,
