### ISSUE TITLE
Bodygroups does not affect Entity part

### ISSUE THREAD

**Issue by FarukGamer** [CapsAdmin/pac3#374]
I've noticed that the bodygroups does not change correctly, 
I was making pets that should flap with their wings wihle idling and walking.

As i know this issue was already fixed a while ago (https://github.com/CapsAdmin/pac3/commit/d6158e7c544111c71abcfeb1733f789ae3c63d0e & https://github.com/CapsAdmin/pac3/commit/154204287f85cd2e3aab40af492f52535f4041b2)

I ready tried it with normal playermodels and non-standard ValveBiped playermodels.

**Steps to reproduce**

1. Select a playermodel or make a model in pac
2. Create an BodyGroup element
3. Select BodyGroup name
4. Change the model index value

**Comment by DatAmazingCheese** [comment]
It seems it works sometimes and doesn't other times in my experience.

Enabling depreciated features and changing bodygroups on the model directly seems to work.

**Comment by AMIDIBOSS** [comment]
Could you explain a little more?
How "Directly to the model"?

**Comment by roboderpy** [comment]
They change ![4fe49c08ca_hl2_2017-08-27_15-36-57](https://user-images.githubusercontent.com/6339511/29748285-b6f8577e-8b3d-11e7-81b0-8faac41ea67d.png)

**Comment by roboderpy** [comment]
If someone got a PAC that has broken bodygroups, please send it here.

**Comment by AMIDIBOSS** [comment]
I have one!

**Comment by roboderpy** [comment]
Attach as zip file by dragging and dropping into message box

**Comment by AMIDIBOSS** [comment]
I got it from steam workshop!

**Comment by AMIDIBOSS** [comment]
[pac3_104691717.zip](https://github.com/CapsAdmin/pac3/files/1254425/pac3_104691717.zip)

**Comment by AMIDIBOSS** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=104691717

**Comment by Techbot121** [comment]
he meant the pac costume (.txt), not pac itself

**Comment by AMIDIBOSS** [comment]
ah, ok

**Comment by ReverendV92** [comment]
I'm getting the same issue. I have three body groups set on the TF2 soldier, and I can only change up to one or two. If I change the rocket body group, it affects the helmet and grenade body groups.

**Comment by roboderpy** [comment]
no?
![9beb653c03_explorer_-2017-09-07_19-19-24](https://user-images.githubusercontent.com/6339511/30163024-7c6ab918-9401-11e7-8003-d34004f8a90e.png)

**Comment by roboderpy** [comment]
I refactored bodygroups code, try develop branch

**Comment by AMIDIBOSS** [comment]
Ok, the gmod versions are playing here...

**Comment by ReverendV92** [comment]
I'm using the workshop version. Let me try the GitHub version.

**Comment by ReverendV92** [comment]
![2017-09-07 13_38_43-garry s mod](https://user-images.githubusercontent.com/5511029/30179443-0a5347e8-93d2-11e7-937f-82943c30ca96.jpg)
On the develop version from GitHub, it doesn't appear to work at all when changing body groups.

**Comment by roboderpy** [comment]
HahAAAAAAAAAAAAAAAAAAAA

**Comment by AMIDIBOSS** [comment]
and What?

**Comment by roboderpy** [comment]
https://github.com/CapsAdmin/pac3/commit/5c6ace6f2bef344168329c496a61999507663c55
