### ISSUE TITLE
Models attached via editor "jumping" on player move.

### ISSUE THREAD

**Issue by plsbx** [CapsAdmin/pac3#377]
Hello,

Models attached to player via pac_editor "jumping" while player is in move. 

Staying + moving camera = Okey
Jump = Not
Moving forward/etc = Not

I used newest PAC on server.
It is possible to get smooth attachments move?

**Comment by roboderpy** [comment]
Prediction errors. Bone render origin are not the same as reported positions and network origins. Nothing can be done on PAC's side. This is a known bug, and i know why this happens, but this is not fixable.
