### ISSUE TITLE
PAC3 - Broken Effects

### ISSUE THREAD

**Issue by TricycleRaptor** [CapsAdmin/pac3#378]
Hello,

Recently started running into an issue where effects will work properly when not worn, but will stop working once applied. I have done several clean installs of PAC from both the Workshop and from the SVN and have found no other insights regarding this issue. I have not installed any new addons that may conflict with PAC3.

Thanks.

**Comment by roboderpy** [comment]
https://github.com/CapsAdmin/pac3/commit/38b5f7bb7114ceeda2a2d9e54b9d33363fe869cc
