### ISSUE TITLE
Input Lag after hovering over Save/Load menus

### ISSUE THREAD

**Issue by sauermon** [CapsAdmin/pac3#380]
I recently upgraded my server to the most recent PAC version, since I hadn't been bothered to upgrade for a long time, and I've noticed that, repeatedly, if I hover over the save/load tabs in the editor to load something, I get the loading lag as expected, but after that for about 10 minutes I get an odd input lag to the server. I can receive packets and messages just fine, however anything I type doesn't go through, binds don't work, but general movement does. Once the lag finally subsides, All is well until I hover over the save/load menus again, where the cycle starts again. I don't know if this is a bug with pac or some clientside issue, as it seems to randomly affect some clients but not others.

**Comment by CapsAdmin** [comment]
Next time this happens can you run 
```lua
local count = 0
local indent = 0

local out = ""

local function dump(pnl)
	out = out .. tostring(pnl) .. "[" .. (pnl:IsVisible() and "vis" or "novis") .. "]" .. "\n"
	count = count + 1
	indent = indent + 1
	for k, v in pairs(pnl:GetChildren()) do
		out = out .. ("\t"):rep(indent)
		dump(v)
	end
	indent = indent - 1
end

dump(vgui.GetWorldPanel())

out = "total panels: " .. count .. "\n" .. out

file.Write("vgui_dump.txt", out)
```

and put the contents of data/vgui_dump.txt on https://gist.github.com/ ?

I have a feeling it could be related to gui panels not being removed.

**Comment by sauermon** [comment]
I ran the code and dumped the output. As an aside, I had PAC and GCompute open when the code was ran. 

https://gist.github.com/sauermon/4a1495e62297a92398282f528d615812

**Comment by roboderpy** [comment]
Was already fixed
