### ISSUE TITLE
Performance issues with sounds.

### ISSUE THREAD

**Issue by Techbot121** [CapsAdmin/pac3#381]
when a sound fails to load it seems to lower the fps significantly for some reason. 
maybe awesomium issue?

also I use the [x,x] selector thing if that matters

**Comment by Techbot121** [comment]
by significantly I mean from 20-30 fps to 110

**Comment by Techbot121** [comment]
Ok the issue seems to be only related for the webaudio part. 
It works fine with the ogg part which I'm using now instead.

**Comment by roboderpy** [comment]
http://wiki.garrysmod.com/page/sound/PlayURL

`noblock` - Disables streaming in blocks. It is more **resource-intensive,** but it is required for IGModAudioChannel:SetTime
