### ISSUE TITLE
Projectiles always firing from my head in my own game.

### ISSUE THREAD

**Issue by AwkwardFerret** [CapsAdmin/pac3#383]
So I made a pac3 that fires projectiles at my hitpos bone. It worked fine in a server, yet whenever I test them in my own game, The projectiles will always fire from my head, which is quite an annoyance. Is there some command other than pac_sv_projectiles that I should know of?

**Comment by AwkwardFerret** [comment]
I FIXED IT (kinda)

THIS ISSUE CAN BE SOLVED BY GETTING FALCO'S PROP PROTECTION

**Comment by ToastyEngineer** [comment]
This solution seems very wrong tbh lmao. But if you say so

**Comment by OrbitalParallax** [comment]
is there a good solution tho?

**Comment by AwkwardFerret** [comment]
This is the only workaround I found. I'm not any good in coding, but I'm thinking that prop protection corrects the origin point of it's parents so it fires from there.
