### ISSUE TITLE
Not able to move Spawned Models when editing anything other than my playermodel.

### ISSUE THREAD

**Issue by TurretVista** [CapsAdmin/pac3#385]
When trying to move around a model or entity connected to a prop, ragdoll, model, or anything else other than my playermodel, I can't move it or edit it at all. The arrows used for moving it around are literally all over the place, like a bullet that bounces off walls. They are extremely stretched out, and are all moving away from the model and seek to not even have an end, meaning I can't even try to use them. I've messed around with all of the settings, and used other models, the models that Garry's Mod comes with. Nothing happens, and it's a shame that this is happening to me, it's the main feature PAC3 has that I use. Please help.

**Comment by DatAmazingCheese** [comment]
Here are some simple fixes.

1) Is your group or parent model hidden?

2) Is PlayX present on the server, if so was it enabled when you experienced the issue.

**Comment by roboderpy** [comment]
They move
![aa23b52670_hl2_2017-08-28_10-32-06](https://user-images.githubusercontent.com/6339511/29758254-29c70356-8bdc-11e7-9111-b859dadb8177.png)
