### ISSUE TITLE
Pac3 Audio Error

### ISSUE THREAD

**Issue by LOLOLOLOLLOLOLOLOLOL** [CapsAdmin/pac3#393]
I Load In A Server Or Single Player And I Get A Error With My Dropbox Link and (3d noplay noblock)
at the end of it. What to do to solve dis?

**Comment by ToastyEngineer** [comment]
Just a simple question, is it a public dropbox link?
Probably dead then.

**Comment by LOLOLOLOLLOLOLOLOLOL** [comment]
its not a public Link

**Comment by Datamats** [comment]
Make sure that the Dropbox link is availible from when you are not logged into Dropbox and it downloads instantly
