### ISSUE TITLE
Issue with PAC events

### ISSUE THREAD

**Issue by MrFrostt** [CapsAdmin/pac3#394]
Hello everyone, currently I've stomped into issue with PAC, it can't be conflicting with anything since I tested it without any other addons. So thing is, when ever I create event and make it Invent, it still remains active all time no matter what... any ideas how to fix it?

P.S I've used GitHub and Workshop version, in both of them is the same result. The issue accured or 29.02,2017 if I'm not wrong.

**Comment by Earu** [comment]
Did it happen once or mutiple time, and was it during all games you did or just one game?

**Comment by MrFrostt** [comment]
It's happening on 2 tested gamemodes so far, DarkRp, Sandbox

**Comment by Earu** [comment]
Some addons / script of yours must be conflicting

**Comment by ToastyEngineer** [comment]
They did say they tried it without addons.
Probably talking about the lua folder then.

**Comment by MrFrostt** [comment]
Well in general I tested on single player/multi player without addons, like clean server and it still activates itself.

**Comment by Earu** [comment]
Can you send a screenshot and/or the list of things you have in your garrysmod/lua folder

**Comment by MrFrostt** [comment]
Here it is. 
![explorer_2017-04-03_16-19-57](https://cloud.githubusercontent.com/assets/10675694/24610916/11a44bd8-1889-11e7-85a6-92230df65059.png)

**Comment by Earu** [comment]
mmh possibly a .dll then, did you ever download stuff outside the workshop for garrysmod?

**Comment by MrFrostt** [comment]
Only things like ULX from github and some addons from the scriptfodder

**Comment by Earu** [comment]
When you tested without addons, do you mean without addons from the workshop only or litterally anything

**Comment by MrFrostt** [comment]
Without anny addon installed from workshop, but maybe I shall try to get rid of version from workshop and test the GitHub one?

**Comment by Earu** [comment]
Try removing everything from your addon folder besides the pac3 version from GitHub

**Comment by MrFrostt** [comment]
Alright, could you maybe add me on steam for faster communication? http://steamcommunity.com/profiles/76561198035402320/

**Comment by Earu** [comment]
Im not able to go on steam at the moment, I could help from discord though

**Comment by MrFrostt** [comment]
Alright that's good too, what chanel to join?

**Comment by Earu** [comment]
https://discord.gg/AJhCT <- PAC3 server discord

**Comment by ToastyEngineer** [comment]
I do believe it might be pacs fault. I remember something like this and which script would mess around with timers?

**Comment by MrFrostt** [comment]
Please check #Issues on the Discordapp, I sent 2 videos there showing what's going on.

**Comment by CapsAdmin** [comment]
Not sure why you're talking about conflicting addons. What event is it?
