### ISSUE TITLE
Checking "Reset on hide" on an animation entity doesn't actually do anything v2

### ISSUE THREAD

**Issue by MystiaLorelei** [CapsAdmin/pac3#396]
https://github.com/CapsAdmin/pac3/issues/281

Just want to bring attention to this feature request (possibly bugfix? I'm not sure what the intended behavior for Hide on Reset is supposed to be even.) again after all those issues got closed.

Would help some PACs I have. Currently I do really ugly hacks involving exact timing on events and set animation lengths to hide the lack of a working reset. And rate 0, specific frame 'animations' that are partially hidden by animation blending or otherwise non-obvious.

**Comment by Cordon** [comment]
Was going to reopen the issue but forgot.
Tried the timeex() hack that was suggested last time but it didn't seem to work for me, even though I did everything right.

**Comment by roboderpy** [comment]
GMod limitations...
