### ISSUE TITLE
Webaudio too quiet/OGGs never load

### ISSUE THREAD

**Issue by Cordon** [CapsAdmin/pac3#397]
I tried amplifying the volume in Audacity, but that just took a shit on the quality, the volume was the same in-game.
OGGs never seem to load, I am using the same method as I do for webaudio which always works, with public links through Google Drive.

**Comment by Earu** [comment]
You did convert your audio file to .ogg or .wav right?

**Comment by Cordon** [comment]
Of course.

**Comment by roboderpy** [comment]
WebAudio uses native `sound.PlayURL` call, while OGG use hidden web panel. Also, because of Chromium security limitations, it is impossible to load OGGs from domains without `access-control-allow-origin: *` in headers
