### ISSUE TITLE
PAC outfits disappear in water

### ISSUE THREAD

**Issue by Rapolis** [CapsAdmin/pac3#399]
This is the weirdest bug that has been persisting on PAC3 for a long time.
Here's proof:
https://gyazo.com/171d5a827b4afe2ebfc7541a8d50e967
PAC outfit invisible underwater while you are out of water, PAC outfit is invisible while out of water and you are underwater, PAC outfit visible while it is underwater and you are underwater.
This is a bug that has to be fixed.

**Comment by ToastyEngineer** [comment]
Not a bug.
pac_suppress_frames 0

**Comment by Techbot121** [comment]
Like Toasty said it's intentional since it would have to draw your PAC twice and would impact your Framerate. 

you can enable/disable it using the `pac_suppress_frames` console command 

or in the editor like this:
![](http://techbot.xyz/ShareX/screenshots/2017/04/17/hl2_18-35-34.png)

**Comment by Rapolis** [comment]
Thanks. Really helps to fix unrealistic glitches.
