### ISSUE TITLE
pac models are darker and weird on my screen only

### ISSUE THREAD

**Issue by CmBxKing** [CapsAdmin/pac3#40]
For some reason on my screen all props on pac are much darker than they are on everyone elses. Problems that arise from this include: Im not able to see what my pac actualy looks like and can sometimes butcher color shading and it will look good on my screen but terrible on other, everyone elses pac look wierd and i cant see how good they actualy look, In one case there was somebody with a pac that had a large orb surrounding them that was pitch black but on everyone else's screens he look like the sun and i didnt know that so i punished him on a server im admin on bcuz i thought his pac was just a mingey blinding pac but was punished by higher admin because i had just punished somebody who didnt actualy do anything wrong (on everyone elses screens atleast)

P.S. yes my brightness is all the way up and i have the video options on gmod to the best possible but still my pac brightness is messed up

please tell me what to do to fix

**Comment by CapsAdmin** [comment]
this sounds to me like a directx issue
