### ISSUE TITLE
Other can't see my pac3 only who have that addons can see my pac

### ISSUE THREAD

**Issue by BallTh** [CapsAdmin/pac3#400]
yep like in titles other can't see my pac only who have that addon or model can see my pac :/
help?

**Comment by BallTh** [comment]
help plz?

**Comment by Datamats** [comment]
Either use models that already people do have or upload them online. Please join the PAC3 Discord if you need any more help https://discord.gg/p4uf9

**Comment by BallTh** [comment]
but does it have anyways to make who that not have model saw me?

**Comment by Earu** [comment]
If you're using content other players don't have mounted / installed it will not work, you should use .obj models instead. People will see as error models the content you used and that they don't have.

**Comment by BallTh** [comment]
oh ok thanks
