### ISSUE TITLE
2 bugs (Models going to the center, bone selection causing black screen when moving)

### ISSUE THREAD

**Issue by Rapolis** [CapsAdmin/pac3#404]
This has been bugging me a lot, I tried fixing this somehow but it didn't work. I am building my own car and when I hid the bone of the steering wheel (by setting the size to 0.1) and putting a custom model of steering wheel on top, I try to go farther away from it and it goes under the car right in the center of the group.
Here is the gif:
https://gyazo.com/2bba06b4e9def7b5bdf8873b031abdc4
Notice the steering wheel going under the vehicle.
Other people confirmed to see this same thing on me. They sent me screenshots of it.
Is it some sort of a bug? Or is it a glitch with bones?

Bone glitches I found:
When selecting a specific bone and moving, you move super far away into the void.
Possible fix for this: reset your view position and unselect the bone.
Here is the gif:
https://gyazo.com/57ff9e437652a6eafb18d108ebbf8ee9

I hope you understand what I mean, because I am not English.

**Comment by Rapolis** [comment]
Bump.

**Comment by roboderpy** [comment]
Check develop branch for these issues

**Comment by CapsAdmin** [comment]
I think if you set lod to 0 it would work (default is -1)
