### ISSUE TITLE
Decoding "pacnamehere" failed: luadata_decode:1: unexpected symbol near '<eof>'

### ISSUE THREAD

**Issue by fluffyzeal** [CapsAdmin/pac3#407]
So, long story short, I transferred all my pacs from another laptop to this one, back in mid December, they all work fine. But any pac I've created in 2017 is suddenly having this problem. Tried using a friends pac via drop box and that didn't work either. I have the most recent version of the steam workshop version of pac.
Thanks.

**Comment by roboderpy** [comment]
Means PAC file is corrupted
