### ISSUE TITLE
Crashing from adding any part type to the default model.

### ISSUE THREAD

**Issue by Count-Of-Pac** [CapsAdmin/pac3#409]
After extensive trial and error, I discovered I'm unable to add any parts under a default model. I crash to desktop instantly every time. I've cleared my addons and verified my game files just in case it was an addon confliction and it is still happening. Side note: this didn't start happening to me until about a week ago.

On top of this issue, I'm also experiencing the part limit bug others have reported. These two errors combined have made making pacs almost impossible for me. Any help would be greatly appreciated.

**Comment by CapsAdmin** [comment]
still? reopen if yes

**Comment by Sounalius** [comment]
I can confirm this is ongoing. I'm literally unable to use pac as a result of this for the majority of my creations.

**Comment by Sounalius** [comment]
One thing I've noticed is that prior creations to updates, such as the Steam release of July 26th, are able to function properly in terms of adding things to models whatsoever. Everything I've attempted to build afterwards experiences this issue.
