### ISSUE TITLE
cant see anyone elses pac

### ISSUE THREAD

**Issue by killerfish9999** [CapsAdmin/pac3#412]
I can use my pac everyone can see my pac but I cant see anyone elses

**Comment by BallTh** [comment]
Go to setting at Utilities (I think) then go find pac3 then set the range or maybe something like that then set whatever u want for me I set it to max so I can see everyone Pac

**Comment by KabusIblis** [comment]
pac_enabled 1
pac_draw_distance 2000
pac_restart
problem solved

**Comment by roboderpy** [comment]
No replies from issue creator, closing this.
