### ISSUE TITLE
Projectiles always firing from my head 

### ISSUE THREAD

**Issue by OrbitalParallax** [CapsAdmin/pac3#416]
any fix?

**Comment by BallTh** [comment]
I don't know cause this also happen to me :3

**Comment by dan11fly** [comment]
Change the bone the projectile is shooting from

**Comment by OrbitalParallax** [comment]
woooww i would have never thought of that GENIUS!! i swear to god if your
not joking

**Comment by dan11fly** [comment]
Did that fix your problem?

**Comment by OrbitalParallax** [comment]
no i had it set the right hand and it was shooting out my head. it rarely
happens tho. any way that was a while ago and its gone now
