### ISSUE TITLE
Model goes into line

### ISSUE THREAD

**Issue by BallTh** [CapsAdmin/pac3#418]
At the title said some part of my model in line and a part that turn into line also get cut

**Comment by ToastyEngineer** [comment]
What even

**Comment by Datamats** [comment]
Can you try to be a bit more descriptive and embed a screenshot of the problem?

You can also join the pac3 discord and ask for help there https://discord.gg/utpR3gJ

**Comment by BoxOfFlex** [comment]
bad shameless advertising smh

**Comment by Earu** [comment]
this is the official pac discord, i don't see how thats advertising, its like extra for the original product

**Comment by BallTh** [comment]
ok i idon't know wat did u guy say bad shameless advertising i didn't advertising

**Comment by ToastyEngineer** [comment]
That wasn't directed at you.

**Comment by BallTh** [comment]
Oh ok but sorry for my english :3

**Comment by BallTh** [comment]
![untitled](https://user-images.githubusercontent.com/24986230/27132411-09c4a96a-5139-11e7-9e50-a354438121e2.png)
![untitled2](https://user-images.githubusercontent.com/24986230/27132455-2ce6458e-5139-11e7-8fa1-02158acef94d.png)

**Comment by BallTh** [comment]
at da pics for the second one it should have same at the right and at the top right it also get cut ._.

**Comment by BallTh** [comment]
Any help .-.

**Comment by Avernakis8** [comment]
cut it up further or reduce poly count

**Comment by BallTh** [comment]
and how do i reduce poly count? ._.

**Comment by KabusIblis** [comment]
https://blender.stackexchange.com/questions/5320/cutting-a-mesh-in-half

**Comment by BallTh** [comment]
Thanks I can find a way now thanks for you guys time :3 have good year
