### ISSUE TITLE
All hitpos bones are unusable.

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#424]
Every bone that traces hit position is unusable when trying to make new outfits. They are still functional in old outfits for some reason. These bones do not appear as choices, and trying to put the bone name in manually just results in invalidbone.

**Comment by roboderpy** [comment]
If they are not accesable using `ManipulateBoneX` then yes, they will never be valid

**Comment by nerdkoopa** [comment]
But they USED to work just fine. That's the problem!

**Comment by roboderpy** [comment]
Fixed in Develop
