### ISSUE TITLE
Make a new male base UV map

### ISSUE THREAD

**Issue by CapsAdmin** [CapsAdmin/pac3#426]
03:13 - Jenrey™: caps
21 June 2017
23:00 - Jenrey™: caps
23:00 - Jenrey™: make a new male base bump map
22:14 - Jenrey™ is now Away.
22:50 - Your state is set to Offline.
22:50 - Jenrey™ is now Offline.
22:50 - Lost connection to Steam, will rejoin chat automatically when connection regained.
22:50 - Connected again and rejoined chat.
22 June 2017
00:07 - Jenrey™ is now Offline.
04:33 - Your state is set to Offline.
04:33 - Lost connection to Steam, will rejoin chat automatically when connection regained.
04:33 - Connected again and rejoined chat.
07:44 - Jenrey™ is now Online.
09:44 - Jenrey™: Caps
09:44 - Jenrey™: Make a new male base UV map
07:45 - Jenrey™ is now Away.

**Comment by CapsAdmin** [comment]
why?

**Comment by KabusIblis** [comment]
male and female base shares the same uv

**Comment by Jenrey** [comment]
its just mirroring on the other side of the model and its annoying for some pacs

**Comment by CapsAdmin** [comment]
use new model parts
