### ISSUE TITLE
can you add support for 2k images in pac3

### ISSUE THREAD

**Issue by CapsAdmin** [CapsAdmin/pac3#428]
00:17 - Daniel: can you add support for 2k images in pac3
00:17 - Daniel: please

**Comment by roboderpy** [comment]
why

**Comment by CapsAdmin** [comment]
images are forced to be 1024x1024 and anything beyond that seems to have issues loading

**Comment by roboderpy** [comment]
Creating 1024x1024 HTML panels for texture grabbing is already a problem

**Comment by dan11fly** [comment]
14:00 - VSonyPower: Basically
14:00 - VSonyPower: you cannot create a HTML model box bigger than 1024x1024
14:00 - VSonyPower: but u can create a HTML background he didnt notice.
14:00 - VSonyPower: HTML background limitations are 10000x10000\

**Comment by roboderpy** [comment]
i was able to create 4Kx4K HTML panels without problem

**Comment by dan11fly** [comment]
14:04 - VSonyPower: having images outside the 4:3 ratio is a issue
14:04 - VSonyPower: i see whats going on
14:06 - VSonyPower: if hes using HTML
14:06 - VSonyPower: roboderpy inserted his image from a page wich allows him to modify the HTML code
14:06 - VSonyPower: its basically like the steam thing
14:06 - VSonyPower: to change limits
14:06 - VSonyPower: of the artwork size

**Comment by dan11fly** [comment]
For example if you paste this in chrome console before uploading artwork on your steam profile, the picture will be bigger
document.getElementsByName("image_width")[0].value = 1000;document.getElementsByName("image_height")[0].value = 1;

**Comment by dan11fly** [comment]
that's the steam thing he was walking about

**Comment by roboderpy** [comment]
whut

**Comment by dan11fly** [comment]
Hold on he's going to sign in and explain

**Comment by roboderpy** [comment]
https://github.com/CapsAdmin/pac3/blob/82475b754ae784637a271afa118c03509b9a1193/lua/pac3/core/client/libraries/urltex.lua#L76 instead of size put 4096

**Comment by dan11fly** [comment]
I've sent VSonyPower the lua file

**Comment by dan11fly** [comment]
He said he will add 4k support and support for .mdl model files too

**Comment by dan11fly** [comment]
14:28 - VSonyPower: it will upload from your computer the model
14:28 - VSonyPower: to show it to everyone
14:28 - VSonyPower: that would require me to modify the main file
14:28 - VSonyPower: that controls the whole addon

**Comment by VSonyPower** [comment]
That will take some days of testing / coding tho Daniel.

**Comment by Techbot121** [comment]
![a](http://techbot.xyz/ShareX/screenshots/2017/06/22/432t42t.gif)

**Comment by dan11fly** [comment]
Lol what's that pic is all about?

**Comment by dan11fly** [comment]
Edited Lua file #1 
Test image: 3840x2160
Result: https://s12.postimg.org/tk3jv24st/test1.png

**Comment by VSonyPower** [comment]
We've tried replacing the size, there are all the results.

**Comment by CapsAdmin** [comment]
you need to change this https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/libraries/urltex.lua#L3 

you can just do `lua_run_cl pac.urltex.TextureSize = 4096` before you load any textures

**Comment by CapsAdmin** [comment]
you can now use vtf and whatnot in the new parts
