### ISSUE TITLE
I have an old PAC which, when applied, crashes everyone with PAC enabled in the server

### ISSUE THREAD

**Issue by brandonsturgeon** [CapsAdmin/pac3#429]
I don't really know where to post this, but it seems like some kind of flaw that should be reported.

Do you want me to post the PAC? Send it privately?

**Comment by BallTh** [comment]
maybe i will look why does it crash
P.S. i won't steal you pac :)

**Comment by KabusIblis** [comment]
Best bet to get this fixed is to PM @CapsAdmin via Discord, don't post the outfit here

**Comment by brandonsturgeon** [comment]
Thanks @KabusIblis .  I wouldn't have posted the PAC here :p 

Does Caps have a discord server?

**Comment by Techbot121** [comment]
yep over here discord.gg/utpR3gJ

**Comment by KabusIblis** [comment]
updated the readme specifically for this 👌

**Comment by roboderpy** [comment]
Found the case - your pac textures on Mars are way too large. Will try to fix crash caused by very large url textures.

**Comment by roboderpy** [comment]
https://github.com/Facepunch/garrysmod-issues/issues/3276
