### ISSUE TITLE
Manipulate parts in other parent groups

### ISSUE THREAD

**Issue by Cordon** [CapsAdmin/pac3#443]
e.g. I want to lower my move speed when my health is below a certain threshold or I want to disable draw weapon for only 1 weapon instead of all of them. There's no way to do this (that I am aware of) other than to make lots of entity parts, which seems inefficient and there's an apparent jitter and a split second where you can see the entity without textures (if it has a material part) and at original size while the entities are changing.

**Comment by CapsAdmin** [comment]
this should be possible now with target part name in proxy
