### ISSUE TITLE
Possible options for projectiles?

### ISSUE THREAD

**Issue by Cole4110** [CapsAdmin/pac3#447]
I think this is where I'm supposed to do this?? anyway!
More of a quality of life thing than anything but super useful maybe too would be
A "Remove projectiles on hide" and "Maximum projectiles" value box to projectiles
Would be super useful for keeping only one or two instances of a specific projectile in existence at any given time
For instance something like a grappling hook!

**Comment by CapsAdmin** [comment]
I've added Maximum but remove on hide is problematic as the projectile functions by firing when visible.
