### ISSUE TITLE
Return focus to game while still showing Pac menu

### ISSUE THREAD

**Issue by lilggamegenuis** [CapsAdmin/pac3#449]
### **Feature request** to allow "Hiding" the pac menu while still being able to see it.

Many times I need to test how an event works by doing some action in game (Animations, Jumping, chatting, etc).
But to do this I have to hide the menu, so if I want to see the event activate i have to try and do the action and immediately unhide to try and see it which is really difficult.

So I'm suggesting adding a option to set the transparency level when hidden (Or unhidden, so the user can have hidden and unhidden have the same transparency to only return focus)

**Comment by Earu** [comment]
Unfortunately I'm not entirely sure but that would require painting most Ui elements which @capsadmin doesn't want as it needs to be compatible with derma skins

**Comment by lilggamegenuis** [comment]
Can't it use the same method as how hiding normally works? Since when it hides, it has a fade.

**Comment by Earu** [comment]
That's an engine method

**Comment by lilggamegenuis** [comment]
hmm, well is it at least possible to add a option not hide the menu but only restore focus to the game?

**Comment by Earu** [comment]
Probably yes

**Comment by CapsAdmin** [comment]
alt+e ?

**Comment by Earu** [comment]
I forgot this was a thing lol

**Comment by lilggamegenuis** [comment]
😐 oh. I wish i new about that before
