### ISSUE TITLE
ogg not working? :~:

### ISSUE THREAD

**Issue by Ghostgamer128** [CapsAdmin/pac3#450]
I'm having issues with the ogg I can't hear anyones music and I can't even hear mine theres somthing wrong with it is there a way to fix this problem?

**Comment by roboderpy** [comment]
Is `awesomium_process.exe` muted or not? In `SndVol.exe`

**Comment by roboderpy** [comment]
Happens for a plenty of users, but case of this bug is still unknown

**Comment by bluemetaknight** [comment]
How does one fix this issue? Same thing happens with me.

**Comment by CapsAdmin** [comment]
I've heard reports of people being able to hear oggs with sound2 or gmod chromium branch. Reopen if you don't.
