### ISSUE TITLE
Another Error with PAC3

### ISSUE THREAD

**Issue by Aldronea** [CapsAdmin/pac3#452]
I seem to be missing the ability to adjust PAC distance from the Q menu?
https://steamuserimages-a.akamaihd.net/ugc/835832990477228411/ED687AA5D929617DEE6F417E42E0E480DFE1B433/
https://steamuserimages-a.akamaihd.net/ugc/835832990477231299/0FA1DA030650D8A413F6CF7769D0AB2CBBDAE724/https://stea

**Comment by Aldronea** [comment]
https://steamuserimages-a.akamaihd.net/ugc/835832990477566057/19457568CBFA9FD458AD41D6B9CD4A9B0D1F6ED3/
But it works on the server?

**Comment by Earu** [comment]
If it does not work on the server you're playing itws likely its done on purpose or that they messed with pac code, or that they have addons conflicting (which shouldnt happen in theory)
