### ISSUE TITLE
Can't move camera/interact with models near the middle of the screen

### ISSUE THREAD

**Issue by ghost** [CapsAdmin/pac3#453]
Basically, my cursor won't do anything unless I click near the screen's edges. I couldn't think of a better way to explain it so I recorded a quick video for you guys. It feels like there's some kind of invisible window in the way. Yes, I have uninstalled PlayX

https://www.youtube.com/watch?v=T4L8FlZ58zo

**Comment by roboderpy** [comment]
Conflicting addon that adds invisible, but interactable panel at center of screen.

**Comment by andrufb** [comment]
@roboderpy Any ideas on what is it exactly? I can't think of an addon that I have that does that...

here's literally EVERYTHING I have http://steamcommunity.com/sharedfiles/filedetails/?id=399098827

**Comment by lilggamegenuis** [comment]
the Cinema maybe?

**Comment by andrufb** [comment]
@lilggamegenuis I'll try disabling the Media Player one

**Comment by andrufb** [comment]
Nope. Completely uninstalled the Cinema and the Media Player ones. Still the same

**Comment by roboderpy** [comment]
Try to disable all addons but pac3
