### ISSUE TITLE
Hitpos bone no longer an option?

### ISSUE THREAD

**Issue by chromamods** [CapsAdmin/pac3#455]
Hello! Following the new update with PAC3, it would appear that the option to use the 'hitpos' bone, the bone which allows you to connect models to the area where your crosshairs are, has been _removed_ from the editor.  I am curious as to whether this is a glitch, or simply a removal in the now current update.

Thank you for your answers,
-Chroma.

**Comment by lilggamegenuis** [comment]
I think it's a glitch as manually entering "hitpos" into the bone option works fine.

**Comment by CapsAdmin** [comment]
fixed in develop branch (soon to be merged)
