### ISSUE TITLE
Error flooding in console related to projectiles.

### ISSUE THREAD

**Issue by GiggleHub** [CapsAdmin/pac3#457]
lua/pac3/core/shared/projectiles.lua:166: attempt to call method 'GetEyeTrace' (a nil value)
  1. unknown - lua/pac3/core/shared/projectiles.lua:166

Projectiles in question:
http://imgur.com/a/CDptR

This appears to be occurring after this bug happens:
https://github.com/CapsAdmin/pac3/issues/444

**Comment by CapsAdmin** [comment]
fixed
