### ISSUE TITLE
Spawnmenu

### ISSUE THREAD

**Issue by Immortalyes** [CapsAdmin/pac3#46]
When trying to select a model from the spawnmenu, the item you click on spawns in the world and not in PAC.

**Comment by CapsAdmin** [comment]
The way I have to do this right now is stupid but it's the only clean solution. There is no player spawn prop hook on the client, only on server so I have to check on the server and send back a message to the client.

PAC3 should have its own model browser but this feels a bit wrong to add when people are so used to the spawnmenu.
