### ISSUE TITLE
cant find a way to have mouse1 activate an event without unbind

### ISSUE THREAD

**Issue by LunarWalker** [CapsAdmin/pac3#462]
I can't find a way to have mouse1 activate an event without unbinding it from primary attack, whenever I start an event and set it to command than try to bind that command to mouse1 it unbinds it from primary attack and I can't use primary attack without binding it back, which in turn unbinds my command event.

**Comment by UnknownShifter** [comment]
bind mouse1 "+attack; pac_event name"
