### ISSUE TITLE
Custom model issue for meshlab instructions

### ISSUE THREAD

**Issue by babycakies** [CapsAdmin/pac3#464]
Wiki>custom models>My custom model looks fullbright!>using meshlab>Generating normals

there are no instructions on how and what to do for your custom model, it is a blank space

**Comment by roboderpy** [comment]
Try SSBump. Also Bump mapping on custom models does not working (See https://github.com/Facepunch/garrysmod-issues/issues/2489 https://github.com/CapsAdmin/pac3/issues/365)
