### ISSUE TITLE
Restricting for certain groups not working.

### ISSUE THREAD

**Issue by Gewad** [CapsAdmin/pac3#468]
So please excuse me for being dumb but I used the "PAC in gamemodes" page to try and restrict users from using pack and only whitelisted people.
Here is my code:
local ranks = {
    "moderator",
    "Developer",
    "pac3",
    "admin",
    "superadmin",
    "Owner",
    "senioradmin",
    "pac3trainer",
    "pac3officer",
}
hook.Add("PrePACConfigApply", "PACRankRestrict", function(ply)
    for _,rank in pairs(ranks) do
        if not ply:GetUserGroup() == rank then
            return false, "Insufficient rank to use PAC."
        end
    end
end)
hook.Add("PrePACEditorOpen", "PACRankRestrict", function(ply)
    for _,rank in pairs(ranks) do
        if not ply:GetUserGroup() == rank then
            return false, "Insufficient rank to use PAC."
        end
    end
end)
Now the file is saved in garrysmod/addons/pac3-master/lua/autorun/server and the file is called pac_rankrestrict.lua
Sorry if this is something stupid I have done I fear I might have misplaced the file or something.

Thanks in advance,

Gewad.

P.S. I didn't add the code thing to the code because it removed all the lines and kinda made it one big pile of text. But if thats useful I have added the code thing to it below here:

`
local ranks = {
    "moderator",
    "Developer",
    "pac3",
    "admin",
    "superadmin",
    "Owner",
    "senioradmin",
    "pac3trainer",
    "pac3officer",
}
hook.Add("PrePACConfigApply", "PACRankRestrict", function(ply)
    for _,rank in pairs(ranks) do
        if not ply:GetUserGroup() == rank then
            return false, "Insufficient rank to use PAC."
        end
    end
end)
hook.Add("PrePACEditorOpen", "PACRankRestrict", function(ply)
    for _,rank in pairs(ranks) do
        if not ply:GetUserGroup() == rank then
            return false, "Insufficient rank to use PAC."
        end
    end
end)
`

**Comment by ToastyEngineer** [comment]
The code of the wiki page has been updated, make sure to check again.
If you **add** a file, make sure you restart the server afterwards.

Also for proper code blocks use this here
![image](https://user-images.githubusercontent.com/11852198/29641086-3d0a5710-8862-11e7-949d-ffb68a93393d.png)

**Comment by Gewad** [comment]
I added the new code but it still allows users to open the menu.

**Comment by ToastyEngineer** [comment]
Oh I see.

You can't use the hook PrePACEditorOpen serverside. 
You need to run it clientside to restrict it. Putting the latter of the code with the local table in a file inside the /client folder should do. Or you can make it shared and put `if SERVER then` for the serverside part and `if CLIENT then` for the clientside part.
Gonna update the info to that to be more specific on the wiki

**Comment by Gewad** [comment]
Only the restricting the users from opening it isn't working for me right now. However PAC3 is restricted for user.
Thanks mate.

**Comment by ToastyEngineer** [comment]
Do what I wrote above and it will work, trust me. I just tried it myself.

**Comment by Gewad** [comment]
I woke up this morning and realised I forgot to make the file into a lua file.
Thanks for the quick response and fix.
