### ISSUE TITLE
Trying to change bones causes "addons/pac3/lua/pac3/core/client/bones.lua:128: attempt to index local 'ang' (a nil value)"

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#475]
After the "Fixed HideMesh breaks bones angles (inside PAC3)" commit, trying to put anything on ANY bone causes console to spam "addons/pac3/lua/pac3/core/client/bones.lua:128: attempt to index local 'ang' (a nil value)" over and over again, and hides the outfit. See attached screenshot.
https://steamuserimages-a.akamaihd.net/ugc/857228716249686045/CD82BB171D1F9584192CD95A4B6D396F8D0D587B/

**Comment by nerdkoopa** [comment]
Update: Finally found the cause. Updated title and first post.

**Comment by nerdkoopa** [comment]
Update yet again: It apparently does this for ALL bones and spams [ERROR] addons/pac3/lua/pac3/core/client/bones.lua:128: attempt to index local 'ang' (a nil value)
  1. GetBonePosition - addons/pac3/lua/pac3/core/client/bones.lua:128
   2. getpos - addons/pac3/lua/pac3/core/client/bones.lua:259
    3. v - addons/pac3/lua/pac3/editor/client/select.lua:170
     4. unknown - lua/includes/modules/hook.lua:84

**Comment by nerdkoopa** [comment]
Here's how it looks like when I try to change bones. https://steamuserimages-a.akamaihd.net/ugc/857228716249813992/235A30ED2DCD8E841212DB277EA0B1232C10C7E7/

**Comment by CapsAdmin** [comment]
Should be fixed now
