### ISSUE TITLE
Missing } in lua/pac3/core/client/parts/material.lua at line 25

### ISSUE THREAD

**Issue by ReverendV92** [CapsAdmin/pac3#485]
[ERROR] addons/pac3-develop/lua/pac3/core/client/parts/material.lua:25: '}' expected (to close '{' at line 24) near 'DetailBlendFactor'
  1. unknown - addons/pac3-develop/lua/pac3/core/client/parts/material.lua:0

Using develop branch from GitHub.

**Comment by CapsAdmin** [comment]
hold on
