### ISSUE TITLE
Odd material being applied when I wear pac.

### ISSUE THREAD

**Issue by wcsgtfox** [CapsAdmin/pac3#486]
This only appears to be occurring on my friends NutScript server, and only for when I try to load pac. everyone else sees the same issue yet it only happens after I wear a pac, regardless of what I am loading. It applies some odd material to certain parts of my model.. I'm positive it is not related to what I have in the pac's or my model as it works on other servers just fine. Here is a screenshot of the issue, the white parts are not part of that model..
![692d0b3a7ddd160bd5a9adaa7429917aabf01b3b](https://user-images.githubusercontent.com/11651811/30179888-01c77b76-93dc-11e7-86e5-ea015d622a62.jpg)

We are currently utilizing the github pac version, not the workshop addon.

**Comment by Earu** [comment]
are you sure your uvs are matching in the first place? does it happen only to you?

**Comment by wcsgtfox** [comment]
This happens to me only, and others can see it, this model and this pac work fine on other servers, we installed the github version of pac properly.. I am unsure as to what it could be... And the pac I have on there has no material like that applied, nor does it have any materials that go directly on my entity.

**Comment by wcsgtfox** [comment]
Update: it would appear a specific group was causing this, although I have no clue why as it only happens on Nutscript servers, I had a hard light shield that had a custom obj, material, sub material and hold type... none of the materials come even close to looking like what is on my model in the screenshot provided in my original post. Maybe sub material has a bug?; Because plenty of my working pacs without sub material seem fine.

**Comment by CapsAdmin** [comment]
the sub material part is known to be buggy and strange, i'd recommend using the new parts from now on
