### ISSUE TITLE
.zip models will unload upon rewear and refuse to redownload

### ISSUE THREAD

**Issue by digivee** [CapsAdmin/pac3#489]
Upon wearing a downloaded, ziped, playermodel, it will download fine the first time, but any time afterward when the pac is reworn it unloads and pac spits out `[PAC3] unable to open file for writing
` in console, replacing my player model with the ERROR.mdl

Others can see my model (assumingly because they load it once), I however cannot.

The zip looks like [this](https://i.imgur.com/TIl35dM.png)
Using store so theirs no compression in winrar. It just simply worked once and now its not

**Comment by roboderpy** [comment]
Because ponyscape pac3 is always outdated, this might already be fixed
