### ISSUE TITLE
pac.DrawEntity2D doesn't render the entity when it's crouching

### ISSUE THREAD

**Issue by ghost** [CapsAdmin/pac3#490]
pac.DrawEntity2D seems to act weird when the player crouches.
https://i.imgur.com/6kXlBSe.png

https://i.imgur.com/Z2BzL19.png

Here's the code;

```
	self.PModel.Paint = function(self,w,h)
		
		local ent = LocalPlayer()
		ent:SetAngles(Angle(0,0,0))
		local cam_ang = ent:EyeAngles() + Angle(0,180,0)
		cam_ang.p = 0
		local cam_pos = ent:LocalToWorld(ent:OBBCenter()) - cam_ang:Forward() * ent:BoundingRadius() * 95
		
		local w,h = scrw, scrh
		
		pac.DrawEntity2D(ent, 0, 0, w, h, cam_pos, cam_ang, 3, 3000)

	end
```

**Comment by Techbot121** [comment]
closing this issue as it's quite old. If it still happens on latest develop version, feel free to reopen.

**Comment by thegrb93** [comment]
I think pac.DrawEntity2D has a host of issues iirc, but I don't know if anyone has the setup or will to fix all of it.
