### ISSUE TITLE
Inconsistent invalidbone angle behavior

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#491]
Invalidbone has changed how it handles angles, and it is not the same between outfit owner and other clients.
In the old behavior still present in the Workshop version, models on invalidbone followed player yaw angle, and nothing else. This was synced on both outfit owner and other clients.
In the new behavior, models on invalidbone follow both player eye pitch and yaw on the outfit owner's end, but do not rotate at all on other clients.

**Comment by roboderpy** [comment]
__INVALIDBONE__ is invalid - means you should never use it

Before update bone count was calculated wrong, and one of bones was always a non existing bone
