### ISSUE TITLE
Model2 size resets on wear.

### ISSUE THREAD

**Issue by Delta983** [CapsAdmin/pac3#492]
Alright so say you make a model2 in pac, port an entire MDL model and all that good stuff, and then bone merge it.

If you then want the model to look skinnier by putting the size of the model2 to for an example 0.95, making all the bones shrink just a little to make it look skinny, it all resets back to 1 when you wear Your pac, the numbers will remain 0.95 however the model will look as if it is size 1. 
I dont know what causes this, does anyone else have this problem?

**Comment by CapsAdmin** [comment]
fixed
