### ISSUE TITLE
PAC 4 model2 animation issue

### ISSUE THREAD

**Issue by AlyISan** [CapsAdmin/pac3#493]
With a working, correctly imported MDL zip file on model2 ( With correct files, textures etc. ) animations work flawlessly clientside. ( Both models have the same skeleton, bonemerged and work with no issue. ) However when another player sees the loaded PAC, the animations don't work unless the person wearing the PAC re-wears. The animations then break AGAIN when the person wearing the PAC leaves the other players view. Often T-Posed or the last animation seen, looping.

EDIT: Tested with three separate people, please let me know if you need me to explain in-depth more.

**Comment by steampunko** [comment]
What is PAC4 even

**Comment by CapsAdmin** [comment]
what kind of animations? email me at eliashogstvedt@gmail.com

**Comment by AlyISan** [comment]
Apologies, one of your updates resolved this somehow.

**Comment by roboderpy** [comment]
Please close the issue on your own next time
