### ISSUE TITLE
Lua Error during Serverside Use

### ISSUE THREAD

**Issue by Mmmaaattt95** [CapsAdmin/pac3#494]
When opening the PAC3 editor on a server I get the following error spammed:

[ERROR] lua/pac3/editor/client/panels/properties.lua:281: attempt to call field 'Header' (a table value)
  1. unknown - lua/pac3/editor/client/panels/properties.lua:281

Can someone please advise.

**Comment by CapsAdmin** [comment]
what derma skin is the server using?

**Comment by Mmmaaattt95** [comment]
Standard I believe. It is also a WW3RP Clockwork based server
