### ISSUE TITLE
Crash on server join

### ISSUE THREAD

**Issue by Stanstar22** [CapsAdmin/pac3#496]
Getting this error, have tried deleting LUA Cache, all addons, all pac3 related files and all lua in my gmod folder.

From crash log:
-Lua Stack Traces-
  Client
    0. AddParticles - [C]:-1
      1. (null) - lua/pac3/core/client/parts/effect.lua:57
        2. include - [C]:-1
          3. LoadParts - lua/pac3/core/client/parts.lua:120
            4. (null) - lua/pac3/core/client/init.lua:44
              5. include - [C]:-1
                6. (null) - lua/autorun/pac_init.lua:24
                  7. include - [C]:-1
                    8. (null) - lua/autorun/pac_editor_init.lua:2

  Server
    Lua Interface = NULL

  MenuSystem
    *Not in Lua call OR Lua has panicked*

**Comment by CapsAdmin** [comment]
looks like pac is trying to load a bad particle file. What games do you have installed and mounted to gmod?

**Comment by Stanstar22** [comment]
I've got:
CS:S
CS:GO
HL2
HL2:EP1
HL2:EP2
HL2:Lost Coast
Left 4 Dead 2
TF2

Now I think about it could it possibly be an addon I have installed that is loading through pac, even if the addon is not on the server?

**Comment by Avernakis8** [comment]
Well you're missing Portal and Portal 2 on that list.... _maybe_ l4d1 idk and all half-life's

**Comment by Stanstar22** [comment]
They're not necessary to run gmod, I've had no errors before today.

**Comment by Stanstar22** [comment]
Found the issue, if I enable this [https://steamcommunity.com/sharedfiles/filedetails/?id=1147261376]addon(url) then it causes the game to crash. Hopefully the SWEP dev will fix :)

**Comment by roboderpy** [comment]
Recent TF2 update broke PAC3

Will look for workaround

**Comment by roboderpy** [comment]
fixed
