### ISSUE TITLE
Problem in menus

### ISSUE THREAD

**Issue by Kiruclanz** [CapsAdmin/pac3#498]
Since the last update awhile ago this part of the pac editor window can't be raised or lowered anymore, which is REALLY annoying when you need to use drop-down windows like those for submaterial parts, because their drop down menus go off-screen and you can't fix it by raising the menu's position anymore.

![bccfd25e188795cd7db159910fc85b58](https://user-images.githubusercontent.com/12915173/31188433-e03d2eb0-a902-11e7-9f62-bf5951684be5.gif)

**Comment by roboderpy** [comment]
fixed in develop
