### ISSUE TITLE
Random color on particle is "true" by default in older pacs, causing rainbow havoc

### ISSUE THREAD

**Issue by AeoMayo** [CapsAdmin/pac3#500]
Not inherently a bug, but I was told to post this here.

While I'm glad "random color" in particle is finally fixed, it's set to "true" by default when the part is created, meaning it's still toggled on in all my older pacs before it was fixed, creating mass color chaos. Since the setting doesn't exist in the pac file itself until it's changed, I can't use notepad++ to set it to false across all my pac files.

If possible, I suggest making it be set to false by default upon creation, and keeping it false if the setting doesn't exist in the pac file, retroactively fixing older pacs where it's not meant to be on. Which is probably a good majority of pacs, because since it didn't work until now, most people ignored it and left it on and are probably confused now as to why their particles are changing colors randomly.

**Comment by roboderpy** [comment]
fixed on develop
