### ISSUE TITLE
PAC4 Entity2 Issue.

### ISSUE THREAD

**Issue by russetdapone** [CapsAdmin/pac3#501]
After using them, Entity2 will make you skip and lag around derpily until your playermodel reverts

ALSO Normal entity Model Changing is disabled/broken. 
Dont know how to fix.
Touching ground will make you revert
Damage reverts you
movement is laggy to unplayable.
Its unusable.

**Comment by steampunko** [comment]
What is pac4 even

**Comment by russetdapone** [comment]
PAC3 updated using github

**Comment by CapsAdmin** [comment]
I think I've fixed this now. Reopen if not.
