### ISSUE TITLE
Not able to Wear PAC3

### ISSUE THREAD

**Issue by Ripskilt** [CapsAdmin/pac3#502]
I run a nutscript server and am having a problem putting PAC3 on it. I had it working for SA+ but now it does not work at all. 

No one is able to wear Pac3 atm

**Comment by LuaTenshi** [comment]
Any errors? What code are you using to make it SA only?

**Comment by Ripskilt** [comment]
Nevermind I found the issue, was a file that was conflicting with it. 

Someone gave me a file to add to make it so it was donaters only but it did not work. So the file was hidden inside some files. I found it, removed it, and boom. PAC3 is working fine now. Thanks.
