### ISSUE TITLE
Issues with TF2 Pyro Update

### ISSUE THREAD

**Issue by BLEEPBLOOPforLife** [CapsAdmin/pac3#504]
The new TF2 Pyro Update seems to be causing issues with PAC3. Clients with TF2 updated to the Pyro Update and has it mounted will crash on Sending Client Info. I have analyzed multiple dump files from players on my server and can safely conclude that it seems to be a particle from TF2 causing it. When my players unmounted TF2, they were able to load into the server just fine. Please fix this problem.

**Comment by roboderpy** [comment]
Duplicate of https://github.com/CapsAdmin/pac3/issues/496

https://github.com/CapsAdmin/pac3/commit/f35a6fe29abcfcda1ccc6b4462035a6eacb100c1

stop
