### ISSUE TITLE
PAC4 Model2 textures not loading for people

### ISSUE THREAD

**Issue by Delta983** [CapsAdmin/pac3#517]
So apperantly some people cant see the textures of my model2 port, others can.. It's a 50/50 or something i dont know.

I done everything right and by the book, i have ported model2 before so i know the process very well, its just this one model that people arent able to see the texture of, the model itself loads fine, and i have a friend who had the same problem with his model so i figured i should post this here incase it is a bug that needs to be fixed. I will post the model i decided to use here so you can see if its just the model's fault or pac bugging out, I did a bit of editing on the model before i uploaded it to dropbox and stuff so it came on about 6.03MB which shouldnt be that bad.

https://steamcommunity.com/sharedfiles/filedetails/?id=918676251

**Comment by CapsAdmin** [comment]
can you post the edited model?

**Comment by CapsAdmin** [comment]
or email me 

eliashogstvedt@gmail.com

**Comment by Delta983** [comment]
Hey sorry for the late reply, I will send you an email With the zipfile for the edited model i used in pac

**Comment by CapsAdmin** [comment]
Which textures are missing? The hair is error for me and there's only one texture in the zip.

```
[PAC3] the model wants to find ct_helga_eyeball_l.vmt but it was not found in the zip archive
[PAC3] the model wants to find ct_helga_eyeball_r.vmt but it was not found in the zip archive
[PAC3] the model wants to find ct_helga_hair.vmt but it was not found in the zip archive
```

If it's the hair that you're talking about, maybe some people are subscribed to the addon and some aren't?

**Comment by AlyISan** [comment]
Same happens to me.

I'm a novice with source modeling however I did the following -
I made sure the correct textures were referenced in the QC, that the model functioned and worked as a whole. Included and edited the VMT's to utilize the right VTF's yet it still breaks.

Messing around with it ATM, seeing if I either did something wrong or PAC4 refuses to play nice with models with multiple body groups and skins.

**Comment by CapsAdmin** [comment]
Maybe make sure it works in gmod as a normal addon first. If it does and doesn't in pac3 then something is probably wrong.

(I don't know much about exporting models and whatnot)

**Comment by CapsAdmin** [comment]
it looks like i've got the emails mixed up with another issue

**Comment by AlyISan** [comment]
Tested the model as a normal addon for GMOD, works fine.

**Comment by Delta983** [comment]
Basically I removed the head and only kept the body to use in pac3, so ill try to edit the vmt and remove the info regarding  all this 

[PAC3] the model wants to find ct_helga_eyeball_l.vmt but it was not found in the zip archive
[PAC3] the model wants to find ct_helga_eyeball_r.vmt but it was not found in the zip archive
[PAC3] the model wants to find ct_helga_hair.vmt but it was not found in the zip archive

What's odd is, if i edit the texture I have in the zip, lets say I change the skin color on the arms and load the mdl.zip in pac3, the texture is untouched.. its confusing.

**Comment by CapsAdmin** [comment]
I tried this now and it seems to be working. Others are saying they can see me fine. There have been fixes and such since this thread.
