### ISSUE TITLE
Crash fix causing error on some clients

### ISSUE THREAD

**Issue by G-Force007** [CapsAdmin/pac3#518]
[ERROR] string length overflow
  1. Read - [C]:-1
   2. Read - lua/includes/extensions/file.lua:12
    3. Initialize - addons/pac3-master/lua/pac3/core/client/parts/effect.lua:38
     4. CreatePart - addons/pac3-master/lua/pac3/core/client/parts.lua:86
      5. SetTable - addons/pac3-master/lua/pac3/core/client/base_part.lua:751
       6. SetTable - addons/pac3-master/lua/pac3/core/client/base_part.lua:752
        7. SetTable - addons/pac3-master/lua/pac3/core/client/base_part.lua:752
         8. AttachPACPart - addons/pac3-master/lua/pac3/core/client/integration_tools.lua:129
          9. AttachPACPart - addons/pac3-master/lua/pac3/core/client/integration_tools.lua:171
           10. InvalidatePlayerOutfits - gamemodes/darkrp/gamemode/shared/sh_pacmodels.lua:129

`for file_name in pairs(pac_loaded_particle_effects) do
			local data = file.Read("particles/"..file_name, "GAME", "b")
			if data then
				for str in data:gmatch("\3%c([%a_]+)%c") do
					found[str] = str
				end
			end
		end`

Guessing file.Read is reading a file that's greater than 64MB?

**Comment by CapsAdmin** [comment]
Can pcf files be that big? I've added a limit to 10 mb to see if that fixes it.

Having all the games mounted the largest one i saw was 3 mb.

**Comment by roboderpy** [comment]
no replies and it is probably fixed.
