### ISSUE TITLE
Black screen when clicking effect

### ISSUE THREAD

**Issue by combine132** [CapsAdmin/pac3#52]
Not sure if it's my settings, or if it's PAC messing with me.

When I add an effect to my group it works fine, however if I add it to a lampshade like in the picture and click on it, the screen goes black.
I will then have to close the editor and reopen it again.

Before clicking the effect (Look in the editor):
![2014-06-30_00002](https://cloud.githubusercontent.com/assets/1353356/3430203/33e352c4-005f-11e4-82c7-e3f1bdb85e76.jpg)

After clicking the effect (Once again, look in the editor):
![2014-06-30_00003](https://cloud.githubusercontent.com/assets/1353356/3430206/429df8aa-005f-11e4-8a95-b0b1ab1b129b.jpg)

After that I'll have to close and reopen the editor for anything to display:
![2014-06-30_00004](https://cloud.githubusercontent.com/assets/1353356/3430208/52b713b6-005f-11e4-9e56-03fe07a38013.jpg)

**Comment by ZzZMarkJonesZzZ** [comment]
Had the same problem. Do what LUModder said to fix it.

**Comment by KeYStonEKnighT** [comment]
thanks for the reply but i figured it out a long time ago and i haven't
played garry's mod in ages lol.
