### ISSUE TITLE
The Animation Editor no longer shows up :/ Why and how do I fix it?

### ISSUE THREAD

**Issue by NearStone** [CapsAdmin/pac3#520]
I used to have a working animation editor, then it stopped working, now it's not even there. I'd like a bit of feedback on how to fix it.

**Comment by Techbot121** [comment]
Are you on the workshop version or GitHub?

anyway you can get there in two different ways:

old way:
by typing `animate` in the console

new way:
by simply selecting the custom animation part in PAC

in the newer versions of PAC the animation (if it's small) gets stored in the outfit it self so you don't need a separate file for it anymore.

**Comment by NearStone** [comment]
Thanks! I'm using the workshop version btw. I appreciate it!

**Comment by NearStone** [comment]
Well then, when I select the "custom animation" button in pac3, it says pac3 has made errors and doesn't show the usual custom animation screen :/
