### ISSUE TITLE
Resourcebrowser improvements

### ISSUE THREAD

**Issue by Techbot121** [CapsAdmin/pac3#521]
here I'll collect some stuff that comes up or what people ask for.

- Ability to change the Icon sizes

**Comment by Techbot121** [comment]
just noticed that is already implemented with ctrl+mousewhee;

**Comment by Tenrys** [comment]
lol

**Comment by Techbot121** [comment]
- Add some sort of info button "(?)" or something that lists navigation help and keyboard shortcuts

**Comment by CapsAdmin** [comment]
Yeah I've always been lazy to document these hidden features, even outside of the resource browser. Maybe a + - button and the bottom right corner is enough.

**Comment by Techbot121** [comment]
- disabling the movement on the camera while you're typing in the search bar

**Comment by Jophes** [comment]
Created PR #748 to add GUI controls for zooming to the resource browser
Video of controls in use:
https://giant.gfycat.com/ThoughtfulMadeupCowrie.webm

And it seems movement of the camera has already been disabled when typing in the search bar.
