### ISSUE TITLE
Projectile damage issue

### ISSUE THREAD

**Issue by Vandarx** [CapsAdmin/pac3#534]
Projectile damage seems to be broken (but dealing damage via mass still works). Returns this error:

[ERROR] lua/pac3/extra/shared/projectiles.lua:321: attempt to index global 'owner' (a nil value)

(also, while on the subject of projectiles, they have large shadows if physical is ticked, for some reason)

**Comment by CapsAdmin** [comment]
This was fixed a while back.

**Comment by Vandarx** [comment]
Ah, my bad; I neglected to test the developer branch.
