### ISSUE TITLE
Client parts command auto run on wear and other non-related event update

### ISSUE THREAD

**Issue by poofyteddy** [CapsAdmin/pac3#537]
Hi,
I'm running into issue trying to use the advanced part named command.
No mater where i put the command part in the pac tree (under event, under hidden category ...) the code in it will run when i wear the PAC, and also if another event, related or not, is triggered.

you can find in attachment a simple pac that have 2 command part with voluntary wrong command in them, so you can see them on the console.
you can trigger the bug by typing `pac_event test 2` twice in the console, or by re-wearing it.

Thank for you time, hoping i send enough information and didn't create a duplicate.
[AutoRun Commande.txt](https://github.com/CapsAdmin/pac3/files/1464786/AutoRun.Commande.txt)

**Comment by poofyteedy** [comment]
i'm starting to wonder if i'm alone having this issue ...  maybe no one use command, or it's the desired behavior.

**Comment by roboderpy** [comment]
This should be (mostly) fixed in develop now

**Comment by poofyteddy** [comment]
@roboderpy could you please lead me to the comit that fixed it?

**Comment by roboderpy** [comment]
https://github.com/CapsAdmin/pac3/commit/ec5096938024f5130857561c50d3e73759a7f173
