### ISSUE TITLE
Pac Custom models broken

### ISSUE THREAD

**Issue by Stefadorum** [CapsAdmin/pac3#538]
[https://i.imgur.com/JyJi8Lw.jpg](url)
Is what it looks like
[https://i.imgur.com/sCG02nk.png](url)
That is what the model is supposed to look like

Im trying to use PAC3 to import it into Gmod, but the model is completely broken
Any help would be greatly appreciated

**Comment by EgrOnWire** [comment]
That is an issue with your exporter toolkit/plugin.

Make sure your exporter has similiar or matching settings:

- Faces: triangles
- Precision: 3
- Texture coordinates: enabled
- Normals: enabled
- Smoothing groups: enabled
- Relative: disabled
- Hidden objects: disabled

**Comment by Stefadorum** [comment]
Thank you a lot for the answer :)
But im relatively new with this, i usually use Crafty to export it from mdl to obj, and then use Dropbox.
Is it possible you can tell me what you mean with exporter toolkit/plugin?
Thanks anyway for the answer!

**Comment by EgrOnWire** [comment]
@Stefadorum Crafty is a bad choice to do model conversion, i suggest you switch to Blender or 3DSMax (if you're a student).

Exporter plugin is a piece of software that does conversion from one data type to another, for example in 3DS Max you can export objects in your scene to another program that does not support .max files, but instead uses .obj's or other file types, into which 3DS Max can convert.

**Comment by Stefadorum** [comment]
Thank you a lot for your help and followed your instructions
But unfortunately, the problem is still the same

**Comment by SladeXanthas** [comment]
When a model bugs out like this, it usually means that your model is just too high poly.  What is the tri count in Blender?  Anything above like, 20-25K and it's gonna have issues.

**Comment by thegrb93** [comment]
Try exporting with blender? Crafty may be putting some garbage in that the parser can't handle.

**Comment by roboderpy** [comment]
He doesn't export it with crafty. And crafty **is known** to work with pac models. Pac obj parser ignore extra data and garbage, because format standart allow any kind of data in obj file and pac obj parser handles it.

**Comment by thegrb93** [comment]
All right. We can't do any testing without the obj itself. If it's still happening and you can upload it for us then I'll reopen.
