### ISSUE TITLE
Broken camera, some features aren't working

### ISSUE THREAD

**Issue by ExoticCheese** [CapsAdmin/pac3#540]
> ##  HELLO!

 **I have been having some troubles with the pac3 camera and moving effects/objects in some of the online servers in gmod. I can only move around with the camera but i cant look around... Also i cant move 
any objects or effects... I would be thankful if you would fix this.**

# `(ﾉ◕ヮ◕)ﾉ*:･ﾟ✧`

**Comment by roboderpy** [comment]
duplicate of https://github.com/CapsAdmin/pac3/issues/453
