### ISSUE TITLE
pac3 audio issue 

### ISSUE THREAD

**Issue by mario8955** [CapsAdmin/pac3#541]
Hello! i am a friendly Pac user asking this for a friend.
i have been watching her game and her audio for pac3 isn't working properly, now some audio does work like "Squee" or such, but I tried uploading a song to drop box for her , like I've done in the past, and it has worked for her.. but to no luck, I'm having trouble with the answer, so hopefully someone will be able to help me with this, thank you, and ill do research on this too, and see if anyone else is having the issue

**Comment by Etothepowerof26** [comment]
if its an ogg then you would have to use the "ogg" item in pac3
otherwise idk

**Comment by thegrb93** [comment]
Can't help without the url to the sound
