### ISSUE TITLE
 Pac3 Editior: Entities refuse to work

### ISSUE THREAD

**Issue by hunterkrovac** [CapsAdmin/pac3#545]
Okay so i am trying to use the entities in pac3 editor and the entities refuse to work all i see is a playermodel that is flipped. I tried this on other servers and the issue still happens. I check console each server i go to has pac_enable_entities 1. This has been going on for the past 3 months. I am using the workshop version of pac3. Does anyone know how to fix this issue?

**Comment by roboderpy** [comment]
Use github version, also, flipped model means bones are being messed up.
