### ISSUE TITLE
.ogg wont stop on hide

### ISSUE THREAD

**Issue by Delta983** [CapsAdmin/pac3#549]
Like the title says, my .ogg audio files wont stop on hide when i have the box checked the says '' stop on hide '' :| any ideas? the links I use are; 

https://www.dropbox.com/s/fi62jgxihdrvqcn/mix_15s_audio-joiner_com_.ogg?dl=1
https://www.dropbox.com/s/7mcgpx773kiuql8/Initial_D_-_Deja_Vu_mp3cut_net_.ogg?dl=1

EDIT: So i ticked off the box that says '' stop on hide '' and now it stops on hide, so thats odd.. its like the box is inverted lmao, anyhow it works now.

**Comment by CapsAdmin** [comment]
It's inverted, but it's too late to fix that now as it will break all outfits that wants the opposite behavior.
