### ISSUE TITLE
Submaterial Issue

### ISSUE THREAD

**Issue by Kiruclanz** [CapsAdmin/pac3#552]
In the latest github version of Pac, there's an issue with the submaterial part.

When you change the submaterial of a model, if its the first submat, it will reset the texture once you wear or load the pac outfit. **This only happens for the first submat.** As in the material with the index of "1". It happens for every model, and it only occurs when trying to change the first submat.

**Comment by CapsAdmin** [comment]
This is kind of a known bug but i haven't bothered to look into it. Partly because I didn't make the sub material part. With the new model parts however this shouldn't be an issue anymore.

**Comment by roboderpy** [comment]
Is this still an issue?

**Comment by thegrb93** [comment]
I think it does yeah

**Comment by roboderpy** [comment]
can't reproduce OR issue is not explained clearly.

**Comment by thegrb93** [comment]
The bug I've noticed before is when loading an outfit it'll set setmaterial index 1 to nil regardless of what the part's settings are and then it'll apply the parts settings. I'm thinking once https://github.com/CapsAdmin/pac3/issues/588 is done, that behavior will be fixed though.

**Comment by roboderpy** [comment]
loaded saved outfit with submats
![loaded](https://i.dbot.serealia.ca/2018/03/hl2_2018-03-18_14-27-57.png)

**Comment by thegrb93** [comment]
Remove the submaterial 1 part and set submaterial 1 manually, load the outfit, you'll see submaterial 1 get reset to default.
