### ISSUE TITLE
my pac screws my game up if it's too big

### ISSUE THREAD

**Issue by KatherineAKABirb** [CapsAdmin/pac3#553]
i have no idea if this is an issue with pac3, gmod, or my internet, but every single time i wear a pac around 699KB, it spams my console with 
loopback:send reliable stream overflow
and kills my connection to the server. anyone know what i can do to prevent this from happening? i've spent 17 hours on this pac ._.

**Comment by FarukGamer** [comment]
Its pretty easy.. Reduce the amounts of content you that stuffed in you Outfit.

**Comment by KatherineAKABirb** [comment]
damn. ok, i guess i'll have to do that -.-

**Comment by roboderpy** [comment]
Try develop branch

**Comment by roboderpy** [comment]
Develop branch should fix that.

Try develop pac3 with develop dlib, it should definely fix any outfit overflows.
