### ISSUE TITLE
No More Room in Hell Military & Police Weapons addon causes PAC3 model part to stop working.

### ISSUE THREAD

**Issue by FatBaldBastard** [CapsAdmin/pac3#556]
https://steamcommunity.com/sharedfiles/filedetails/?id=1127166461
Singleplayer.

Using PAC3 in combination with above addon (just having it installed is enough) causes model part to always be invisible, regardless of settings.
https://cdn.discordapp.com/attachments/263801829299716106/396760526979465216/unknown.png

**Comment by roboderpy** [comment]
![fuck](https://i.dbot.serealia.ca/2018/03/notepad%2B%2B_2018-03-23_14-56-01.png)
please end my suffering

report to addon's author
