### ISSUE TITLE
Padded bodygroups do not work

### ISSUE THREAD

**Issue by EgrOnWire** [CapsAdmin/pac3#557]
![bodygroups on imgur](https://i.imgur.com/AVkAGuW.jpg)
Bodygroups with spaces before their names do not work properly

**Comment by roboderpy** [comment]
Because they should not contain spaces at all?

**Comment by EgrOnWire** [comment]
Or you shouldn't trim spaces BEFORE applying the bodygroup?
Engine works fine.

**Comment by roboderpy** [comment]
Bodygroups should not contain spaces at all. Use underscores for spaces.

Excess spaces are trimmed on multiple layers, and bodygroup part doesn't trim spaces.

**Comment by CapsAdmin** [comment]
I don't understand your response @roboderpy 

I forgot who made the bodygroup stuff (me?), but did they ever work? A better and easier to use implementation without limitations can be found in model2 and entity2.

**Comment by roboderpy** [comment]
Bodygroups should not contain any spaces.
If you put ":Trim()" in search field you can find many lines in source files where properties are getting trimmed internally, on all parts.

**Comment by roboderpy** [comment]
It seems bodygroups are not working at all now

**Comment by roboderpy** [comment]
fixed in develop
