### ISSUE TITLE
Bass starts playing at full volume sometimes, then returns to normal when entering the play radius.

### ISSUE THREAD

**Issue by thegrb93** [CapsAdmin/pac3#560]

**Comment by thegrb93** [comment]
That's my theory anyway. I'll see if I can figure it out.

**Comment by thegrb93** [comment]
seems to be the webaudio part

**Comment by thegrb93** [comment]
maybe it's because OnDraw is being called with pos at LocalPlayer() pos due to the outfit being outside PVS?

**Comment by roboderpy** [comment]
Yep because of bad BASS integration. But no, because of pursuit state of bass channel. Sound starts to play before callback is called (on low framerate of client), which causing it to be heard at maximum value because callback turns it off.

**Comment by thegrb93** [comment]
Shouldn't the noplay flag prevent that?

**Comment by roboderpy** [comment]
![bark](https://i.dbot.serealia.ca/2018/01/346fd9c1c3_firefox_2018-01-09_13-55-48.png)

**Comment by thegrb93** [comment]
Can you report to garrysmod-issues if you haven't yet? I think you know more about it than I do.

**Comment by thegrb93** [comment]
These are the flags used, `local flags = "3d noplay noblock"`

**Comment by roboderpy** [comment]
im lazy, and they won't fix it. issue will just get rotten in place

**Comment by thegrb93** [comment]
noblock means it's async right? could removing that flag fix it?

**Comment by roboderpy** [comment]
I was getting loud sound in both cases, with `noplay` and `noblock` enabled/disabled. it is just an issue with bass. Only way to workaround this is writting file into sound/ folder and playing it using `EmitSound` which uses BASS for oggs too, but it doesn't seem to have any issues with playing the sound.

**Comment by thegrb93** [comment]
Are you sure this is a problem with BASS? I think it's a problem with the outfit playing the sound to be outside PVS.

**Comment by thegrb93** [comment]
It happens more when that is the case.

**Comment by roboderpy** [comment]
```
[PAC3] failed to render Player [2][MAGKEKV3000 (null98932)]:
[VLL: pac3-original - pac3/core/client/parts/webaudio.lua]:172: attempt to index local 'stream' (a nil value)
```

**Comment by roboderpy** [comment]
Also `3d noplay noblock` is not working for me at all ![lol](https://i.dbot.serealia.ca/2018/01/d149c56418_hl2_2018-01-14_08-55-39.png)

**Comment by roboderpy** [comment]
all should be working now
