### ISSUE TITLE
Toggle command doesnt work with camera

### ISSUE THREAD

**Issue by FlamingFox5** [CapsAdmin/pac3#563]
Tried to make a thirdperson with camera and command event to toggle it on and off, only toggles off and doesn't toggle back on. Even though when i open pac the little clock for event is blu signifying it should of went back to third person. Guessing this is a bug

**Comment by roboderpy** [comment]
Camera updated only ondraw and this is a bug

**Comment by roboderpy** [comment]
fixed in develop
