### ISSUE TITLE
I can see my own PAC3 outfit, but not anyone else's

### ISSUE THREAD

**Issue by Cameron-Stuart** [CapsAdmin/pac3#570]
I've been playing with PAC3 on my favourite server, and when I wear my PAC outfit everyone can see it. But I cannot see anyone else's PAC outfits. Everyone can see them, apart from me.

**Comment by FarukGamer** [comment]
Enter pac_enable 1 in you console

**Comment by Cameron-Stuart** [comment]
I have already made sure that pac_enable is set to one.

**Comment by Cameron-Stuart** [comment]
I managed to fix the issue. For some reason my render distance was set to -14672409
