### ISSUE TITLE
Bonemerged model keeps glitching out of place

### ISSUE THREAD

**Issue by spaceboat** [CapsAdmin/pac3#571]
So im trying to bonemerge a jacket onto my character but when I move to certain places, the bonemerged part of the jacket moves out of place from where I want it to stay. Not sure what im doing wrong

**Comment by spaceboat** [comment]
Yeah, like if i walk to the right it starts moving out of place

**Comment by thegrb93** [comment]
But does it stay that way while holding still? or does it return to the correct position?

**Comment by spaceboat** [comment]
Yeah it stays in the position but if i look at a certain angle it goes back to place

**Comment by thegrb93** [comment]
Could you upload your pac?

**Comment by spaceboat** [comment]
Alright, sending one now

**Comment by thegrb93** [comment]
I think I've found the issue to be due to FollowPart code which adds euler angles instead of using proper rotation matrices. I'll fix it.

**Comment by thegrb93** [comment]
@CapsAdmin @roboderpy I changed the code of FollowPart in bone.lua to this, which seems to fix the gimble-locking/angle addition artifacts, but it screws up pre-existing pacs that use FollowPart. Idk if it's right, mind looking?

```
local part_ang, follow_ang = Matrix(), Matrix()
part_ang:SetAngles(part.Angles + part.AngleOffset)
follow_ang:SetAngles(part.FollowPart.cached_ang)
local angles = (part_ang * follow_ang):GetAngles()

if part.FollowAnglesOnly then
	local pos = mat:GetTranslation()
	mat:SetAngles(angles)
	mat:SetTranslation(pos)
else
	mat:SetAngles(angles)
	mat:SetTranslation(part.Position + part.PositionOffset + part.FollowPart.cached_pos)
end
```

**Comment by thegrb93** [comment]
Found some neater code. Produces the same results
```
if part.FollowAnglesOnly then
	local pos, angles = LocalToWorld(Vector(), part.Angles + part.AngleOffset, Vector(), part.FollowPart.cached_ang)
	mat:SetAngles(angles)
else
	local pos, angles = LocalToWorld(part.Position + part.PositionOffset, part.Angles + part.AngleOffset, part.FollowPart.cached_pos, part.FollowPart.cached_ang)
	mat:SetTranslation(pos)
	mat:SetAngles(angles)
end
```

**Comment by thegrb93** [comment]
Made some neater code that produces the same results
```
if part.FollowAnglesOnly then
	local pos, angles = LocalToWorld(Vector(), part.Angles + part.AngleOffset, Vector(), part.FollowPart.cached_ang)
	mat:SetAngles(angles)
else
	local pos, angles = LocalToWorld(Vector(), part.Angles + part.AngleOffset, Vector(), part.FollowPart.cached_ang)
	mat:SetTranslation(part.Position + part.PositionOffset + part.FollowPart.cached_pos)
	mat:SetAngles(angles)
end
```

**Comment by thegrb93** [comment]
Try updating and using the bone2 part instead of bone. You'll see some things are misaligned, but once you realign them, it should work.

**Comment by roboderpy** [comment]
Closing as no reply and fix is already implemented
