### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by Quinlan102** [CapsAdmin/pac3#572]
This error happen when a player join the server
[Anthony ツ|2|STEAM_0:1:75646395] Lua Error:

[ERROR] addons/pac3-master/lua/pac3/core/client/part_pool.lua:40: Player is NULL(!?)
  1. UniqueID - [C]:-1
   2. parts_from_ent - addons/pac3-master/lua/pac3/core/client/part_pool.lua:40
    3. fn - addons/pac3-master/lua/pac3/core/client/part_pool.lua:389
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by roboderpy** [comment]
Use develop branch
