### ISSUE TITLE
Client Error Happens on both Dev&master

### ISSUE THREAD

**Issue by Quinlan102** [CapsAdmin/pac3#573]
Happens when player joins the server.
I have tried both master & dev package
Happens on both.

[Anthony ツ|3|STEAM_0:1:75646395] Lua Error:

[ERROR] addons/pac3-master/lua/pac3/core/client/part_pool.lua:40: Player is NULL(!?)
  1. UniqueID - [C]:-1
   2. parts_from_ent - addons/pac3-master/lua/pac3/core/client/part_pool.lua:40
    3. fn - addons/pac3-master/lua/pac3/core/client/part_pool.lua:389
     4. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by roboderpy** [comment]
Please update tracebacks from dev brach

**Comment by Quinlan102** [comment]
Traceback?

**Comment by roboderpy** [comment]
`[Anthony ツ|3|STEAM_0:1:75646395] Lua Error:` and then comes traceback

**Comment by thegrb93** [comment]
He's saying that error wasn't generated by code from dev branch.

**Comment by Kamshak** [comment]
This was fixed in 8d03fa39c47dfcd0d9cb15403068091f4c0dd517
