### ISSUE TITLE
Events keep rounding down decimal values on wear.

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#574]
Events do not allow any decimal values to be place in any form at all. They always round down everything.  The values get rounded down the moment you press Wear. For example, 1.5 gets rounded down to 1. This makes it completely impossible to have any kind of precision. The only place that still allows decimal values, is the expression line in proxy, and even then only if you put it in parenthesis.

**Comment by SladeXanthas** [comment]
I'm also getting this with the latest build.  Makes setting animation rate impossible.
