### ISSUE TITLE
PAC Browser

### ISSUE THREAD

**Issue by epicmarkvan** [CapsAdmin/pac3#575]
When searching for models in the addons or whatnot, it's particularly difficult to find it with this new menu/browser. Can't click on regular addons now and just see everything inside them, I have to follow the paths of the folders inside of the Workshop selection or use the search box just to find it instead of the simplicity the old system had where like the Q menu I can just open it up, go down to Addons, find the addon and select what I want. Not to mention it's particularly difficult to resize this new menu. Don't mean to sound like I'm insulting your work, but it's a bit frustrating.

**Comment by CapsAdmin** [comment]
When you browse for a model, the browser becomes a model only browser. This mode was completely broken for local addons so this is now fixed.

As for being able to click on the addons folder and see all content, this feature has been added when browsing for models as it's useful.

I'm not sure what you mean about annoying to resize though.

**Comment by epicmarkvan** [comment]
Like the new resource browser, when you want to drag the corners and resize, it's very difficult to actually find the corner. Perhaps it's just me. Appreciate the fix for the other stuff either way!
