### ISSUE TITLE
Bodygroup Not Changing

### ISSUE THREAD

**Issue by epicmarkvan** [CapsAdmin/pac3#577]
Hey, I know I just did a thing, so my b if I'm coming off badly but I've been playing with the bodygroup ability in PAC and it seems to only work for some models. For instance, messing around with TnB models works fine but others, specifically the ones I seem to be having trouble with are [http://steamcommunity.com/sharedfiles/filedetails/?id=1238400272](url) and all the models by this author. I don't know if it's a different kind of code he uses to identify bodygroups or a fault of PAC but I figured it'd be good to bring to your attention.

**Comment by roboderpy** [comment]
this already fixed multiple times. if you are using workshop pac3, use git version of pac3
