### ISSUE TITLE
Broken camera

### ISSUE THREAD

**Issue by FlamingFox5** [CapsAdmin/pac3#581]
Pac editor camera is 2d, no clue what caused this. https://gyazo.com/b8339e0c7db1c02d30c55ee848e10f63

**Comment by thegrb93** [comment]
Looks ortho, not 2d. Probably an addon conflict

**Comment by CapsAdmin** [comment]
maybe it's zoomed in

try holding the down arrow button on the keyboard

**Comment by roboderpy** [comment]
it's definely zoomed in
