### ISSUE TITLE
Problem with Clearing PAC Outfit

### ISSUE THREAD

**Issue by RatatouilleLT** [CapsAdmin/pac3#582]
Hi,

a group of friends and I have setup a nutscript-based server, but we're having some problems with PAC.

Every time a user clears his PAC outfit, it changes his model to the model chosen on the context (C) menu. His model **cannot** be changed with ULX / nutscript afterwards.

_**Example:**_

The player is set to the ULX group 'user'. with no permissions to any administrative commands. The user has his playermodel on the context (C) menu set to Dr. Kleiner, yet his model in-game doesn't change. The player then opens up the PAC editor and clears his outfit, reverting his normally set playermodel to the playermodel set on the context (C) menu. Trying to change the model through the ULX command '!model [user] [desired playermodel path]' through the console does not work, as well as through the nutscript command '/charsetmodel [user] [desired playermodel path]'. Killing the player would not reset his playermodel as well, however making the player re-join would reset his playermodel to the desired one.

I have only added a few things to the schema that would affect PAC:

`local ranks = {
	["moderators"] = true,
	["developers"] = true,
	["donators"] = true,
	["admins"] = true,
	["superadmin"] = true,
	["owners"] = true,
}
hook.Add("PrePACConfigApply", "PACRankRestrict", function(ply)
	if not ranks[ply:GetUserGroup()] then
              return false,"Insufficient rank to use PAC."
        end
end)`

This _bug_ still happens even if the user is not set to any of the staff ranks. 

Thank you in advance!

**Comment by thegrb93** [comment]
I've also been talking to a few people regarding this issue.

It's because setting an entity's model/color/material/submaterial in clientside overrides whatever the server tries to set it to. Reverting this behavior so that the server has control over it again seems to only occur on NotifyShouldTransmit but I'm still not exactly sure how it works. Maybe @willox has insight to this?

**Comment by thegrb93** [comment]
Although, for players pac should always be setting their model in serverside. So maybe there's a clientside setmodel somewhere that needs to be removed.

**Comment by roboderpy** [comment]
this should be fixed in one of commits both on master and develop
