### ISSUE TITLE
Custom Animation: Lua error if outfit root owner is not a player (e.g. an Entity)

### ISSUE THREAD

**Issue by Kamshak** [CapsAdmin/pac3#584]
One solution would be to generate something like UUIDs for all Entities in a uniform way (e.g. using https://github.com/Tieske/uuid). This could be exposed on the part as PART:GetOwnerUuid() so that it can be used.

custom_animation.lua (PART:GetAnimID(), l. 29)

Any thoughts @CapsAdmin @roboderpy ?

**Comment by roboderpy** [comment]
https://github.com/CapsAdmin/pac3/commit/4443aad03de5b9525d5b7fac7583d23663b1594a
