### ISSUE TITLE
pac.HideEntityParts / pac.ToggleIgnoreEntity not working with integration tools

### ISSUE THREAD

**Issue by Kamshak** [CapsAdmin/pac3#585]
To test this i spawned a bot, did

pac.SetupENT(bot)
bot:AttachPACPart(some_outfit)

then used
pac.HideEntityParts(bot) and pac.ToggleIgnoreEntity(bot, true, "testing")

which both had no effect (on their own or in a Think hook).

I couldn't test if this affects normal pacs as well (without using integration tools) since i was alone on the server

**Comment by roboderpy** [comment]
![it did work](https://i.dbot.serealia.ca/2018/02/hl2_2018-02-26_16-06-30.png)
![scr](https://i.dbot.serealia.ca/2018/02/hl2_2018-02-26_16-06-56.png)
![it did work](https://i.dbot.serealia.ca/2018/02/hl2_2018-02-26_16-07-08.png)
![scr](https://i.dbot.serealia.ca/2018/02/hl2_2018-02-26_16-07-19.png)
