### ISSUE TITLE
People can't see when I pac a entity that is not myself

### ISSUE THREAD

**Issue by Atlas2** [CapsAdmin/pac3#587]
The thing is, i was trying to pac a ragdoll so people could see it in multiplayer, right? And then i can see the ragdoll with the custom model only clientside, other people see it as a normal hl2 ragdoll, I think is a bug in pac's code so im posting it here

**Comment by SladeXanthas** [comment]
I also noticed this while trying the same thing last night, not sure if it's an entity ownership issue.

**Comment by roboderpy** [comment]
fixed already
