### ISSUE TITLE
Events round down positive decimal values to integers on wear.

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#591]
Events keep rounding down all positive decimal values into integers when you press Wear. This does not happen to negative decimal values. On timer events this can be fixed by putting the offset to anything but 0, but it doesn't work on any other events. This renders dot_forward and other events mostly unusable for anything that requires precision. This issue does not happen on the Workshop branch, but it does happen on the master branch. On the dev branch this happens on servers, but not in singleplayer.

My last report of this issue was completely deleted. Why?

**Comment by CapsAdmin** [comment]
It says it was fixed in a commit. You can always reopen issues if you feel they're closed for a wrong reason.

**Comment by nerdkoopa** [comment]
Well, the issue is still there. It wasn't fixed at all.

**Comment by nerdkoopa** [comment]
Updated the first post. This happens on master branch.

**Comment by thegrb93** [comment]
Develop branch is where the fix is.

**Comment by thegrb93** [comment]
I just read that theres some mixed behavior between singleplayer and multiplayer?

**Comment by nerdkoopa** [comment]
Yes, this happens in dev branch too, just not in singleplayer.

**Comment by roboderpy** [comment]
I test all changes always in multiplayer. My changes are proven to *not* to work in singleplayer. If it doesn't work, you probably is doing something wrong.

**Comment by roboderpy** [comment]
![before](https://i.dbot.serealia.ca/2018/02/hl2_2018-02-28_06-41-06.png)
after wear
![after](https://i.dbot.serealia.ca/2018/02/hl2_2018-02-28_06-41-18.png)
![0.5](https://i.dbot.serealia.ca/2018/02/2018-02-28_06-43-06.png)
