### ISSUE TITLE
Ogg part not playing sound since last gmod update

### ISSUE THREAD

**Issue by humwhoareyouexactly** [CapsAdmin/pac3#592]
Since the latest february update, ogg part do not play any sound ever since, not sure if it has something to do with that line in the changelog : "Updated BASS.DLL to 2.4.13.8-mp3free"

**Comment by roboderpy** [comment]
Ogg part use html panel

**Comment by thegrb93** [comment]
Yeah, the webaudio part uses bass.

**Comment by CapsAdmin** [comment]
Does sound2 work?

**Comment by humwhoareyouexactly** [comment]
Sound2 works perfectly fines, its more of old pac that uses the old ogg part that as of now doesn't work. Maybe if there was a part converter like how there is one for ogg to webaudio, but for ogg to sound2 this time.

**Comment by CapsAdmin** [comment]
sound2 is more or less ogg but improved + it can handle source engine sound paths

**Comment by roboderpy** [comment]
OGG part still plays for me, BASS stuff got more weird. sorry, we can't fix this on our side
