### ISSUE TITLE
Wearing outfits seems to do nothing on the latest version?

### ISSUE THREAD

**Issue by Jarmmo** [CapsAdmin/pac3#596]
It says that it's sending it to the server and applying it but noone can see any outfits

**Comment by Dekosem** [comment]
Same issue here

**Comment by Avernakis8** [comment]
I do believe it's something with the new blacklist/whitelist options that you can find in Utilities>PAC3>Pac
Apparently ticking the "Blacklist is a whitelist" box makes you see others pacs idk why this is a thing but, it's a workaround i guess. ¯\_(ツ)_/¯

**Comment by swiffereye** [comment]
I'm having the same issue. The only way I found around it was by setting/saving an outfit as autoload and then restarting pac.

**Comment by thegrb93** [comment]
Fairly certain it was fixed. Make sure you are using the 'develop' branch.

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/tree/develop

**Comment by swiffereye** [comment]
What do I do with this?

**Comment by thegrb93** [comment]
Click the green 'clone or download' button

**Comment by swiffereye** [comment]
Now what?

**Comment by swiffereye** [comment]
I downloaded the ZIP file and opened it in WinRar

**Comment by thegrb93** [comment]
extract zip to garrysmod/garrysmod/addons

**Comment by thegrb93** [comment]
If you aren't the server host then you need the server host to do this instead.

**Comment by swiffereye** [comment]
Nothing as of now. Well it's ok I can just keep saving my pacs as auto and restarting pac.

**Comment by thegrb93** [comment]
You have to unsubscribe from the workshop version

**Comment by swiffereye** [comment]
Mkay let me try that

**Comment by swiffereye** [comment]
Oh wait, I already unsubed

**Comment by thegrb93** [comment]
Possible you have an addon conflicting with pac then
