### ISSUE TITLE
Mdl entity problem (From Logzombie)

### ISSUE THREAD

**Issue by Jarmmo** [CapsAdmin/pac3#599]
Custom .mdl links from dropbox seem to turn straight into an error if applied to entity or entity2, while remaining functional on model2 parts. All downloaded models seem to refuse to download while the console says they've downloaded successfully when applied to the entity once again. Unless they're loaded via PAC's autoload, or previously loaded in singleplayer, none others seem to work both on client and server-side on Entity and Entity2 only. As previously mentioned, model2 seems to download fine.

**Comment by Jarmmo** [comment]
"I just realised I missed out something: This is after 2 seperate mdl-cache clears, just if someone mentions that."

**Comment by CapsAdmin** [comment]
is this still an issue?
