### ISSUE TITLE
Model2 Mdl doesn't load and gives errors in console

### ISSUE THREAD

**Issue by Dekosem** [CapsAdmin/pac3#600]
Here's what's in my console everytime i try to load a mdl model:

[ERROR] lua/pac3/core/shared/util.lua:911: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. old - lua/pac3/core/shared/util.lua:911
    3. func - lua/pac3/libraries/resource.lua:254
     4. stop - lua/pac3/libraries/resource.lua:60
      5. callback - lua/pac3/libraries/resource.lua:297
       6. unknown - lua/pac3/libraries/resource.lua:193

**Comment by CapsAdmin** [comment]
This has something to do with metastruct's implementation of the game.MountGMA function. They are looking into fixing it as I write this comment.
