### ISSUE TITLE
Imported models (.obj hosted on Dropbox, etc.) don't save with Advanced Duplicator 2

### ISSUE THREAD

**Issue by CheezusChrust** [CapsAdmin/pac3#601]
Pretty much the title. Any time I import a model and change the group so it's parented to an entity of my choice, it doesn't seem to save through being duplicated. It *used* to, in the last major version of PAC, but after the last major update it seems to have broken. I use that feature a ton as it helps me build vehicles, and having to re-add the model each time I spawn it can get bothersome.

**Comment by roboderpy** [comment]
Fixed in develop
