### ISSUE TITLE
Problem with saving PAC3 in the latest version

### ISSUE THREAD

**Issue by Uberfuchs** [CapsAdmin/pac3#602]
Update below

**Comment by Uberfuchs** [comment]
So, here are two files. One file, which has been saved in the latest PAC3 with "My Outfit" group that PAC3 starts with *will not load for other players*. A version of this PAC3 *without* that *will load for other players.* If anything is added to the "My outfit" the PAC3 *will work.*
```
[2] = {
	["children"] = {
	},
	["self"] = {
		["DrawOrder"] = 0,
		["UniqueID"] = "3278660379",
		["AimPartUID"] = "",
		["Hide"] = false,
		["Name"] = "my outfit",
		["ClassName"] = "group",
		["OwnerName"] = "self",
		["EditorExpand"] = false,
		["Duplicate"] = false,
	},
},
```
Spent an extensive amount of time trying to figure this out. The difference in the files below is listed above.
[this pac loads properly.txt](https://github.com/CapsAdmin/pac3/files/1813565/this.pac.loads.properly.txt)
[this pac doesn't load properly.txt](https://github.com/CapsAdmin/pac3/files/1813566/this.pac.doesn.t.load.properly.txt)

**Comment by roboderpy** [comment]
not longer an issue
