### ISSUE TITLE
Temporarily disable caching or clear cache option in editor

### ISSUE THREAD

**Issue by lilggamegenius** [CapsAdmin/pac3#603]
This would either be a button or checkbox that would disable/clear caches so you can be certain that the data you are working with is the latest data. as of right now, the only way to clear the cache is to have Garry's mod closed (or maybe just have pac3 unloaded) and manually delete the cache since pac3 keeps a file handle of the files open preventing windows from deleting the files (*nix doesn't have that issue).

With a cache disable/clear option in the editor, this will help debug problems and errors that happen from outdated objects such as .obj and .mdl's that have since been updated.
Another thing pac could do to fix this issue is to check the [last modified date](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) from the server, or conditionally get the new data with [If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since)

**Comment by roboderpy** [comment]
Headers are being checked by `HTTP` internally and Steam's HTTP deals with cache internally, nothing can be done from GMod side on that. If could, i did it already.

**Comment by roboderpy** [comment]
Added pac_clear_objs and pac_clear_objs on develop
