### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by unbracingnine44** [CapsAdmin/pac3#604]
can someone tell me how to have any plane model from the steam Workshop and put it into pac3 for example if I wanted a muscly playermodel or something like that I would have to download the .gma file to get the source models and textures I need but I have no idea how to apply these files towards a pack to make player model I've tried just adding the models and extracting them from MDL to OBJ it kinda works but it looks horrible when you have to crop it out a little just so it looks natural when your player walks around and you're not in the t pose.

**Comment by Uberfuchs** [comment]
This is probably not the best place to ask for this kind of help.

**Comment by roboderpy** [comment]
obj doesn't support texture metadata and multi texturing in general. also obj doesn't have animations. use zip and entity2 part.
