### ISSUE TITLE
Issue w/ Develop - Can't wear PAC3 on props

### ISSUE THREAD

**Issue by Uberfuchs** [CapsAdmin/pac3#607]
Current develop branch of PAC3, not present in the master branch. On trying to wear PAC3 on a prop a player own's, they get this message:
```[PAC3] received message from server but owner is not valid!?```
I tested it with the master and develop versions. Only the develop version has this issue. There is a possibility I could have something configured wrong. If that is the case, please let me know.

**Comment by Techbot121** [comment]
both branches are even now, try again and tell if it still doesn't work.

**Comment by CapsAdmin** [comment]
but I thought I fixed it in develop, which is merged with master now lol

**Comment by roboderpy** [comment]
Should be fixed in develop
