### ISSUE TITLE
URLtex on chromium fix

### ISSUE THREAD

**Issue by EggrollWireson** [CapsAdmin/pac3#609]
https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/libraries/urltex.lua#L101

Chromium panels do not need refreshing after they've been initialized, instead :Refresh() kills panel's rendering.

**Comment by willox** [comment]
This should be fixed in gmod (and it will)

**Comment by EggrollWireson** [comment]
@willox :eggplant:
