### ISSUE TITLE
Projectile Limit?

### ISSUE THREAD

**Issue by Sounalius** [CapsAdmin/pac3#611]
I've found that I can only spawn a maximum of three projectiles in one sequence (via timerx in this case). Is this intentional, and if so, where can I find the limitation on it? I've attempted to locate it, but I'm clearly missing it, if it's there.

**Comment by Sounalius** [comment]
Anyone?

**Comment by thegrb93** [comment]
Never used projectile or looked at the code, but there's a 'maximum' setting which the user sets. Is that set greater than 3?

**Comment by Sounalius** [comment]
What setting is this, and where? I've never noticed that.

**Comment by thegrb93** [comment]
In the part settings. I believe it's labeled 'Maximum'
