### ISSUE TITLE
Proxy expression "command" usage & neseccity. Expression feedback loops.

### ISSUE THREAD

**Issue by xEvanrocks** [CapsAdmin/pac3#615]
In the proxy expression documentation, the function Command() is not understood.

> command - Based off events (unsure, code unclear) - command(index) (unclear)

I've tried to do some digging into the code myself (despite my incompetence, so I might not be correct with my claims) and the function command always appears to.
`return 0,0,0`
/pac3/core/client/parts/proxy.lua line 485

In terms of use it would be very useful to have a function which a bool (the event) can be combined with functions, which brings me to my next point.

Lerp interpolates given 3 inputs, the raitio, the first value, and the seccond value, for the proxy that I want to use, there has to be a smooth transition between a given value. the method I purpose is a variable or function which takes the output of the proxy for use in the expression. The feedback function in tandom with Lerp would allow for a target value to smoothly be interpolated to, for example:
Define feedback() as being the last output that the proxy has given
`lerp(0.5,feedback(),10)`
The sequence of the output will look as such:
0, 5, 7.5, 8.75, 9.375, 9.6875...
If applyed to a variable, this will come off as a smooth transition from 0 to 10.

I feel these 2 functions would be very useful in the collection of tools that may be used for creating PAC's.

**Comment by CapsAdmin** [comment]
The command proxy function is meant to be used with the command "pac_proxy". It allows you to modify proxies from a console command. `pac_proxy test 5` will modify a proxy called `test` in your outfit using the command function and set its return value to 5.

I've added `feedback` now in the develop branch. Your lerp example worked for me. `lerp(0.1, feedback(), 20)`
