### ISSUE TITLE
Camera and Rotating Problems

### ISSUE THREAD

**Issue by Fabian272** [CapsAdmin/pac3#617]
I have some problems that if i use either github or workshop pac the middle of pac wont be useable , neither rotating or moving camera works there and my mouse cursor turns in as if i was editing / marking text, what could be causing this issue? I've seen that theres a guide on the community page that says it could be playx but i dont even have it

**Comment by CapsAdmin** [comment]
what other addons do you have?

**Comment by Fabian272** [comment]
what ones could conflict with it?
i have lots of vehicles and weapon addons for the most part and some npcs and entities

**Comment by Fabian272** [comment]
just a few addons that are script like or something like for example nombat , and some posing tools

**Comment by Fabian272** [comment]
****Issue solved, it was an addon conflict with Maestro admin mod****

**Comment by AlexanderB2109** [comment]
I'm having this exact same problem but I can't figure out what addon is causing it. https://steamcommunity.com/profiles/76561198347577457/myworkshopfiles/?appid=4000&browsefilter=mysubscriptions Here's my addons list, hopefully it shows up correctly. Does anyone know which of these conflict with PAC3? Sorry to necrothread and sorry for being annoying.

**Comment by thegrb93** [comment]
Disable half your addons and see if it gets fixed. If not, disable another half of the remaining ones, otherwise, re-enable half of the ones you disabled. Repeat until you find the culprit.
