### ISSUE TITLE
Cvar to autodisable if FPS gets too low.

### ISSUE THREAD

**Issue by LuaTenshi** [CapsAdmin/pac3#618]
Often you're playing with PAC and you're running at a consistent FPS but suddenly a bunch of people run up to you with complex PACs and your FPS tanks. It would be nice to just automatically disable PAC when a huge fps drop like that occurs. Maybe then it could also enable it again once your FPS has stabilized.

**Comment by CapsAdmin** [comment]
see max render time in settings

**Comment by LuaTenshi** [comment]
I've set that but I'm not sure if that's what I'm looking for. I'm looking for something that's based on FPS not some render time I know nothing about. Plus it would be nice to disable PAC even when something that's not PAC is hitting your FPS hard.

**Comment by Hazbelll** [comment]
Max Render Time's not very good anyway as it's just a vicious cycle of: PAC Hits Max Render Time > PAC Turns off > PAC No Longer Hits Max Render Time > PAC Turns On > Repeat.

This causes more harm than good as it often just crashes your game from re-rendering PACs so quickly in such little time. OP is asking for a real solution, not a half-assed one.

**Comment by thegrb93** [comment]
That is strange behavior. Might be better to permanently disable the outfit until its worn again or something.

**Comment by CapsAdmin** [comment]
PAC shouldn't crash gmod by rendering an outfit in just one frame. There can be many reasons an outfits render time is high for which is why it's checked once in a while. It's an intended feature. (checks randomly every 2-4 seconds)
