### ISSUE TITLE
More detailed max render time options

### ISSUE THREAD

**Issue by NanoAi** [CapsAdmin/pac3#619]
Some PACs cause major FPS drops, for example a person can be running a steady 100+ FPS, then have their FPS drop to just below 30 FPS when someone with a complex PAC gets close to them.

**Comment by Noiwex** [comment]
This topic was beaten to death 3 years ago, I don't think it's worth bothering with it.

**Comment by CapsAdmin** [comment]
I've edited this issue to be about FPS related control only as #209 mentions the rest
