### ISSUE TITLE
Pac3 is broken - does anyone know how to fix it?

### ISSUE THREAD

**Issue by proximityblue** [CapsAdmin/pac3#621]
My Pac3 is broken, and I don't know how to fix it.
My Pac (which I spent ages working on) had to be deleted due to all my models coming up as errors, even the default model was an error.
![image](https://user-images.githubusercontent.com/38113084/38384508-3c8d3f86-3907-11e8-9d95-daa951eecebf.png)
I added a model and it came out looking like this.
I also can't use the Pac3 jiggles (clothing) as it has been deleted from the addon menu.
(e.g. capes and trenches, and also the default male and female models)

Does anyone know how to fix this? 

P.S: I can't use Pac AT ALL in singleplayer, which kinda sucks

**Comment by CapsAdmin** [comment]
Instead of the error model you get the popcan. Are all the models like this? Can you spawn them from the spawnmenu as props in sandbox?

**Comment by lilggamegenius** [comment]
are you using the workshop version or the git version? (also please tell me you still have copies of your pacs because its probably not the pacs themselves that are broken)

**Comment by roboderpy** [comment]
![def](https://i.dbot.serealia.ca/2018/04/firefox_2018-04-08_06-24-55.png)

Something overrides `util.IsValidModel` and do it wrong.
