### ISSUE TITLE
Fix tpose for Pony Player Models?

### ISSUE THREAD

**Issue by michaelfirestar** [CapsAdmin/pac3#622]
this may have been very long time ago but tpose used to work with PPM (Pony Player Models) but now if you use tpose it just sucks your body into a little ball that you can't work with

![image](https://user-images.githubusercontent.com/4983498/38459781-d303bf04-3a73-11e8-9bb4-4f9c42ba238d.png)

Please fix this maybe?

**Comment by thegrb93** [comment]
It's a problem with the model, not pac.
