### ISSUE TITLE
PAC3 might have interference with other 3d rendering.

### ISSUE THREAD

**Issue by rebel1324** [CapsAdmin/pac3#624]
When I assign material to the model, other 3d rendering hook's model's submaterial get swapped by the pac's overriding material.

pac data: https://pastebin.com/ACvHyWVM

![image](https://user-images.githubusercontent.com/2784192/38604418-47f7dc20-3dab-11e8-9652-5b6e726d670d.png)
![image](https://user-images.githubusercontent.com/2784192/38604423-4e388b8e-3dab-11e8-9de3-bc039ccbccfd.png)

**Comment by thegrb93** [comment]
What mod is rendering the shield?

**Comment by rebel1324** [comment]
well i assume it's related with http://wiki.garrysmod.com/page/render/MaterialOverrideByIndex is not returning nil in PAC3

**Comment by thegrb93** [comment]
It does look like model2 isn't resetting the override correctly though.

**Comment by thegrb93** [comment]
Looks like model is using MaterialOverride and not resetting it too though.

**Comment by roboderpy** [comment]
Fixed in develop
