### ISSUE TITLE
I redownloaded gmod and lost all my pacs, any way to restore it?

### ISSUE THREAD

**Issue by berke33110** [CapsAdmin/pac3#626]
So, I just had to redownload Gmod because my game was crashing everytime, i forget to backup pac3 files now i lost all my pac's, is there is any way to restore them back? or will i lose all of my years?

**Comment by roboderpy** [comment]
You lost them.

**Comment by Techbot121** [comment]
The next time you reinstall make sure to backup your garrysmod/data/pac3/ folder and you should be fine.
