### ISSUE TITLE
Model2 submat issue

### ISSUE THREAD

**Issue by EggrollWireson** [CapsAdmin/pac3#627]
https://github.com/CapsAdmin/pac3/commit/434bf9c6a46f22bd1fdf19e3ece2ac4b630f33a2

This could be causing submaterials in model2 to be replaced by nil, despite being present in the outfit file.

["Materials"] = ";egon_ringbeam"
In-game: https://i.imgur.com/JdphwZ0.png

**Comment by CapsAdmin** [comment]
the idea is to reset submaterials when you change the model

**Comment by EggrollWireson** [comment]
materials reset on wear, not on model change @CapsAdmin

**Comment by CapsAdmin** [comment]
They have been for a long time until today. The commit you linked to should fix this.

**Comment by EggrollWireson** [comment]
it did the opposite for me

**Comment by CapsAdmin** [comment]
In model2 or entity2? I see there's some leftover code in entity2 that does the same in a think function for some reason.

Sub materials are supposed to be set to blank when the user changes the model. In the past this was done on wear but the logic for this was bad. Now there shouldn't be any way (except for entity2) that it will reset dynamically.

**Comment by EggrollWireson** [comment]
model2, it works in "before patch" version and resets my mats to nil after the patch

**Comment by CapsAdmin** [comment]
can you send me an example outfit and tell me the steps needed to reproduce the bug?
