### ISSUE TITLE
PAC4 Not uploading custom models

### ISSUE THREAD

**Issue by TanzaKnight** [CapsAdmin/pac3#628]
I have seen three different methods on how to use the files for a model from an addon, and making it to where you would not need a content pack for people to see the model you are using like they would need to in PAC3.

No matter what happens, no matter what steps I take, and no matter how closely I look at the issue... **nothing** works for me. I replicate exactly how others are doing this, even using the exact same model and addon, and it does not work. I modify the dropbox link correctly, I set the file and folder paths correctly, I add all of the necessary files inside of a folder correctly, yet nothing seems to be working for me.

If anyone could help me figure out this issue, I would be eternally grateful.

**Comment by CapsAdmin** [comment]
What does the console say when you wear? Can you share the link you're trying to use?

**Comment by TanzaKnight** [comment]
I figured out the issue. When compressing the finished folder into a zip, it **has** to be in the .zip format. I was using the .7z format, that was the issue.

**Comment by CapsAdmin** [comment]
great
