### ISSUE TITLE
Arrow Keys

### ISSUE THREAD

**Issue by UnknownShifter** [CapsAdmin/pac3#629]
So, one problem I've been encounter is:  whenever I click on anything that had a text model path, such as setting the model or texture of an object, I used to be able to use my arrow keys to jump to a certain digit, and omit it in case I screwed up.  Now, when I use my 'left' or 'right' arrow key to navigate through the path, it'll un-select itself.  Do you think that y'all could make a change to the code so it _doesn't_ do that anymore?  Cheers.

**Comment by CapsAdmin** [comment]
I fixed this 3 days ago. Reopen if it's still an issue
