### ISSUE TITLE
Projectiles aim part name field clearing on wear (master branch)

### ISSUE THREAD

**Issue by pingu7867** [CapsAdmin/pac3#632]
I'm confused as to why that happens only now, whereas it worked fine before. Why does pac behave that part-selection fields aren't permanent, and they clear on cloning? It also does this with beam end point names. 

I would have thought that if pac loads a part and the part has some part name field it refers to, it would just take the name and search the part that has it to find which specific part is "internally" in the memory or something, and I see the aim part name field with the target part's name there in the outfit text file. The information is there, and there's no obvious reason that it should be malfunctioning, given that pac has the information needed to make these parts function. I'll provide more information if needed.

[bugtesting3.txt](https://github.com/CapsAdmin/pac3/files/1935123/bugtesting3.txt)

**Comment by CapsAdmin** [comment]
fixed
