### ISSUE TITLE
Entity Issues

### ISSUE THREAD

**Issue by scoutmcfly** [CapsAdmin/pac3#637]
In the experimental entity section, whenever I put a link to an mdl file and enter it, the model blinks in for half a second and then switches back to the original playermodel. I don't know if I'm doing something wrong or if it's a bug, but it is an issue. Is there a fix to this?

**Comment by scoutmcfly** [comment]
I've tried the same model on 3 different servers, 1 not even having enhanced playermodels. I've tried on The Great Adventure Dark RP, Lenny Face Gaming Sandbox #1, and The Official Pac3 Server with enforce off. I'm not sure what else could be interfering.

**Comment by thegrb93** [comment]
Need the model to test it
