### ISSUE TITLE
PAC3 blacklist does not work

### ISSUE THREAD

**Issue by Uberfuchs** [CapsAdmin/pac3#640]
To reproduce I joined the server with PAC3 disabled, and PAC3 blacklist enabled.

I enabled PAC3.

PAC3 from players loaded.

![pac3_blacklist_not_working](https://user-images.githubusercontent.com/13978129/39394064-3b7c53a2-4a9b-11e8-9f34-a059c1c2dcb2.png)

**Comment by roboderpy** [comment]
Not for now.
