### ISSUE TITLE
Shared Materials are separate in viewmodel and other entity groups.

### ISSUE THREAD

**Issue by EggrollWireson** [CapsAdmin/pac3#641]
Materials used by separate visual groups aren't being initialized on outfit upload.
The texture initializes after reloading the outfit twice, one in first person mode, one in third person.

[Example](https://i.imgur.com/7qS0dYR.png)

**Comment by thegrb93** [comment]
You're saying those other groups can't access the toolgun_screen material until the outfit loads twice?

**Comment by EggrollWireson** [comment]
tfw reply after 4 months of waiting.
yes, if you didn't understood the problem, materials on the 1st person are broken till i load 3rd person parts.

**Comment by CapsAdmin** [comment]
I think this is taken care of with the new parts. I can't reproduce the bug at least.
