### ISSUE TITLE
Multiple lighting issues with models.

### ISSUE THREAD

**Issue by EggrollWireson** [CapsAdmin/pac3#642]
Any model, be it mdl or mdl2 appears have a broken light layering order.

1. Multiple lights, flashlight adds one projected texture, light glitches out.
2. No lights besides point_light in scene, mdl2 does not display flashlight texture.
3. No light sources, flashlight "sticks" to the last pos it was seen enabled.

https://dl.dropboxusercontent.com/s/f6yj8wg9vevlt6r/pac3_glitch_lights.webm

**Comment by CapsAdmin** [comment]
Isn't this just a bug in gmod when drawing models manually? It's why this feature is off by default.

**Comment by thegrb93** [comment]
Is this still an issue? I know a lot has been done to the multicore rendering since this issue was created.

**Comment by EggrollWireson** [comment]
Yes, the "sticky" lightmaps on dynMeshes are still an issue. Hadn't noticed any lights flickering though.

**Comment by thegrb93** [comment]
I'm not sure how the flashlight/projected texture code works, but I can look later. If it's something beyond our control, I'll add the thirdparty label again.

**Comment by EggrollWireson** [comment]
Might be that renderer can't access the buffer for all of the shadow maps on a model in multicore mode.
Or the index for the maps is broken.

**Comment by CapsAdmin** [comment]
The rendering in pac is fundamentally flawed when it comes to this. I'll fix this at some point.
