### ISSUE TITLE
Part clearing

### ISSUE THREAD

**Issue by SamsonYBC** [CapsAdmin/pac3#644]
I'm not sure, whats causing this, but whenever i try to wear parts, Saving is fine, but all the pac parts clear, like ive not loaded anything up, when i have. could this be because i have the Github and Workshop version of Pac3? 

I've tested on another server, a friends private one, it works there. so maybe its just PAC3 on the Official server

**Comment by SladeXanthas** [comment]
Do you mean you have both the Github and Workshop version installed? You only want to have one version of PAC installed at a time, lest conflicts happen.

**Comment by roboderpy** [comment]
Having both versions installed will produce undefined behaviour, please use only one version of pac3 (preferrably git version)
