### ISSUE TITLE
Custom models are fully black when I join a server

### ISSUE THREAD

**Issue by SisterAlbethra** [CapsAdmin/pac3#650]
Every time I've joined a server the custom models are entirely black and I am unsure why.

**Comment by thegrb93** [comment]
I have a theory why this happens. I think it might be because your gmod client already had the custom materials created from a previous session, so creating them again fails (or causes some strange behavior).

**Comment by thegrb93** [comment]
And yes, created material names persist across sessions.

**Comment by SisterAlbethra** [comment]
Thank you!
 I will try this and sees what happens!

**Comment by thegrb93** [comment]
My comment was describing an internal problem with gmod/pac3. I don't think it'll be able to help you. Sorry for the confusion.

**Comment by SisterAlbethra** [comment]
It's fine, do you have any ideas how to fix it though?

**Comment by thegrb93** [comment]
Material creation would need to check if a material of the same name exists first, or make the material names unique based on time or something. That's assuming my theory is right. I'll test it sometime soon.

**Comment by SisterAlbethra** [comment]
So it appears only one pac does this while all the others are just fine.

**Comment by roboderpy** [comment]
If @thegrb93 is right this should be fixed on develop branch. Comment if not.

**Comment by thegrb93** [comment]
Another thing it could be is the $flags of the material not being correct for some reason. I had run into it with starfall before. Missing MATERIAL_VAR_VERTEXCOLOR was the issue I had. I recently documented them https://developer.valvesoftware.com/wiki/Material_Flags

**Comment by SladeXanthas** [comment]
Make sure that your Dropbox links have dl=1 and not dl=0. This behaviour was changed as of the newer versions of PAC.

**Comment by thegrb93** [comment]
I don't think that's it. I'll let you know if it happens again or not though.

**Comment by roboderpy** [comment]
Are you using custom textures? If so, are you on chromium branch? On chromium branch there is some issue with :IsLoading(), but it is already fixed

**Comment by thegrb93** [comment]
Probably fixed by https://github.com/CapsAdmin/pac3/commit/a197a1d8aa5b8b18f0521c5fad47d5e2202e2002
