### ISSUE TITLE
QOL Addition Request

### ISSUE THREAD

**Issue by UnknownShifter** [CapsAdmin/pac3#653]
So, on the older versions of the PAC Editor(like workshop), long lists often had a grey bar between long selections, like holdtypes.  Could something similar be implemented?  It's often dreadful at times working with holdtypes and other things without hunching over my computer like I'm from Notre Dame.

![20180530112216_1](https://user-images.githubusercontent.com/14335188/40736756-1e33321e-63fc-11e8-9ee3-8f71cc6fe8db.jpg)

**Comment by CapsAdmin** [comment]
This should still be there. Are you using a derma skin?
