### ISSUE TITLE
Autoload no longer... auto loads

### ISSUE THREAD

**Issue by lilggamegenius** [CapsAdmin/pac3#657]
For about a month or two, the autoload outfit on pac does not load on startup. There appears to be no errors from pac or anything else related. Tested with both the normal branch and develop. Everything else seems to function properly as well.

**Comment by thegrb93** [comment]
It seems to work for me. You have data/pac3/autoload.txt right?

**Comment by lilggamegenius** [comment]
yes, if i load autoload manually, it loads fine.

**Comment by roboderpy** [comment]
I've changed a bit autoload code on develop branch, now should work properly

**Comment by lilggamegenius** [comment]
Yeah, i checked out the develop branch on my server and confirmed it working

**Comment by pingu7867** [comment]
seems to load when you first move

**Comment by joeyjumper94** [comment]
so uh, when will this be fixed on the workshop?
