### ISSUE TITLE
Ammunition proxies don't work in viewmodel

### ISSUE THREAD

**Issue by Vuthakral** [CapsAdmin/pac3#661]
I have no idea how this proxy actually works but I'd presume it's because it tries to get the entity's current/max ammo and etc, but since the current entity is viewmodel it doesn't have one.

Working fine in third person: https://i.imgur.com/9KRWcM3.gifv
Doesn't work in first person: https://i.imgur.com/6bb7VcG.gifv

Suggestion for this: Possibly a separate optional field for "target" or "input"? e.g. you could identify "self" and have it as "self" by default similar to how the group works? (Keep in mind I have very little knowledge of how glua works so this could be impossible for all I know)

**Comment by roboderpy** [comment]
Fixed in develop
