### ISSUE TITLE
PAC3 causes lag in TTT spectator camera

### ISSUE THREAD

**Issue by moschetto** [CapsAdmin/pac3#662]
Whether it's coupled with Pointshop 2 or not, including PAC on the server results in some significant jitter and lag in the spectator camera in TTT. When you're alive, it's fine. Just looking to get that jitter resolved, if possible.

**Comment by roboderpy** [comment]
Try with pac_enable 0 while in spectator mode

**Comment by thegrb93** [comment]
Can you cl_showerror 1 and see if any errors show? Jitter sounds like prediction error.
