### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by proximityblue** [CapsAdmin/pac3#664]
So, I was looking through my Garry's Mod folder and found PAC3 in my addons folder, but when I try and find it in Garry's Mod it's not there.
![image](https://user-images.githubusercontent.com/38113084/41507119-dc976b6e-7223-11e8-80ef-c765a8a78f6f.png)
At the moment, PAC3 only works in multiplayer servers, not in singleplayer. Is there any way to make it work in singleplayer?
Thanks.
(P.S. I'm sorry if there isn't enough information but this is all I can say about it at the moment. I'm not an expert in PAC3.)

**Comment by FarukGamer** [comment]
You might just forgot to subscribe it or you used the Github version.

**Comment by proximityblue** [comment]
I just downloaded it, restarted Garry's Mod and now PAC3 works fine. 
Thank you! :D
