### ISSUE TITLE
Viewmodel Weapon

### ISSUE THREAD

**Issue by pointhurt** [CapsAdmin/pac3#668]
I followed the tutorial about changing your viewmodel weapon. But what I wanna know is if there's a way to hide the original viewmodel weapon. Because honestly, having the model I want over the original model looks pretty dumb.

**Comment by Vuthakral** [comment]
Just use entity bones, set them to the weapon bones and set their size to 0.1 or 0.01. If you have parts attached to it do not set the size to 0 or else they can start flicking and rotating at random.

**Comment by pointhurt** [comment]
I can't find the weapon bone.

**Comment by pointhurt** [comment]
Nevermind, I figured it out.

**Comment by thegrb93** [comment]
I think the 'Entity' part has options that allow you to hide the viewmodel. If not, then the bone scaling idea should work too.
