### ISSUE TITLE
Per-entity draw distances are inverted.

### ISSUE THREAD

**Issue by TomatoCo** [CapsAdmin/pac3#672]
on lines 743 to 745 of core/client/part_pool.lua one of the distance checks is inverted.

lines 743 and 745 compare that the entity's distance is less than or equal to the permissible draw distance, but line 744 checks that the entity's distance is GREATER THAN or equal to the permissible draw distance. The code is written as the permissible distance is less than or equal to the entity's distance, which has the two values being compared inverted from the other distance checks.

(also generally the distance checks are inconsistent, one checking that the distance is not equal to 0 then checking if it's equal to zero, with the other checking if it's not nil and then checking if it's less than or equal to zero. in practice it's the same result but could be cleaner).

This was first noticed when an entity had SetPACDrawDistance(1500) performed on it and the client's draw distance was set to 500. At close range the PAC parts drew, but as the client backed up the parts stopped drawing. After a certain distance, they started drawing again. Due to the erratic movement of the entity this was originally chalked up to janky rendering in general, but testing narrowed down on distance being the only factor and after staring at the draw conditional for a while this irregularity jumped out at me.

**Comment by roboderpy** [comment]
Check develop branch for distance code and try your stuff here, it should work now
