### ISSUE TITLE
ply:AttachPACPart

### ISSUE THREAD

**Issue by YourSenpaiElite** [CapsAdmin/pac3#673]
Other people don't see outfits what attached using ply:AttachPACPart. Only LocalPlayer can see it.
Tested on workshop version and master version.

**Comment by YourSenpaiElite** [comment]
Part of my code
`local ply = LocalPlayer()
if not ply.AttachPACPart then 
pac.SetupENT( ply )
ply:SetShowPACPartsInEditor( false )
end
ply:AttachPACPart( outfit, ply )`

**Comment by lilggamegenius** [comment]
What about the develop branch?

**Comment by YourSenpaiElite** [comment]
![screenshot_7](https://user-images.githubusercontent.com/32411308/42738049-be1726a0-8896-11e8-9620-f821bfb27002.png)
Left - Local Player, Right - Other Player
Still don't show up
