### ISSUE TITLE
Pac3 Stealer Found !!!!

### ISSUE THREAD

**Issue by tokelpl** [CapsAdmin/pac3#677]
This is the code what i found and adapted to work please repair it:

`local parts = select(2,debug.getupvalue(pac.GetLocalParts,1))
parts[uid of localplayer] = parts[uid of target]
`

Client Side code

**Comment by thegrb93** [comment]
pac data can be read an loads of ways, this isn't unique at all or fixable.

**Comment by roboderpy** [comment]
We are all aware of all steal methods, but it is something we can't fix (and it will never be fixed, removing debug library isn't a good thing to do). Sorry. You have to deal with these players on your own. And moreover - almost all users use basic hacks to workaround sv_allowcslua and therefore can be catched even with hand made anticheat
