### ISSUE TITLE
Custom animation part broken: editor frames initializing as a nil value or something?

### ISSUE THREAD

**Issue by pingu7867** [CapsAdmin/pac3#682]
The following error message when creating or attempting to select a custom animation part

[ERROR] addons/pac3-master/lua/pac3/editor/client/animation_timeline.lua:374: attempt to perform arithmetic on a nil value
  1. Init - addons/pac3-master/lua/pac3/editor/client/animation_timeline.lua:374
   2. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
    3. Open - addons/pac3-master/lua/pac3/editor/client/animation_timeline.lua:240
     4. v - addons/pac3-master/lua/pac3/editor/client/animation_timeline.lua:324
      5. Run - lua/includes/modules/hook.lua:84
       6. Call - addons/pac3-master/lua/pac3/editor/client/init.lua:232
        7. Call - addons/pac3-master/lua/pac3/editor/client/parts.lua:115
         8. DoClick - addons/pac3-master/lua/pac3/editor/client/parts.lua:306
          9. OnMouseReleased - lua/vgui/dlabel.lua:232
           10. unknown - lua/vgui/dmenuoption.lua:77

[ERROR] addons/pac3-master/lua/pac3/editor/client/animation_timeline.lua:87: attempt to index field 'frame' (a nil value)
  1. Stop - addons/pac3-master/lua/pac3/editor/client/animation_timeline.lua:87
   2. Close - addons/pac3-master/lua/pac3/editor/client/animation_timeline.lua:214
    3. v - addons/pac3-master/lua/pac3/editor/client/animation_timeline.lua:326
     4. Run - lua/includes/modules/hook.lua:84
      5. Call - addons/pac3-master/lua/pac3/editor/client/init.lua:232
       6. TrySelectPart - addons/pac3-master/lua/pac3/editor/client/logic.lua:63
        7. unknown - addons/pac3-master/lua/pac3/editor/client/panels/tree.lua:500

Timer Failed! [pace_refresh_tree][@addons/pac3-master/lua/pac3/editor/client/panels/tree.lua (line 495)]

**Comment by thegrb93** [comment]
Is this still happening? I haven't seen any error. I assume it's fixed now.
