### ISSUE TITLE
Custom Animation: Gesture Animation Type Broken

### ISSUE THREAD

**Issue by Tekxephi** [CapsAdmin/pac3#688]
i just installed this to my game from pac3 on the workshop, and now all my animations are broken.

 with gesture, the animation shouldnt stop playing at the end but keep playing the end part(like pac3 on the workshop).
 we want to use pac4 because it has better data tables, but knowing it makes my pac broken, it is unusable

**Comment by Yagira** [comment]
> with gesture, the animation shouldnt stop playing

That's exactly what it should do, gestures only play once. What you're looking for is a stance.

> TYPE_GESTURE = 0 -- Gestures are keyframed animations that use the current position and angles of the bones. **They play once** and then stop automatically.

> TYPE_STANCE = 2 -- Stances are keyframed animations that use the current position and angles of the bones. **They play forever** until manually stopped. Use RestartFrame to specify a frame to go to if the animation ends (instead of frame 1).
