### ISSUE TITLE
NULL entity error

### ISSUE THREAD

**Issue by Etothepowerof26** [CapsAdmin/pac3#689]
Happens rarely when someone leaves, usually lasts for like 10 seconds
 
[PAC3] lua/pac3/core/client/parts/material.lua:426: Tried to use a NULL entity!

1. UniqueID - [C]:-1
   2. UpdateMaterial - lua/pac3/core/client/parts/material.lua:426
    3. OnEvent - lua/pac3/core/client/parts/material.lua:438
     4. CallEvent - lua/pac3/core/client/base_part.lua:912
      5. CallEvent - lua/pac3/core/client/base_part.lua:914
       6. CallEvent - lua/pac3/core/client/base_part.lua:914
        7. SetMaterial - lua/pac3/core/client/parts/model.lua:745
         8. unknown - lua/pac3/core/client/parts/material.lua:456
          9. CallRecursive - lua/pac3/core/client/base_part.lua:589
           10. Deattach - lua/pac3/core/client/base_part.lua:935
            11. Remove - lua/pac3/core/client/base_part.lua:980
             12. RemoveChildren - lua/pac3/core/client/base_part.lua:684
              13. Remove - lua/pac3/core/client/base_part.lua:986
               14. RemoveChildren - lua/pac3/core/client/base_part.lua:684
                15. Remove - lua/pac3/core/client/base_part.lua:986
                 16. RemoveChildren - lua/pac3/core/client/base_part.lua:684

**Comment by thegrb93** [comment]
Your line numbers aren't matching up with the current source files. Are you using the develop branch?

**Comment by Etothepowerof26** [comment]
From looking at the code, it isn't checking if `self:GetPlayerOwner()` is valid
```
function PART:UpdateMaterial(now)
	self:GetMaterialFromParent()
	for key, val in pairs(self.StorableVars) do
		if self.ShaderParams[key] or self.TransformVars[key] then
			self["Set" .. key](self, self["Get"..key](self))
		end
	end

        --here is where its erroring
	pac.UpdateMaterialParts("update", self:GetPlayerOwner():UniqueID(), self, self.Materialm)
end
```

**Comment by thegrb93** [comment]
Try updating, this is the code in the latest version.
```lua
function PART:UpdateMaterial(now)
	if not self:GetPlayerOwner():IsValid() then return end
	self:GetMaterialFromParent()

	for key, val in pairs(self.StorableVars) do
		if self.ShaderParams[key] or self.TransformVars[key] then
			self["Set" .. key](self, self["Get"..key](self))
		end
	end

	pac.UpdateMaterialParts("update", self:GetPlayerOwner():UniqueID(), self, self.Materialm)
end
```
