### ISSUE TITLE
Chromium branch breaks urltex

### ISSUE THREAD

**Issue by homonovus** [CapsAdmin/pac3#690]
All urltex will either not apply or not download while on the chromium branch of gmod

**Comment by EggrollWireson** [comment]
say thanks to willox. after i suggested not to refresh the page to make them load, he broke 'em further

**Comment by willox** [comment]
np

**Comment by willox** [comment]
the options are to either add some functions to HTML panels that'll call back when the rendering has complete, or to expose something similar to urltex in gmod by default

i think the latter is best

**Comment by thegrb93** [comment]
I kind of prefer HTML panel though because if lets you layout the image however you want @willox

**Comment by willox** [comment]
There's no way to tell if it has finished rendering. It probably only works with Awesomium because Awesomium is slower to tell you when the page has loaded.

**Comment by CapsAdmin** [comment]
Getting the texture data from a webview is stupid anyway. It's probably best to make it use the new method (download image to data and load) if possible. There might be some visual differences like better quality and texture clamp/repeat though

**Comment by roboderpy** [comment]
Still work for me (both in PAC3 and PPM/2) and i don't think Chromium branch will not work for others

**Comment by roboderpy** [comment]
Fixed
