### ISSUE TITLE
Pac editor shortcuts work even when editor is not focused

### ISSUE THREAD

**Issue by lilggamegenius** [CapsAdmin/pac3#693]
The new Pac editor shortcuts added help speed up workflow but it doesn't seem to check if the editor is focused or not. meaning if you have something bound to delete and try to use that bind while the editor is open but unfocused it will still delete the selected part. This is really frustrating because in order to use a bind that's mapped to something in the editor, i have to fully close pac instead of just hiding the editor.

**Comment by roboderpy** [comment]
Fixed
