### ISSUE TITLE
Pac3 panel/tree.lua error

### ISSUE THREAD

**Issue by BlueCrescentMoon** [CapsAdmin/pac3#695]
Um, I've never seen pac do this. Can't click on anything besides the top bar and it automatically moves one by one to the bottom item. I use the workshop version of Pac3.

**Console error**
[ERROR] addons/pac3-develop/lua/pac3/editor/client/panels/tree.lua:37: Tried to use invalid object (type Panel) (Object was NULL or not of the right type)
  1. LocalToScreen - [C]:-1
   2. unknown - addons/pac3-develop/lua/pac3/editor/client/panels/tree.lua:37

Timer Failed! [Simple][@addons/pac3-develop/lua/pac3/editor/client/panels/tree.lua (line 36)]

**Screenshot of the error in action**
[http://puu.sh/BlvEJ.jpg](url)

**Comment by thegrb93** [comment]
Try the develop version. The workshop version shouldn't even exist for how behind it is.

**Comment by roboderpy** [comment]
he do use develop version

**Comment by thegrb93** [comment]
But he said `I use the workshop version of Pac3`

**Comment by thegrb93** [comment]
Oh I see in the error now

**Comment by roboderpy** [comment]
He plays on our server AND error traceback tells you the version

**Comment by thegrb93** [comment]
Ya, I noticed

**Comment by Cynosphere** [comment]
still an issue, im blaming the fact that pac favors the client's version when it honestly shouldn't.

don't:clap:trust:clap:the:clap:client

**Comment by thegrb93** [comment]
What do you mean? Server lua takes precedence over client.

**Comment by roboderpy** [comment]
Clients can override anything on their side since they are 100% compromised. 

And FYI, it loads client's version when sv_allowcslua is 1 (which is compromised too) and only on pac_restart
