### ISSUE TITLE
Setting group owner to an npc and wearing the outfit with an 'experimental entity' part makes your playermodel the npc's model

### ISSUE THREAD

**Issue by JitZub** [CapsAdmin/pac3#696]
If i spawn a zombie, give him a pac costume, then set his entity size as 2, it also changes my size to 2

**Comment by thegrb93** [comment]
I couldn't get the size bug to work, but I found a different one with the experimental entity part

**Comment by CapsAdmin** [comment]
There seems to be a few problems. First of all OnHide is not being called when the owner of the part has changed, so this causes the entity not to revert changes on its old owner.

Another problem is that some of the size and model code is designed for players only. I've changed reworked this now so it works on any entity that you can modify.
