### ISSUE TITLE
Flex only works for players/npcs but not ragdolls

### ISSUE THREAD

**Issue by datHunter007** [CapsAdmin/pac3#700]
I was editing my Playermodel face with Flex, but everytime i change it, it goes back to normal.
It goes from: "Edited Face --> Normal Face" in two or three seconds. Can it be fixed or do i have to use other things (Event, Proxy etc.)?
![20180901201601_1](https://user-images.githubusercontent.com/42897020/44948879-3ff7e100-ae26-11e8-9180-7980e7e0f7df.jpg)
![20180901201548_1](https://user-images.githubusercontent.com/42897020/44948882-5140ed80-ae26-11e8-8d57-a54a3112aad2.jpg)

**Comment by thegrb93** [comment]
There's a chance this could be an addon conflict. I'll test it and see

**Comment by thegrb93** [comment]
Seems to be a conflict from sandbox itself,
	3: Line 281	"MouthMoveAnimation"		gamemodes/base/gamemode/animations.lua
	4: Line 233	"nil"		gamemodes/base/gamemode/animations.lua

**Comment by thegrb93** [comment]
Just need to add a hook to MouthMoveAnimation that returns false when a mouth flex is active

**Comment by thegrb93** [comment]
The base MouthMoveAnimation is pretty awful for performance. Jeez

**Comment by thegrb93** [comment]
I'll see whats making the rest of the face not work

**Comment by thegrb93** [comment]
Ok it seems SetFlexWeight needs to be ran every frame or it returns to the normal weight.

**Comment by thegrb93** [comment]
Needs to be ran in UpdateAnimation for players

**Comment by thegrb93** [comment]
Note: It seems to be impossible for ragdolls to have their flex weight set in clienside so this part will never work for those.

**Comment by roboderpy** [comment]
It is possible to do so, reopen and assign me, i will do it eventually when i get back into gmod

**Comment by thegrb93** [comment]
Does it work now or no?

**Comment by thegrb93** [comment]
The workshop version stays behind this version for a long time. Try this version instead.

**Comment by Techbot121** [comment]
uh workshop got updated like 10 days ago

**Comment by thegrb93** [comment]
And before that, its last update was like 2 years ago.

**Comment by thegrb93** [comment]
Which is still behind this version. What's your point? Besides, it was 2 years ago before that update when it was last updated.

**Comment by thegrb93** [comment]
No, the workshop version doesn't have this fix https://github.com/CapsAdmin/pac3/commit/537f446c2ba9f7de7d7aa59604b8a1fe11336bd9

**Comment by roboderpy** [comment]
I added flex support for in-pac ragdolls. About serverside ragdolls - https://github.com/CapsAdmin/pac3/issues/700#issuecomment-417898012

**Comment by thegrb93** [comment]
Nice
