### ISSUE TITLE
pac3 is not showing for other players

### ISSUE THREAD

**Issue by feederthe3rd** [CapsAdmin/pac3#701]
yes i am wearing it but it does not show for other players

**Comment by thegrb93** [comment]
Loading the outfit isn't enough, you have to actually apply it so that the server receives it which is done with the "Wear" control. If people still can't see it then they need to check their pac options and make sure they have pac enabled.

**Comment by feederthe3rd** [comment]
yes i tried doing that nothing happned

**Comment by thegrb93** [comment]
Do you see others' outfits? Do they see others' outfits?

**Comment by feederthe3rd** [comment]
yeah nvm mate i fixed it but removing the whole pac3 from my pc

**Comment by thegrb93** [comment]
ok good job
