### ISSUE TITLE
Material Refract part non-functional.

### ISSUE THREAD

**Issue by Avernakis8** [CapsAdmin/pac3#703]
Big bad. Idk if this has been posted yet but material refract part under experimental doesn't do anything atm apparently, when put on a model it just turns said model invisible and attempts to tick flags for model, etc. or adding textures to it doesn't do anything either, it remains invisible no matter what.

**Comment by bluemetaknight** [comment]
The refract material part is designed to be used on sprites from my experience. If you want to achieve the same effect on a 3d part, you have to just use the material 3d part with a normal map and the TF2 Spy cloak effect.

**Comment by Avernakis8** [comment]
I'm bumping this because this is still an issue that I've been wanting fixed for a while now.
The only solution currently is having to go through the whole .mdl making process in a modelling program and creating refract .vtfs/.vmts to work with the .mdl but of course that means it'll only work with those materials and that exact .mdl file. Many of my pacs that I've been meaning to update with this exact thing have hit a dead end because of this. ahjsdgahjsdgashd pls
