### ISSUE TITLE
PAC3 props do not show up once worn.

### ISSUE THREAD

**Issue by JevrathTheDragon** [CapsAdmin/pac3#705]
Right, so I have looked over the FAQ and found nothing on this. I have also spent time with the people on the discord for help to no avail. They suggested using both GitHub versions, disabling all add-ons, allow gmod through the firewall, allow gmod to access everything, and using console commands. None of these worked and they said try the git hub so I am. Long story short I work for a server and the PAC3 does not work for some reason. When you attempt to WEAR a pac it goes invisible and removes any and all fields in the menu. I tried this on a single player map with the same problem. I get no script errors or anything. This has never happened before and the server dev and owner don't know what the fuck is going on. Is this a bug or has it changed so much to the point it has to be a very precise way? I find examples from PAC3 work fine but anything custom made disappears. You can also ADD props to the example and it works but you cannot make one from scratch. Here is a short video of what is happening. https://www.youtube.com/watch?v=1u36o5rU1Bc&feature=youtu.be

**Comment by thegrb93** [comment]
You might have something installed that is causing it. Maybe you have two pac versions installed that are conflicting. Make sure you only have the develop branch installed and if that doesn't work, remove all other addons to be sure it's not one of them causing the issue. Here's the link to the develop branch https://github.com/CapsAdmin/pac3/archive/develop.zip

**Comment by JevrathTheDragon** [comment]
I have tried this already. I forgot to state that in the whole list of stuff I have tried.

**Comment by thegrb93** [comment]
Try cleaning your gmod install or delete your config 'cfg' folder to get fresh config.

**Comment by JevrathTheDragon** [comment]
This problem has been fixed. Seems this was a temporary problem overall. Thank you for the help though. Guess it just didn't like me for the day haha.

**Comment by thegrb93** [comment]
You're welcome
