### ISSUE TITLE
sv_pac_webcontent_limit value persistent across servers

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#707]
Similar to #284 ?
Multiple people have reported that when they visit servers with sv_pac_webcontent_limit set to anything other than -1 and then switch to another server the value stays the same.

_also why is it sv_pac instead of pac_sv like all the other commands_

**Comment by roboderpy** [comment]
Duplicate of #284 and FCVAR_ARCHIVE & FCVAR_REPLICATED is still broken on client. But this bug can be workarounded on PAC3 side.

**Comment by roboderpy** [comment]
should be fixed in develop
