### ISSUE TITLE
Certain conditions cause gmod to still listen to attack buttons (mouse left and right) even in the editor

### ISSUE THREAD

**Issue by pingu7867** [CapsAdmin/pac3#709]
Unknown vanilla replication procedure.

One replication procedure is known with an addon conflict, which could be an investigation vector to discover the underlying causes of how this affects gmod, other functions in gmod that could also trigger this, and as such how it affects the pac editor. Entering Wiremod's wire_sound_browser_open command is one of the ways to cause the issue.

Changing the attack buttons to another makes no effect on attacking in the pac editor, so clicking causes our character to attack either way while in the pac editor.

pac_restart doesn't fix the behaviour.

**Comment by pingu7867** [comment]
I am uncertain if the issue is present without wiremod, because though I talked about this with someone in the pac discord help channel and the person didn't specify that it happened after using the wire sound browser (so it probably exists in vanilla pac usage), because I do not know a replication procedure for this issue, I cannot be certain about it being present without wiremod.

**Comment by lilggamegenius** [comment]
I think this might be related to #693

**Comment by thegrb93** [comment]
I don't think so, seems like gui conflict

**Comment by roboderpy** [comment]
I added code to prevent pranks like this done by other addons
