### ISSUE TITLE
Beam parts using material parts causes script errors

### ISSUE THREAD

**Issue by SirSputnik** [CapsAdmin/pac3#711]
Whilst I was working on a Pac I tried using the material3d part as the material for a beam part but when I assigned the material part to the beam a script errors pop up. this is probably a conflict between the materials on the beam and the new material part, so it would be great if this can be fixed or a new beam part gets put in the experimental tab.
![image](https://user-images.githubusercontent.com/44304413/47244952-51ee0d00-d3ef-11e8-9959-0ed45e10f983.png)

**Comment by thegrb93** [comment]
Fixed by https://github.com/CapsAdmin/pac3/pull/741 presumably
