### ISSUE TITLE
The buggy "don't wear for these players" menu.

### ISSUE THREAD

**Issue by Cl3ffy** [CapsAdmin/pac3#712]
The "don't wear for these players" menu keeps selecting players on its own at seemingly random times. Even if I then unselect these players they still wont be able to load my pac (requesting outfits doesn't help, restarting pac and then requesting shows mixed results) and they will usually get reselected again after some amount of time.
I have had these same problems ever since the feature was added to develop branch.

Recently the menu seems to have stopped adding players who join the server on the list and only shows those who were present at the time I join.

**Comment by thegrb93** [comment]
Do you have 'friends only' enabled?

**Comment by Cl3ffy** [comment]
Nope.

**Comment by thegrb93** [comment]
I'm wondering if there's a bug with cookies. I've never seen this behavior though.

**Comment by Cl3ffy** [comment]
Also, the "wear for friends only" setting doesn't seem to be doing anything. People who aren't in my friends are still able to see my pacs if I have it enabled. I'm not sure how long that setting hasn't been working for me.

**Comment by thegrb93** [comment]
Ok I fixed the cookie issue. I don't see the friend issue though...
