### ISSUE TITLE
When any player walks their pac jitters and moves arround

### ISSUE THREAD

**Issue by NinjasInMyBasement** [CapsAdmin/pac3#713]
I HAVE SEEN THE OTHER POST TELLING YOU TO CHANGE THE PARENT TO THE EYES INSTEAD OF HEAD. DID NOT FIX

For the user making the pac, everything seems fine, however for everyone else PAC jitters so incredibly bad when players move. It is almost like they are vibrating. When a player is still there is no problem, but otherwise it is really obnoxious. I dont ever recall this issue existing until I started my own server. I have no server settings which I think would affect PAC.

**Comment by AnyaOQuinn** [comment]
How often do you reboot your server or restart the map?

**Comment by NinjasInMyBasement** [comment]
I reboot the server a couple times a day.

**Comment by thegrb93** [comment]
Maybe this can help

sv_maxrate 0
sv_minrate 100000
sv_maxupdaterate 33
sv_maxcmdrate 33

**Comment by thegrb93** [comment]
Also from what I've read, some servers suffer from it and others don't. Maybe 3rd party mod? Strip your server of mods and see if pac works better after that.

**Comment by NinjasInMyBasement** [comment]
After my server dies down, I will see if a server with JUST PAC does it.
