### ISSUE TITLE
unable to un-blacklist someone.

### ISSUE THREAD

**Issue by niitsel** [CapsAdmin/pac3#714]
this has been an issue i've dealt with for a few months now, and i've pulled my hair out over trying to fix it more times than i'd like to admit.

i recall back then i was experimenting, trying to figure out what the entire blacklist feature was for when it first came out, and for some reason the person I ticked refused to untick. 
after everything, even after unticking it and restarting the game, it still turns back on.  i've tried searching in the files to see if that kind of info is stored locally but i've found nothing of the sort.

the only thing that i've discovered to work is for the "blacklisted" player to reconnect to the server, and i'd need to untick the box right when they connect so that they would be able to see it for the remainder of their stay on the server.

it persists across servers, i've found.

so, for these past few months my friend has never been able to see my PAC due to this. surely it can't be intended.

**Comment by thegrb93** [comment]
Related to https://github.com/CapsAdmin/pac3/issues/712 probably

**Comment by thegrb93** [comment]
I'll check it out

**Comment by thegrb93** [comment]
Ok I confirmed the cookie is not deleted. I'll look for why that is.

**Comment by thegrb93** [comment]
Should be fixed. lemme know if it isn't.

**Comment by thegrb93** [comment]
Make sure the server updates to the develop branch
