### ISSUE TITLE
Pac too large of a file?

### ISSUE THREAD

**Issue by PeroxideHarp** [CapsAdmin/pac3#717]
I've been messing with this pac for a while and only just recently has it not been working (seen by others). My other pacs are able to be worn and seen by others but this one isn't. I'm hoping that I won't have to start over because this.

I'm also getting these lines of text in the console:
[PAC3] Marking transmission session with id 1211733102 as dead, cleaning up... Dropped 4 parts
[PAC3] Marking transmission session with id 623565276 as dead, cleaning up... Dropped 4 parts
[PAC3] Marking transmission session with id 1238065768 as dead, cleaning up... Dropped 4 parts
[PAC3] Marking transmission session with id 308936246 as dead, cleaning up... Dropped 4 parts
[PAC3] Marking transmission session with id 168197065 as dead, cleaning up... Dropped 4 parts
[PAC3] Marking transmission session with id 1562692915 as dead, cleaning up... Dropped 4 parts
[PAC3] Marking transmission session with id 1110756993 as dead, cleaning up... Dropped 4 parts
[PAC3] Marking transmission session with id 184651949 as dead, cleaning up... Dropped 4 parts
[PAC3] Marking transmission session with id 848075449 as dead, cleaning up... Dropped 4 parts

**Comment by thegrb93** [comment]
Those messages indicate those transmissions took longer than a minute to send. Could reset the timeout of transmissions whenever there's a successful transfer.

**Comment by roboderpy** [comment]
Fixed in develop
