### ISSUE TITLE
Update to animations library broke my code :(

### ISSUE THREAD

**Issue by bbblitz** [CapsAdmin/pac3#719]
In 3663b2caa98d56060f5567605e3aa9371e335bbe the animations library was reworked, and now RegisterLuaAnimation's equivalent (pac.animations.RegisterAnimation) does not have a server-side component. I think this will cause hitboxes to not update correctly when animating. Is there a way to use the new animations interface to update hitboxes on the server?

For reference, I was using RegisterLuaAnimation in a gamemode, and just relied on pac3 to provide it (since I use other parts of pac3 in the gamemode, pac3 is a hard dependency anyway whether I had animbonelib or not).

**Comment by thegrb93** [comment]
Lua driven animations are incredibly cpu intensive though

**Comment by thegrb93** [comment]
I'll leave it open in case you want to implement it, but marking it wontfix for now.
