### ISSUE TITLE
PAC3 Crashing issue

### ISSUE THREAD

**Issue by Anon40** [CapsAdmin/pac3#73]
Pac3 makes Gmod crash when i mouse over the 'my outfit' part and anything in that list.

Situation is most likely caused because of the system specs:

CPU: Intel Pentium 4 2.36 (~2.4) GHz
RAM: 1.5 GB
GPU: ATI Radeon 9250 graphics card with 128 MB Memory
OS: Win7 Ultimate & WinXP SP3 (not in use, but listing it anyway)

Mind if you make it a little more adoptable to these settings? Thank you.

**Comment by CapsAdmin** [comment]
reopen or make a new issue if this still an issue
