### ISSUE TITLE
Use normal playermodel when PAC is disabled

### ISSUE THREAD

**Issue by CaptainPRICE** [CapsAdmin/pac3#731]
Personally, I find this very abusive, disturbing, and mostly annoying as a player of PvP/PAC server.
I have no intentions to download this addon.
I have disabled PAC (completely) on my client, too, here are some screenshots:

![PAC -> PAC3](https://user-images.githubusercontent.com/9789070/49043070-3df5b200-f1ca-11e8-88dc-697217defeb3.png)

![PAC -> Settings](https://user-images.githubusercontent.com/9789070/49042929-d2abe000-f1c9-11e8-8dee-815e4d83e1f4.png)

The problem arise when another player uses a custom playermodel for their PAC, in my case a player were using `models/pac/male/base_male.mdl`, the model I do not have obviously.

The solution I am proposing:
Make a (persistent) variable store last playermodel used before it is changed to a PAC model, and then when client doesn't have PAC model downloaded, use the saved playermodel instead.
That way it will render their actual [HL2] playermodel instead of a missing PAC model.

All happy ^^

**Comment by thegrb93** [comment]
It sets their model in server-side. Don't know if there is an easy solution for this.

**Comment by CaptainPRICE** [comment]
> It sets their model in server-side

Yeah right, but there must be some solution to this.

**Comment by thegrb93** [comment]
On applying or clearing model modifier, would need to network the player's original model to players with pac disabled, and on receiving that, the model would need to be overrided in clientside until the modifier is either cleared.

**Comment by thegrb93** [comment]
Personally I wish pac didn't set it serverside either, but there's a lot of issues that happen otherwise.

**Comment by CaptainPRICE** [comment]
Here is a [temporary solution](https://github.com/RawSoftware/FuckPAC3) for now.

**Comment by roboderpy** [comment]
It is impossible to have different models clientside/serverside since it cause desync in pretty much all ways with the server. This is limitation of source engine and we can't workaround it.
