### ISSUE TITLE
PAC3 randomly adding/renaming bones from custom MDLs

### ISSUE THREAD

**Issue by Sofemon** [CapsAdmin/pac3#734]
Pac seems to randomly rename, add or even override some bones from custom MDLs

![image](https://user-images.githubusercontent.com/33532750/49334553-e8514900-f5bf-11e8-8037-e30ab6802c28.png) 
This is what the rootbone is supposed to be named (Previewed within HLMV)

![image](https://user-images.githubusercontent.com/33532750/49334577-58f86580-f5c0-11e8-8270-6603b45a1c96.png)
Meanwhile PAC seems to rename it to "Pinger rightoot" along with adding 2 "skirt" bones that aren't part of the original armature.

**Comment by thegrb93** [comment]
I've found this annoying too

**Comment by CapsAdmin** [comment]
They are added in addition and doesn't really exist on the model. I think this was a bad decision and should have at least been grouped together with attachments since they are read only you can't change them.

**Comment by thegrb93** [comment]
A 'Friendly bone names' toggleable option in the options menu would also be good so you can switch between the true name and the friendly names

**Comment by CapsAdmin** [comment]
Sounds good.

As a developer I just realized I find it annoying as well. I always just PrintTable'ing the pac_bone table.

I've been wanting to implement more model stuff in the resource browser as well though.

**Comment by thegrb93** [comment]
I think this was fixed wasn't it?
