### ISSUE TITLE
DoAnimationEvent hook failing

### ISSUE THREAD

**Issue by Earu** [CapsAdmin/pac3#736]
![Animation error](https://i.imgur.com/WsK3I5p.png)

**Comment by thegrb93** [comment]
Can you give the outfit? Or at least the part that errors?

**Comment by Earu** [comment]
Well no, because I have no idea what causes this, most outfits I have seemed to cause this, did not pay attention too much since I posted here though.

**Comment by Earu** [comment]
I have not managed to reproduce the error. I think its related to outfitter. Not certain.

**Comment by roboderpy** [comment]
fixed
