### ISSUE TITLE
[Nutscript] No one can see anyone's PAC3

### ISSUE THREAD

**Issue by MacMillonn** [CapsAdmin/pac3#738]
So, Currently running a nutscript halorp server and for some reason no one can see anyone else's PAC, Yes they've clicked wear and it even shows up in console that the outfit being loaded. I've had everyone check blacklist settings and to make sure friends only was set to 0. Any help or incite would be great thanks.

**Comment by thegrb93** [comment]
Never used or worked with nutscript. Can you give a link to it? Maybe someone will take a look then.

**Comment by roboderpy** [comment]
Nutscript is not the problem.

@MacMillonn need to check for errors in server's startup and client's join procedure, clients report Lua errors after they joined. Also make sure nothing being printed in the client's console after some time after someone wears a pac
