### ISSUE TITLE
PAC Web Download Issue

### ISSUE THREAD

**Issue by HereticsEnd** [CapsAdmin/pac3#743]
https://steamuserimages-a.akamaihd.net/ugc/949595415279493676/22AD125857107E525400FD191339DBF30A88CE3C/

So I've been having this issue for a while, and I honestly can't remember when it started. Whenever I load into a server that has PAC, there's always one of these "Download is too large" for the people that have large pacs. However, I'm under the presumption that 20mbs or 30mbs isn't too large of a file to download. At least, not for me anyhow, and I honestly don't care. I've tried the console commands to disable the web content limit and how much it would allow, but no dice. Anyone able to assist me with this predicament? I searched through the other topics and I didn't see anything like this pop up, aside from "Control the amount of Web Content one can have in PAC", however that seemingly is how it started this whole thing. Any assistance would be wonderful! And if there is another post that I missed, please direct me to it and delete this. Cheers!

Commands used that refuse to work:
pac_webcontent_allow_no_content_length 0
pac_webcontent_allow_no_content_length -1
pac_webcontent_limit -1
pac_webcontent_limit 0

P.S: No one else on the server has this problem aside from me.

**Comment by thegrb93** [comment]
pac_webcontent_limit

**Comment by thegrb93** [comment]
Also sv_pac_webcontent_limit -1, but I think that is for the server

**Comment by HereticsEnd** [comment]
I swear to god if its as easy as that, I'm gonna be mad at myself. Trying it out now.

**Comment by HereticsEnd** [comment]
Yeah, it's not working.

**Comment by mghimaran** [comment]
Is this a specific problem on a single server or is it wide-spread?

**Comment by thegrb93** [comment]
Probably the server has sv_pac_webcontent_limit set to something. Users can't control that I assume. Try setting pac_webcontent_limit to something large, maybe then it'll override the server setting.

**Comment by thegrb93** [comment]
Ah yea the server setting always overrides the client one. Maybe that can be changed.
```lua
local sv_limit = GetConVarNumber("sv_pac_webcontent_limit")

if sv_limit ~= -1 then
	limit = sv_limit
end
```

**Comment by thegrb93** [comment]
@CapsAdmin @roboderpy Can I set that to `if limit == -1 and sv_limit ~= -1 then`

**Comment by CapsAdmin** [comment]
yeah, server shouldn't override unless explicitly set by server

**Comment by thegrb93** [comment]
I'm thinking it is explicitly by the server. I was wondering if the client should override if set explicitly by the client though.

**Comment by HereticsEnd** [comment]
> Is this a specific problem on a single server or is it wide-spread?

It's widespread for me. No matter where I join.

**Comment by thegrb93** [comment]
Probably the replicated/archived convar bug. Try setting it in singleplayer to -1, then join a server. @roboderpy I think patched a few other places where this was an issue.

**Comment by HereticsEnd** [comment]
> Probably the replicated/archived convar bug. **Try setting it in singleplayer to -1, then join a server.** I don't fully know how it works, but a reinstall should also fix it. @roboderpy I think patched a few other places where this was an issue.

Tried that but it didn't work :C. Think I'll have to resort to a clean reinstall.

**Comment by HereticsEnd** [comment]
Can confirm that a clean reinstall of everything Garrys Mod has fixed the problem. Thank you all!

**Comment by roboderpy** [comment]
client.vdf is the problem.

Added pac_webcontent_limit_force in develop
