### ISSUE TITLE
PAC3 Custom Model lighting problem

### ISSUE THREAD

**Issue by mghimaran** [CapsAdmin/pac3#744]
I've been importing models from Fallout New Vegas into Gmod but all of them seem to have very weird lighting, whenever I go into certain spots of the map it almost goes completely dark out of the blue, is this a problem with the server or the model? Or is it a problem with the texture/material.

**Comment by thegrb93** [comment]
Can't know for certain without the outfit or map. Does it happen on other maps?

**Comment by mghimaran** [comment]
I've tested it on many maps, it does, pretty sure it's the origin now that you say it.

**Comment by roboderpy** [comment]
Check $illumposition in your qc file
