### ISSUE TITLE
Pac 3 Won't Export All Files Into Server Addons!

### ISSUE THREAD

**Issue by wickerface** [CapsAdmin/pac3#746]
I'm using Pac 3 because Pointshop 2 requires it. Everytime I try putting pac3-master into my server addons the workshop.bat and the workshop.sh files won't transfer. And I think it's making Pointshop not work. If anyone has any fixes let me know!

**Comment by roboderpy** [comment]
those files are not required for working pac3.

and this is not help forum nor support forum. Moreover, you should question up pointshop 2 creator, not us.
