### ISSUE TITLE
Flex not working on models other than base playermodel (eg.: flexing a second head not working) 

### ISSUE THREAD

**Issue by Kenajcrap** [CapsAdmin/pac3#749]
First off, my apologies if I'm misunderstanding the limitations of flex and this was actually never possible or I'm just not doing this right

If that's not the case, here is the problem: I created a model, set it's path to breen and was trying to flex it's face, but the face being flexed was the main playermodel instead.

Here is what I've already tried and the result:

Created a flex as a child of the target model >> main playermodel flexes instead
Created a entity and a flex as a childs of the target model >> main playermodel flexes instead
Created a entity as a child of the target model and created a flex as a child of the entity >> nothing flexes?

I'm on mobile, so I will only be able to upload screenshots in a couple hours, until then this might be enough just to know if this is an actual problem or just not possible.

Ty in advance for your time.

**Comment by bluemetaknight** [comment]
Found a solution. Just untick root owner on the flex part and it should work.

**Comment by Jophes** [comment]
Just to clarify for Kenajcrap, this was the intended functionality. 
When root owner is ticked, the flex part alters the player instead of the part's parent. 
I submitted PR #760 to change the default value to false and add a description when you hover over the property to make this clearer.
