### ISSUE TITLE
Lightwarps are "offset" on experimental material 3d part

### ISSUE THREAD

**Issue by AnyaOQuinn** [CapsAdmin/pac3#750]
What it says on the tin.  Lightwarp textures seem to wrap very strangely when you're using material 3d.

Correct (with original material part):

![image](https://user-images.githubusercontent.com/5251535/50804853-dd27c200-12bd-11e9-8f8a-809ddb321be8.png)

Not so correct (with material 3d):

![image](https://user-images.githubusercontent.com/5251535/50804912-1d874000-12be-11e9-95d4-bedd11f7729a.png)

Lightwarp used:

![image](https://user-images.githubusercontent.com/5251535/50804933-34c62d80-12be-11e9-88b8-38e8ea6567f5.png)

**Comment by AnyaOQuinn** [comment]
Update: This is a fault of how .pngs are loaded with material 3d.  This can be amended by saving the lightwarp as a VTF in VTFEdit, with Clamp S and Clamp T checked (to prevent tiling) and linking to that instead.  Case closed.

**Comment by thegrb93** [comment]
I believe pngs can have their tiling flags set too, but glad that fixed it.
