### ISSUE TITLE
pac_friendonly override issue

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#751]
You can not see any PAC outfits for people who are on your friends list, unless pac_friendonly is enabled, regardless of any other filter settings on any client. Because of this, you can only see other people's PACs or your friend's PACs, but never both at the same time. Additionally, PAC outfits do not load automatically and they all have to be manually requested on every occasion.

EDIT Jan 21st: The issue has gotten worse. Not a single outfit loads from people who are on your friends list, no matter the settings on either client, no matter the restarts or cache clearings. Tested on the official PAC3 server.

**Comment by thegrb93** [comment]
If you want to e-mail me your steam (see my profile for e-mail) I can add you and test it on my server with you. I'll be home in 3 hours if so.

**Comment by Techbot121** [comment]
might be related to 
8575b7d
and
e24cc08

**Comment by thegrb93** [comment]
I'll try to get some friends together and test it tonight. As far as I know, it isn't an issue, but it could just be that no one's noticed it or it's a conflict with another addon.

**Comment by thegrb93** [comment]
I honestly can't reproduce it. If you can join my server and test with me then I might be able to look into it.

**Comment by nerdkoopa** [comment]
The issue has somehow gotten worse, see first post.

**Comment by thegrb93** [comment]
What's the official pac3 server? I'm still inclined to believe it's a conflict since it works fine on mine.
