### ISSUE TITLE
pac_allow_mdl and pac_allow_mdl_entity not saving properly

### ISSUE THREAD

**Issue by Pumpkin101** [CapsAdmin/pac3#753]
I got on GMOD today after letting my computer update last night, but when I got on one of my main servers I play on (which has a l o t of custom model pacs). It ended up coming up as 'mdl is not allowed' instead of downloading the model like usual, even though I had loaded all of these pacs multiple times before. I tried doing /fixpac to no avail. Even tried restarting my entire game once more and it still didn't work, all it'll say is. 

[PAC3] part[model2][clothing][2265] mdl files are not allowed
[PAC3] part[bodygroup][][2422] - Unable to find bodygroup collar on 'Pumpkin' (Pumpkin)<STEAM_0:0:89828754>
[PAC3] part[model2][][2423] mdl files are not allowed

Any idea why this might be happening? RP'ing without my PAC on is hell for me and I hope to have it fixed before an Event we plan to do tonight, thanks!

**Comment by thegrb93** [comment]
Make sure pac_allow_mdl and pac_allow_mdl_entity are both 1. Otherwise, the server added something to stop mdls being used or restricted them to admin/vip rank or something.

**Comment by Pumpkin101** [comment]
See, the issue is. Everyone else can see custom models just fine on the server, even those with the same ranking as me. So, it has to be a client side thing with pac_allow_mdl and pac_allow_mdl_entity messing up. I even went into a single player world to try enabling it for clientside, but still it refuses to allow me to see models on the server. So I dunno what's up with it.

**Comment by thegrb93** [comment]
check your cfg/client.vdf and see if it's set to 1 there.

**Comment by thegrb93** [comment]
If so then maybe it's an html issue not properly reporting the error.

**Comment by thegrb93** [comment]
If they do have one, then they also need to be returning the reason for failing.

**Comment by thegrb93** [comment]
In that case, those Convars are not behaving correctly because they should be settings that to 1 in the .vdf

**Comment by roboderpy** [comment]
Altrough thos convars contain no `FCVAR_ARCHIVE` flag on client realm, they are still affected by https://github.com/Facepunch/garrysmod-issues/issues/3323

**Comment by Yagira** [comment]
I don't know about GMOD itself but I'm 99% sure that it has been fixed in PAC. Since 9e56bc8b5890e74025c6afd3267027cb399b0da8 I haven't experienced any problems. I'm pretty sure it only happens because people are playing on servers that are still using the workshop version, which doesn't include that fix. I've decided to test it and here are the results.

Workshop PAC: https://i.imgur.com/qAFKd3n.png
Develop Branch PAC: https://i.imgur.com/3NhYNk4.png

In both cases pac_allow_mdl is set to 0 in client.vdf. The dev version ignores the clientside setting and uses whatever is set on the server, seems pretty "fixed" to me.

**Comment by thegrb93** [comment]
And yea people are still reporting issues

**Comment by Yagira** [comment]
Has anyone actually reported the issue while using the dev version?

**Comment by thegrb93** [comment]
Workshop needs to be updated then. @CapsAdmin

**Comment by Pumpkin101** [comment]
Hi, I'm not sure if this is a necropost. But I've been referring a lot of people to this thread, as I've had about two people in the last week have this issue on a gmod server I play on.

I'd just like to let you know, just in case it may have become an issue again.
