### ISSUE TITLE
Forcing constant negative mass on a physics part causes a crash.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#755]
Just something I ran into by accident. If you somehow force the mass value to stay negative you'll crash your game.

1. Add a Model
2. Add a Physics part
3a. Click on Mass and scroll to a negative value, keep holding the mouse button
or
3b. Add a Proxy (Variable = Mass, Min/Max = any negative value)

**Comment by thegrb93** [comment]
That's really interesting. It will affect a lot more than pac probably.

**Comment by thegrb93** [comment]
I'm at work right now so I can't, but just replace n with `math.Clamp(n, 0.001, 50000)` at https://github.com/CapsAdmin/pac3/blob/13bfdab923b5db2d8330271639b640eef3fd1490/lua/pac3/core/client/parts/physics.lua#L50

**Comment by thegrb93** [comment]
Never mind, I just used github's editor.

**Comment by thegrb93** [comment]
I would still make sure forcing 0.001 mass doesn't have the same issue.

**Comment by Yagira** [comment]
Just tried it. Seems to be working fine even with 0.001 mass.

**Comment by thegrb93** [comment]
All right
