### ISSUE TITLE
Custom Models not loading in for me and other players, but they see if fine(vtf files)

### ISSUE THREAD

**Issue by PrestonGarvey** [CapsAdmin/pac3#761]
I am unable to see custom models, I get a variety of different problems, such as they will return 'unsuccessful' which leaves me completely invisible, I am unable to determine the problem. pac_allow_mdl and entity both don't change the outcome.
![image](https://user-images.githubusercontent.com/26331619/52697670-e8ff4780-2f3f-11e9-99f9-7db0e9a88233.png)

**Comment by PrestonGarvey** [comment]
![image](https://user-images.githubusercontent.com/26331619/52697660-e3a1fd00-2f3f-11e9-92d3-ce34e224b157.png)

**Comment by Yagira** [comment]
'unsuccessful' doesn't really mean anything specific. Check your console (~) for errors.

**Comment by PrestonGarvey** [comment]
Unfortunately the console doesn't tell me anything either, they are vtf files being imported, i don't know much about that kind of thing 
![image](https://user-images.githubusercontent.com/26331619/52698651-eef62800-2f41-11e9-93d8-c3b540ef7cf5.png)

**Comment by PrestonGarvey** [comment]
> 'unsuccessful' doesn't really mean anything specific. Check your console (~) for errors.

Unfortunately the console doesn't tell me anything either, they are vtf files being imported, i don't know much about that kind of thing, the errors there seem unrelated to the problem
https://user-images.githubusercontent.com/26331619/52698651-eef62800-2f41-11e9-93d8-c3b540ef7cf5.png

**Comment by Yagira** [comment]
I suggest that you join the Discord https://discordapp.com/invite/utpR3gJ and we'll try to solve it over there.

**Comment by PrestonGarvey** [comment]
Update: I believe the firewall or blocker is preventing access to a website where the files are located

**Comment by roboderpy** [comment]
Cloudflare

**Comment by FarukGamer** [comment]
I do use Cloudflare for years and there no problems on my side with that.

**Comment by Techbot121** [comment]
cloudflare is right now blocking the chrome version (13) gmod is using.
