### ISSUE TITLE
bodygroups are broken when bonemerges are used

### ISSUE THREAD

**Issue by kaelinsanity** [CapsAdmin/pac3#762]
![image](https://user-images.githubusercontent.com/47693176/52901020-a3ef4580-31cb-11e9-8029-c8a08f9a47cc.png)
![image](https://user-images.githubusercontent.com/47693176/52901093-735bdb80-31cc-11e9-9f53-54eb49cf2894.png)
![image](https://user-images.githubusercontent.com/47693176/52901162-7905f100-31cd-11e9-823b-20607f71fe6c.png)
whenever i bonemerge a model, any bodygroups break
steps to reproduce:
1. have a model with bodygroups
2. have a model that can be bonemerged onto the first model
3. bonemerge the two models together
4. try to use a bodygroup and watch as it does nothing

**Comment by Techbot121** [comment]
closing this issue as it's quite old. If it still happens on latest develop version, feel free to reopen.
