### ISSUE TITLE
GetParsedArguments change broke existing events.

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#766]
I'm talking about 0caaffa
Before that change event arguments used to default to some value even if the user never actually set them, for example adding a command event (or any event that uses _time_) and leaving it at 0 would default it to 0.1, making the event work.

After the change all arguments default to 0, so if you never changed the value yourself your events wont work anymore, forcing you to change all of them.

**Comment by roboderpy** [comment]
fixed

*aaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAA*
