### ISSUE TITLE
PAC3 Outfit Lags when UTime is installed 

### ISSUE THREAD

**Issue by notthisoneguy** [CapsAdmin/pac3#767]
The PAC3 Outfits are lagging behind during movement and glitch out sometimes.

I tried it with a couple of friends on my own dedicated server.
When ULX is installed, everyone's PAC3 Outfit is lagging behind the player. For oneself their own outfit behaved totally normal, but everyone else was lagging around.

When I removed ULX from my server that issue completely vanished. Everything was working fine. No lagging PAC3 Outfits.

**Comment by thegrb93** [comment]
Wonder if it's a hook ordering thing.

**Comment by virion88** [comment]
Did it got fixed yet?

**Comment by thegrb93** [comment]
Not pac's issue.

**Comment by thegrb93** [comment]
https://github.com/TeamUlysses/ulx/issues/152

**Comment by thegrb93** [comment]
Guess I'll leave it open so users know not to use ULX with Pac3

**Comment by thegrb93** [comment]
Try getting rid of all the ulx modules and see if it helps. We can isolate the issue by removing different pieces of ULX.

**Comment by Fires1** [comment]
Found this thread after #250 .

Good lord. Super frustrating this has no solution because there's no better admin addon.

**Comment by thegrb93** [comment]
I'll debug it now

**Comment by thegrb93** [comment]
I wasn't able to reproduce it with singleplayer or listen-server. If one of you are able, let me know how, or if you have a dedicated server and can debug for me, then I'll be willing to help find the problem.

**Comment by virion88** [comment]
I'll do it once I'm home. Have to work 2 more hours and then drive home another 2 hours. Me and a friend have much experience with it so I will ask him to record this on video while we are doing this.

**Comment by thegrb93** [comment]
Ok, the first thing I would test is removing ulx entirely, but leaving ulib installed. If the problem occurs still after that, then it can be narrowed down to ulib. Otherwise, remove the ulx modules one by one from ulx/lua/ulx/module. I haven't tested to see which ones are needed for ulx to work but hopefully it is as its name implies. If the problem still occurs then we've narrowed it down to the core ulx, but if it stops occuring after removing a module then we know which module is causing it.

**Comment by virion88** [comment]
Alright, after a long night and hours of investigation, my friend and me came to conclusion that **UTime is the reason** for PAC3 outfits to lag behind. If you use everything but UTime, PAC3 works fine.

**Comment by thegrb93** [comment]
So its the same issue as https://github.com/CapsAdmin/pac3/issues/250 and https://github.com/CapsAdmin/pac3/issues/300

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/issues/894
