### ISSUE TITLE
Exprimental materials do not work correctly

### ISSUE THREAD

**Issue by Rodocks** [CapsAdmin/pac3#770]
I was trying to make an outfit using a vtf I found this page: https://wiki.pac3.info/tutorial/replacing-materials detailing how to use custom materials but I couldn't get it to work. The material would not load I checked the URL I had uploaded it to and there is nothing wrong with the URL, so I downloaded the example off of the wiki https://wiki.pac3.info/_media/asset/example/submaterial.txt and found that it had the same issue as mine.

**Comment by Yagira** [comment]
What exactly happens? Are you playing on chromium/64 version of gmod? If so then the example won't work as it's using the old materials, which do not work with these versions.
