### ISSUE TITLE
Workshop PAC3: Camera Jitter

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#775]
When I attach a jigglebone to something, and then put the camera on the jigglebone, when the object moves, the camera is all jittery. How do I fix this?

If I use an object instead of a camera, the object moves smoothly. If I attach a camera to that object, it lags behind the object/is jittery again.

If I attach a camera directly without the jigglebone it's perfectly static relative to the object. So what's causing this?

**Comment by mrwallace888** [comment]
https://drive.google.com/open?id=1KtMWWe24pqku2F3RSS4Hjq4JSU7VvAJa
This will explain.

**Comment by thegrb93** [comment]
Attempting to manipulate something with the manipulator axes that is parented to a jigglebone jitters too.

**Comment by mrwallace888** [comment]
Is there a fix?

**Comment by thegrb93** [comment]
Might be

**Comment by roboderpy** [comment]
Don't expect this get really fixed due to Source Engine's limitations

**Comment by mrwallace888** [comment]
Everything is always limited by the Source Engine. But why does it do jitter?

**Comment by roboderpy** [comment]
Due to how pac3 handle bones and probably how gmod/source handle bone manipulations on each game frame

**Comment by mrwallace888** [comment]
Also I somehow broke it now so once I screw with the Camera thing a bit in the PAC3 editor, it gets permanently broken. When I get in a vehicle it's like stuck on my head in front of me sideways. Can't change it. Have to reload the map. Don't know how I cause it.

**Comment by thegrb93** [comment]
The jigglebones are computed in lua, I don't see why it wouldn't be fixable. It's just a matter of spending the time to figure it out.

**Comment by Yagira** [comment]
I'm surprised you got it working at all, because it shouldn't. In your video you have nothing that limits the camera to vehicle only (and no, the owner itself doesn't do that), yet when you exit you go back to first person, PAC wouldn't do that, it would keep the camera on the car at all times. Seems like there is something else that messes with your camera.

As for the camera stuttering I haven't noticed any problems, on single player there is no lag at all. 

> Attempting to manipulate something with the manipulator axes that is parented to a jigglebone jitters too.

Can't recreate either. Everything works fine on my end. The 'jittery manipulator' happens randomly on different parts and doesn't seem to be related to jiggle bones at all. Anyway its more accurate to just the properties panel and change the values there.

**Comment by thegrb93** [comment]
Was a long time ago so might've been fixed since then

**Comment by roboderpy** [comment]
Fixed

**Comment by mrwallace888** [comment]
Hey Robo does this fix the Steam Workshop version?
And you're saying that this has been fixed?
Also, what about the whole camera activates itself when sitting? When I use camera at all, it just activates when using thirdperson or something. Anyways, I'll try this in-game.

**Comment by thegrb93** [comment]
The workshop has to be updated manually I think...

**Comment by thegrb93** [comment]
It's 877 commits behind. I think its time to update.

**Comment by mrwallace888** [comment]
Is the GitHub version fixed?

**Comment by thegrb93** [comment]
Idk, try it and see. Make sure you use the develop branch.

**Comment by mrwallace888** [comment]
The Workshop version still jitters.
I've disabled all addons except for PAC3 and simfphys vehicles.
Though I don't believe that it jitters as much at least.
I'm attempting the GitHub version.
