### ISSUE TITLE
Webaudio loop bug

### ISSUE THREAD

**Issue by akronmna1** [CapsAdmin/pac3#777]
When I using loop function in webaudio, it doesn't work. idk why, help pls

**Comment by roboderpy** [comment]
this should be fixed with develop branch

try develop branch and see if this fixes the issue

if it does, press 
![firefox_09-10-45-4e2162a](https://user-images.githubusercontent.com/6339511/57053745-2ca15c00-6cba-11e9-8663-72e9ef2578c3.png)

**Comment by akronmna1** [comment]
Ok, where I can download dev branch?

**Comment by Yagira** [comment]
https://github.com/CapsAdmin/pac3/archive/develop.zip

**Comment by akronmna1** [comment]
Loop still badly working

**Comment by akronmna1** [comment]
After map changing, loop was broking
