### ISSUE TITLE
Experimental model/entity material "leak"

### ISSUE THREAD

**Issue by Yagira** [CapsAdmin/pac3#778]
~~Started happening after https://github.com/CapsAdmin/pac3/commit/a520eeba27f0de20b86c3d8ea750e5647570a37f (most likely)~~
The issue is pretty much the same as #774 except it affects normal materials instead of submaterials.
It affects every model that doesn't have any materials attached. Caused by material override set to 'all'.

![image](https://user-images.githubusercontent.com/12747052/57053966-fc45c780-6c91-11e9-94f1-b91306e2167f.png)

**Comment by thegrb93** [comment]
Any change you can provide a reproduction example?

**Comment by Yagira** [comment]
These are broken:
1. Multiple models, one model with attached material3d, material override set to ``all``. 
[example1.txt](https://github.com/CapsAdmin/pac3/files/4943568/example1.txt)

2. Multiple models, material3d not attached to anything, instead the material name is used in the material field on one of the models. 
[example2.txt](https://github.com/CapsAdmin/pac3/files/4943569/example2.txt)

3. Multiple models, one model with attached material3d, material override set to ``default`` AND the material name is used in the material field on one of the models at the same time.
[example3.txt](https://github.com/CapsAdmin/pac3/files/4943618/example3.txt)

This one seems to work fine:
1. Multiple models, one model with attached material3d, material override set to ``default``.
[example4.txt](https://github.com/CapsAdmin/pac3/files/4943617/example4.txt)

All of the broken ones load differently on each load/wear/restart and look differently for each person.
![my view](https://user-images.githubusercontent.com/12747052/87873793-a52a3080-c9c4-11ea-9deb-2a694e5d1160.png)
![someone elses view](https://user-images.githubusercontent.com/12747052/87873801-b70bd380-c9c4-11ea-9842-5c3ab2e85faa.png)

**Comment by thegrb93** [comment]
Suspecting this https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/parts/material2.lua#L196

**Comment by CapsAdmin** [comment]
fixed i think, reopen if not
