### ISSUE TITLE
HL2RP Load Error

### ISSUE THREAD

**Issue by TheChubgger** [CapsAdmin/pac3#78]
Hey, CapsAdmin. I'm an Operator on a HL2RP server and I suggested Pac3 to the owner. He added it and we made our models. The next day when we came back, it loaded our models but it made us all black guys holding our hands out.. We really need you to fix it. We made complex models but can't use them. It only does this on HL2RP, I already tested on sandbox and such. Screenshot: http://steamcommunity.com/sharedfiles/filedetails/?id=301277658

Thats all I got so far, let me know if you might need some more info.

**Comment by CapsAdmin** [comment]
reopen if this is still an issue
