### ISSUE TITLE
Envmap no longer changes in material3d

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#780]
Environment maps can no longer be changed in material3d, but still work with the regular material part. Any attempt to put in an envmap texture results in nothing, despite optimal settings.
For some reason any outfits made in previous versions are still able to display their original envmaps, but attempting to change them again will result in nothing changing, getting the old envmap stuck on. Envmap in material3d simply doesn't react to any changes at all.

**Comment by Yagira** [comment]
Do you have any outfit examples?

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/commit/935884de34559c4dd6573f5a602424d7f28e7ca3
https://github.com/CapsAdmin/pac3/commit/f24b4d7c2b831b581fe92bbb8f9c84e49c9535e3

maybe these caused it

**Comment by nerdkoopa** [comment]
Yagira, here are some exmples
working envmap, workshop version: https://www.dropbox.com/s/xdkge4m6df66953/envmap%20works.txt?dl=0
Broken envmap, latest version: https://www.dropbox.com/s/s624ugb18xuafno/envmap%20broke.txt?dl=0

Also new bug, the editor no longer allows capital letters in file names.

**Comment by Yagira** [comment]
Seems to work fine?
![image](https://user-images.githubusercontent.com/12747052/57102658-4ecfc400-6d24-11e9-8b0f-44f94500545e.png)

**Comment by nerdkoopa** [comment]
Oh for god's sake why is it that I keep encountering issues that nobody can reproduce? Can you at least confirm the filename capital letters issue? Saving an outfit just turns all uppercase letters in the filename to lowercase.

**Comment by Yagira** [comment]
Yes that actually happens.

**Comment by nerdkoopa** [comment]
Also, the envmap issue was found first on meta construct, where I was able to reproduce it.

**Comment by nerdkoopa** [comment]
Yagira, try to change the envmap on either one of those examples while on a server.

**Comment by thegrb93** [comment]
Gmod can't write upper case filenames anymore iirc.

**Comment by nerdkoopa** [comment]
Damn, I always put an uppercase first letter in every PAC I ever made. How badly is this gonna bite me in the ass later? Are there gonna be conflicts? I tested, and I still can save uppercase named files if the file was like that before the update. This is gonna suck, as the PAC editor still orders capitalized names first.

**Comment by Yagira** [comment]
Pretty sure it can still read them correctly so manually changing the file name should work.

**Comment by nerdkoopa** [comment]
Yagira, were you able to change the envmaps on the materials? During my test, I wasn't able to.

**Comment by Yagira** [comment]
I had to remove the basetexture, it seems like that combo just looks bad on meta? 
![image](https://user-images.githubusercontent.com/12747052/57103773-f3530580-6d26-11e9-9b4e-0f7f97df0c4a.png)

With basetexture, after increasing the saturation.
![image](https://user-images.githubusercontent.com/12747052/57103895-43ca6300-6d27-11e9-9ddb-45f1725ff023.png)

It seems like meta lightning just makes it invisible

**Comment by nerdkoopa** [comment]
No Yagira, the envmap went just plain non-functional. Not appearing when told to, not disappearing when told to, simply not reacting to any attempted changes.

**Comment by Yagira** [comment]
Envmaps got disabled for HDR

**Comment by nerdkoopa** [comment]
Wait are you serious?! But they still worked with the conditions I mentioned earlier, PAC made in previous version

**Comment by nerdkoopa** [comment]
Disabling envmaps for HDR is just plain idiotic, if that really is a feature and not a bug.

**Comment by Yagira** [comment]
Well, some envmaps were made for hdr and some for non-hdr. That means if you use a non-hdr envmap on your pac, HDR players will see it completely differently. Thats why it was disabled, because you never know how the other player is gonna see it.

**Comment by nerdkoopa** [comment]
In my tests using an hdr envmap texture behaves consistently both with hdr on and off, with all clients seeing it the same. However, I can confirm that using a non-hdr envmap fucks up.

**Comment by Yagira** [comment]
Yeah but what about non hdr players that want to use non-hdr envmaps, because they work for them?

**Comment by nerdkoopa** [comment]
Then LET THEM use them! Again, this solution didn't fix anything, just created another, much more annoying issue.

**Comment by Yagira** [comment]
If we let them use them hdr players won't see them correctly. And what about hdr players that want to use non-hdr maps, because they like the different effects they give, without knowing that they will look completely different for non-hdr players?

It fixed the differences between hdr and non-hdr players so it solved the problem.

**Comment by nerdkoopa** [comment]
But now it created an issue of nobody being able to have a basic functionality when enabling better lighting, or god forbid the ONLY lighting.
