### ISSUE TITLE
pac_friendsonly 1 causes outfit to hide/remove itself upon Wear

### ISSUE THREAD

**Issue by arthurgeron** [CapsAdmin/pac3#782]
If pac_friendsonly is set to 1, your autoload outfit will show to others normally but your pac will look completely empty for yourself, if you go and load any outfit and proceed to click `Wear` you will wear the outift but  it will get removed from your pac_editor and not show to you anymore.

**Comment by Yagira** [comment]
Doesn't happen on the dev branch. Either it was fixed or is related to something else.

**Comment by NanoAi** [comment]
I've been getting this error on and off I'll need to make sure that it's running on the latest version and I'll get back to this issue.
