### ISSUE TITLE
Request: Evnmaps back on HDR

### ISSUE THREAD

**Issue by nerdkoopa** [CapsAdmin/pac3#784]
Commit https://github.com/CapsAdmin/pac3/commit/191b0591bdf8d1fee16a3478bab022dba4e43537
made it so that envmaps in material3d no longer work when HDR is enabled. The reasoning behind this was that non-HDR envmaps don't show up correctly for HDR users. This is not a good fix, as it disables a basic functionality to fix an issue that already had a solution without removing the feature. Before this commit, the fix was to use HDR envmaps, as those work consistently regardless whether or not HDR is on or off.

So, you have a feature where option 1 works for some and option 2 works for everyone. What do you do?
A: Keep it as is and let users judge for themselves on a case-by-case basis.
B: Remove the entire feature so it doesn't work for anybody.
You chose B, and that makes no sense. It would be like removing the model part's ability to display non-HL2 models just because not everyone has TF2 or CSS mounted.

Could you please return envmaps on material3d to work with HDR on again? Disabling a basic feature for the sake of perceived consistency is not the way to go, especially when a non-restrictive solution already exists.

**Comment by Yagira** [comment]
Cool. Now check what that commit actually did.

**Comment by nerdkoopa** [comment]
Oh fuck, I'm a retard. Apologies.
