### ISSUE TITLE
Render ERROR

### ISSUE THREAD

**Issue by Chaosit27** [CapsAdmin/pac3#786]
Hi, I've got this text messages: [PAC3] failed to render Player [1][^1 Di la cheos [CI.Ω]]:
addons/pac3-master/lua/pac3/core/client/parts/poseparameter.lua:24: attempt to perform arithmetic on a nil value
your pac3 outfit failed to render!
addons/pac3-master/lua/pac3/core/client/parts/poseparameter.lua:24: attempt to perform arithmetic on a nil value
hiding your outfit to prevent further errors
[PAC3] failed to render Player [1][^1 Di la cheos [CI.Ω]]:
addons/pac3-master/lua/pac3/core/client/parts/poseparameter.lua:24: attempt to perform arithmetic on a nil value
your pac3 outfit failed to render!
addons/pac3-master/lua/pac3/core/client/parts/poseparameter.lua:24: attempt to perform arithmetic on a nil value
hiding your outfit to prevent further errors

and another players can see my custom Player Model, but they can't see other things from my pac.... please help me! ^_^

**Comment by Jophes** [comment]
Any chance you can post the PAC that was causing this?

**Comment by thegrb93** [comment]
The only way this error can occur is if an entity:GetNumPoseParameters() returns nil. What were you trying to pose parameter?
