### ISSUE TITLE
Saving files names wont stay capitalized

### ISSUE THREAD

**Issue by Pumpkin101** [CapsAdmin/pac3#787]
Hi, it's me again.

So, my pac recently has started dying once more. Even after I tried completely reinstalling it and everything, deleting all the files related to it and seeing if that would help. But still, it has these issues.

Recently, my pac started bugging out where. Whenever I'd save my pac with its name in caps, it would forcefully make the name lower case. While all my previous ones would be fine, any new ones wouldn't. It wasn't really a big deal at first, y'know? I could just edit the names in the pac files.. but then it started getting worse.

Edit: Well, it seems reinstalling fixed the events messing up. But the capitalization is still irritating, not as urgent though!

**Comment by Jophes** [comment]
Windows is case insensitive, and Linux is case sensitive for files/directories. It's possible it's forcing lower case to resolve any compatibility issues between the two, but I'll take a look when I get home.

**Comment by thegrb93** [comment]
Yeah, gmod only saves lowercase filenames in linux. Very annoying

**Comment by mrwallace888** [comment]
Yeah, it appears my Windows copy has started doing this in-game. But not with just PAC. It also starts happening with things like filenames for Dupes, Simfphys Dupes, Stop Motion Helper stuff, etc.

**Comment by thegrb93** [comment]
Yeah, it's a gmod thing

**Comment by UnknownShifter** [comment]
HERE'S A TIP

I'm a neatfreak when it comes to my PAC organization.  A way to rectify this is by going into your pac3 folder, e.g: Steam > steamapps > common > GarrysMod > garrysmod > data > pac3
Once you're in there, you can rename your folders and files to have the cases that they need.
