### ISSUE TITLE
E2 Converter ignoring position/rotation offsets

### ISSUE THREAD

**Issue by megalatapalapapuas** [CapsAdmin/pac3#788]
Before converter
![image](https://user-images.githubusercontent.com/50799377/57982692-99627780-7a6a-11e9-9532-85eca1040f00.png)

After converter
![image](https://user-images.githubusercontent.com/50799377/57982687-89e32e80-7a6a-11e9-9114-1cd3f9326559.png)

**Comment by thegrb93** [comment]
Something around this https://github.com/CapsAdmin/pac3/blob/eb85fef769b2ea1301d74596525a287823f6ba37/lua/pac3/editor/client/tools.lua#L419 not working right?

**Comment by megalatapalapapuas** [comment]
@thegrb93 maybe, this trouble happens only with props that have offset

**Comment by megalatapalapapuas** [comment]
@thegrb93 there were no errors in the console

**Comment by thegrb93** [comment]
:gsub("ANGLES", toang(part:GetAngles()))
:gsub("POSITION", tovec(part:GetPosition()))

might be that these aren't taking that into account

**Comment by thegrb93** [comment]
That code is atrocious. A gsub table there would be better too.

**Comment by megalatapalapapuas** [comment]
@thegrb93 Converter doesn't taking offsets to account. But i could be wrong i'm not a lua programmer
![image](https://user-images.githubusercontent.com/50799377/58034336-32b38b80-7b48-11e9-8ca1-8e9a0adf0fb1.png)

![image](https://user-images.githubusercontent.com/50799377/58034307-1fa0bb80-7b48-11e9-9035-5649764d31ad.png)

**Comment by thegrb93** [comment]
Yeah, that explains it then. Shouldn't be hard to fix.

**Comment by megalatapalapapuas** [comment]
@thegrb93 :(
![image](https://user-images.githubusercontent.com/50799377/58096227-6cdb6680-7bf6-11e9-9b7d-61c8bd3adb0e.png)

**Comment by thegrb93** [comment]
I updated the code, try again. If that still doesn't work, I'll get into it again later tonight.

**Comment by megalatapalapapuas** [comment]
@thegrb93 
![image](https://user-images.githubusercontent.com/50799377/58105989-30653600-7c09-11e9-858c-e050c3092630.png)

**Comment by thegrb93** [comment]
Looks better at least. Is that the only part out of place?

**Comment by megalatapalapapuas** [comment]
@thegrb93 i forgot 2 turn off pack parts

**Comment by megalatapalapapuas** [comment]
@thegrb93 hood went back

**Comment by thegrb93** [comment]
wat?

**Comment by thegrb93** [comment]
I'll figure it out tonight. Just need to correct the math.

**Comment by megalatapalapapuas** [comment]
@thegrb93 now its working fine, thx
