### ISSUE TITLE
Camera "Breathing" When Driving a PAC Vehicle

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#794]
Don't know what causes this but when driving in third-person in a PAC-edited vehicle, the camera zooms in and out depending on which direction the vehicle is facing. In Master Chris's Charger, for example, rather than just zoom in and out depending on vehicular angle, the camera sort of "breathes" in and out slowly. Don't know why. I'm not sure if the camera bug is a Source limitation or what. I'd maybe look into it. You should be able to replicate it with a Vanilla game. I think even just setting the outfit owner to the vehicle is enough to cause it.

**Comment by mrwallace888** [comment]
Bump. Anybody know about this?

**Comment by thegrb93** [comment]
What do you mean pac edited vehicle? What was edited? What kind of vehicle? I didn't see any issue with it and the jeep.

**Comment by thegrb93** [comment]
Nvm just saw it happening.

**Comment by thegrb93** [comment]
It's like the throbbing a selected entity in the editor makes.

**Comment by thegrb93** [comment]
Ah no that's not it

**Comment by thegrb93** [comment]
The trace.Hull is hitting something

**Comment by thegrb93** [comment]
Something in pac is causing one of these to change
```lua
local mn, mx = Vehicle:GetRenderBounds()
local radius = ( mn - mx ):Length()
local radius = radius + radius * Vehicle:GetCameraDistance()

-- Trace back from the original eye position, so we don't clip through walls/objects
local TargetOrigin = view.origin + ( view.angles:Forward() * -radius )
local WallOffset = 4
```

**Comment by thegrb93** [comment]
Pac is causing `Vehicle:GetRenderBounds()` to change

**Comment by mrwallace888** [comment]
Is there a fix for this at all?

**Comment by thegrb93** [comment]
If I can find what's causing it, yeah.

**Comment by mrwallace888** [comment]
Progress?

**Comment by thegrb93** [comment]
no

**Comment by thegrb93** [comment]
It's not easy to find so I haven't looked. Will be a series of disabling/enabling code to find it.

**Comment by thegrb93** [comment]
Took an hour, but traced the problem to `function pac.ResetBones(ent)`

**Comment by thegrb93** [comment]
```
Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 342	"ResetBones"		addons/pac3/lua/pac3/core/client/bones.lua
	3: Line 94	"nil"		addons/pac3/lua/pac3/core/client/part_pool.lua
	4: C function	"pcall"
	5: Line 208	"RenderOverride"		addons/pac3/lua/pac3/core/client/part_pool.lua
	6: Line 833	"v"		addons/pac3/lua/pac3/core/client/part_pool.lua
	7: Line 84	"nil"		lua/includes/modules/hook.lua
```
This is called every frame and the bone manipulation functions in it are causing renderbounds to be recalculated.

**Comment by thegrb93** [comment]
Someone else more experienced with the render pipeline should fix it.

**Comment by CapsAdmin** [comment]
Whenever I call the ManipulateBone* functions on the vehicle clientside this happens. I have no idea why but it seems like a bug in gmod.

Maybe I will avoid using these functions in the future, but for now I'm closing with cantfix.

**Comment by thegrb93** [comment]
Looks like gmod dev finally fixed this
