### ISSUE TITLE
Clearing PAC Resets Playermodel

### ISSUE THREAD

**Issue by Rush101** [CapsAdmin/pac3#796]
Models are enforced on the server however clearing PAC resets a player's model to the model they have chosen through the context (C) menu. It does this for any ulx group and does not allow you to set the player's model server side after it has been cleared through pac, it automatically changes back to their C menu model. Repsawning doesn't fix this, you have to reconnect to the server completely. 
I have checked through the collection for conflicting addons, the issue still occured and I even changed the collection entirely to a different one, which is used on our main server (where clearing pac works perfectly) however even with that collection on the new server, the same issue occurs. enforceplayermodel is set to true and the server is showing in the correct category for its gamemode. This is the first time I've come across this issue and I don't know what else to try, any help much appreciated!

**Comment by Yagira** [comment]
pac_modifier_model 0 disables playermodel changes through PAC.

**Comment by Rush101** [comment]
Thanks Yagira but the issue isn't that they can change playermodel through PAC, it's that when clearing PAC with pac_clear_parts it removes their PAC as it's supposed to but also changes their playermodel to whatever they set it as through C menu -> Playermodel. I did still change the setting you suggested though and it hasn't had an effect.

For example - lets say I'm playing as Obi-Wan Kenobi, I clear my pac with that command above or have an admin clear it for me, it will then change my playermodel to whichever model I have chosen client side and won't change to anything other than that.

**Comment by thegrb93** [comment]
You're saying that Obi-Wan Kenobi isn't what you chose client side?
>won't change to anything other than that
What is trying to change it but can't?

**Comment by Rush101** [comment]
Say you join the server, you hop into a job (obi wan as an example), your playermodel is then changed to the obi wan playermodel which is set in jobs.lua, if I then run pac_clear_parts it would not only clear my pac but also change my playermodel to the one that I have chosen through the C menu when. What it should actually be doing is just clearing my parts and keeping the obi wan playermodel.

**Comment by thegrb93** [comment]
Ok you're talking about DarkRP. Now we have some context. You should probably use pac_modifier_model 0 since darkrp's own model management will probably conflict with pac's.

**Comment by Yagira** [comment]
Make sure that pac_modifier_model 0 is actually set on the server and not your client

**Comment by Rush101** [comment]
Will do - where should I place this?

**Comment by Yagira** [comment]
Server config I guess

**Comment by Rush101** [comment]
Hasn't worked unfortunately, the server log shows: Unknown command "pac_modifier_model" and server.vdf still shows: "pac_modifier_model"		"1"

**Comment by Rush101** [comment]
So I did some digging into this and I finally figured out what this command needs to work. You need to create a ConVar in pac3/core/server/init.lua. Copy and paste: 
CreateConVar("pac_modifier_model", "0", {FCVAR_NOTIFY}, "Allow to use clientside models")
into the file and it should resolve the issue (it worked for me).

**Comment by thegrb93** [comment]
That's really weird, I've never encountered it being an unknown command before.
