### ISSUE TITLE
Outfitter reloading pac while editting causes loss of unsaved work

### ISSUE THREAD

**Issue by VCSoldier** [CapsAdmin/pac3#799]
every time i use PAC there's always that one time i'm doing something then it starts undoing it all for no reason, its not my keyboard because its happened across multiple servers and keyboards.
i dont even know whats causing it though

**Comment by thegrb93** [comment]
Has this happened to anyone else? I've never heard of it. Does it happen when pushing a key or just randomly for no apparent reason?

**Comment by thegrb93** [comment]
My only guess would be an admin is trolling you, but happening across multiple servers says otherwise.

**Comment by thegrb93** [comment]
Could it be an event being triggered that's somehow causing an undo input?

**Comment by VCSoldier** [comment]
It happens when i'm taking a break looking at it , sometimes even when i'm moving shit. the only solution is to quickly exit out of PAC before it undoes all of it

**Comment by thegrb93** [comment]
So it starts repeatedly undo-ing?

**Comment by thegrb93** [comment]
My only guess is something is going wrong here https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/editor/client/undo.lua#L216

That can only happen if your input library is misbehaving. Do you have any input mods? What is your keyboard layout/OS?

**Comment by thegrb93** [comment]
You can see ctrl+shift+z or ctrl+y redo, and ctrl+z undos.

**Comment by VCSoldier** [comment]
i dont have any input mods,  im using a normal keyboard

**Comment by VCSoldier** [comment]
UK Varient

**Comment by thegrb93** [comment]
No weird drivers or 3rd party keyboard software? Windows sticky keys?

**Comment by VCSoldier** [comment]
Nope, ive even went out of my way to disable all of the useless windows stuff like sticky keys due to how annoying it is

**Comment by thegrb93** [comment]
I can't diagnose it without more information on what's causing it. Considering this seems to be a unique case, idk.

**Comment by thegrb93** [comment]
Are your binds custom? Are you running a gmod on the chromium or x64 branch?

**Comment by VCSoldier** [comment]
running it on chromium,

**Comment by thegrb93** [comment]
I don't think that would cause it, but it would be worth trying the stable branch instead.

**Comment by Jophes** [comment]
Perhaps a video of it happening with an input overlay (Google obs input overlay) would help figure out what is going on

**Comment by Yagira** [comment]
I've had that happen for me once and only on Metastruct, someone told me that Meta auto refreshes playermodels to make Outfitter work (this might be made up can't really confirm lol). Can't say anything about other servers, I don't play multiplayer that much, but I've never seen this happen on singleplayer (clean gmod, no addons instealled).

Also I'm pretty sure its not an input thing. It doesn't undo as ctrl+z does, it just reloads PAC and loads what seems to be the last saved version (last backup?).

**Comment by thegrb93** [comment]
That's definitely a different issue.

**Comment by VCSoldier** [comment]
i think its just outfitter doing a reload automatically, because i just realised its on servers that have outfitter
it just flashes for a breif moment to base male or whatever base im using for the skeleton, and then loads the last backup/autosave

**Comment by thegrb93** [comment]
Oh, you made it sound like it was the undo function being triggered. Well I guess it is outfitter then.
