### ISSUE TITLE
Settings Stuck

### ISSUE THREAD

**Issue by epicmarkvan** [CapsAdmin/pac3#800]
My settings for the blacklist seem to be stuck, and no matter how much I untick them, they reset and block the once selected players from seeing it. I can't seem to undo it.

**Comment by Yagira** [comment]
Delete the **garrysmod/cl.db** file, it should reset the blacklists. You should probably update PAC as well.

**Comment by thegrb93** [comment]
Yeah, latest pac doesn't have this issue
