### ISSUE TITLE
question about broken pac3s

### ISSUE THREAD

**Issue by joeyjumper94** [CapsAdmin/pac3#802]
so my friend has a pac3 and a part of it is on the ground cause the "chest" bone is specified by the pac3, on his client, the "chest" bone is real so it looks right on his end, but i see the part on the floor, why is that?
is there a way to add a bone to a model if it doesn't exist?

**Comment by thegrb93** [comment]
I think the part will go to the position of the entity of the position of the bone can't be found. For players this will be on the floor. You can't add a bone to a model.

**Comment by joeyjumper94** [comment]
do you mean we need to edit the model itself?

**Comment by thegrb93** [comment]
I'm confused. How does he see the chest bone and you don't. Do you have different versions of the same model?
