### ISSUE TITLE
Entity & Experimental Entity break IKs

### ISSUE THREAD

**Issue by Vuthakral** [CapsAdmin/pac3#808]
Title.

This has been a bug for as long as PAC3 has existed and I'm surprised nobody else has noticed or brought it up sooner.

For those who don't know, an IK or Inverse Kinematic chain is a thing which can hold a hand or foot bone in place while an animation plays, allowing stuff like weapons to be held with ease without having to trouble the animators.

Here's a very noticeable example, on my Halo elite playemodels:

- What the IK does & should be doing when an entity/entity2 part is present: [https://i.imgur.com/sL3yQFd.gifv](https://i.imgur.com/sL3yQFd.gifv)
- What the IK does when an experimental entity part is present: [https://i.imgur.com/spAX0PL.gifv](https://i.imgur.com/spAX0PL.gifv) (Note on entity2 when the part is removed, the problem corrects itself.)
- What the IK does when a normal entity part is added: [https://i.imgur.com/3IStASd.gifv](https://i.imgur.com/3IStASd.gifv) (note the problem persists even after the entity part is removed, but adding entity2 and removing it fixes it again.)

And no, ticking the "Inverse Kinematics" box does not fix this problem, even if re-worn.

edit: typos

**Comment by thegrb93** [comment]
Might be triggering this code to run. https://github.com/CapsAdmin/pac3/blob/97ab99e9e8f5f16063ee5480ee33d21970822b8c/lua/pac3/core/client/util.lua#L884

Can you put print("IK True") and print("IK False") next to each of those SetIK and see if they appear in console?

**Comment by thegrb93** [comment]
Although, ticking the Inverse Kinematics box should fix it if that were the case, so it could be something else causing it. Would be good info to start with though.

**Comment by Vuthakral** [comment]
Nothing printed when adding either entity part, sizing/scaling them, or checking the Inverse Kinematics box in either Entity or Player Config parts.

Screenshots: [https://imgur.com/a/Qbm7zUG](https://imgur.com/a/Qbm7zUG)

> 			if ent.pac_enable_ik then
> 				ent:SetIK(true)
> 				print("IK Set to true")
> 				ent:SetModelScale(1, 0)
> 			else
> 				ent:SetIK(false)
> 				print("IK Set to false")
> 				ent:SetModelScale(size == 1 and 1.000001 or size, 0)
> 			end

**Comment by thegrb93** [comment]
Hm, the only other place is here. https://github.com/CapsAdmin/pac3/blob/97ab99e9e8f5f16063ee5480ee33d21970822b8c/lua/pac3/libraries/animations.lua#L422

Could you try that one?

**Comment by thegrb93** [comment]
If that's not it then there's something else going on engine-wise that will need to be investigated piece by piece.

**Comment by Vuthakral** [comment]
Rest in pepsi, still nothing. [https://imgur.com/a/5obJMdu](https://imgur.com/a/5obJMdu)

>	if anims and table.Count(anims) > 0 then
>		ent:SetIK(false)
>		print("IK Set to false")
>		ResetInSequence(ent)

**Comment by thegrb93** [comment]
Then it's something missing in either of these needed for IK to work

https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/parts/model2.lua#L665
https://github.com/CapsAdmin/pac3/blob/master/lua/pac3/core/client/parts/model2.lua#L687

**Comment by thegrb93** [comment]
Or it's entirely possible that IK just breaks after player:SetModel(). Each of these cases I can test later when I'm home.

**Comment by pingu7867** [comment]
As a temporary fix, assuming SetIK even works, what is the name of the player in the code, or how to get it, so that clientside (let's say with lua in the command part) I can get my player to set the IK?

Also I'd point our attention to line 425 of animations.lua where the only thing that sets the IK to true there is nullified as a comment
https://github.com/CapsAdmin/pac3/blob/97ab99e9e8f5f16063ee5480ee33d21970822b8c/lua/pac3/libraries/animations.lua#L425

**Comment by thegrb93** [comment]
Yeah, you can try lua_run Entity(1):SetIK(true) and lua_run_cl Entity(1):SetIK(true) in singleplayer (make sure sv_allowcslua 1) in console and see if that changes anything. That's something I would test.

**Comment by pingu7867** [comment]
Yeah, something's not updating the IK or animations, or something keeps reverting the IK to false. The entity (entity1 and entity2) parts are the only thing that let IK budge, and in only one way (breaking it/setting to false without reversibility) which seems not to be done with the SetIK method itself, but something else. I've replaced every occurence of SetIK(false) in pac-develop to SetIK(true). IK behaves the same way as before: starts on at the game instance startup, breaks irreversibly the moment a pac entity part is put.

**Comment by thegrb93** [comment]
The best way to see is to disable the two features I linked earlier and see if it works after that, but I'll try it myself as well later.

**Comment by thegrb93** [comment]
OK, I found the problem

ent:EnableMatrix("RenderMultiply", mat), this causes IK to break.

**Comment by thegrb93** [comment]
Fixed the experimental entity, looking at legacy entity now.

**Comment by pingu7867** [comment]
This is great and all, but the changes caused the opposite. Now IK cannot be disabled.

**Comment by thegrb93** [comment]
Not sure how it could be disabled before either. The 'size' parameter doesn't seem to be used. If you want to disable it, you can just set size to 1.0001. Since the experimental entity doesn't even have an option for it, I'm not going to worry about it.
