### ISSUE TITLE
Inverse Kinematics Option Borken

### ISSUE THREAD

**Issue by VCSoldier** [CapsAdmin/pac3#817]
The Option to enable inverse kinematics is broken in the entity settings tool bit, doesnt seem to work at all, feet still float over edges that should be adaptable please fix

**Comment by thegrb93** [comment]
It depends on of your model is being scaled, if it is then IK won't work

**Comment by thegrb93** [comment]
Also you need to be using the develop branch.

**Comment by VCSoldier** [comment]
wierd, the hands seem to use it but the feet dont. maybe its a experimental movement problem causing it

**Comment by VCSoldier** [comment]
Oh no wait its just feet are broken for some reason, idk why though

**Comment by thegrb93** [comment]
Try without pac installed, then with pac installed but no outfit, then with pac and with an outfit and see where it breaks.
