### ISSUE TITLE
listen server issues (was: I cant see someone for example, as Kirby in Pac3)

### ISSUE THREAD

**Issue by dany777** [CapsAdmin/pac3#82]
I was with a friend, we are wearing the Kirby Pac3, but we see eachother normal, for me i see myself Kirby, but i see my friend normal, anithing to fix?

When i wear the south park example, my camera goes crazy on first person
Doesnt stop shaking up and down and is annoying me, any fix? + it was on listen server, not dedicated

**Comment by CapsAdmin** [comment]
comment to myself: listen server issues
