### ISSUE TITLE
PAC3 "NetDeserializeTable" Error

### ISSUE THREAD

**Issue by Hermit17** [CapsAdmin/pac3#820]
Hello,
So recently I've been having this error with PAC3 where whenever I "clear" or "wear" any PAC's it gives me:

[ERROR] gamemodes/nutscript/plugins/pac.lua:66: attempt to call field 'NetDeserializeTable' (a nil value)
  1. func - gamemodes/nutscript/plugins/pac.lua:66
   2. unknown - lua/includes/extensions/net.lua:32

I've asked a few friends that are competent with coding for Lua, at least compared to me and they couldn't help me. I'd appreciate it if anyone has any insight on what the problem is.

**Comment by thegrb93** [comment]
Out of date nutscript or out of date pac3.

**Comment by Hermit17** [comment]
Thanks man, I have the Workshop PAC3 addon and I'm using Nutscript 1.1. I'll try to test some stuff, see if I can narrow down which one it is.

**Comment by thegrb93** [comment]
Most likely nutscript in that case

**Comment by Hermit17** [comment]
Do you know where I can find the most up to date nutscript version? Also, PAC just refuses to open now, very cool.

**Comment by thegrb93** [comment]
No idea. I assume github.

**Comment by Hermit17** [comment]
Gotcha, thanks.

**Comment by thegrb93** [comment]
https://github.com/Chessnut/NutScript/issues/830
