### ISSUE TITLE
Pac4 Animations continue to loop

### ISSUE THREAD

**Issue by StupidDogYoureMakingMeLookBad** [CapsAdmin/pac3#821]
I ade a pac4 with custom animations and when I use them they loop. I don't want this so I unchecked loop and they still loop! I want to do this so that it has time to play the sounds. I've seen it done before but I can't do it. I even tried timerx but not even that works! Please help

**Comment by thegrb93** [comment]
What's pac4? Can I have a sample animation? I'm not familiar with animations.

**Comment by StupidDogYoureMakingMeLookBad** [comment]
I'll send you a clip
