### ISSUE TITLE
Wearing appears to no longer reload your PAC Outfit clientside (Singleplayer)

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#830]
After testing out previous commits, I realised this issue has been going ever since the start of 2019. The only real workaround currently is using pac_wear_parts "PacnameHere" in the console after already loading the PAC up before wearing.

Surprisingly this small feature was something I never knew was that important until now, circumventing certain parts from generally loading incorrectly on the first load. Not only did it give feedback to the player that their PAC has applied (outside of console feedback), but it also reloaded the parts, E.G Holdtypes, that required a second load to properly function without the need of manually ticking and unticking hide afterwards.

Supposedly wearing PACs still loads somewhat normally in the latest commit for other people, but the lack of information given almost lead me to believe that my PACs weren't loading. 

*Yes, I've been on a server using a 2018 build all of this time, it's probably time I brought some light onto some newer issues experienced.*

**Comment by Logzombie** [comment]
Came back to update this, this only appears to occur in singleplayer now. Hosting peer to peer or going on a multiplayer server does not have this issue. Wear function just does not appear to reload in singleplayer. So won't close, but above info is horribly outdated.

**Comment by CapsAdmin** [comment]
I can't reproduce this on latest develop.

**Comment by Logzombie** [comment]
Update, this was fixed roughly 14 days ago. Likely caused by Gmod update. Until this is reproduced in an upcoming develop version, I can consider this _fixed._ Can likely close this now.
