### ISSUE TITLE
Other players Requesting outfits appears to reload YOUR PAC outfit on clientside.

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#832]
..Possibly related to #830? 

This is probably the most confusing issues out of the few that I've found in the latest master and developer commits as of this post. When another player on the server hits the "request outfits" button in utilities (now rather frequent due to #831), the PAC outfit currently being worn by a player will be reloaded on their own client. 

This isn't a particularly weighty issue, but a confusing one at that since it can occur while in the editor itself, possibly getting in the way of any editing currently being performed. Quite an annoyance unfortunately.

**Comment by thegrb93** [comment]
Outfitter induced issue maybe?

**Comment by Logzombie** [comment]
Coming back to close this issue, this was fixed ages ago and was used with a buggy version of PAC3. Re-open if bug regarding this is re-discovered.
