### ISSUE TITLE
Can't see other players pacs, but they can see mine. (PAC is enabled)

### ISSUE THREAD

**Issue by Zihut** [CapsAdmin/pac3#837]
Before you ask, yes i have enabled PAC3 and messed with all the settings. I deleted PAC3 multiple times, and uninstalled Gmod 2 times. Nothing works.
I can see my own PAC, and others can see them too. But when i look at others wearing PAC, it is like PAC is unenabled.

Some events dont work either, the Command and Button events do not work.

**Comment by thegrb93** [comment]
Sounds like a bad setting. delete cfg/client.vdf to clear your stored console settings.

**Comment by Zihut** [comment]
Thank you, i think this fixed my issue :D
