### ISSUE TITLE
Flex part value capped at 1

### ISSUE THREAD

**Issue by MEESTERSoupCan** [CapsAdmin/pac3#840]
I used to be able to set flex values past 1, usually up to 5 or 10. Was this change intentional, or something that was indirectly patched in?

**Comment by Techbot121** [comment]
while this is true for the `flex` part, you can still make funny faces using the new `faceposer` part by changing the scale.
![image](https://user-images.githubusercontent.com/3000604/188720532-3aa5748d-95bb-4150-9e78-daeee06fd15f.png)
