### ISSUE TITLE
Are steering wheel hands in PAC3 vehicles possible?

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#841]
At least, in the way I'm thinking? Here, refer to [this video](https://streamable.com/mnrj0) to see what I mean.

**Comment by thegrb93** [comment]
Probably depends on if the arms have an animation for it. So depends on the model. The working arms animation uses IKrules and such I assume. Or it could just be a pose parameter maybe.

**Comment by thegrb93** [comment]
I doubt normal hl2 playermodel arms have animations for it.

**Comment by mrwallace888** [comment]
Maybe if there was a thing where you could assign bones to things. So like, left upperarm gets assigned to the main model's bone "car body" (or whatever the root/base bone is), and the upperarm pivots there. Then you assign the left hand to the steering wheel bone, and then it can go from there or something.

**Comment by thegrb93** [comment]
There is follow bone option, but it does not do IK.

**Comment by mrwallace888** [comment]
Well I mean how do you even use that?

**Comment by thegrb93** [comment]
create some kind of pac part like a model and name it, then put that name in the bone follow part and the bone will follow it.

**Comment by mrwallace888** [comment]
Is it the aim part option
