### ISSUE TITLE
Custom .mdl animation issues

### ISSUE THREAD

**Issue by Max-Kore** [CapsAdmin/pac3#842]
I recently learned how to import custom models, and I was trying to import a player-model that uses a custom skeleton. 
  I was able to do this by loading the experimental model as normal though a dropbox link, then 
creating an experimental entity with the same dropbox link.
  The custom skeleton loaded, and the player-model worked as intended.
  However, whenever I jumped, fired a weapon, sat down, or did any action other than walking or crouching, the model reverted back to the default valve biped, resulting in improper proportions.
  It was possible to load back the custom skeleton by using the PAC3 'wear' option, but the model would still revert as it did before if I did any actions.
  No amount of changing the entity or model hierarchy had any effect on the glitch.
Issue #838 might be in reference to the bug.

**Comment by wrefgtzweve** [comment]
Had the same issue, switched from singleplayer to p2p friends only and it worked really buggy, then joined a server with pac and it worked fine.

**Comment by Yagira** [comment]
Make sure to set ``pac_modifier_model 1`` on both your client and the server. Also disable addons that force playermodels such as the enhanced playermodel selector.

**Comment by Techbot121** [comment]
I've used a few custom models now and it doesn't seem to happen to me, feel free to reopen if this is still the case.
