### ISSUE TITLE
I think Submaterial messes with bones oddly.

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#843]
I don't really know how to describe it, I think this occurs with a model that has a submaterial set.

So basically, let's say I adjust a bone on a model attached to an owner, with the model having submaterials. I got the upperarm bone, I give it an animation (I don't think the animation part matters whatsoever, but this was what I was doing) using the "custom animation" thing, let's say just moving the arm up and down. Then I adjust the bones for the forearm, hand and fingers as I please. Then I add a new model, and once I try to put it on one of the bones on the arm or whatever, then the arm gets broken. It's like the child bones of the upperarm have not been edited. I can't change their size, rotation, or anything else. They're stuck with the values for everything being zero (the axis stuff still shows the number I put in, but visually the bones don't change at all). Even if I wear the item it still does it.

I'm likely overcomplicating this, I don't really have a video as of now to show what I'm talking about. But I don't know, just something seems to break the bones back to their normal state. The animation for the upperarm can still play, but the child bones won't visually be edited by anything. I think this happens on all the models I've used that have had submaterials and such. I don't think it does it to other things.

**Comment by mrwallace888** [comment]
Fix?

**Comment by thegrb93** [comment]
Give example pac
