### ISSUE TITLE
Is it possible to change the code somehow so that it works with Advanced Bone Tool?

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#845]
Weird question, but you think it might be possible to make PAC3 compatible with Advanced Bone Tool? I can edit bones on... let's say a ragdoll that has certain bones on it that don't have physics and can be moved with the Bone Tool instead. Anyways, so I can edit stuff with the tool, but PAC3 resets the angle, size, position, etc. of all the bones I've edited with the tool once the outfit owner is set to that ragdoll. And even after that, I can't edit the bones again, nothing visually changes.

**Comment by Techbot121** [comment]
is it possible? probably, but I don't think many people will use it that way and it seems to be a niche use case. Maybe a copy bone position/orientation tool from existing entities would be more useful instead.
