### ISSUE TITLE
Adding sounds to Custom Animations?

### ISSUE THREAD

**Issue by mrwallace888** [CapsAdmin/pac3#846]
When you make a custom animation, when you wear the outfit it'll play the animation and the animation will loop.

Is there a way to make it so that you can make it play a sound for every time the animation loops?

**Comment by mrwallace888** [comment]
Bump?

**Comment by thegrb93** [comment]
Maybe a proxy timer? I don't know of any method.

**Comment by Techbot121** [comment]
I more or less added it in a way, still need to do multiplayer testing. 
The option is only visible on the `event` part if you have a custom animation on your outfit and looks like this:
![image](https://user-images.githubusercontent.com/3000604/188723564-577e5fa2-f2d6-4f93-809f-90a0562306f6.png)

you can specify which animation to use (kinda cryptic at the moment) and the frames at which it should trigger:
![image](https://user-images.githubusercontent.com/3000604/188723688-af3a1942-4ab8-42bf-8b17-17cee6e94436.png)

if you need something that holds it for a while combine it with a timeex proxy or something
