### ISSUE TITLE
"Command" expression in proxy takes value from part name instead of an argument

### ISSUE THREAD

**Issue by GrandpaScout** [CapsAdmin/pac3#847]
I don't know if this is intended, but using a `command()` expression takes the name of the proxy part as its argument when searching the player's `pac_proxy` commands instead of an argument on the function itself.

For example, a proxy named "foo" with the expression `command("bar")` will only change when the player enters `pac_proxy foo x y z` into the console

**Comment by Techbot121** [comment]
this is intended. 
While it may look like it, `command()` doesn't actually take any input at all and is just intended to be used directly without arguments, similarly how `time()` or `timeex()` work for example.
