### ISSUE TITLE
Webaudio + Streaming music + events = errors

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#85]
Pretty much, PAC breaks when you try to stream music through Webaudio and have it toggle with events (or even try to put an event on one)

[ERROR] lua/pac3/core/client/parts/webaudio.lua:161: Cannot use SetTime on a block streamed audio channel. Use the 'noblock' flag when creating the channel to disable block streaming.

**Comment by Python1320** [comment]
maybe we can just add noblock option
