### ISSUE TITLE
Webaudio not playing on the first time it's toggled

### ISSUE THREAD

**Issue by Cl3ffy** [CapsAdmin/pac3#853]
As the title says, when I try to play a webaudio, it wont play on the first toggle but works fine afterwards. Going in and out of thirdperson mode will reset this issue making it rather frustrating.
This issue has been around for probably atleast a year now, but it hasn't always been a thing.

Here's a video demonstrating the issue. The audio might be a little quiet. The file played is an mp3 file uploaded to dropbox.
https://www.youtube.com/watch?v=mNeBR_FbRs4

**Comment by LegitSpy** [comment]
Try making it a wav instead. I remember i once had this issue but i don't exactly remember how i fixed it. This might be a possible solution though.

**Comment by Cl3ffy** [comment]
WAV files don't seem to work at all for me.

**Comment by LegitSpy** [comment]
Well, i tried...

**Comment by thegrb93** [comment]
@Cl3ffy I just committed an update to https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/parts/webaudio.lua on the develop branch. See if that fixes the issue.

**Comment by Cl3ffy** [comment]
I did some testing with DBot and it turns out the issue was not in the webaudio but in the event.
There is a simple workaround which is to make the event a child of the sound and not the other way around.
