### ISSUE TITLE
Friends

### ISSUE THREAD

**Issue by Phoenix282917** [CapsAdmin/pac3#855]
I can see there pac but they cant see mine what do I do btw im new to it so idk much about settings

**Comment by thegrb93** [comment]
Easiest fix is delete cfg/client.vdf

**Comment by Phoenix282917** [comment]
How do I do that and what does that mean

**Comment by thegrb93** [comment]
Open your garrysmod folder on your computer and delete that file to reset it

**Comment by Phoenix282917** [comment]
Will I lose all my work?

**Comment by thegrb93** [comment]
Just settings

**Comment by Phoenix282917** [comment]
So I will lose nothing right?

**Comment by thegrb93** [comment]
right

**Comment by Phoenix282917** [comment]
Ok good thank you well we will see

**Comment by Phoenix282917** [comment]
Um how do I get to the files

**Comment by thegrb93** [comment]
Right click game in steam -> Properties -> Local Files -> Browse Local Files

**Comment by Phoenix282917** [comment]
Oh ok thank you

**Comment by Phoenix282917** [comment]
How do I delete it

**Comment by thegrb93** [comment]
Right click file -> Delete

**Comment by Phoenix282917** [comment]
K

**Comment by Phoenix282917** [comment]
So I did it will my friends see my pac and will I have all my work?

**Comment by thegrb93** [comment]
See for yourself

**Comment by Phoenix282917** [comment]
Thanks

**Comment by Phoenix282917** [comment]
He still can't see it

**Comment by thegrb93** [comment]
Maybe it's their settings, or your outfit is marked as 'disturbing' and they don't have disturbing option enabled.

**Comment by Phoenix282917** [comment]
Hm ok I will try it

**Comment by Phoenix282917** [comment]
We have the same settings and I can see his he can't see my pac wtf

**Comment by Phoenix282917** [comment]
When he leaves and rejoins he can see it but when I change pac he then can't see it
