### ISSUE TITLE
When detecting owner_velocity_up in an event (presumably parent as well), the event can fire randomly when pressing forwards or backwards.

### ISSUE THREAD

**Issue by Vuthakral** [CapsAdmin/pac3#856]
I have an event which is checking owner_velocity_up, if it is equal to or greater than 5.

My intention for this event is to tell if the player is either falling or moving downhill. The  event fires randomly to be either when pressing forwards or backwards as well, regardless of if moving uphill/downhill. The "randomly" is in regards to which motion (forwards/backwards) will cause it to trigger. 

Example:
Event set to find owner_velocity_up equal to or greater than 5:

* Will trigger when jumping as velocity is > 5
* Will trigger whether moving either up or downhill when moving forwards or backwards exclusively. Never both directions triggering this at once.

__________

Sidenote: Is there a better way to achieve what I am trying to do (detecting if a player is moving up/down in the world space)?

**Comment by thegrb93** [comment]
Looks like the implementation of owner_velocity_up is the velocity in the camera's up direction. Would probably be better for that to be velocity in the world up direction.

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/blob/97ab99e9e8f5f16063ee5480ee33d21970822b8c/lua/pac3/core/client/parts/event.lua#L767

**Comment by thegrb93** [comment]
owner_world_velocity_up could be added to resolve this.

**Comment by thegrb93** [comment]
I pushed the master by accident. It's in develop now.
