### ISSUE TITLE
gmod crashes when opening a map

### ISSUE THREAD

**Issue by dueldragon** [CapsAdmin/pac3#86]
i downloaded pac3  and then i realized that when i load a map gmod crashes to desktop without warning or any report. it's just freezes when the map is about load completly and then crashes. i figured that pac3 is causing it. and i want this addon. so what can i do?

**Comment by Marstruc** [comment]
So... I know this is necro-ing, but I've been checking this out. PAC3 seems to have a problem loading. No folder is created in the /data folder in garrysmod/garrysmod/. The only way to FIX this, is to delete your data and cache folders, and unload PAC3. I'm unsure why, but this just seems to be the problem.

**Comment by LUModder** [comment]
Marstruc, I already said how to fix it, it's a problem with the autoload file sometimes glitching on loading, as far as I know, it has been fixed, you don't need to delete your WHOLE data folder to fix it.

**Comment by Marstruc** [comment]
And as I said... the folder isn't even created.

**Comment by LUModder** [comment]
You're not even the OP, unless you are, but it doesn't seem like it.

**Comment by Marstruc** [comment]
Does it matter? Really?

**Comment by LUModder** [comment]
Honestly, it does and doesn't, you're telling people how to fix it the wrong way, even if you have or haven't had the problem.
