### ISSUE TITLE
Problems with the automatic loading of other players' outfits.

### ISSUE THREAD

**Issue by Sephotai** [CapsAdmin/pac3#860]
For a while now, I've had to click on the "request outfits" button to see other players' PAC3s as soon as they change them, whereas before I had absolutely no need to do that and as soon as a player changed or put in an outfit, I could see it directly without having to click on the button or make a bind of it. Can you help me with this, please ?

**Comment by thegrb93** [comment]
Try resetting your pac settings by removing the client.vdf in garrysmod/cfg. Note: other addon's settings will be reset too.
