### ISSUE TITLE
[Issue] PAC 3 isn't working properly in Clockwork

### ISSUE THREAD

**Issue by Contamination** [CapsAdmin/pac3#863]
Hello guys, i'm actually running a under a Clockwork schema, i installed the original PAC3 addon from the workshop and here's the two problems i encounter:

First, if I install the "PACpatch" plugin in clockwork it is possible to wear something, but even if you choose a basic model in the character creation, PAC patch is made to "clear" every parts, so you spawn with your sandbox model...

If i remove the PAC patch plugin, I can't wear anything, I have several saves where I change the basic playermodel origin with the "entity" option, so when my pac entity is set as let's say Male07 model, it only wears the Male07 model with nothing else that i've created in the save.

I hope you can help me, I can go on a discord if writing doesn't help much and would be very happy to give you more precisions if needed, have a nice day!

**Comment by thegrb93** [comment]
I don't know anything about clockwork. All I know is pac3 is designed for sandbox. Maybe you can try updating your version to the latest develop branch here instead of workshop.
