### ISSUE TITLE
Does not work bone fingers.

### ISSUE THREAD

**Issue by Heyter** [CapsAdmin/pac3#864]
https://dropmefiles.com/OA5OF video

[2020-03-01 23-46-16.zip](https://github.com/CapsAdmin/pac3/files/4272432/2020-03-01.23-46-16.zip)

sbox_bonemanip_misc 1
sbox_bonemanip_player 1
sbox_bonemanip_npc 1

**Comment by thegrb93** [comment]
Fingers are controlled by flex controllers I think.

**Comment by Heyter** [comment]
> Fingers are controlled by pose parameters I think.

Nope, nothing changed..

**Comment by thegrb93** [comment]
Hm, yeah you're right; Looking at the fingerposer tool, it uses ManipulateBoneAngles. Same thing pac3 uses I believe. https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/entities/weapons/gmod_tool/stools/finger.lua#L393

**Comment by thegrb93** [comment]
Just saw https://github.com/Facepunch/garrysmod-issues/issues/4402 . I think we can close then.

**Comment by Heyter** [comment]
> Just saw [Facepunch/garrysmod-issues#4402](https://github.com/Facepunch/garrysmod-issues/issues/4402) . I think we can close then.

I don't understand, how this helped me?
How me solve my problem???

**Comment by thegrb93** [comment]
In your graphics settings turn up model detail.
