### ISSUE TITLE
Flashing PAC case

### ISSUE THREAD

**Issue by SPICEYNO** [CapsAdmin/pac3#867]
Basically, every time something slightly big is spawned, the pac starts flashing repeatedly, with you mostly not being able to see the pac itself. This has been happening for a while and ive tried solutions for similar problems with no result.
Video: https://steamusercontent-a.akamaihd.net/ugc/777374397319519156/FF6C6D85D6B1310C4CBDF2874347B52589E3FF61/

**Comment by DBotThePony** [comment]
![firefox_qSVQAek2oe](https://user-images.githubusercontent.com/6339511/82457495-b26b9180-9adf-11ea-959a-9224a6d3c709.png)

Also, you might have rendertime limit option enabled
