### ISSUE TITLE
MDL zips should check for existing models in the game and skip not found ones

### ISSUE THREAD

**Issue by Cynosphere** [CapsAdmin/pac3#868]
> [PAC3] the model want to include models/pac3_cache/1315907695/f_anm.mdl but it doesn't exist
> [PAC3] the model want to include models/pac3_cache/1315907695/custom_animation_female.mdl but it doesn't exist

f_anm.mdl is a stock GMod model used by all player models
custom_animation_female.mdl was from an older version of Custom Taunt but is entirely optional

Whether or not a model should be optional is going to be hard to determine is the issue.

[Model used](https://steamcommunity.com/sharedfiles/filedetails/?id=1844633740)

**Comment by WTTG2Noir** [comment]
bc those are not valid paths like before compiling the f_anm.mdl etc needs to be in the given folder of the $cdmaterials "<path>"

**Comment by Cynosphere** [comment]
> f_anm.mdl is a stock GMod model used by all [female] player models

**Comment by thegrb93** [comment]
So I guess the behavior should be modified so if it can't find the model, it checks if it exists in the game?

**Comment by CapsAdmin** [comment]
Sounds reasonable to me. Not sure how to generalize this though. 

How does the code know where to find f_anm.mdl if it's not included? Should we use a lookup table or does mdl support some sort of fallback mechanism? Lookup table for models like f_anm is probably fine for now.

**Comment by thegrb93** [comment]
I'm current experimenting with it

**Comment by Yagira** [comment]
You know what would be better, being able to include additional mdl files in your zip so you could actually import models that have custom animation sets.

**Comment by thegrb93** [comment]
That would be good in addition to this.

**Comment by thegrb93** [comment]
I got the other animation errors fixed, but still get `[PAC3] the model want to include models/pac3_cache/1370833833/custom_animation_female.mdl but it doesn't exist
`

**Comment by thegrb93** [comment]
You can try the fix in that pull request and let me know how it goes.

**Comment by thegrb93** [comment]
@Yagira actually I think it already supports that.

**Comment by thegrb93** [comment]
I'm not sure how it selects which model to be the primary model though..

**Comment by Yagira** [comment]
Yeah well, the thing is, it doesn't really work. Maybe its specific to the model I tried but the animations are completely messed up. Also including the animation .mdl seems to break the materials? There's also a huge fps drops when using it as my entity.
You can try it yourself.
https://dl.dropboxusercontent.com/s/4de40jrynqdl9yf/pac%20test.zip - animation .mdl included
https://dl.dropboxusercontent.com/s/pv98vfcs0xvfpbe/pac%20test2.zip - no animations

**Comment by thegrb93** [comment]
I think there's another unrelated bug causing that.

**Comment by thegrb93** [comment]
The fps drop is due to the fucked up materials I think.

**Comment by thegrb93** [comment]
Yeah it's another bug. The .mdl didn't get edited properly. I decompiled the mdl and you can see the material names are wrong.
