### ISSUE TITLE
PAC outfits refuse to wear for others

### ISSUE THREAD

**Issue by MatteBlackMan** [CapsAdmin/pac3#870]
I've had a problem with all the versions of PAC I've used for a couple months now, and that's that my outfits refuse to apply and display for others in any given server, even my own. I have disabled all other add-ons for my game, only leaving PAC on, and yet the problem persists. Both the 32 and 64 bit versions give me this problem. This is very frustrating as I have put a lot of time and effort into the PACs that I wear. If there's any more information need to investigate the issue then I am more than willing to give you it

**Comment by Yagira** [comment]
Try resetting your addons. Close GMOD, find and delete the cfg/client.vdf and cl.db files in your garrysmod folder.

**Comment by MatteBlackMan** [comment]
I've tried what you have suggested, and I am still unable to wear outfits. 
Also, I do not agree with the "addon conflict" tag, as I stated in my initial paragraph that I had started a game with every addon I had completely off

**Comment by thegrb93** [comment]
It's the addons of the server that could be causing issues. Not the ones of your game.

**Comment by thegrb93** [comment]
It sounds like you have the player whitelist enabled or something. Basically it only lets players you specifically allow to see the outfit.

**Comment by MatteBlackMan** [comment]
I'll have a look at it, I usually never touch the whitelist but I've had problems with settings that switch on without me noticing before

**Comment by MatteBlackMan** [comment]
I have come to the conclusion that it was an add-on conflict, thanks for putting up with my issue

**Comment by thegrb93** [comment]
Glad you found the problem.
