### ISSUE TITLE
PAC3 messes with F2S: Stronghold weapon animations

### ISSUE THREAD

**Issue by Fires1** [CapsAdmin/pac3#875]
Heyo!

Using most recent version, with Pointshop 2, noticing in Stronghold weapons will do one of few things

- Flip to opposite side of screen

- Change model to other weapons while remaining functionally the same

- Animation will "reset" to the draw animation

I isolated this problem to PAC3 and as a short term solution disabled PAC3 and Pointshop when the server's on Stronghold, we are a variety server so we change gamemodes and it works fine everywhere else.

Few questions: What could be causing this and is there a way I can easily fix it gamemode side? Or is it possible to disable PAC3 from fuckering around with weapons entirely.

Thank you!

**Comment by thegrb93** [comment]
IIrc pac3 likes to spam the bone manipulation functions despite not wearing a pac. Can't remember if I fixed that or not.

**Comment by Fires1** [comment]
I have a Stronghold repository if anyone needs to look into it. It's an abandoned gamemode so I'm trying to fix as much as I can. Do you have any ideas or solutions @thegrb93 ?

**Comment by Fires1** [comment]
I'll do some testing later and keep this thread posted.

**Comment by Fires1** [comment]
Some observations since I haven't had time to use your example:

We were testing and primarily realized the core of the issue stems from player model changes.

1) Animation "resets" to the deholster when a player spawns with a custom model

2) Animation "resets" to the deholster animation when a player changes custom player model.

We couldn't find it to happen with any other Pointshop item changes. Just players

**Comment by Fires1** [comment]
I also had some temporary luck with changing Pointshop 2 from setting bodygroups when a model is changed, see https://github.com/Kamshak/Pointshop2/blob/ef748dda9a2265a2080c617b850ef251025b56fd/lua/kinv/items/pointshop/sh_base_playermodel.lua#L39-L43

This worked to a degree. On my screen I just saw my gun sort of shift outwards and come back, but for my helper it didn't change at all.

**Comment by Techbot121** [comment]
reopen if you feel this is still an issue, bones have changed quite a lot since this issue was created.
