### ISSUE TITLE
Downloaded model needs child materials to update after model is downloaded

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#877]
Self-explanatory. Material 3D parts applied to an imported mdl with multiple material overrides (basically to anything that isn't set to ALL) don't load properly upon first wear. It seems to lose all ability to override whatsoever, and just puts whatever texture on the entire model. 

Edit: Tested on bonemerged Ragdolls as opposed to material 3D on entity. (This is preferred for getting animation parts to actually function as intended from prior experience)

First wear:
![image](https://user-images.githubusercontent.com/50374409/80147304-39921c00-85ab-11ea-9b22-d249df17334b.png)

Second wear: (intended result)
![image](https://user-images.githubusercontent.com/50374409/80147528-8d046a00-85ab-11ea-861f-5a96abbb7c90.png)

**Comment by Yagira** [comment]
The material override setting is a mess and breaks everything. Sometimes it replaces the materials on props/map/other players/whatever.

**Comment by Logzombie** [comment]
@thegrb93 Example:

[!material3dtest.txt](https://github.com/CapsAdmin/pac3/files/4918740/material3dtest.txt)

Note: What you see loaded before wearing is what other players will see when you first wear. Wearing again rectifies said issue.
Edit: Updating this to bonemerged ragdolls, as this is what I'm testing this with.

**Comment by thegrb93** [comment]
The problem also happens with material_2d so its any material. Also it fixes after hiding and showing the part. I think it's more likely a problem with the submaterial implementation or the material part not created yet by the time the entity part is showing.

**Comment by thegrb93** [comment]
Looks like a gmod bug.

When the entity is first shown, entity:GetMaterials() returns
```
CSEntity [class C_BaseFlex]
1	models/error/new light1
```

But after hiding and showing again, we get
CSEntity [class C_BaseFlex]
1	pac3_cache/2716971774/headlol
2	pac3_cache/2716971774/skoside_2
3	pac3_cache/2716971774/byxa_fram_2
4	pac3_cache/2716971774/byxa_bak_2
5	pac3_cache/2716971774/sko_under
6	pac3_cache/2716971774/hand
7	pac3_cache/2716971774/jacket_front
8	pac3_cache/2716971774/jacket_back
9	pac3_cache/2716971774/chainsawtex1
10	pac3_cache/2716971774/tex1

**Comment by thegrb93** [comment]
Maybe has something to do with the model being downloaded?

**Comment by thegrb93** [comment]
Yeah, I think the problem is the model isn't set yet because it's still being downloaded, the materials try to apply but can't.

I guess the solution is for downloaded models to trigger materials to update after finishing.

**Comment by thegrb93** [comment]
@Logzombie a work-around for now is to include the materials in the zip instead of trying to use material parts.

**Comment by CapsAdmin** [comment]
I've made a crude fix, but i think it should work. 

Please confirm.

**Comment by Logzombie** [comment]
Update, "crude fix" appears to be working so far with no major issues, at least none that I can find after multiple tests with multiple PACs that utilise a heavy amount of Material parts allocated to different areas on a single model. Will re-open if this begins to fail or open a new issue regarding a bug that may require this mentioned. Hopefully by now, no others should be having this issue on the newest develop versions considering the accuracy it has managed for my stuff.
