### ISSUE TITLE
Pasting a new link into experimental Sound's url causes errors until rewear

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#878]
Essentially this has started spamming the chat with errors only recently. Upon applying a new url into experimental sound parts, it will cause errors in the chat until reworn entirely. Causing the outfit to refresh upon every trigger, albiet still not fixing the issue until the wear button is manually pressed.

(At this point I'm just dumping a bunch of issue reports on things people have failed to report issues on. There's a lotta shite that needs fixing)

![image](https://user-images.githubusercontent.com/50374409/80147835-0439fe00-85ac-11ea-8a37-98e86908dcbe.png)

**Comment by thegrb93** [comment]
Are you using the develop branch of pac3? We had this reported before and switching to develop fixed it.

**Comment by Logzombie** [comment]
Double checked, I was using an outdated version of the develop branch. This seems to be functioning on the latest version. That, and I didn't see a previous post for this thus decided to post this issue. My bad, this is already fixed by the looks of it. If I find any other particular issues related to this, I'll reopen it.
