### ISSUE TITLE
Random sunbeams appearing on player

### ISSUE THREAD

**Issue by TankNut** [CapsAdmin/pac3#88]
On several occasions I have run into the issue where what appears to be a sunbeam effect appears on a player that's wearing a PAC outfit even if they don't have the effect itself added to their outfit.
![2014-10-05_00001](https://cloud.githubusercontent.com/assets/1381265/4518830/2f62aa9a-4ca1-11e4-9c2a-7656fece2a20.jpg)

(This happens to other players on the server as well, providing they have PAC activated.)
(So far I have only seen it happen on a server, singleplayer appears to be fine.)

**Comment by CapsAdmin** [comment]
reopen if this is still an issue
