### ISSUE TITLE
The Owner Alive event doesn't actually detect whether the owner is alive or not

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#880]
Yeah this just.. doesn't function, like, at all. Unless there's some hidden definition on what this should actually do, inverted or not, this just doesn't appear work.

**Comment by thegrb93** [comment]
Does is_on_fire event work? It is implemented the same way. If so then I have no idea whats wrong and it might be a conflicting addon.

**Comment by thegrb93** [comment]
That or clientside ent:Alive() doesn't work and that would be a gmod bug.

**Comment by Logzombie** [comment]
Likely a Gmod bug considering I'm not using any additional active addons, this occurs either way.

**Comment by thegrb93** [comment]
Seems to work fine for me. Going to need an example.
