### ISSUE TITLE
PAC3 Does not work in local and P2P servers at all?

### ISSUE THREAD

**Issue by Cordon** [CapsAdmin/pac3#884]
You can see your own PAC, but you can't see anyone else's, no matter how many times they wear it. Weirdly enough, NPCs with outfits work (at least NPC dupes that have outfits on them do).
Restarting PAC or requesting outfits doesn't do anything either.

**Comment by DBotThePony** [comment]
did you tried develop branch?

**Comment by Cordon** [comment]
Yeah, I always use develop.

**Comment by KeksyBatsy** [comment]
You can try to delete or move cl.db in garrysmod dir, and see if it fixed.

**Comment by thegrb93** [comment]
or also client.vdf in cfg
