### ISSUE TITLE
Pac3 overriding playermodels when cleared

### ISSUE THREAD

**Issue by Sovient** [CapsAdmin/pac3#885]
Hi

I'm having this issue on my server where if a player clears his pac, it will switch to a playermodel we have and force users to use it regardless of choice until they rejoin the server. This applies for changing jobs (Since we are running on the DarkRP gamemode) which forces users to be a model their not supposed to be having, any help?

**Comment by maxwebbnz** [comment]
Same here, seems to be happening server wide.

**Comment by Yagira** [comment]
pac_modifier_model 0

**Comment by thegrb93** [comment]
Yeah an entity part will return your model to what it was when you wore the pac.

**Comment by thegrb93** [comment]
I think Yagira's solution is most suitable for rp servers.
