### ISSUE TITLE
PAC3 Metal Banging Sound

### ISSUE THREAD

**Issue by Noahbg** [CapsAdmin/pac3#886]
PAC3 is causing metal banging sounds when walking around or just doing anything. Its a 50/50 chance of it happening, but when it does it's unbearable causing the server to be unplayable. I will try and get a video of it happening if possible. I'm not sure if it's because of the small gmod update the other day, since before that it was working fine.

**Comment by owltaver** [comment]
yeah, that's because clientside models now properly initializes its world matrix on creation

**Comment by thegrb93** [comment]
I've actually not seen this happening. Is it because the parts are colliding with each other or something? It still doesn't really make any sense.

**Comment by owltaver** [comment]
> I've actually not seen this happening. Is it because the parts are colliding with each other or something? It still doesn't really make any sense.

It's actually a little worse.

CModels do collide and this can cause spam sounds, depending on material that is set on model. Also some crazy stuff with physix happenning. CModel physics may break and all clients geting spam in console with crazy physix warnings. Model phys objects can just fly away and collide with any stuff on map. So if player have a lot models it can just cause lagg or freeze clients.

**Comment by thegrb93** [comment]
Is there an example outfit somewhere?

**Comment by owltaver** [comment]
here some exemple: https://pastebin.com/rKBXWSY6
one iteresting thing - it work imedeatly on wear if you change debug clmdl mode to 2 (pac_debug_clmdl 2)
i guess that because second mode uses ents.CreateClientProp that was affected in update.

**Comment by Noahbg** [comment]
Is there any way to fix this?

**Comment by Noahbg** [comment]
Bump

**Comment by thegrb93** [comment]
Doesn't clank if you use pac_debug_clmdl 0. Just use that? I can add a setmovetype in 2's case but see if the first option works.
