### ISSUE TITLE
PAC won't load outfits

### ISSUE THREAD

**Issue by Matryan** [CapsAdmin/pac3#89]
Hey,
I run a new sandbox server and I decided to install PAC.
I used this git repository but when ever anyone tries to load their outfits, nothing happens...
This gets spammed in console:

"luadata decode error:
attempt to call a nil value"

I'm not sure what's wrong here but I'm thinking it could just be my server's config... But I don't know.

Cheers,
Matt.

**Comment by killincreepers1** [comment]
I understand this is old, but can you explain your fix?

**Comment by Matryan** [comment]
I don't really remember. 
I think it may have been my custom Anti-Cheat...

**Comment by LUModder** [comment]
I know QAC causes problems with PAC and can't read files so.
