### ISSUE TITLE
I need help with this.

### ISSUE THREAD

**Issue by seeiker** [CapsAdmin/pac3#897]
Hi, Good morning, Today I have a problem that I want to solve a long time ago, A long time ago I had a server and I stopped doing it for this, because I did not know how to solve it. I am very beginner on the subject of pac3, but what I have done is this.
I wanted to edit the playermodel on my previous server, but after touching things, it ended like this and I never knew how to return it to normal as it came in the steam workshop, but today the problem persists, I need help with this as soon as possible, I am carrying out a project and it will be ruined by this.
I already tried to fix it with youtube videos like "Immersive First Person" But when I "had it" I think, all the playermodels were changed at the height of a dog. I don't know what to do anymore. Please help me.

![Screenshot_30](https://user-images.githubusercontent.com/65847831/82765683-2dd68700-9def-11ea-8a26-14f1668cab03.png)

![Screenshot_29](https://user-images.githubusercontent.com/65847831/82765686-3333d180-9def-11ea-86bd-d4b1c248c687.png)

![Screenshot_31](https://user-images.githubusercontent.com/65847831/82765690-38911c00-9def-11ea-9a5c-8a7770529eac.png)

**Comment by thegrb93** [comment]
Need the troublesome outfit in order to help.

**Comment by seeiker** [comment]
The skin?

**Comment by seeiker** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=656834283&searchtext=

**Comment by thegrb93** [comment]
The pac outfit
