### ISSUE TITLE
Death ragdollize parent not properly unsetting part.draw_hidden

### ISSUE THREAD

**Issue by Zeni44** [CapsAdmin/pac3#900]
When toggling the "death ragdollize parent" option in the entity part, your own and other player pacs using the same feature seem to turn invisible upon the player dying and respawning. 
It doesn't seem to happen 100% of the time and going back into firstperson (from death camera or thirdperson addons) fixes it on your own pac on your end only.

From what I found it seems to be `part.draw_hidden` still being set to `true` on each part.
As for the pac fixing itself it seems to be camera related when the local player's pac is invisible/visible which calls`pac.HideEntityParts` and/or `pac.ShowEntityParts` which leads to `part.draw_hidden` being set back to `false`

**Comment by thegrb93** [comment]
Maybe the ragdoll being hidden/deleted hides the outfit and then player respawning doesn't unhide it? Or some kind of race condition between the two.

Add debug.Trace() after `function pac.HideEntityParts(ent)` and after `function pac.ShowEntityParts(ent)` and then reproduce the issue and show the latest few stack traces.

**Comment by Zeni44** [comment]
```
] ctp

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 251	"ShowEntityParts"		addons/pac3/lua/pac3/core/client/part_pool.lua
	3: Line 840	"v"		addons/pac3/lua/pac3/core/client/part_pool.lua
	4: Line 84	"nil"		lua/includes/modules/hook.lua

Zeni suicided!

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 251	"ShowEntityParts"		addons/pac3/lua/pac3/core/client/part_pool.lua
	3: Line 840	"v"		addons/pac3/lua/pac3/core/client/part_pool.lua
	4: Line 84	"nil"		lua/includes/modules/hook.lua


Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 236	"HideEntityParts"		addons/pac3/lua/pac3/core/client/part_pool.lua
	3: Line 759	"v"		addons/pac3/lua/pac3/core/client/part_pool.lua
	4: Line 84	"nil"		lua/includes/modules/hook.lua

] aowl revive
```
This was tested on the master branch while remaining in thirdperson the entire time.
I also tried it on the develop branch and it seems to happen there as well.

After reviving/normally respawning, it still remained hidden. 
Guess it's a race condition issue? I would create a pull request myself but pac is too vast for me to find the proper cause instead of a workaround.

**Comment by thegrb93** [comment]
So the first one is when you died, then the second two are when you respawn?

**Comment by thegrb93** [comment]
Could you update to 'develop' branch and before the `debug.Trace()` add `print(ent, CurTime())`? That will help me know what frame these occured and what entity they occured on.

**Comment by Zeni44** [comment]
> So the first one is when you use the camera to correct it, and the next two are when you die and respawn?

Correct, these are the results I get on the develop branch

```
] ctp
Player [1][Zeni]	12104

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 261	"ShowEntityParts"		addons/pac3/lua/pac3/core/client/part_pool.lua
	3: Line 859	"v"		addons/pac3/lua/pac3/core/client/part_pool.lua
	4: Line 84	"nil"		lua/includes/modules/hook.lua

] kill
Zeni suicided!
Entity [173][class C_HL2MPRagdoll]	12236

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 261	"ShowEntityParts"		addons/pac3/lua/pac3/core/client/part_pool.lua
	3: Line 859	"v"		addons/pac3/lua/pac3/core/client/part_pool.lua
	4: Line 84	"nil"		lua/includes/modules/hook.lua

Entity [173][class C_HL2MPRagdoll]	12237

Trace:
	1: Line 32	"Trace"		lua/includes/extensions/debug.lua
	2: Line 245	"HideEntityParts"		addons/pac3/lua/pac3/core/client/part_pool.lua
	3: Line 778	"v"		addons/pac3/lua/pac3/core/client/part_pool.lua
	4: Line 84	"nil"		lua/includes/modules/hook.lua

] aowl revive
```

**Comment by thegrb93** [comment]
Does the server have `pac_sv_hide_outfit_on_death 1` ?

**Comment by Zeni44** [comment]
`"pac_sv_hide_outfit_on_death" = "0"`

At least setting it to `1` makes it reappear on each respawn but obviously results in the outfit being hidden on death.

**Comment by thegrb93** [comment]
I think it's this https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/part_pool.lua#L796 causing this https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/core/client/part_pool.lua#L768 to trigger. Try removing the `ent:GetNoDraw() or` case from that `if` and see if that helps.

I'll take closer look after I'm done with the zip fixes

**Comment by Zeni44** [comment]
Haven't been able to reproduce the bug with that line removed.

**Comment by thegrb93** [comment]
I think if you can change that line to
`if (ent:GetNoDraw() and not (ent.pac_death_ragdollize or ent.pac_death_hide_ragdoll)) or`
that'll solve the issue. If you can confirm, then I'll put the fix in.

**Comment by Zeni44** [comment]
The fix seems to work but if you have anything that ends up calling `ply:Kill()` on an already dead player, it will break again like before.

Not sure how important that is since only custom stuff will probably invoke that kind of behavior but may be something to consider

**Comment by thegrb93** [comment]
Does that happen with that whole condition removed, like your previous test? I'm considering just removing the ent:GetNoDraw()

**Comment by Zeni44** [comment]
Having the`ent:GetNoDraw()` check removed makes it work as intended.
The test model and friend I abducted with his pac shows as intended even when `ply:Kill()` gets called on them again while dead.
Guess that's it?
