### ISSUE TITLE
Others pac is flicking on and off all the time

### ISSUE THREAD

**Issue by JakeAspire** [CapsAdmin/pac3#902]
It's been going on for a month. Whenever I come into drawing distance of somebody, their pac loads in and then immediately goes away, and then it starts flicking, like I can see it one second and then its gone, constantly. I'm not getting any errors about it in console, and I really don't know what is going and why. I have reinstalled g-mod and my add-ons a couple of times, didn't help.

Addendum: could me being in a US-sanctioned region be a problem? 
Addendum2: Seems to be happening a lot less on non-beta version of g-mod. Happens a lot on chromium- Same as x86-64 but an update behind.

**Comment by Yagira** [comment]
Try `pac_override_fov 1` it usually helps with similar problems.

**Comment by JakeAspire** [comment]
Thank you. I will try doing that in 1-2 hours and see if it changes anything.

**Comment by JakeAspire** [comment]
Hello, pac_override_fov 1 does nothing to fix the issue for me.

**Comment by Yagira** [comment]
No idea then. You can try to reset your addon settings. Close GMod, find and delete the `cfg/client.vdf` and `cl.db` files in your `garrysmod` folder.

**Comment by JakeAspire** [comment]
Hello again, removing cl.db didn't work. Couldn't even find cfg/client.vdf anywhere. I also tried removing pac from my addons folder, unsubbing from the add-on and using pac3masterfile.

**Comment by DBotThePony** [comment]
do you have render time limit set? in pac3 settings

**Comment by JakeAspire** [comment]
Yes,its set on 5

**Comment by JakeAspire** [comment]
Yeah, turning it to 0 helped, I think, I don't remember making it 5 though...
Anyways, thank you!

**Comment by thegrb93** [comment]
Gotta love servers tweaking their clients' pac settings. There should be a message in the new issue for resetting the settings first.

**Comment by thegrb93** [comment]
Render time limit should permanently disable the pac though. The flickering needs to not be a thing.

**Comment by JakeAspire** [comment]
> Render time limit should permanently disable the pac though. The flickering needs to not be a thing.

Well ,it was flickering it on and off, I literally tried everything, even reinstalling the game, add-ons by 1, downloads. I didn't even think looking into render time limit since I never touch it

**Comment by Yagira** [comment]
Weird that you couldn't find the file. It stores all the variables so deleting that usually fixed most setting related problems. Is it even possible for it to not exist? The exact location is `Steam\steamapps\common\GarrysMod\garrysmod\cfg\client.vdf`

**Comment by JakeAspire** [comment]
> Weird that you couldn't find the file. It stores all the variables so deleting that usually fixes most setting related problems. Is it even possible for it to not exist? The exact location is `Steam\steamapps\common\GarrysMod\garrysmod\cfg\client.vdf`

Yes, it is there now, after I reinstalled everything again. 0_o
