### ISSUE TITLE
mouse button events not showing up

### ISSUE THREAD

**Issue by homonovus** [CapsAdmin/pac3#911]
mouse_left and mouse_right do not show up in the button key list
because key_left and key_right exist, both belonging to the arrow keys

offending code: https://github.com/CapsAdmin/pac3/blob/ab0d0b63420fb5319f3ef353618f07abfa4b2aa3/lua/pac3/core/client/parts/event.lua#L1023-L1033

**Comment by thegrb93** [comment]
See if this is better. I'll check later. https://github.com/CapsAdmin/pac3/pull/914
