### ISSUE TITLE
Dropbox sound not working

### ISSUE THREAD

**Issue by Fidelitygh** [CapsAdmin/pac3#915]
Trying to load a sound off of dropbox, does not work at all. Not much else I can add.

**Comment by thegrb93** [comment]
You can add malfunction outfit and url to the sound.

**Comment by Fidelitygh** [comment]
https://www.dropbox.com/s/5zd0dsuwmsredo3/JoJo_s-Bizarre-Adventure-Stardust-Crusaders-OST-Stardust-Crusaders.mp3?dl=0
[talltaro.txt](https://github.com/CapsAdmin/pac3/files/4725866/talltaro.txt)

**Comment by thegrb93** [comment]
Your sound file is corrupt I think.
