### ISSUE TITLE
Error when using webaudio

### ISSUE THREAD

**Issue by BizLight** [CapsAdmin/pac3#917]
I'm using dropbox, making a simple pac3 (event with "is_flashlight_on" and a webaudio)
![simplepac3](https://user-images.githubusercontent.com/29734480/83839480-da283f80-a704-11ea-8e94-a64c4c6efb95.PNG)
And it produces this error, every time. I uploaded and re-uploaded multiple times, I used .ogg, to no avail.
![simplepac3part2](https://user-images.githubusercontent.com/29734480/83839572-0c39a180-a705-11ea-8755-91d5c4f77600.PNG)
I was maybe looking if there was a fix for this or maybe it's on my part, couldn't find anything really related to this.

The link below is the music file which will supposedly download:
[https://www.dropbox.com/s/vtp2qjxxx2dv5u8/Michael%20Jackson%20Smooth%20Criminal%20%28Audio%20HQ%29.mp3?dl=1](url)

**Comment by thegrb93** [comment]
Works fine for me. Try updating your pac version.
