### ISSUE TITLE
PAC issue with "Clearing" on Nutscript

### ISSUE THREAD

**Issue by DeadSignal** [CapsAdmin/pac3#922]
My friends and I have come across this a couple times over the years, and me being below novice and them learned coders we both have the same answer, "no idea". When hitting the "Clear" function, it breaks the set character models on the server and reverts the player back to Kleiner or whichever playermodel they have by default, forcing them to reconnect to fix the issue. The only thing I personally can think of is an issue with the version of PAC or a Gamemode issue, which I am personally unable to pinpoint due to being highly inexperienced. I figured even if this issue is nebulous it should be referred to somewhere on the internet if anyone is ever to experience this technical difficulty. Thank you for taking the time to read this.

**Comment by Yagira** [comment]
pac_modifier_model 0

**Comment by DeadSignal** [comment]
> pac_modifier_model 0

If this is supposed to be a clientside console fix it doesn't seem to be doing the trick, though I much-appreciate this regardless as it seems like an important command to know in face of such problems.

**Comment by Yagira** [comment]
It's supposed to be serverside console fix. It disables playermodel changes in pac.

**Comment by DeadSignal** [comment]
> It's supposed to be serverside console fix. It disables playermodel changes in pac.

Unless I'm missing something, RCON doesn't recognize this command. We've tried lots of things and at this point my intermediate developers think it's a host issue. Is that possible? I'm at my wits end and it seems like the only people that I thought would know the answers are too.

**Comment by thegrb93** [comment]
Maybe we could disable the functionality to 'keep/revert' models when an RP gamemode is running.
