### ISSUE TITLE
"allow_no_contentlength 0" what causes it and how to fix it?

### ISSUE THREAD

**Issue by Pumpkin101** [CapsAdmin/pac3#924]
I apologize if this has been addressed before, but I was searching for any explanations or fixes on this. But couldn't find any and recently it has become a pretty big issue on a server me and a friend are trying to run.

To put it simply, as of recent when you try to load any PAC3 files from pastebin it gives [this error](https://i.gyazo.com/37f18268cf6373717ea3092a0ae9fcb1.png). Loading PAC3 files from pastebin isn't an issue in itself, because you can just save it as a text file and load it manually. _But, the real issue is being caused on others ends._

One of our players reported being unable to see some custom models because that error was coming up. This was irritating but what made it odd was the issues the other player was having, because the model he was unable to see was also glitching out on their end. Not showing the submaterial area in the experimental models tab (at the bottom) and not loading submaterials in general. We assumed this might be a model issue, so we tried a different pack and model and imported that. The same issue occurred.

No errors comes up in console when this happens, so I'm just hoping to figure out if anyone else has had this issue and if they did. How they fixed it. We tried finding a way to set the 'allow_no_contentlength' to 1 instead of 0, seeing as that seems to be the issue. But it wasn't an option in either server consoles, so - help please?

**Comment by Yagira** [comment]
This happens when `sv_pac_webcontent_limit` is set to something other than the default (-1). So either change that back to -1, or if you want to keep the limits set `sv_pac_webcontent_allow_no_content_length` to 1

**Comment by Pumpkin101** [comment]
Alright, thank you! I'll close this issue for now and leave it to see if it opens up later down the line, or if others have the same issue so they can fix it themselves. Or if it ends up being an actual issue, where it doesn't set properly.
