### ISSUE TITLE
PAC movement's JumpHeight field is nil in Move hook

### ISSUE THREAD

**Issue by Mista-Tea** [CapsAdmin/pac3#925]
Error occurs here on the **client:** https://github.com/CapsAdmin/pac3/blob/ab0d0b63420fb5319f3ef353618f07abfa4b2aa3/lua/pac3/core/shared/movement.lua#L143

Using latest dev commit 170b226 but this has been around for years.

```
[pac3] addons/github_pac3/lua/pac3/core/shared/movement.lua:143: bad argument #1 to 'SetJumpPower'
(number expected, got nil)
  1. SetJumpPower - [C]:-1
   2. v - addons/github_sym_pac3/lua/pac3/core/shared/movement.lua:143
    3. unknown - addons/dash/lua/dash/libraries/hook.lua:36
```

*Ignore the stack trace portion coming from `dash`, this issue has been happening for at least a few years before I even started using dash on the server.*

I don't know what my clients' PACs are using to cause it but I've been seeing this so long now and it doesn't appear to have been reported here before. I haven't tried testing on a vanilla sandbox server because I'd need a client with a PAC that has caused it before.

**Comment by DBotThePony** [comment]
Can not reproduce

**Comment by Mista-Tea** [comment]
Unfortunately I can't really provide any more details since this is all I get. The next time I see it occur I can try to ask the player about their PAC and see if they are doing anything particular that might help.

For all I know it's only nil/erroring on very rare cases and not every time. If this has never been seen before on Metastruct then I guess worst case we can just chalk it up to some other addon conflict.

**Comment by thegrb93** [comment]
Probably some kind of pac hack or addon. I haven't looked through the code yet, but it should be easy to see where JumpHeight would be set to nil if it's pac's fault.

**Comment by Mista-Tea** [comment]
I caught it again and the player told me that playing 2 experimental "player movement" gravity effects at the same time causes the error. E.g. a boost to jump higher and a boost to move forward at the same time.

**Comment by thegrb93** [comment]
Is the error clientside or serverside?

**Comment by thegrb93** [comment]
Will try to reproduce it. Didn't see anything in the source that may cause it.

**Comment by thegrb93** [comment]
Can't reproduce either. Might be something messing with ply.pac_movement
