### ISSUE TITLE
Experimental sound parts play all at once upon wearing (Including looping sounds, regardless of "stop on hide" being ticked)

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#928]
Forwarding this from the comment made in issue #876 

Been having this for a long time now, this is less a huge issue and more just a request for a quality of life change. Similar to basic sound parts (the ones that only play in-game audio), the experimental sound part plays whatever sound links are applied at once when worn. If you have multiple Experimental Sound parts, they will all play in a barrage of loud noise.

This issue unfortunately escalates when it comes to looping sounds or longer audio clips. Regardless of settings used, upon wearing, if the PAC outfit in question has a minute long or sound with a play-count of 99999 (the usual loop amount), wearing will automatically trigger them to play... **For their entire duration/play-count**
The way to fix this is to trigger the event in question all the way through until said sound part is activated. More annoying when they're buried inside of a lengthy timerx hierarchy, or activation based on proximity via proxies. 

Example PAC outfit: [!sound2looptest.txt](https://github.com/CapsAdmin/pac3/files/5020236/sound2looptest.txt)

Steps to recreate: Simply enter thirdperson, apply the outfit, hit Wear, music should play regardless of the command part it is tied to being activated. (Also double checked, this is not an issue regarding command events, as it happens on whatever event you tie it to that isn't immediately active upon wearing)

_Aside from a personal request from me, a friend was also asking I posted this somewhere to get this issue known, as it is quite an annoyance._

**Comment by thegrb93** [comment]
I think its the issue I discovered earlier where wearing the outfit again will cause '.play(true)'. Something to do with recycling the stream. Can look into it.

**Comment by CapsAdmin** [comment]
I've fixed stop on hide at least. I guess when running `pac_event music` you'll want to have a longer timer?

Let me know if this is ok or causes further problems.

**Comment by Logzombie** [comment]
As of recent changes, unless further issues related to this are brought up, I believe for the most part this has been fixed? Re-open if these changes fail any time soon or if there's a way to bypass said fix. I can't seem to immediately break it.
