### ISSUE TITLE
Entire PAC3 randomly tilts for no reason

### ISSUE THREAD

**Issue by GlowingMan** [CapsAdmin/pac3#931]
Sorry to bother, but this issue has made me loose my mind... at complete random, my entire pac3 (I have a custom model that's separated into five parts) will just tilt for no reason. The biggest thing is that every part will tilt the exact same degree at the exact same time.

**Comment by thegrb93** [comment]
Never heard of or seen this before.

**Comment by Logzombie** [comment]
From the description, I believe this is an issue regarding pasting a custom imported model into entity2? Though I usually don't have a consistent issue as it tended to fix on wear. Regardless, it only seemed to occur on some models I imported above others, so alas I have little info to go off of, and only occurred when first loaded.

Some screenshots might help clear this up if it's still occurring.
