### ISSUE TITLE
Extracting models

### ISSUE THREAD

**Issue by GraytheGamer** [CapsAdmin/pac3#933]
So im attempting to recreating this video (https://www.youtube.com/watch?v=znLxcGXa8Nc) but the issue i keep running into is extracting a model that i can use in pac when it is part of a larger mod, like how a model can have multiple details you can choose from on one model, or how you choose from multiple models of the same pac. how can I pull out a singular model?

**Comment by thegrb93** [comment]
You can use clips to hide the part of the model you dont want, or, decompile the model, edit the model so it's just what you want, re-compile it, then use with pac.

**Comment by GraytheGamer** [comment]
well the issue isnt in pac, in the video you have to take materials and models into a specific folder, which becomes and issue with multiple models, as more items appear which makes it difficult to find out which files i need to move
