### ISSUE TITLE
Impossible to open the pac3 if you are not superadmin

### ISSUE THREAD

**Issue by kevinhenschen** [CapsAdmin/pac3#935]
Good evening, this is a problem that lasts on my server and I have not found NO SOLUTION. Everything is in the title: on my server if you are not superadmin you cannot open the menu ... I did not find any addon conflicting with the pac3 and I tried the dev version and the version workshop ... nothing ... a solution? Thank you !

**Comment by thegrb93** [comment]
It's definitely an addon conflicting.

**Comment by DBotThePony** [comment]
not addon conflict but some code added a hook to disallow opening pac3 when not superadmin.

If you are unaware of such behavior, then there is a backdoor among ~~us~~ addons installed.

**Comment by kevinhenschen** [comment]
Thank but i think found solution (not sure) : 
![ps](https://user-images.githubusercontent.com/61383390/93660906-edf97680-fa53-11ea-8fcb-a4daa2770942.png)
I have the impression that the pointshop2 addon overrides the two pac3 restriction functions

**Comment by kevinhenschen** [comment]
I just don't think PointShop2 will go so far as to include an option to restrict pac3 since that's not really its main job

**Comment by kevinhenschen** [comment]
![image](https://user-images.githubusercontent.com/61383390/93660971-737d2680-fa54-11ea-919c-97ec9c7b7455.png)
Solved! I had to find export all my addons folder to find an addon using the hook. And I came across this thing which is activated from the base ... (not very smart :/)
