### ISSUE TITLE
Null entity causes CalcDrag errors.

### ISSUE THREAD

**Issue by zxz41** [CapsAdmin/pac3#936]
Selecting entity 0 (AKA worldspawn) causes `pace.current_part:GetOwner(true)` to return [NULL entity]. Which for some reason causes `origin` to become `nil` due to `pace.current_part:GetDrawPosition()` in some situations.

```
[pac3] addons/pac3/lua/pac3/editor/client/view.lua:185: attempt to index local 'origin' (a nil value)
  1. CalcDrag - addons/pac3/lua/pac3/editor/client/view.lua:185
   2. v - addons/pac3/lua/pac3/editor/client/view.lua:407
    3. unknown - lua/includes/modules/hook.lua:84
```

**Comment by thegrb93** [comment]
I think the IsValid here is breaking it.
https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/editor/client/view.lua#L157

**Comment by thegrb93** [comment]
Also I think this should be game.GetWorld()
https://github.com/CapsAdmin/pac3/blob/ab0d0b63420fb5319f3ef353618f07abfa4b2aa3/lua/pac3/core/client/owner_name.lua#L41

**Comment by thegrb93** [comment]
Never mind, apparently it's supposed to be an actual entity.

**Comment by thegrb93** [comment]
This function creates it. https://github.com/CapsAdmin/pac3/blob/ab0d0b63420fb5319f3ef353618f07abfa4b2aa3/lua/pac3/core/client/owner_name.lua#L43

**Comment by thegrb93** [comment]
The only code path that can lead to nil origin seems to be https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/editor/client/view.lua#L181

**Comment by thegrb93** [comment]
If you had world selected, it should've taken this code path https://github.com/CapsAdmin/pac3/blob/develop/lua/pac3/editor/client/view.lua#L157

**Comment by CapsAdmin** [comment]
ops, wrong issue

**Comment by CapsAdmin** [comment]
Pac shouldn't choose the actual world as world entity. It creates an internal entity at world origin and uses instead to avoid errors that can occur when using the real world entity.

I'm not sure how this could have happened. 

Reopen if it's still happening.
