### ISSUE TITLE
Pac overriding models

### ISSUE THREAD

**Issue by Dannyg27** [CapsAdmin/pac3#938]
ok, this might be an issue with Darkrp or serverside or something that i should have done but haven't on my server
but i've experienced it in singleplayer and with no addons as well so i have come here
i have no idea wether it's a bug or a feature but i have never experienced this in all my time using pac and neither has anyone else in my community
Issue: Whenever i or anyone loads a saved pac it puts on the selected player model from the player model selector in the C menu instead of using the current one forcing one to re log to fix it

**Comment by Dannyg27** [comment]
This is also a permanent serverside model change, meaning that nobody not even admins are able to change the model of the person that did this in any way shape or form

**Comment by thegrb93** [comment]
It is a darkrp-pac3 conflict. See https://github.com/CapsAdmin/pac3/issues/922
