### ISSUE TITLE
Add weapon sheen data to material part

### ISSUE THREAD

**Issue by LUModder** [CapsAdmin/pac3#94]
Since killstreaks have been introduced, there are some VMT data for weapons now, but no where to put it in PAC.

Some example VMT data

"$sheenmap" 		"cubemaps\cubemap_sheen001"
"$sheenmapmask" 		"Effects\AnimatedSheen\animatedsheen0"
"$sheenmaptint" 		"[ 1 1 1 ]"
"$sheenmapmaskframe" 	"0"
"$sheenindex" 		"0"

"Proxies"
{
	"AnimatedWeaponSheen"
	{
		"animatedtexturevar" 		"$sheenmapmask"
		"animatedtextureframenumvar" 	"$sheenmapmaskframe"
		"animatedtextureframerate" 		"40"
	}

I don't know how hard it would be to add, but it'd be nice to have.

**Comment by CapsAdmin** [comment]
are you sure this is part of gmod's version of the source engine though?

**Comment by robotboy655** [comment]
It is not.
