### ISSUE TITLE
Can't change skin of experimental model with proxy.

### ISSUE THREAD

**Issue by KeksyBatsy** [CapsAdmin/pac3#940]
In proxy for pac4 model I can't find skin variable and other things, seems like variables moved from regular pac3 model, please helb :c

**Comment by thegrb93** [comment]
Looks like skin needs to be added to this list: https://github.com/CapsAdmin/pac3/blob/463a65ea05adebbd516c3183bae8029954a6968e/lua/pac3/core/client/parts/model2.lua#L38
