### ISSUE TITLE
Obj won't load with experimental model parts

### ISSUE THREAD

**Issue by thegrb93** [CapsAdmin/pac3#941]

**Comment by Techbot121** [comment]
I think this is resolved now by prepending `obj` to the url?

**Comment by thegrb93** [comment]
Like obj:// ? That's a bit ridiculous. If a url is provided, the downloaded file's header should contain either zip or obj and it can determine what the file type is from that. I'll take a peek at the source

**Comment by thegrb93** [comment]
Looks like it should work for an extension of .obj https://github.com/CapsAdmin/pac3/blob/009b474b8dde71391f3a4380c7c014c8ebf32691/lua/pac3/core/client/parts/model.lua#L601

Maybe has been fixed already.
