### ISSUE TITLE
Resizing Playermodel prevents moving while in third person

### ISSUE THREAD

**Issue by thennothinghappened** [CapsAdmin/pac3#942]
As the title says. I have not tested with other changes in attributes, however I was able to reproduce the issue with this addon loaded only, too. Any change in playermodel size caused me to be unable to move while using the thirdperson console command.

**Comment by thegrb93** [comment]
I think using a thirdperson addon instead of the source engine thirdperson would fix the issue. No idea why this would happen.

**Comment by thennothinghappened** [comment]
I've tried many third party ones without success, any specific ones you suggest?

**Comment by thegrb93** [comment]
simple thirdperson. enable it by holding c.
