### ISSUE TITLE
Using particles from hl2/materials/particles is broken

### ISSUE THREAD

**Issue by ocso639** [CapsAdmin/pac3#943]
As the title says, using particles from that folder is glitchy and causes broken/flickering effects.

**Comment by thegrb93** [comment]
Do you have a test outfit?

**Comment by ocso639** [comment]
Yes, how would I send it to you?

**Comment by thegrb93** [comment]
you can put the file here in this chat window.

**Comment by ocso639** [comment]
[glitchy particle.txt](https://github.com/CapsAdmin/pac3/files/5626914/glitchy.particle.txt)

**Comment by thegrb93** [comment]
I think materials like that only work if 3d is set to true. Try that.

**Comment by thegrb93** [comment]
Otherwise you'll need an unlit generic material
