### ISSUE TITLE
Outfits lagging

### ISSUE THREAD

**Issue by TheNickSkater** [CapsAdmin/pac3#944]
So I use Poinshop2 and Hats/Other outfits lag on other players.

What I noticed though: They dont lag behind if I spectate them in third person view.

I use this on a TTT Server.

Is there anyway this can be fixed, its really really anoying.

Thanks!

**Comment by FarukGamer** [comment]
Duplicate https://github.com/CapsAdmin/pac3/issues/767

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/issues/894 as well
