### ISSUE TITLE
Figure out a way to make the experimental parts default and deprecate the old one

### ISSUE THREAD

**Issue by CapsAdmin** [CapsAdmin/pac3#945]
Do people think the experimental parts miss functionality? If so, what should be added before they become the default?

**Comment by thegrb93** [comment]
We'll need an outfit pool to test with so we're sure the migration works.

**Comment by CapsAdmin** [comment]
While worth looking into, I don't think that's in scope here. 

The way I see this being done is more or less marking the old parts as legacy and removing "experimental" from the name in the new parts.

You would still be able to make the old parts by enabling legacy features. Old outfits would still load the old parts. It's only when you create a new outfit that you'll be directed to use the new parts.

**Comment by thegrb93** [comment]
Oh, I thought you'd migrate the old parts to new parts. I guess this would be a lot easier then.

**Comment by iskawhiskers** [comment]
How did you mark woohoo as deprecated?

**Comment by CapsAdmin** [comment]
The difficult part about this taks is to figure out if the experimental parts really have everything they need before the old one are marked as deprecated.

**Comment by thegrb93** [comment]
The model/entity parts seem to be lacking the most. I already recently had to add 'skin' to them. I don't think any others are lacking but may be wrong.

**Comment by CapsAdmin** [comment]
this is now kinda done
