### ISSUE TITLE
Model gets reset to default gmod playermodel

### ISSUE THREAD

**Issue by Trainiac21** [CapsAdmin/pac3#947]
I want to use pac3 on my server, however the models we are using don't have a playermodel option so when I try to load a saved outfit, it changes the model to the model I use for sandbox, any idea why this is happening

before
![image](https://user-images.githubusercontent.com/76668931/103182510-cd726100-4879-11eb-95a7-633beb844bce.png)

after
![image](https://user-images.githubusercontent.com/76668931/103182519-e1b65e00-4879-11eb-9c62-e2e6f29b1cec.png)

**Comment by thegrb93** [comment]
https://github.com/CapsAdmin/pac3/issues/922

**Comment by thegrb93** [comment]
pac_modifier_model 0
