### ISSUE TITLE
Cannot change my player model without resetting pac outfit.

### ISSUE THREAD

**Issue by ghost** [CapsAdmin/pac3#95]
When I change my player model via the usual way and kill myself, the player model sticks until I go into PAC3 and press clear outfit. There is also a bug with model manipulator in which if I try to change my player model via that it does not work no matter what I do (kill doesn't work nor resetting pac outfit). The model manipulator thing was working before but now I can never change it. I experienced this when I was in a server and I don't know if the admin has stopped it or what but it is really pissing me off and  I even tried typing pac_restart in console, again it didn't work.
So does anyone have an idea on what to do? Please help!

**Comment by CapsAdmin** [comment]
You've set a player model in the entity part. Make the model field in the entity part blank or set pac_modifier_model to 0
