### ISSUE TITLE
Sound2/Web Sound Bug

### ISSUE THREAD

**Issue by Ternax** [CapsAdmin/pac3#961]
For some reason when wearing my PAC, the rear jet sounds that should only play on the event trigger permanently play. Hiding the sound won't stop it, however clicking the link and clicking out of the link fixes it. Doing pac_restart in console also fixes it.

Note: The server I recorded this on had an outdated PAC, so that may have caused it? Not too sure though.

https://streamable.com/8q2rme

**Comment by Ternax** [comment]
Update:
It does this bug on every server, even the ones with the updated PAC. It's started doing it on my searchlight sound now.

**Comment by CapsAdmin** [comment]
I've fixed issues related to this recently. Can you try the latest develop branch?

**Comment by Ternax** [comment]
> I've fixed issues related to this recently. Can you try the latest develop branch?

I tried it on Meta Construct just now and I'm having no issues. I've downloaded the latest branch. However some sounds are either randomly cutting out or doing super distorted. I've not managed to nail down which sound is going distorted though.

**Comment by Ternax** [comment]
> > I've fixed issues related to this recently. Can you try the latest develop branch?
> 
> I tried it on Meta Construct just now and I'm having no issues. I've downloaded the latest branch. However some sounds are either randomly cutting out or doing super distorted. I've not managed to nail down which sound is going distorted though.

Okay it's weird. The pitch of random sounds is changing when wearing the PAC. Sometimes it goes that low that it goes super distorted. It's not one singular sound that's going wrong.

**Comment by CapsAdmin** [comment]
can you give me a reproducable outfit?

**Comment by Ternax** [comment]
> can you give me a reproducable outfit?

Unfortunately no, sorry. All I can do is share videos of the issues happening or sending screenshots.

**Comment by CapsAdmin** [comment]
I'm not sure what else I can help with. It seems like I fixed the bug you were first talking about, but now there's a new one. Is that correct?

If you can find a consistent way to reproduce the new bug where the sound is weird on wear let me know in a new issue.
