### ISSUE TITLE
Add shotgun part

### ISSUE THREAD

**Issue by maska228** [CapsAdmin/pac3#965]
title says it all

**Comment by iskawhiskers** [comment]
you can currently make a "shotgun" using multiple projectiles and a couple of proxies to simulate random bullet spread, though a "projectile amount" value would fit nicely into the projectile part (i.e. spawn x number of projectiles instead of a hardcoded single projectile per unhide)

**Comment by maska228** [comment]
> you can currently make a "shotgun" using multiple projectiles and a couple of proxies to simulate random bullet spread, though a "projectile amount" value would fit nicely into the projectile part (i.e. spawn x number of projectiles instead of a hardcoded single projectile per unhide)

you arent familiar with memes in discord server, are you?

**Comment by Logzombie** [comment]
_Hitscan part when_

**Comment by Avernakis8** [comment]
_Hitscan part when_

**Comment by iskawhiskers** [comment]
> you arent familiar with memes in discord server, are you?

understandable, have a nice day
