### ISSUE TITLE
Hitpos Aiming Resetting

### ISSUE THREAD

**Issue by Ternax** [CapsAdmin/pac3#966]
For some reason any parts that are set to aim at the Hitpos no longer save. They reset every time a PAC is loaded on the latest version.

Before Save: 

![image](https://user-images.githubusercontent.com/11888187/105033827-8890b300-5a50-11eb-928d-bd9256304377.png)

After Save:

![image](https://user-images.githubusercontent.com/11888187/105033764-76167980-5a50-11eb-92ff-039ae8616864.png)

**Comment by CapsAdmin** [comment]
I changed this to look a little different visually in the property, so I suspect it doesn't actually reset.

However I can̈́t reproduce this. Can you send me an example outfit?

**Comment by Ternax** [comment]
> I changed this to look a little different visually in the property lately, so I suspect it doesn't actually reset.
> 
> However I can̈́t reproduce this. Can you send me an example outfit?

Sure thing. Here's a very simple propane tank that should aim at the Hitpos fine. 

Here's a demonstration:

https://user-images.githubusercontent.com/11888187/105092738-8e5eb680-5a99-11eb-9b9c-8a38cd5ae706.mp4

[test.txt](https://github.com/CapsAdmin/pac3/files/5838583/test.txt)
