### ISSUE TITLE
Player Movement Issue

### ISSUE THREAD

**Issue by Ternax** [CapsAdmin/pac3#968]
Player movement is no longer letting me fly at fast speeds or move. The only time I can move forwards is if I change the max air speed to above 5000. I can't go up and down via space and ctrl anymore either.

Is this because of a change of how player movement works now? Or a bug?

**Comment by CapsAdmin** [comment]
In the past the movement part's speeds did not accurately represent the movement speed you told it to use. I fixed this now, which does mean that you might have to change it.

See https://github.com/CapsAdmin/pac3/issues/929 for more info. 

It's currently being tested as seen on https://github.com/CapsAdmin/pac3/projects/5

If you think there's a new bug introduced by this (apart from that you need to change the speeds) you can post in the other issue.
