### ISSUE TITLE
OGG Won't play.

### ISSUE THREAD

**Issue by n2projects** [CapsAdmin/pac3#969]
[PAC3] OGG error: stream[0xa7201920][4][https://dl.dropboxusercontent.com/s/kzizvwcrpkhs1rq/Dead-Or-Alive-You-Spin-Me-Round.ogg?dl=0] reason: download failed

The error I got.

**Comment by CapsAdmin** [comment]
Works for me right now. A few commits ago it might not have worked though, could you try updating?

**Comment by TR011F4C3** [comment]
Updating what?

**Comment by Logzombie** [comment]
PAC Version from the Github develop branch most likely. It's being very frequently updated as of right now.

**Comment by TR011F4C3** [comment]
Bit of a GMOD and Github noob, how do I download it? Theres no releases as far as I can see.

**Comment by Logzombie** [comment]
This page:
![image](https://user-images.githubusercontent.com/50374409/105633186-130d5400-5e4f-11eb-943e-f0af0f1a0bbf.png)

Switch this drop down menu to Develop or whatever current version it is at for you: 
![image](https://user-images.githubusercontent.com/50374409/105633204-228c9d00-5e4f-11eb-922c-36a7f61a7405.png)

Click on this, and hit Download Zip:
![image](https://user-images.githubusercontent.com/50374409/105633218-37693080-5e4f-11eb-9462-7f39a28c2fe9.png)

**Comment by TR011F4C3** [comment]
OGG error: stream[0x7081a768][2][http://dl.dropboxusercontent.com/s/kzizvwcrpkhs1rq/Dead-Or-Alive-You-Spin-Me-Round.ogg?dl=0] reason: download failed

Got latest version - it's still broken.

**Comment by Logzombie** [comment]
Try removing the ?dl=0 off the end of the link. That's about the only other possible alternative I can think of straight away.

**Comment by TR011F4C3** [comment]
Still doesn't work.

**Comment by Ternax** [comment]
Also having this issue. Also don't know if this is related but my webaudio sometimes lags out and goes super jumpy. I was playing with a friend as well and it was always extremely laggy with audio. This error is spamming my console so idk if it's related to that.

**Comment by Ternax** [comment]
If you want an idea of what it sounds like with that sound bug @CapsAdmin, here's an example of one of my PACs playing it's audio:

https://user-images.githubusercontent.com/11888187/107633451-f3a06480-6c5f-11eb-800e-633fc8dbad19.mp4

**Comment by Techbot121** [comment]
please reopen if it still happens, it could have a number of reasons why it would play like that, for example cpu usage etc... 
you can also try playing with the `webaudio_buffer_size` console command. You can try `256, 512, 1024, 2048, 4096, 8192, 16384` the default is `2048`.
