### ISSUE TITLE
cant access pac editor at all

### ISSUE THREAD

**Issue by BATJUAN** [CapsAdmin/pac3#97]
so i just downloaded this addon again since i wanted to use the paypay 2 armor with it but when i go to the spawn menu then when i go to activate it theres nothing there. can anyone help me with this like i cant use it at all ive reinstalled the addon a few times and stuff and nothing is working

**Comment by Ameno-Sagiri** [comment]
I know this is old, but try pac_editor in console. If it isn't recognize as a command, then YOU didn't install PAC3 properly.

If it's through workshop, then I don't know. Workshop is a dick.
