### ISSUE TITLE
PAC stops working and spams lua errors upon restarting

### ISSUE THREAD

**Issue by JohnWeak1** [CapsAdmin/pac3#982]
```
[ERROR] lua/pac3/core/client/parts/legacy/bone.lua:236: attempt to index global 'pac' (a nil value)
  1. unknown - lua/pac3/core/client/parts/legacy/bone.lua:236 
```

this happens with the Workshop version

**Comment by CapsAdmin** [comment]
when does this happen? when i read this error it looks like something else is trying to unload pac

**Comment by JohnWeak1** [comment]
> 
> 
> when does this happen? when i read this error it looks like something else is trying to unload pac

it happens when I do "pac_restart" in the console

**Comment by CapsAdmin** [comment]
> > when does this happen? when i read this error it looks like something else is trying to unload pac
> 
> it happens when I do "pac_restart" in the console

Okay, so maybe that's broken in the workshop version. 

But why are you using that command? Did you get an error before that?

pac restart was made for developers

**Comment by Logzombie** [comment]
> pac restart was made for developers

Basically everyone's been using it regardless to reset PAC when it breaks or potentially has issues, this isn't an uncommon thing.

**Comment by CapsAdmin** [comment]
I know and it's too late for me to change this now. The best I can do when someone complains about pac_restart behavior/bugs is to fix the problem and explain why it exists so that people are more likely to report bugs.

In a way I don't care about pac_restart here, I care about why it was used in the first place.

**Comment by CapsAdmin** [comment]
I've fixed it now, but I'd still like to know why you are using pac_restart in the first place.
