### ISSUE TITLE
$detailtint in Material part appears to not function with imported VTF textures

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#986]
Sort of just remembered this appears to be an issue when fooling around with texture settings with an existing PAC.
Black and white Detail map, made for use with RGB recolour, however the $detailtint function in Material 3D appears to do nothing to the detail map's colour when altered. With other tint functions I would assume I am not using this one incorrectly.
![20210204064042_1](https://user-images.githubusercontent.com/50374409/106855171-6b94ea80-66b4-11eb-9690-e08d46581a8b.jpg)

**Comment by CapsAdmin** [comment]
When encountering issues like this you should google them, because the material part is supposed to give you all the options gmod have and so if something doesn't work it might be a gmod or source engine issue.

It seems like it's not working with bumpmap according to https://github.com/Facepunch/garrysmod-requests/issues/623

**Comment by Logzombie** [comment]
I had a gut feeling it may have been a source issue.. But I wouldn't have thought it would've had anything to do with the bumpmap. Wouldn't have thought source has all of these issues revolving around Bumpmap since Specular textures have a similar issue.

**Comment by Logzombie** [comment]
Judging by how the detail tint _does_ function without a bumpmap applied, I can already close this. What I'm also looking for to achieve this effect is already solved through self-illum it turns out. 
![20210204084941_1](https://user-images.githubusercontent.com/50374409/106870073-99842a00-66c8-11eb-9891-5809d8f0832c.jpg)
