### ISSUE TITLE
Websound does not seem to function properly with pitch proxies

### ISSUE THREAD

**Issue by Logzombie** [CapsAdmin/pac3#987]
It seems websound doesn't entirely deprecate ogg parts just yet. From what I've seen so far, this is only an issue with pitch, as volume appears to scale fine.

Here's an example of pitch based on movement speed: Websound fails to scale in pitch properly, while ogg does so flawlessly.
[!!websoundpitchproblem.txt](https://github.com/CapsAdmin/pac3/files/5924724/websoundpitchproblem.txt)

How to use: Hold E for Websound, R for Ogg, move around while holding either button.

**Comment by Techbot121** [comment]
it was just a silly typo, I just fixed it.
