### ISSUE TITLE
New pac update conficts with outfitter and bones that are resized flicker in size.

### ISSUE THREAD

**Issue by Synkstar** [CapsAdmin/pac3#992]
This gets spammed in the console ( of the clients no error on the server )and it turns everyone else that is not you into a kleiner regardless of their default pm.
```
[Outfitter] Fullupdate	not needed	models/player/kleiner.mdl
[Outfitter] Fullupdate	not needed	models/player/leymirba/trackerpm.mdl
```
I tried multiple commits and went back to https://github.com/CapsAdmin/pac3/commit/84dfb45b1c7d6e42e69602ef2c0b82f675b51910  and the issues dont exist. So it has to be something after that

**Comment by DannyDan4** [comment]
Can attest to this problem, however, I do not get the 'everyone is kleiner' problem.

**Comment by Synkstar** [comment]
It does work on the workshop version now. So it has to be something just on the dev version

**Comment by Synkstar** [comment]
It says this in the chat now
`[PAC3] ERROR: models/player/leymirba/trackerpm.mdl is not a valid player model on the server. Defaulting to kleiner.`

**Comment by CapsAdmin** [comment]
@Python1320

**Comment by CapsAdmin** [comment]
Try setting the model field in entity to blank. Does that work with outfitter?

Pac tries to set the model both clientside and serverside. If you're using a model that don't exist on the server you'll get that message. I think it should still work though.

If you want to use custom models in pac (server and client), see:

https://wiki.pac3.info/tutorial/using-mdl-files

**Comment by Synkstar** [comment]
But it does work now if I remove the model name in pac so should I close this issue?

**Comment by CapsAdmin** [comment]
If you believe it's solved.

For the record, I removed the entity part's ability to auto fill in your current clientside model. This was a bad choice on my part which probably caused a lot headache with outfitter.
