### ISSUE TITLE
Make netstream global so it doesn't send concurrently with advdupe2/starfall

### ISSUE THREAD

**Issue by thegrb93** [CapsAdmin/pac3#998]

**Comment by thegrb93** [comment]
This'll allow removal of net_stream.Identifier as well.

**Comment by CapsAdmin** [comment]
I explicitly added it to avoid conflict with starfall, but your reasons against that make sense.

I think the proper way is to reuse the library itself, so if it already exists bail out and use the existing version.

But feel free to do whatever makes sense for you in the context of all 3 addons.

**Comment by thegrb93** [comment]
I should move it to lua/autorun in all three so that only one gets sent/loaded
